### ISSUE TITLE
mainTest.py does not work when run independently

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1002]
If one tries to run `mainTest.py` on it's own, then the tests in the `TestMain` class encounter an error:

```
Traceback (most recent call last):
  File "rmgpy/rmg/mainTest.py", line 108, in testRMGExecute
    self.rmg.execute()
  File "rmgpy/rmg/main.py", line 529, in execute
    self.initialize(**kwargs)
  File "rmgpy/rmg/main.py", line 371, in initialize
    self.loadInput(self.inputFile)
  File "rmgpy/rmg/main.py", line 206, in loadInput
    from input import readInputFile
  File "input.py", line 2, in <module>
    database(
NameError: name 'database' is not defined
```

At first glance, it seems like there's an issue with directories, and `main.py` is trying to import from the newly created input file, `input.py` instead of the actual `rmg/input.py` module.

The tests work properly when running the full test suite, although it raises a warning about multiple RMGDatabase instances.

**Comment by mliu49** [comment]
Fixed by #1160.
