### ISSUE TITLE
Error when using a seeding mechanism

### ISSUE THREAD

**Issue by dyu2017** [ReactionMechanismGenerator/RMG-Py#1028]
I often get the following errors when using the seed mechanism generated with a first model.
Is there any reason for this?

Traceback (most recent call last):
  File "/home/user/RMG-WORK/RMG-Py/rmg.py", line 156, in <module>
    rmg.execute(**kwargs)
  File "/home/user/RMG-WORK/RMG-Py/rmgpy/rmg/main.py", line 665, in execute
    bimolecularReact=self.bimolecularReact)
  File "/home/user/RMG-WORK/RMG-Py/rmgpy/rmg/model.py", line 622, in enlarge
    spcs = [self.retrieveNewSpecies(rxn) for rxn in rxns]
  File "/home/user/RMG-WORK/RMG-Py/rmgpy/rmg/model.py", line 1683, in retrieveNewSpecies
    return self.getSpecies(obj)
  File "/home/user/RMG-WORK/RMG-Py/rmgpy/rmg/model.py", line 1668, in getSpecies
    raise e
KeyError: 73

**Comment by nyee** [comment]
I think the issue might be with parsing the species index. In the seed mechanism, do any of the species names have a parenthesis with numbers, eg S(140)? If so, please try renaming the species in the seed mechanism and resubmitting the job.

**Comment by dyu2017** [comment]
@nyee Thanks. This worked.
