### ISSUE TITLE
Reactions lost during movement from edge to core in enlarge step

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1037]
In rare cases certain edge reactions seem to be lost during the movement to core process.  Since enlarge doesn't appear to be well tested I think this may have gone unnoticed.  I found this because the surface algorithm needs to track what reactions are entering the surface and I found that some of the ones I was tracking failed to show up after enlargement.  This occurs with pruning and filtering turned off.  Note:  NO, O2 and N2 are already in core.  

Species added to core
C5H11O2-2
Species added to core
[N]=[N]
Species added to core
CH2(S)
Species added to core
HNO
Species added to core
N(=O)N=O
Species added to core
O(N=[N])[O]
Species added to core
C5H11-3
Species added to core
CH3
Species added to core
O=O
Species added to core
NC3H7
Species added to core
CH2
Reactions expected, but not found in core
O2(2) + N2(4) <=> O(N=[N])[O](964)
in current core?
False
in old core?
False
in current edge?
False
in old edge?
True
Reactions expected, but not found in core
NO(3) + NO(3) <=> N(=O)N=O(965)
in current core?
False
in old core?
False
in current edge?
False
in old edge?
True
Traceback (most recent call last):
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmg.py", line 156, in <module>
    rmg.execute(**kwargs)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/rmg/main.py", line 745, in execute
    assert False
AssertionError

**Comment by mjohnson541** [comment]
This was a pdep issue, with pdep certain unimolecular reactions are converted to PDepNetworks, during this process those reactions are removed from core/edge, this implies that reactions can't be precisely tracked and the current surface algorithm as implemented now doesn't apply to pdep reactions.
