### ISSUE TITLE
`None` is generated instead of a Species during enlarge() step, possibly due to reaction deflation?

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#1077]
Running a job on master, which previously ran smoothly, now generates the following trace:

```
Traceback (most recent call last):
  File "/home/alongd/Code/RMG-Py//rmg.py", line 159, in <module>
    rmg.execute(**kwargs)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/main.py", line 689, in execute
    bimolecularReact=self.bimolecularReact)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/model.py", line 645, in enlarge
    self.processNewReactions([rxn], spc)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/model.py", line 774, in processNewReactions
    self.addReactionToUnimolecularNetworks(rxn, newSpecies=newSpecies, network=pdepNetwork)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/model.py", line 1395, in addReactionToUnimolecularNetworks
    assert isinstance(newSpecies, Species)
AssertionError
```

where an object sent to `addReactionToUnimolecularNetworks()` is not a Species.

Adding a logging.info statement to [enlarge()](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/rmg/model.py#L639) (which calls `processNewReactions` which then calls `addReactionToUnimolecularNetworks()`) gives prior to the traceback:
```
rxn: C=C=N + [H] <=> 21, spc: CH2CHNH(21)
rxn: 21 <=> C[C]=N, spc: CH2CHNH(21)
rxn: 21 <=> CC=[N], spc: CH2CHNH(21)
rxn: 21 <=> C1[CH]N1, spc: CH2CHNH(21)
rxn: N=[CH] + [CH2] <=> 21, spc: CH2CHNH(21)
rxn: [CH2][C]=N + [H] <=> 21, spc: CH2CHNH(21)
rxn: [H] + C(=[N])[CH2] <=> 21, spc: CH2CHNH(21)
rxn: C=C=N + [H] <=> C(=C)[NH], spc: None
```

I.e., `retrieveNewSpecies()` returned `None`.

The [retrieveNewSpecies(self, deflatedRxn)](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/rmg/model.py#L1695) function assumes each deflatedRxn sent to it has at least one reactant/product which is an integer (i.e., in the core). This is a very logical assumption if everything works as expected, but we should throw an error if the for loop in `retrieveNewSpecies()` ends without returning a thing.

Looking into this with @goldmanm, we suspect that the deflatedRxn being sent to `retrieveNewSpecies` represents a resonance isomer which is not the structure that appears in the core, hence no core species are found and returned.

**Comment by alongd** [comment]
closed via #1078
