### ISSUE TITLE
Thermo central database unit tests occasionally error

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1099]
I received these errors in one of the thermo central database tests on the autoseed and fixBarrierHeightTest branches for no apparent reason.  I only had to retrigger the unittests on travis and they passed the second time, but if common this could get very troublesome.  Since I got different results on different runs I think it might just be a connection issue?  So far (from a very small sample size) I seem to be getting this sort of error in about 50% of travis unittest runs.  

First example:  
======================================================================

ERROR: Test situation where both registration_table and results_table have no

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/ReactionMechanismGenerator/RMG-Py/rmgpy/data/thermoTest.py", line 1170, in testRegisterInCentralThermoDB1

    registered_species = Species().fromSMILES(str(registered_species_entry['SMILES_input']))

KeyError: 'SMILES_input'

Second example:  
======================================================================

FAIL: Test situation where both registration_table and results_table have no

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/ReactionMechanismGenerator/RMG-Py/rmgpy/data/thermoTest.py", line 1166, in testRegisterInCentralThermoDB1

    self.assertEqual(len(registered_species_entries), 1)

AssertionError: 0 != 1

**Comment by mjohnson541** [comment]
New ones:  
======================================================================

ERROR: Test situation where both registration_table and results_table have no

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/ReactionMechanismGenerator/RMG-Py/rmgpy/data/thermoTest.py", line 1148, in testRegisterInCentralThermoDB1

    tcdi = ThermoCentralDatabaseInterface(host, port, username, password, application)

  File "/home/travis/build/ReactionMechanismGenerator/RMG-Py/rmgpy/data/thermo.py", line 1923, in __init__

    self.client = self.connect()

  File "/home/travis/build/ReactionMechanismGenerator/RMG-Py/rmgpy/data/thermo.py", line 1936, in connect

    client.server_info()

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1082, in server_info

    read_preference=ReadPreference.PRIMARY)

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/database.py", line 478, in command

    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/contextlib.py", line 17, in __enter__

    return self.gen.next()

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/mongo_client.py", line 798, in _socket_for_reads

    with self._get_socket(read_preference) as sock_info:

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/contextlib.py", line 17, in __enter__

    return self.gen.next()

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/mongo_client.py", line 764, in _get_socket

    with server.get_socket(self.__all_credentials) as sock_info:

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/contextlib.py", line 17, in __enter__

    return self.gen.next()

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/server.py", line 163, in get_socket

    with self.pool.get_socket(all_credentials, checkout) as sock_info:

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/contextlib.py", line 17, in __enter__

    return self.gen.next()

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/pool.py", line 582, in get_socket

    sock_info = self._get_socket_no_auth()

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/pool.py", line 618, in _get_socket_no_auth

    sock_info, from_pool = self.connect(), False

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/pool.py", line 555, in connect

    _raise_connection_failure(self.address, error)

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/pool.py", line 63, in _raise_connection_failure

    raise NetworkTimeout(msg)

NetworkTimeout: [secure]:[secure]: timed out

======================================================================

ERROR: the thermo is exact match, so no need to register in

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/ReactionMechanismGenerator/RMG-Py/rmgpy/data/thermoTest.py", line 1087, in testSatisfyRegistrationRequirements3

    tcdi = self.connectToTestCentralDatabase()

  File "/home/travis/build/ReactionMechanismGenerator/RMG-Py/rmgpy/data/thermoTest.py", line 1034, in connectToTestCentralDatabase

    tcdi = ThermoCentralDatabaseInterface(host, port, username, password, application)

  File "/home/travis/build/ReactionMechanismGenerator/RMG-Py/rmgpy/data/thermo.py", line 1923, in __init__

    self.client = self.connect()

  File "/home/travis/build/ReactionMechanismGenerator/RMG-Py/rmgpy/data/thermo.py", line 1936, in connect

    client.server_info()

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/mongo_client.py", line 1082, in server_info

    read_preference=ReadPreference.PRIMARY)

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/database.py", line 478, in command

    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/contextlib.py", line 17, in __enter__

    return self.gen.next()

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/mongo_client.py", line 798, in _socket_for_reads

    with self._get_socket(read_preference) as sock_info:

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/contextlib.py", line 17, in __enter__

    return self.gen.next()

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/mongo_client.py", line 764, in _get_socket

    with server.get_socket(self.__all_credentials) as sock_info:

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/contextlib.py", line 17, in __enter__

    return self.gen.next()

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/server.py", line 163, in get_socket

    with self.pool.get_socket(all_credentials, checkout) as sock_info:

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/contextlib.py", line 17, in __enter__

    return self.gen.next()

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/pool.py", line 582, in get_socket

    sock_info = self._get_socket_no_auth()

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/pool.py", line 618, in _get_socket_no_auth

    sock_info, from_pool = self.connect(), False

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/pool.py", line 555, in connect

    _raise_connection_failure(self.address, error)

  File "/home/travis/miniconda/envs/rmg_env/lib/python2.7/site-packages/pymongo/pool.py", line 63, in _raise_connection_failure

    raise NetworkTimeout(msg)

NetworkTimeout: [secure]:[secure]: timed out

**Comment by KEHANG** [comment]
I think it's caused by occasional connection failures. The high failing rate can be from Travis server side or most likely the database host server side (which is RMG server). I can restart the database server and see if it helps.

**Comment by mjohnson541** [comment]
Thanks!  I just had 6 in a row pass so that seems to have fixed the issue for now.
