### ISSUE TITLE
Invalid cantherm/measure input file created (multiple reactions with same label)

### ISSUE THREAD

**Issue by faribas** [ReactionMechanismGenerator/RMG-Py#112]
An RMG-Py job created a pdep file network1798_2.py that, when run thorugh cantherm.py, fails as:

``` python
(rmgpy1)[fariba@venture pdep]$ python /home/fariba/Code/RMG-Py/cantherm.py network1798_2.py 
CanTherm execution initiated at Thu Apr 11 16:21:49 2013

###############################################################
#                                                             #
#                          CanTherm                           #
#                                                             #
#   Version: 0.1.0 (14 May 2009)                              #
#   Authors: RMG Developers (rmg_dev@mit.edu)                 #
#   P.I.:    William H. Green (whgreen@mit.edu)               #
#   Website: http://rmg.sourceforge.net/                      #
#                                                             #
###############################################################

Loading species H2CCCH(54)...
Loading species CC#[C](687)...
Loading species C3H2(38)...
Loading species H(11)...
Loading species [CH2]C#[C](685)...
Loading species C1C=[C]1(686)...
Loading species CH3(22)...
Loading species C2(69)...
Loading species N2(5)...
Loading transition state TS1...
Loading transition state TS2...
Loading transition state TS3...
Loading transition state TS4...
Loading transition state TS5...
Loading transition state TS6...
Loading reaction reaction1...
Loading reaction reaction2...
Loading reaction reaction3...
Loading reaction reaction4...
Traceback (most recent call last):
  File "/home/fariba/Code/RMG-Py/cantherm.py", line 61, in <module>
    cantherm.execute()
  File "/home/fariba/Code/RMG-Py/rmgpy/cantherm/main.py", line 220, in execute
    self.jobList = self.loadInputFile(self.inputFile)
  File "/home/fariba/Code/RMG-Py/rmgpy/cantherm/main.py", line 202, in loadInputFile
    self.jobList = loadInputFile(self.inputFile)
  File "/home/fariba/Code/RMG-Py/rmgpy/cantherm/input.py", line 360, in loadInputFile
    exec f in global_context, local_context
  File "network1798_2.py", line 214, in <module>
    kinetics = Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""R_Recombination estimate: [C_rad/H2/Ct,H_rad]"""),
  File "/home/fariba/Code/RMG-Py/rmgpy/cantherm/input.py", line 163, in reaction
    raise ValueError('Multiple occurrences of reaction with label {0!r}.'.format(label))
ValueError: Multiple occurrences of reaction with label 'reaction1'.
```

Sure enough, the file contains two `reaction1` reactions (and two `reaction2`s)

Full file is here:

``` python
species(
    label = 'H2CCCH(54)',
    structure = SMILES('C#C[CH2]'),
    E0 = (338.572,'kJ/mol'),
    modes = [
        HarmonicOscillator(frequencies=([3000,3100,440,815,1455,1000,2175,525,432.689,432.698,1818.5],'cm^-1')),
        HinderedRotor(inertia=(0.000900968,'amu*angstrom^2'), symmetry=1, barrier=(0.119627,'kJ/mol'), semiclassical=False),
    ],
    spinMultiplicity = 2,
    opticalIsomers = 1,
    molecularWeight = (39.0559,'amu'),
    collisionModel = LennardJones(sigma=(5.118e-10,'m'), epsilon=(1.97136,'kJ/mol')),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[3.09172,0.0173334,-8.20226e-06,-2.63335e-09,2.66039e-12,40755.9,8.10966], Tmin=(100,'K'), Tmax=(946.058,'K'), comment="""Low temperature range polynomial"""), NASAPolynomial(coeffs=[6.98216,0.00727208,-2.37771e-06,3.99149e-10,-2.69328e-14,39733.9,-11.9545], Tmin=(946.058,'K'), Tmax=(5000,'K'), comment="""High temperature range polynomial""")], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(338.572,'kJ/mol'), comment="""NASA function fitted to Wilhoit function with B = 1000 K. Weighted RMS error = 0.020*R; Unweighted RMS error = 0.016*R; 
DFT_QCI_thermo"""),
)

species(
    label = 'CC#[C](687)',
    structure = SMILES('CC#[C]'),
    E0 = (509.217,'kJ/mol'),
    modes = [
        HarmonicOscillator(frequencies=([2750,2800,2850,1350,1500,750,1050,1375,1000,2175,525],'cm^-1')),
        HinderedRotor(inertia=(2.8481,'amu*angstrom^2'), symmetry=1, barrier=(65.4834,'kJ/mol'), semiclassical=False),
    ],
    spinMultiplicity = 2,
    opticalIsomers = 1,
    molecularWeight = (39.0559,'amu'),
    collisionModel = LennardJones(sigma=(5.118e-10,'m'), epsilon=(1.97136,'kJ/mol')),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[3.19855,0.0160834,-1.31287e-05,7.55468e-09,-1.73804e-12,61274.9,8.39545], Tmin=(100,'K'), Tmax=(1321.16,'K'), comment="""Low temperature range polynomial"""), NASAPolynomial(coeffs=[4.28044,0.00964036,-2.21725e-06,2.33961e-10,-9.36202e-15,61265.5,3.92084], Tmin=(1321.16,'K'), Tmax=(5000,'K'), comment="""High temperature range polynomial""")], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(509.217,'kJ/mol'), comment="""NASA function fitted to Wilhoit function with B = 1000 K. Weighted RMS error = 0.011*R; Unweighted RMS error = 0.006*R; 
Thermo group additivity estimation: group(Cs-CtHHH) + gauche(Cs(RRRR)) + other(R) + group(Ct-Cs) + other(R) + group(Ct-H) + other(R) + radical(Acetyl)"""),
)

species(
    label = 'C3H2(38)',
    structure = SMILES('C(=[CH])=[CH]'),
    E0 = (530.397,'kJ/mol'),
    modes = [
        HarmonicOscillator(frequencies=([540,610,2055,180,180,180,724.081,3251.45,3251.56],'cm^-1')),
    ],
    spinMultiplicity = 3,
    opticalIsomers = 1,
    molecularWeight = (38.048,'amu'),
    collisionModel = LennardJones(sigma=(5.118e-10,'m'), epsilon=(1.97136,'kJ/mol')),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[2.6868,0.0353355,-7.31919e-05,7.04873e-08,-2.45856e-11,63833.3,8.93545], Tmin=(100,'K'), Tmax=(907.561,'K'), comment="""Low temperature range polynomial"""), NASAPolynomial(coeffs=[4.79165,0.0100418,-4.91481e-06,8.87432e-10,-5.68303e-14,64110.8,2.61897], Tmin=(907.561,'K'), Tmax=(5000,'K'), comment="""High temperature range polynomial""")], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(530.397,'kJ/mol'), comment="""NASA function fitted to Wilhoit function with B = 1000 K. Weighted RMS error = 0.019*R; Unweighted RMS error = 0.017*R; 
DFT_QCI_thermo"""),
)

species(
    label = 'H(11)',
    structure = SMILES('[H]'),
    E0 = (211.805,'kJ/mol'),
    spinMultiplicity = 2,
    opticalIsomers = 1,
    molecularWeight = (1.00794,'amu'),
    collisionModel = LennardJones(sigma=(5.949e-10,'m'), epsilon=(3.31997,'kJ/mol')),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[2.5,-2.06395e-14,3.16626e-17,-1.60855e-20,2.52789e-24,25474.2,-0.444973], Tmin=(100,'K'), Tmax=(3203.53,'K'), comment="""Low temperature range polynomial"""), NASAPolynomial(coeffs=[2.5,-8.60783e-12,3.51727e-15,-6.30075e-19,4.17513e-23,25474.2,-0.444973], Tmin=(3203.53,'K'), Tmax=(5000,'K'), comment="""High temperature range polynomial""")], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(211.805,'kJ/mol'), comment="""NASA function fitted to Wilhoit function with B = 1000 K. Weighted RMS error = 0.000*R; Unweighted RMS error = 0.000*R; 
primaryThermoLibrary"""),
)

species(
    label = '[CH2]C#[C](685)',
    structure = SMILES('[CH2]C#[C]'),
    E0 = (583.674,'kJ/mol'),
    modes = [
        HarmonicOscillator(frequencies=([3000,3100,440,815,1455,1000,2175,525],'cm^-1')),
        HinderedRotor(inertia=(1.40849,'amu*angstrom^2'), symmetry=1, barrier=(32.384,'kJ/mol'), semiclassical=False),
    ],
    spinMultiplicity = 3,
    opticalIsomers = 1,
    molecularWeight = (38.048,'amu'),
    collisionModel = LennardJones(sigma=(5.118e-10,'m'), epsilon=(1.97136,'kJ/mol')),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[3.19757,0.0177615,-1.90654e-05,1.13244e-08,-2.73191e-12,70228.5,7.16215], Tmin=(100,'K'), Tmax=(1002.83,'K'), comment="""Low temperature range polynomial"""), NASAPolynomial(coeffs=[5.92594,0.00687878,-2.78724e-06,5.02956e-10,-3.41629e-14,69681.3,-6.00839], Tmin=(1002.83,'K'), Tmax=(5000,'K'), comment="""High temperature range polynomial""")], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(583.674,'kJ/mol'), comment="""NASA function fitted to Wilhoit function with B = 1000 K. Weighted RMS error = 0.011*R; Unweighted RMS error = 0.011*R; 
DFT_QCI_thermo"""),
)

species(
    label = 'C1C=[C]1(686)',
    structure = SMILES('C1C=[C]1'),
    E0 = (502.87,'kJ/mol'),
    spinMultiplicity = 1,
    opticalIsomers = 1,
    molecularWeight = (39.0559,'amu'),
    collisionModel = LennardJones(sigma=(5.118e-10,'m'), epsilon=(1.97136,'kJ/mol')),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[3.60049,0.00147436,3.61189e-05,-4.743e-08,1.81793e-11,60502.3,8.66221], Tmin=(100,'K'), Tmax=(943.575,'K'), comment="""Low temperature range polynomial"""), NASAPolynomial(coeffs=[6.77275,0.00668231,-1.81735e-06,3.26896e-10,-2.55704e-14,59073.2,-10.8587], Tmin=(943.575,'K'), Tmax=(5000,'K'), comment="""High temperature range polynomial""")], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(502.87,'kJ/mol'), comment="""NASA function fitted to Wilhoit function with B = 1000 K. Weighted RMS error = 0.038*R; Unweighted RMS error = 0.034*R; 
Thermo group additivity estimation: group(Cs-(Cds-Cds)(Cds-Cds)HH) + gauche(Cs(RRRR)) + other(R) + group(Cds-CdsCsH) + gauche(CsOsCd) + other(R) + group(Cds-CdsCsH) + gauche(CsOsCd) + other(R) + ring(Cyclopropene) + radical(cyclopropenyl-vinyl)"""),
)

species(
    label = 'CH3(22)',
    structure = SMILES('[CH3]'),
    E0 = (136.55,'kJ/mol'),
    modes = [
        HarmonicOscillator(frequencies=([532.913,1391.1,1391.15,2779.21,3448.42,3448.49],'cm^-1')),
    ],
    spinMultiplicity = 2,
    opticalIsomers = 1,
    molecularWeight = (15.0345,'amu'),
    collisionModel = LennardJones(sigma=(3.758e-10,'m'), epsilon=(1.23553,'kJ/mol')),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[3.94801,0.000827588,8.34936e-06,-9.82641e-09,3.80107e-12,16425.4,0.336652], Tmin=(100,'K'), Tmax=(660.435,'K'), comment="""Low temperature range polynomial"""), NASAPolynomial(coeffs=[3.2217,0.00522646,-1.64125e-06,2.58224e-10,-1.62579e-14,16521.3,3.53938], Tmin=(660.435,'K'), Tmax=(5000,'K'), comment="""High temperature range polynomial""")], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(136.55,'kJ/mol'), comment="""NASA function fitted to Wilhoit function with B = 1000 K. Weighted RMS error = 0.003*R; Unweighted RMS error = 0.004*R; 
DFT_QCI_thermo"""),
)

species(
    label = 'C2(69)',
    structure = SMILES('[C]#[C]'),
    E0 = (825.623,'kJ/mol'),
    modes = [
        HarmonicOscillator(frequencies=([1676.37],'cm^-1')),
    ],
    spinMultiplicity = 3,
    opticalIsomers = 1,
    molecularWeight = (24.0214,'amu'),
    collisionModel = LennardJones(sigma=(4.443e-10,'m'), epsilon=(0.920412,'kJ/mol')),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[3.54696,-0.00113875,4.46275e-06,-3.72915e-09,9.95669e-13,99297.9,4.02567], Tmin=(100,'K'), Tmax=(1198.77,'K'), comment="""Low temperature range polynomial"""), NASAPolynomial(coeffs=[3.0665,0.00180036,-8.86512e-07,1.75326e-10,-1.24655e-14,99317.1,6.03036], Tmin=(1198.77,'K'), Tmax=(5000,'K'), comment="""High temperature range polynomial""")], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(825.623,'kJ/mol'), comment="""NASA function fitted to Wilhoit function with B = 1000 K. Weighted RMS error = 0.003*R; Unweighted RMS error = 0.004*R; 
DFT_QCI_thermo"""),
)

species(
    label = 'N2(5)',
    structure = SMILES('N#N'),
    molecularWeight = (28.0135,'amu'),
    collisionModel = LennardJones(sigma=(4.443e-10,'m'), epsilon=(0.920412,'kJ/mol')),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[3.29868,0.00140824,-3.96322e-06,5.64152e-09,-2.44485e-12,-1020.9,3.95037], Tmin=(298,'K'), Tmax=(1000,'K')), NASAPolynomial(coeffs=[2.92664,0.00148798,-5.68476e-07,1.0097e-10,-6.75335e-15,-922.798,5.98053], Tmin=(1000,'K'), Tmax=(5000,'K'))], Tmin=(298,'K'), Tmax=(5000,'K'), E0=(-8.62478,'kJ/mol'), comment="""primaryThermoLibrary"""),
)

transitionState(
    label = 'TS1',
    E0 = (666.794,'kJ/mol'),
    spinMultiplicity = 1,
    opticalIsomers = 1,
)

transitionState(
    label = 'TS2',
    E0 = (795.478,'kJ/mol'),
    spinMultiplicity = 1,
    opticalIsomers = 1,
)

transitionState(
    label = 'TS3',
    E0 = (564.508,'kJ/mol'),
    spinMultiplicity = 1,
    opticalIsomers = 1,
)

transitionState(
    label = 'TS4',
    E0 = (629.437,'kJ/mol'),
    spinMultiplicity = 1,
    opticalIsomers = 1,
)

transitionState(
    label = 'TS5',
    E0 = (795.478,'kJ/mol'),
    spinMultiplicity = 1,
    opticalIsomers = 1,
)

transitionState(
    label = 'TS6',
    E0 = (962.173,'kJ/mol'),
    spinMultiplicity = 1,
    opticalIsomers = 1,
)

reaction(
    label = 'reaction1',
    reactants = ['H2CCCH(54)'],
    products = ['C3H2(38)', 'H(11)'],
    transitionState = 'TS1',
    kinetics = Arrhenius(A=(5.2e+12,'s^-1'), n=0, Ea=(78447,'cal/mol'), T0=(1,'K'), comment="""Reaction and kinetics from Glarborg/highP."""),
)

reaction(
    label = 'reaction2',
    reactants = ['H(11)', '[CH2]C#[C](685)'],
    products = ['H2CCCH(54)'],
    transitionState = 'TS2',
    kinetics = Arrhenius(A=(1.81e+14,'cm^3/(mol*s)','*|/',3), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(2500,'K'), comment="""R_Recombination estimate: [H_rad,Ct_rad]"""),
)

reaction(
    label = 'reaction3',
    reactants = ['H2CCCH(54)'],
    products = ['C1C=[C]1(686)'],
    transitionState = 'TS3',
    kinetics = Arrhenius(A=(1.05e+08,'s^-1'), n=1.192, Ea=(225.936,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1600,'K'), comment="""Intra_R_Add_Endocyclic estimate: [R3_T,triplebond_intra_H,radadd_intra_cs2H]"""),
)

reaction(
    label = 'reaction4',
    reactants = ['CC#[C](687)'],
    products = ['H2CCCH(54)'],
    transitionState = 'TS4',
    kinetics = Arrhenius(A=(6.13001e+07,'s^-1'), n=1.41407, Ea=(120.219,'kJ/mol'), T0=(1,'K'), comment="""intra_H_migration estimate: [R3H_ST,C_rad_out_2H,Ct_H_out]"""),
)

reaction(
    label = 'reaction1',
    reactants = ['H(11)', '[CH2]C#[C](685)'],
    products = ['CC#[C](687)'],
    transitionState = 'TS5',
    kinetics = Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""R_Recombination estimate: [C_rad/H2/Ct,H_rad]"""),
)

reaction(
    label = 'reaction2',
    reactants = ['CH3(22)', 'C2(69)'],
    products = ['CC#[C](687)'],
    transitionState = 'TS6',
    kinetics = Arrhenius(A=(2e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""R_Recombination estimate: [Y_rad,C_methyl]"""),
)

network(
    label = '1798',
    isomers = [
        'H2CCCH(54)',
        'CC#[C](687)',
    ],
    reactants = [
        ('C3H2(38)', 'H(11)'),
        ('H(11)', '[CH2]C#[C](685)'),
    ],
    bathGas = {
        'N2(5)': 1,
    },
)

pressureDependence(
    label = '1798',
    Tmin = (290,'K'),
    Tmax = (3500,'K'),
    Tcount = 8,
    Tlist = ([292.578,314.289,364.231,459.667,641.642,1011.65,1810.91,3163.57],'K'),
    Pmin = (0.02,'bar'),
    Pmax = (100,'bar'),
    Pcount = 5,
    Plist = ([0.0246349,0.115722,1.41421,17.2828,81.1857],'bar'),
    maximumGrainSize = (1,'kcal/mol'),
    minimumGrainCount = 200,
    method = 'modified strong collision',
    interpolationModel = ('Chebyshev', 6, 4),
    activeKRotor = True,
    activeJRotor = True,
    rmgmode = True,
)

```

**Comment by alongd** [comment]
I think we haven't encountered this issue in the past several years.
We'll keep an eye for duplicate reaction labels in Cantherm, for now I think this issue can be closed.
