### ISSUE TITLE
Sensitivity analysis breaks with new surface algorithm

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#1125]
Running RMG with SA gave the following:
```
Conducting sensitivity analysis of reaction system 2...
Traceback (most recent call last):
  File "/home/alongd/Code/RMG-Py//rmg.py", line 162, in <module>
    rmg.execute(**kwargs)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/main.py", line 781, in execute
    sensWorksheet = sensWorksheet,
  File "rmgpy/solver/base.pyx", line 485, in rmgpy.solver.base.ReactionSystem.simulate (build/pyrex/rmgpy/solver/base.c:23937)
TypeError: simulate() takes at least 9 positional arguments (4 given)
```
The SA call to [simulate](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/rmg/main.py#L760) should be changed according to the changes introduced to base.pyx in https://github.com/ReactionMechanismGenerator/RMG-Py/commit/49823d9e5ff66d55a93928fc46c2ae170c05d995

**Comment by alongd** [comment]
closed via #1127
