### ISSUE TITLE
Pdep Memory Error

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1129]
Simulation:  Cyclopentanone combustion
Output:
...
Warning: Increasing number of grains, decreasing grain size and trying again. (Current badness: 0.5)
Using 66818 grains from -531.64 to 560.40 kJ/mol in steps of 0.02 kJ/mol to compute the k(T,P) values at 343.437 K
Warning: For path reaction CC=C(O)[CH]O[C]=O(9523) <=> CC1[C](O)[CH]OC1=O(19935):
Warning:     Expected kf(343.437 K) = 460.494
Warning:       Actual kf(343.437 K) = 850.108
Warning:     Expected Keq(343.437 K) = 9.38766e-06
Warning:       Actual Keq(343.437 K) = 0
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "CC=C(O)[CH]O[C]=O(9523) <=> $
Warning: For path reaction [O]C1CC1[CH]C(=O)O(9091) <=> [O]C1[CH]C1CC(=O)O(20267):
Warning:     Expected kf(343.437 K) = 4.98344e-18
Warning:       Actual kf(343.437 K) = 6.42041e-18
Warning:     Expected Keq(343.437 K) = 2
Warning:       Actual Keq(343.437 K) = 0
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[O]C1CC1[CH]C(=O)O(9091) <=>$
Traceback (most recent call last):
  File "/home/mattsj/rmgcode/RMG-Py/rmg.py", line 162, in <module>
    rmg.execute(**kwargs)
  File "/home/mattsj/rmgcode/RMG-Py/rmgpy/rmg/main.py", line 687, in execute
    self.reactionModel.enlarge(objectToEnlarge)
  File "/home/mattsj/rmgcode/RMG-Py/rmgpy/rmg/model.py", line 681, in enlarge
    self.updateUnimolecularReactionNetworks()
  File "/home/mattsj/rmgcode/RMG-Py/rmgpy/rmg/model.py", line 1498, in updateUnimolecularReactionNetworks
    network.update(self, self.pressureDependence)
  File "/home/mattsj/rmgcode/RMG-Py/rmgpy/rmg/pdep.py", line 564, in update
    K = self.calculateRateCoefficients(Tlist, Plist, method)
  File "/home/mattsj/rmgcode/RMG-Py/rmgpy/pdep/network.py", line 210, in calculateRateCoefficients
    self.setConditions(T, P)
  File "/home/mattsj/rmgcode/RMG-Py/rmgpy/pdep/network.py", line 345, in setConditions
    self.calculateCollisionModel()
  File "/home/mattsj/rmgcode/RMG-Py/rmgpy/pdep/network.py", line 729, in calculateCollisionModel
    Mcoll = numpy.zeros((Nisom,Ngrains,NJ,Ngrains,NJ), numpy.float64)
MemoryError
 dbolsm(). more than (i1)
 dbolsm(). more than (i1)
 dbolsm(). more than (i1)
 dbolsm(). more than (i1)
 dbolsm(). more than (i1)
 dbolsm(). more than (i1)
 dbolsm(). more than (i1)
 dbolsm(). more than (i1)
 dbolsm(). more than (i1)
 dbolsm(). more than (i1)
 dbolsm(). more than (i1)
 dbolsm(). more than (i1)
 dbolsm(). more than (i1)
 dbolsm(). more than (i1)
 dbolsm(). more than (i1)
...

My pdep block was:    
pressureDependence(
        #two methods available: 'modified strong collision' is faster and less accurate than 'reservoir state'
        method='modified strong collision',
        #these two categories determine how fine energy is descretized.
        #more grains increases accuracy but takes longer
        maximumGrainSize=(0.5,'kcal/mol'),
        minimumNumberOfGrains=250,
        #the conditions for the rate to be output over
        #parameter order is: low_value, high_value, units, internal points
        temperatures=(300,2200,'K',2),
        pressures=(0.01,100,'bar',3),
        #The two options for interpolation are 'PDepArrhenius' (no extra arguments) and 
        #'Chebyshev' which is followed by the number of basis sets in 
        #Temperature and Pressure. These values must be less than the number of 
        #internal points specified above
        interpolation=('Chebyshev', 6, 4),
        #turns off pressure dependence for molecules with number of atoms greater than the number specified below
        #this is due to faster internal rate of energy transfer for larger molecules
        maximumAtoms=15,
 )

**Comment by mjohnson541** [comment]
It seems that this is likely due to Mcoll = numpy.zeros((Nisom,Ngrains,NJ,Ngrains,NJ), numpy.float64) being too large.  

Mcoll is filled by: 
for i, isomer in enumerate(self.isomers):
            collFreq[i] = isomer.calculateCollisionFrequency(self.T, self.P, self.bathGas)
            Mcoll[i,:,:,:,:] = collFreq[i] * isomer.generateCollisionMatrix(self.T, self.densStates[i,:,:], self.Elist, self.Jlist)
                        
I've looked up generateCollisionMatrix in collision.pyx, but I'm having trouble telling if a sparse representation might work well.  Another alternative might be to automatically increase the grain size if the number of isomers gets sufficiently high to keep the tensor small, however, that could adversely affect the accuracy of pdep.
