### ISSUE TITLE
Uncertainty extractSourcesFromModel broken

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1158]
uncertainty.extractSourcesFromModel() is failing to properly parse the kinetics comment in Family.getSourcesForTemplate

Traceback (most recent call last):
  File "QueueGenerator.py", line 243, in <module>
    thermoUnc = getUncertainties(runDir)
  File "QueueGenerator.py", line 176, in getUncertainties
    uncertainty.extractSourcesFromModel()
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/tools/uncertainty.py", line 378, in extractSourcesFromModel
    source = self.database.kinetics.extractSourceFromComments(reaction)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/data/kinetics/database.py", line 576, in extractSourceFromComments
    training, dataSource = self.families[reaction.family].extractSourceFromComments(reaction)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/data/kinetics/family.py", line 2256, in extractSourceFromComments
    rules, trainingEntries = self.getSourcesForTemplate(template)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/data/kinetics/family.py", line 2167, in getSourcesForTemplate
    entryNestedList = eval(evalCommentString)
  File "<string>", line 1
    O_sec_rad;HCO from training reaction 11
             ^
SyntaxError: invalid syntax

**Comment by mliu49** [comment]
Any chance you could post the comment that led to this error?

**Comment by mjohnson541** [comment]
O_sec_rad;HCO from training reaction 11
Estimated using template [O_sec_rad;HCO] for rate rule [O_rad/OneDe;HCO]
Euclidian distance = 1.0

**Comment by mjohnson541** [comment]
Never mind, I think this is actually due to some differences when I ran the original model.  But on master I'm still getting an error nearby:  

Traceback (most recent call last):
  File "QueueGenerator.py", line 249, in <module>
    thermoUnc = getUncertainties(runDir)
  File "QueueGenerator.py", line 182, in getUncertainties
    uncertainty.extractSourcesFromModel()
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/tools/uncertainty.py", line 378, in extractSourcesFromModel
    source = self.database.kinetics.extractSourceFromComments(reaction)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/data/kinetics/database.py", line 576, in extractSourceFromComments
    training, dataSource = self.families[reaction.family].extractSourceFromComments(reaction)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/data/kinetics/family.py", line 2262, in extractSourceFromComments
    rules, trainingEntries = self.getSourcesForTemplate(template)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/data/kinetics/family.py", line 2155, in getSourcesForTemplate
    raise Exception('Could not parse unexpected line found in kinetics comment: {}'.format(comment))
Exception: Could not parse unexpected line found in kinetics comment: Estimated using an average for rate rule [R_ROR;R1_doublebond;R2_doublebond;R_O_H]

to be precise the comment is:  
Estimated using an average for rate rule [R_ROR;R1_doublebond;R2_doublebond;R_O_H]

I'm going to take a look at how this comment is possible.

**Comment by mjohnson541** [comment]
Just tested again and I'm getting the original error again:  

O_sec_rad;HCO from training reaction 11
Estimated using template [O_sec_rad;HCO] for rate rule [O_rad/OneDe;HCO]
Euclidian distance = 1.0

**Comment by mliu49** [comment]
Should be fixed by #1165.
