### ISSUE TITLE
Restart broken?

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#117]
``` python
Loading previous restart file...
Saving current model to HTML file...
Saving current model to Chemkin file...
Chemkin file contains 0 reactions.
Chemkin file contains 2434 reactions.
Saving restart file...
Conducting simulation of reaction system 1...
Traceback (most recent call last):
  File "/Users/rwest/Code/RMG-Py/rmg.py", line 144, in <module>
    rmg.execute(args)
  File "/Users/rwest/Code/RMG-Py/rmgpy/rmg/main.py", line 370, in execute
    relativeTolerance = self.relativeTolerance,
  File "base.pyx", line 108, in rmgpy.solver.base.ReactionSystem.simulate (build/pyrex/rmgpy/solver/base.c:5343)
  File "base.pyx", line 144, in rmgpy.solver.base.ReactionSystem.simulate (build/pyrex/rmgpy/solver/base.c:3109)
  File "simple.pyx", line 136, in rmgpy.solver.simple.SimpleReactor.initializeModel (build/pyrex/rmgpy/solver/simple.c:3021)
  File "/Users/rwest/Code/RMG-Py/rmgpy/rmg/pdep.py", line 163, in getLeakCoefficient
    if len(rxn.products) == 1 and rxn.products[0] not in self.explored:
AttributeError: 'list' object has no attribute 'products'
```

Two observations:
1) The first thing it does after loading a restart file is save the HTML and chemkin (fair enough) then save the restart file again (seems like a waste of time tome!).

2) Why is `rxn` a `list` object in line 163 of rmgpy/rmg/pdep.py after loading the restart?

**Comment by bslakman** [comment]
Got the following error on trying to make restart file, with both minimal and liquid phase const. concentration examples:
```
Traceback (most recent call last):
  File "/Users/belinda/Code/RMG-Py/rmg.py", line 165, in <module>
    rmg.execute(inputFile, output_dir, **kwargs)
  File "/Users/belinda/Code/RMG-Py/rmgpy/rmg/main.py", line 652, in execute
    self.saveEverything()
  File "/Users/belinda/Code/RMG-Py/rmgpy/rmg/main.py", line 796, in saveEverything
    self.notify()
  File "/Users/belinda/Code/RMG-Py/rmgpy/util.py", line 106, in notify
    observer.update(self)
  File "/Users/belinda/Code/RMG-Py/rmgpy/restart.py", line 93, in update
    save(rmg)
  File "/Users/belinda/Code/RMG-Py/rmgpy/restart.py", line 42, in save
    delay=0 if rmg.done else rmg.saveRestartPeriod.value_si
  File "/Users/belinda/Code/RMG-Py/rmgpy/restart.py", line 65, in saveRestartFile
    cPickle.dump(reactionModel, f, cPickle.HIGHEST_PROTOCOL)
  File "/Users/belinda/Code/RMG-Py/rmgpy/data/kinetics/family.py", line 126, in __reduce__
    self.reverse,
AttributeError: 'TemplateReaction' object has no attribute 'reverse'
```

**Comment by JacksonBurns** [comment]
This issue refers to the Python 2.7 version of RMG. Closing as stale.
