### ISSUE TITLE
Parallel error and missing parallel unit tests

### ISSUE THREAD

**Issue by cgrambow** [ReactionMechanismGenerator/RMG-Py#1197]
Running RMG in parallel currently results in this error
```python
Traceback (most recent call last):
  File "/home/cgrambow/.conda/envs/rmg_env/lib/python2.7/site-packages/scoop-0.7.2.0-py2.7.egg/scoop/_control.py", line 150, in runFuture
    future.resultValue = future.callable(*future.args, **future.kargs)
  File "/home/cgrambow/.conda/envs/rmg_env/lib/python2.7/runpy.py", line 252, in run_path
    return _run_module_code(code, init_globals, run_name, path_name)
  File "/home/cgrambow/.conda/envs/rmg_env/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/home/cgrambow/.conda/envs/rmg_env/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/cgrambow/Code/RMG-Py/rmg.py", line 162, in <module>
    rmg.execute(**kwargs)
  File "/home/cgrambow/Code/RMG-Py/rmgpy/rmg/main.py", line 569, in execute
    bimolecularReact=self.bimolecularReact)
  File "/home/cgrambow/Code/RMG-Py/rmgpy/rmg/model.py", line 667, in enlarge
    self.processNewReactions([rxn], spc)
  File "/home/cgrambow/Code/RMG-Py/rmgpy/rmg/model.py", line 734, in processNewReactions
    rxn, isNew = self.makeNewReaction(rxn)
  File "/home/cgrambow/Code/RMG-Py/rmgpy/rmg/model.py", line 484, in makeNewReaction
    reactants = [self.makeNewSpecies(reactant)[0] for reactant in forward.reactants]
  File "/home/cgrambow/Code/RMG-Py/rmgpy/rmg/model.py", line 338, in makeNewSpecies
    if spec.thermo and spec.thermo.label != '': #check if thermo libraries have a name for it
AttributeError: 'Future' object has no attribute 'label'
```
which does not occur in serial. The traceback does not seem super helpful, so I'm not quite sure what's going on.

Additionally, I noticed that parallel unit tests `rmgpy/rmg/parreactTest.py` and `rmgpy/thermo/thermoengineTest.py` are not currently being used. I tested them with `nosetests` by commenting out the `work_in_progress` decorators and they run fine, but that doesn't mean they're complete. Especially for `thermoengineTest.py`, it seems `funcSubmitGet` is not yet being tested and perhaps both unit test files are missing additional methods.

**Comment by mliu49** [comment]
Here's my naive guess at the cause (with how sure I am that the statements are true).
- Thermo generation for species is parallelized via the `submit()` function, which sends thermo jobs to child processes (90% sure).
- The `Future` object some sort of placeholder that waits for a child process to return something; in this case, a thermo data object (10% sure).
- The `if spec.thermo and ...` line is run right after the `submit()` is used to get thermo, so perhaps the thermo hasn't been returned yet by the child process and the `spec.thermo` attribute still holds the `Future` object (30% sure).
