### ISSUE TITLE
thermodynamic filtering error

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1210]
Reached maximum number of edge species
Attempting to remove excess edge species with Thermodynamic filtering
Traceback (most recent call last):
  File "/home/mattsj/rmgcode/RMG-Py/rmg.py", line 173, in <module>
    main()
  File "/home/mattsj/rmgcode/RMG-Py/rmg.py", line 167, in main
    rmg.execute(**kwargs)
  File "/home/mattsj/rmgcode/RMG-Py/rmgpy/rmg/main.py", line 736, in execute
    self.reactionModel.thermoFilterDown(maximumEdgeSpecies=modelSettings.maximumEdgeSpecies)
  File "/home/mattsj/rmgcode/RMG-Py/rmgpy/rmg/model.py", line 1069, in thermoFilterDown
    Gfs = numpy.array([spc.thermo.getFreeEnergy(Tmax) for spc in spcs])
  File "rmgpy/thermo/nasa.pyx", line 287, in rmgpy.thermo.nasa.NASA.getFreeEnergy (build/pyrex/rmgpy/thermo$
  File "rmgpy/thermo/nasa.pyx", line 292, in rmgpy.thermo.nasa.NASA.getFreeEnergy (build/pyrex/rmgpy/thermo$
  File "rmgpy/thermo/nasa.pyx", line 264, in rmgpy.thermo.nasa.NASA.selectPolynomial (build/pyrex/rmgpy/the$
ValueError: No valid NASA polynomial at temperature 0 K.

**Comment by mjohnson541** [comment]
This occurs because calling thermoFilterDown when setThermodynamicFilteringParameters hasn't been called leaves the filtering temperature Tmax set to 0 K, which results in an error when the Gibbs energy is calculated, because our thermo generation doesn't include a valid NASA polynomial for 0 K.
