### ISSUE TITLE
CanTherm CH3OH+HCO example crashes with a TypeError

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#1239]
The `reactions/CH3OH+HCO` CanTherm example crashes with the following trace:
```
Saving kinetics for ch3oh + hco <=> ch3oh + hco...
Traceback (most recent call last):
  File "/home/alongd/Code/RMG-Py//cantherm.py", line 61, in <module>
    cantherm.execute()
  File "/home/alongd/Code/RMG-Py/rmgpy/cantherm/main.py", line 269, in execute
    job.execute(outputFile=outputFile, plot=self.plot)
  File "/home/alongd/Code/RMG-Py/rmgpy/cantherm/kinetics.py", line 127, in execute
    self.save(outputFile)
  File "/home/alongd/Code/RMG-Py/rmgpy/cantherm/kinetics.py", line 227, in save
    kinetics0rev = Arrhenius().fitToData(Tlist, numpy.array(k0revs), kunits=self.krunits)
TypeError: Argument 'Tlist' has incorrect type (expected numpy.ndarray, got list)
```

Looks like the default values assignment [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/cantherm/kinetics.py#L152)
```
if Tlist is None:
    Tlist = 1000.0/numpy.arange(0.4, 3.35, 0.05)
```
generate an unexpected var type.

(This example doesn't crash when a `Tlist` is specified in the kinetics block)

**Comment by alongd** [comment]
solved via #1244
