### ISSUE TITLE
unable to calculate degeneracy error for simple reaction

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1249]
I got the unable to calculate degeneracy error for the reaction:  

[CH3] + CH2O <=> CO[CH2]

Traceback (most recent call last):
  File "/home/mattsj/rmgcode/RMG-Py/rmg.py", line 173, in <module>
    main()
  File "/home/mattsj/rmgcode/RMG-Py/rmg.py", line 167, in main
    rmg.execute(**kwargs)
  File "/home/mattsj/rmgcode/RMG-Py/rmgpy/rmg/main.py", line 532, in execute
    self.initialize(**kwargs)
  File "/home/mattsj/rmgcode/RMG-Py/rmgpy/rmg/main.py", line 394, in initialize
    self.loadDatabase()
  File "/home/mattsj/rmgcode/RMG-Py/rmgpy/rmg/main.py", line 323, in loadDatabase
    family.addKineticsRulesFromTrainingSet(thermoDatabase=self.database.thermo)
  File "/home/mattsj/rmgcode/RMG-Py/rmgpy/data/kinetics/family.py", line 1098, in addKineticsRulesFromTrainingSet
    new_degeneracy = self.calculateDegeneracy(item)
  File "/home/mattsj/rmgcode/RMG-Py/rmgpy/data/kinetics/family.py", line 1581, in calculateDegeneracy
    'but generated {2}').format(reaction, self.label, len(reactions)))
rmgpy.exceptions.KineticsError: Unable to calculate degeneracy for reaction <Molecule "[CH3]"> + <Molecule "C=O"> <=> <Molecule "[CH2]OC"> in reaction family R_Addition_MultipleBond. 
 Expected 1 reaction but generated 0

**Comment by mjohnson541** [comment]
Nvm this was a database issue
