### ISSUE TITLE
Generate Reactions Example is Broken (No module generate_aromatic_resonance_structures)

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/RMG-Py#1250]
I am opening this issue here just so it is documented, though I am pretty sure I can figure out how to update this script. If you execute `run.sh` in the example folder for generate_reactions, the script errors with the following message:

```
Traceback (most recent call last):
  File "../../scripts/generateReactions.py", line 38, in <module>
    import rmgpy.tools.generate_reactions as generate_reactions
  File "/home/mark/RMG/RMG-Py/rmgpy/tools/generate_reactions.py", line 42, in <module>
    from rmgpy.rmg.main import initializeLog, RMG
  File "/home/mark/RMG/RMG-Py/rmgpy/rmg/main.py", line 48, in <module>
    from rmgpy.solver.base import TerminationTime, TerminationConversion
  File "/home/mark/RMG/RMG-Py/rmgpy/solver/__init__.py", line 31, in <module>
    from .base import ReactionSystem, TerminationTime, TerminationConversion
  File "rmgpy/solver/base.pyx", line 55, in init rmgpy.solver.base
  File "/home/mark/RMG/RMG-Py/rmgpy/chemkin.py", line 46, in <module>
    from rmgpy.rmg.model import Species
  File "/home/mark/RMG/RMG-Py/rmgpy/rmg/model.py", line 47, in <module>
    from rmgpy.thermo.thermoengine import submit
  File "/home/mark/RMG/RMG-Py/rmgpy/thermo/thermoengine.py", line 33, in <module>
    from rmgpy.data.rmg import getDB
  File "/home/mark/RMG/RMG-Py/rmgpy/data/rmg.py", line 42, in <module>
    from rmgpy.data.kinetics.database import KineticsDatabase
  File "/home/mark/RMG/RMG-Py/rmgpy/data/kinetics/__init__.py", line 33, in <module>
    from .database import *
  File "/home/mark/RMG/RMG-Py/rmgpy/data/kinetics/database.py", line 46, in <module>
    from .family import  KineticsFamily
  File "/home/mark/RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 46, in <module>
    from rmgpy.molecule.resonance import generate_aromatic_resonance_structures
ImportError: cannot import name generate_aromatic_resonance_structures
```

**Comment by amarkpayne** [comment]
Simple make clean error, false alarm
