### ISSUE TITLE
The methane test fails on master

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#1253]
The [methane test](https://github.com/ReactionMechanismGenerator/RMG-tests/blob/master/examples/rmg/methane/input.py) fails on the current master (1123fcb ; https://github.com/ReactionMechanismGenerator/RMG-database/commit/e2f637307c8aef3c0e05730c73d661b55d936e05) with the following trace:

```
Error: Expecting one matching reverse reaction, not zero in reaction family H_Abstraction for forward reaction [H][H] + [CH-]=[N+]=[N] <=> [N+](=N)=[CH-] + [H].

Error: There is likely a bug in the RMG-database kinetics reaction family involving a missing group, missing atomlabels, forbidden groups, etc.
Reactant
[H][H]
1 H u0 p0 c0 {2,S}
2 H u0 p0 c0 {1,S}

Reactant
[CH-]=[N+]=[N]
multiplicity 2
1 C u0 p1 c-1 {2,D} {3,S}
2 N u0 p0 c+1 {1,D} {4,D}
3 H u0 p0 c0 {1,S}
4 N u1 p1 c0 {2,D}


[CH-]=[N+]=[N]
multiplicity 2
1 C u1 p1 c-1 {2,S} {3,S}
2 N u0 p0 c+1 {1,S} {4,T}
3 H u0 p0 c0 {1,S}
4 N u0 p1 c0 {2,T}

Product
[N+](=N)=[CH-]
1    N u0 p0 c+1 {2,D} {3,D}
2    N u0 p1 c0 {1,D} {4,S}
3 *1 C u0 p1 c-1 {1,D} {5,S}
4    H u0 p0 c0 {2,S}
5 *2 H u0 p0 c0 {3,S}


[N+](=N)=[CH-]
1    N u0 p0 c+1 {2,T} {3,S}
2    N u0 p0 c+1 {1,T} {4,S}
3 *1 C u0 p2 c-2 {1,S} {5,S}
4    H u0 p0 c0 {2,S}
5 *2 H u0 p0 c0 {3,S}

Product
[H]
multiplicity 2
1 *3 H u1 p0 c0

Error: Debugging why no reaction was found...
Error: Checking whether the family's forbidden species have affected reaction generation...
Error: Still experiencing error: Expecting one matching reverse reaction, not 0 in reaction family H_Abstraction for forward reaction [H][H] + [CH-]=[N+]=[N] <=> [N+](=N)=[CH-] + [H].

Traceback (most recent call last):
  File "/home/alongd/Code/RMG-Py/rmgpy/scoop_framework/util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/react.py", line 74, in reactSpecies
    reactions = getDB('kinetics').generate_reactions_from_families(speciesTuple)
  File "/home/alongd/Code/RMG-Py/rmgpy/data/kinetics/database.py", line 458, in generate_reactions_from_families
    successful = family.addReverseAttribute(rxn)
  File "/home/alongd/Code/RMG-Py/rmgpy/data/kinetics/family.py", line 1516, in addReverseAttribute
    raise KineticsError("Did not find reverse reaction in reaction family {0} for reaction {1}.".format(self.label, str(rxn)))
KineticsError: Did not find reverse reaction in reaction family H_Abstraction for reaction [H][H] + [CH-]=[N+]=[N] <=> [N+](=N)=[CH-] + [H].

Traceback (most recent call last):
  File "/home/alongd/Code/RMG-Py//rmg.py", line 173, in <module>
    main()
  File "/home/alongd/Code/RMG-Py//rmg.py", line 167, in main
    rmg.execute(**kwargs)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/main.py", line 567, in execute
    bimolecularReact=self.bimolecularReact)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/model.py", line 644, in enlarge
    rxns = reactAll(self.core.species, numOldCoreSpecies, unimolecularReact, bimolecularReact)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/react.py", line 133, in reactAll
    rxns = list(react(*spcTuples))
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/react.py", line 59, in react
    spcTuples)
  File "/home/alongd/Code/RMG-Py/rmgpy/scoop_framework/util.py", line 154, in map_
    return map(WorkerWrapper(args[0]), *args[1:], **kwargs)
  File "/home/alongd/anaconda2/envs/rmg_env/lib/python2.7/site-packages/scoop-0.7.2.0-py2.7.egg/scoop/fallbacks.py", line 49, in wrapper
  File "/home/alongd/Code/RMG-Py/rmgpy/scoop_framework/util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/react.py", line 74, in reactSpecies
    reactions = getDB('kinetics').generate_reactions_from_families(speciesTuple)
  File "/home/alongd/Code/RMG-Py/rmgpy/data/kinetics/database.py", line 458, in generate_reactions_from_families
    successful = family.addReverseAttribute(rxn)
  File "/home/alongd/Code/RMG-Py/rmgpy/data/kinetics/family.py", line 1516, in addReverseAttribute
    raise KineticsError("Did not find reverse reaction in reaction family {0} for reaction {1}.".format(self.label, str(rxn)))
rmgpy.exceptions.KineticsError: Did not find reverse reaction in reaction family H_Abstraction for reaction [H][H] + [CH-]=[N+]=[N] <=> [N+](=N)=[CH-] + [H].
```

I suspect the problem is with the product
```
Product
[N+](=N)=[CH-]
1    N u0 p0 c+1 {2,D} {3,D}
2    N u0 p1 c0 {1,D} {4,S}
3 *1 C u0 p1 c-1 {1,D} {5,S}
4    H u0 p0 c0 {2,S}
5 *2 H u0 p0 c0 {3,S}

[N+](=N)=[CH-]
1    N u0 p0 c+1 {2,T} {3,S}
2    N u0 p0 c+1 {1,T} {4,S}
3 *1 C u0 p2 c-2 {1,S} {5,S}
4    H u0 p0 c0 {2,S}
5 *2 H u0 p0 c0 {3,S}
```
where the second structure has another charge separation with a `c -2` on the carbon, which gets two lone pairs.

This does NOT crush on the chargedAT (#1206) branch (soon to be merged in), since it does not allow `C ux p2 cx`.

**Comment by alongd** [comment]
closed via #1206
