### ISSUE TITLE
Ranged Reactor Sensitivity Analysis from Script

### ISSUE THREAD

**Issue by mjohnson541** [ReactionMechanismGenerator/RMG-Py#1392]
While sensitivity analysis works with ranged reactors when done at the end of the job it fails when done from the simulate.py script giving the traceback: 
  
rmgpy.exceptions.ReactionError: Got equilibrium constant of 0
Exception rmgpy.exceptions.ReactionError: ReactionError('Got equilibrium constant of 0',) in 'rmgpy.reaction.Reaction.getEquilibriumConstant' ignored
ERROR:root:Problem with reactant Species(index=12, label="C[O]", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[4.00131,-0.00415619,3.2633e-05,-3.71084e-08,1.35694e-11,-6.15038,6.8139], Tmin=(100,'K'), Tmax=(916.91,'K')), NASAPolynomial(coeffs=[4.01637,0.00626787,-1.58053e-06,2.4457e-10,-1.70307e-14,-449.865,4.33797], Tmin=(916.91,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), comment="""Thermo group additivity estimation: group(O2s-CsH) + group(Cs-OsHHH) + radical(H3COJ)"""), molecule=[Molecule(SMILES="C[O]")]) in reaction C[O](12) + CO[O](10) <=> COO(15) + C=O(45)
Traceback (most recent call last):
  File "rmgpy/reaction.py", line 501, in rmgpy.reaction.Reaction.getFreeEnergyOfReaction
  File "rmgpy/species.py", line 403, in rmgpy.species.Species.getFreeEnergy
  File "rmgpy/thermo/nasa.pyx", line 294, in rmgpy.thermo.nasa.NASA.getFreeEnergy
  File "rmgpy/thermo/nasa.pyx", line 299, in rmgpy.thermo.nasa.NASA.getFreeEnergy
  File "rmgpy/thermo/nasa.pyx", line 271, in rmgpy.thermo.nasa.NASA.selectPolynomial
ValueError: No valid NASA polynomial at temperature 2.21845e-314 K.
Exception ValueError: ValueError('No valid NASA polynomial at temperature 2.21845e-314 K.',) in 'rmgpy.reaction.Reaction.getFreeEnergyOfReaction' ignored
ERROR:root:Problem with reactant Species(index=7, label="H", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[2.5,-1.08861e-13,1.40735e-16,-5.92259e-20,7.66587e-24,25474.2,-0.444973], Tmin=(100,'K'), Tmax=(4484.82,'K')), NASAPolynomial(coeffs=[2.50004,-3.40586e-08,1.10997e-11,-1.60664e-15,8.71472e-20,25474.2,-0.445222], Tmin=(4484.82,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), comment="""Thermo library: primaryThermoLibrary"""), molecule=[Molecule(SMILES="[H]")]) in reaction H(7) + C=O(45) <=> C[O](12)
Traceback (most recent call last):
  File "rmgpy/reaction.py", line 501, in rmgpy.reaction.Reaction.getFreeEnergyOfReaction
  File "rmgpy/species.py", line 403, in rmgpy.species.Species.getFreeEnergy
  File "rmgpy/thermo/nasa.pyx", line 294, in rmgpy.thermo.nasa.NASA.getFreeEnergy
  File "rmgpy/thermo/nasa.pyx", line 299, in rmgpy.thermo.nasa.NASA.getFreeEnergy
  File "rmgpy/thermo/nasa.pyx", line 271, in rmgpy.thermo.nasa.NASA.selectPolynomial
ValueError: No valid NASA polynomial at temperature 2.21845e-314 K.
Exception ValueError: ValueError('No valid NASA polynomial at temperature 2.21845e-314 K.',) in 'rmgpy.reaction.Reaction.getFreeEnergyOfReaction' ignored
rmgpy.exceptions.ReactionError: Got equilibrium constant of 0
Exception rmgpy.exceptions.ReactionError: ReactionError('Got equilibrium constant of 0',) in 'rmgpy.reaction.Reaction.getEquilibriumConstant' ignored
Traceback (most recent call last):
  File "/Users/mattjohnson/RMGCODE/RMG-Py/scripts/simulate.py", line 74, in <module>
    main()
  File "/Users/mattjohnson/RMGCODE/RMG-Py/scripts/simulate.py", line 69, in main
    run_simulation(inputFile, chemkinFile, dictFile, diffusionLimited=dflag, checkDuplicates=checkDuplicates)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/tools/simulate.py", line 152, in run_simulation
    simulate(rmg,diffusionLimited)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/tools/simulate.py", line 135, in simulate
    simulatorSettings=simulatorSettings,
  File "rmgpy/solver/base.pyx", line 534, in rmgpy.solver.base.ReactionSystem.simulate
  File "rmgpy/solver/base.pyx", line 624, in rmgpy.solver.base.ReactionSystem.simulate
  File "rmgpy/solver/simple.pyx", line 192, in rmgpy.solver.simple.SimpleReactor.initializeModel
  File "rmgpy/solver/base.pyx", line 445, in rmgpy.solver.base.ReactionSystem.set_initial_derivative
  File "rmgpy/solver/simple.pyx", line 498, in rmgpy.solver.simple.SimpleReactor.residual
  File "rmgpy/solver/base.pyx", line 1164, in rmgpy.solver.base.ReactionSystem.computeRateDerivative
AttributeError: 'NoneType' object has no attribute 'value_si'

**Comment by mjohnson541** [comment]
For those users suffering from this bug just use an input file with fixed reactors (and the chemkin and species dictionary files generated from the ranged reactor run).
