### ISSUE TITLE
Kinetics AttributeError while making seed mechanism

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#1437]
### Bug Description
After terminating a simple ethane oxidation job, RMG crushed while making the seed mechanism with the trace:
```
Saving current model core to Chemkin file...
Chemkin file contains 642 reactions.
Saving current model to verbose Chemkin file...
Chemkin file contains 642 reactions.
Saving current model core to HTML file...
Updating RMG execution statistics...
    Execution time (DD:HH:MM:SS): 00:00:11:31
    Memory used: 621.43 MB

Making seed mechanism...
Performing final model checks...
Traceback (most recent call last):
  File "/home/alongd/Code/RMG-Py//rmg.py", line 173, in <module>
    main()
  File "/home/alongd/Code/RMG-Py//rmg.py", line 167, in main
    rmg.execute(**kwargs)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/main.py", line 917, in execute
    self.check_model()
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/main.py", line 962, in check_model
    p_min=self.Pmin, p_max=self.Pmax)
  File "rmgpy/reaction.py", line 1149, in rmgpy.reaction.Reaction.check_collision_limit_violation
  File "rmgpy/reaction.py", line 1182, in rmgpy.reaction.Reaction.check_collision_limit_violation
  File "rmgpy/reaction.py", line 701, in rmgpy.reaction.Reaction.generateReverseRateCoefficient
  File "rmgpy/reaction.py", line 701, in rmgpy.reaction.Reaction.generateReverseRateCoefficient
  File "rmgpy/reaction.py", line 766, in rmgpy.reaction.Reaction.generateReverseRateCoefficient
AttributeError: 'rmgpy.kinetics.arrhenius.MultiArrhenius' object has no attribute 'T0'
```

### How To Reproduce
input file attached (run on current master branches)
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2226069/input.txt)

**Comment by mliu49** [comment]
Fixed by #1659
