### ISSUE TITLE
Liquid reactor system shows many ZeroDivisionErrors

### ISSUE THREAD

**Issue by cgrambow** [ReactionMechanismGenerator/RMG-Py#1479]
I am simulating a very large system with the liquid reactor and am encountering the following error multiple times during simulation:
```python
Traceback (most recent call last):
  File "/home/cgrambow/Code/RMG-Py/rmgpy/kinetics/diffusionLimited.py", line 91, in getEffectiveRate
    k_diff = self.getDiffusionLimit(T, reaction, forward=False)
  File "/home/cgrambow/Code/RMG-Py/rmgpy/kinetics/diffusionLimited.py", line 127, in getDiffusionLimit
    diff = soluteData.getStokesDiffusivity(T, self.getSolventViscosity(T))
  File "/home/cgrambow/Code/RMG-Py/rmgpy/data/solvation.py", line 220, in getStokesDiffusivity
    D = constants.kB*T/6/constants.pi/solventViscosity/radius # m2/s
ZeroDivisionError: float division by zero
Exception ZeroDivisionError: 'float division by zero' in 'rmgpy.reaction.Reaction.getRateCoefficient' ignored
```
I am not sure yet how to easily reproduce this without running my large system. It also doesn't cause the RMG job to terminate, but I'm not sure how much I can trust the results. Has anyone seen this?

**Comment by cgrambow** [comment]
Solved with ReactionMechanismGenerator/RMG-database#300.
