### ISSUE TITLE
Memory handling for collision matrix doesn't seem to work correctly

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#1499]
### Bug Description
When evaluating rate coefficients for a pdep network, if the collision matrix becomes too large, we will now reduce the number of grains to avoid a memory error (introduced in #1131). However, this seems to lead to other problems downstream.

First, it doesn't seem like the class attribute `Network.Ngrains` is updated, which resulted in an index error in [msc.pyx line 127](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/pdep/msc.pyx#L127). Updating the value of Ngrains in `Network.calculateCollisionModel()` resolved this issue.

With that fix, the network then encountered an error in [msc.pyx line 155](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/pdep/msc.pyx#L155) where the shapes of `Gnj` and `pa` were not broadcastable. While `pa` is initialized within that function, `Gnj` is generated by `Network.calculateMicrocanonicalRates()`, which is done before reaching `Network.calculateCollisionModel()`. Therefore, the size of `Gnj` would be based on the original `Ngrains`, before it is reduced by `calculateCollisionModel()`.

### How To Reproduce
This pdep network should be able to reproduce this error if run with CanTherm (change the extension to .py). It was automatically generated during an RMG job. We tested it on a Ubuntu 16 virtual machine with 16 GB of memory.

[network2580_40.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2503543/network2580_40.txt)

### Expected Behavior
I think the best option might be to fail gracefully? I'm not sure if reducing the number of grains is really the correct approach. We increase the number of grains by factors of 2 if we are unable to reduce the "badness" to a sufficient amount. Then, if we reduce the grains by a factor of 2, it would just put us back to where we were.

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): Ubuntu 16
 - Installation method: source with anaconda
 - RMG version information: custom branches based on master

### Additional Context
This was encountered by @jimchu10. I worked with him to debug the issue.

Also, the job was originally run on RMG server, where it stopped while evaluating this network without any messages. I'm wondering if it could have encountered a catastrophic memory error such that it wasn't even able to catch it with the except statement.

**Comment by mliu49** [comment]
Bumping this because it's still unresolved.

Here's a traceback from a recent instance:
```
Warning: Collision matrix too large to manage
Warning: Adjusting to use 8875 grains instead of 17750
/opt/anaconda2/envs/rmg_py3/lib/python3.7/site-packages/scipy/optimize/optimize.py:1826: LinAlgWarning: Ill-conditioned matrix (rcond=9.79183e-18): result may not be accurate.
  fu = func(x, *args)
/opt/anaconda2/envs/rmg_py3/lib/python3.7/site-packages/scipy/optimize/optimize.py:1826: LinAlgWarning: Ill-conditioned matrix (rcond=5.9437e-17): result may not be accurate.
  fu = func(x, *args)
Traceback (most recent call last):
  File "/home/mjliu/Code/RMG-Py/rmg.py", line 111, in <module>
    main()
  File "/home/mjliu/Code/RMG-Py/rmg.py", line 105, in main
    rmg.execute(**kwargs)
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/main.py", line 828, in execute
    self.reaction_model.enlarge(objectToEnlarge)
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/model.py", line 643, in enlarge
    self.update_unimolecular_reaction_networks()
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/model.py", line 1741, in update_unimolecular_reaction_networks
    network.update(self, self.pressure_dependence)
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/pdep.py", line 838, in update
    K = self.calculate_rate_coefficients(Tlist, Plist, method)
  File "/home/mjliu/Code/RMG-Py/rmgpy/pdep/network.py", line 260, in calculate_rate_coefficients
    self.apply_modified_strong_collision_method()
  File "/home/mjliu/Code/RMG-Py/rmgpy/pdep/network.py", line 874, in apply_modified_strong_collision_method
    self.K, self.p0 = msc.apply_modified_strong_collision_method(self, efficiency_model)
  File "rmgpy/pdep/msc.pyx", line 44, in rmgpy.pdep.msc.apply_modified_strong_collision_method
  File "rmgpy/pdep/msc.pyx", line 133, in rmgpy.pdep.msc.apply_modified_strong_collision_method
IndexError: Out of bounds on buffer access (axis 0)
```
