### ISSUE TITLE
Error calculating any input file from Basic Binary Install

### ISSUE THREAD

**Issue by me1bdh** [ReactionMechanismGenerator/RMG-Py#1506]
### Bug Description
After installing RMG using the Basic Binary Install procedure featured on RMG website we get error output relating to the database `group.py`.

### How To Reproduce
Follow procedure from: http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaUser.html

### Expected Behavior
`> rmg.py input.py` should process instead we get the following error output for any input calculation:

```
Loading thermodynamics library from primaryThermoLibrary.py in /home/$USER/.conda/envs/rmg_env/share/rmgdatabase/thermo/libraries...
Loading thermodynamics group database from /home/$USER/.conda/envs/rmg_env/share/rmgdatabase/thermo/groups...
Error: Error while reading database '/home/$USER/.conda/envs/rmg_env/share/rmgdatabase/thermo/groups/group.py'.
Traceback (most recent call last):
  File "/home/$USER/.conda/envs/rmg_env/bin/rmg.py", line 156, in <module>
    rmg.execute(**kwargs)
  File "/home/$USER/.conda/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 529, in execute
    self.initialize(**kwargs)
  File "/home/$USER/.conda/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 395, in initialize
    self.loadDatabase()
  File "/home/$USER/.conda/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 306, in loadDatabase
    depository = False, # Don't bother loading the depository information, as we don't use it
  File "/home/$USER/.conda/envs/rmg_env/lib/python2.7/site-packages/rmgpy/data/rmg.py", line 96, in load
    self.loadThermo(os.path.join(path, 'thermo'), thermoLibraries, depository)
  File "/home/$USER/.conda/envs/rmg_env/lib/python2.7/site-packages/rmgpy/data/rmg.py", line 118, in loadThermo
    self.thermo.load(path, thermoLibraries, depository)
  File "/home/$USER/.conda/envs/rmg_env/lib/python2.7/site-packages/rmgpy/data/thermo.py", line 738, in load
    self.loadGroups(os.path.join(path, 'groups'))
  File "/home/$USER/.conda/envs/rmg_env/lib/python2.7/site-packages/rmgpy/data/thermo.py", line 787, in loadGroups
    self.groups['group']   =   ThermoGroups(label='group').load(os.path.join(path, 'group.py'  ), self.local_context, self.global_context)
  File "/home/$USER/.conda/envs/rmg_env/lib/python2.7/site-packages/rmgpy/data/base.py", line 230, in load
    exec f in global_context, local_context
  File "/home/$USER/.conda/envs/rmg_env/share/rmgdatabase/thermo/groups/group.py", line 192, in <module>
    """,
  File "/home/$USER/.conda/envs/rmg_env/lib/python2.7/site-packages/rmgpy/data/thermo.py", line 604, in loadEntry
    item = Group().fromAdjacencyList(group)
  File "rmgpy/molecule/group.py", line 1073, in rmgpy.molecule.group.Group.fromAdjacencyList (rmgpy/molecule/group.c:21914)
  File "rmgpy/molecule/group.py", line 1080, in rmgpy.molecule.group.Group.fromAdjacencyList (rmgpy/molecule/group.c:21724)
  File "/home/$USER/.conda/envs/rmg_env/lib/python2.7/site-packages/rmgpy/molecule/adjlist.py", line 633, in fromAdjacencyList
    atom = GroupAtom(atomType, unpairedElectrons, partialCharges, label, lonePairs)
  File "rmgpy/molecule/group.py", line 105, in rmgpy.molecule.group.GroupAtom.__init__ (rmgpy/molecule/group.c:3395)__
```
### Installation Information
CentOS 7
 Basic Binary Install method
       RMG ver. 2.1.0  py27_255  

python/anaconda2-4.2.0

### Additional Context
If installed from source via Git using the same Anaconda environment we get a successful build and can successfully process input files.

**Comment by mliu49** [comment]
Hmm, it seems like the problem is during loading of RMG-database. You wrote that you installed the binary for RMG 2.1.0, so it's possible that you have a newer version of RMG database installed somehow.

Could you use `conda list` to report the versions of both RMG-Py and RMG-database you have? It is strongly recommended that they be the same version. Mismatched versions are sometimes compatible, but definitely not guaranteed.

**Comment by me1bdh** [comment]
From a fresh install of the Binary Install method we observe the following after issuing `conda create -c rmg --name rmg_env rmg rmgdatabase`

We see (among many others):

    The following NEW packages will be INSTALLED:


    rmg:             2.1.0-py27_255        rmg
    rmgdatabase:     2.2.0-py27_0          rmg

A mismatch of the RMG ver. and database is apparent.

**Comment by mliu49** [comment]
That's very interesting. If I run the same command (in Ubuntu 18), Anaconda identifies the correct versions:
```
The following NEW packages will be INSTALLED:

    rmg:                           2.2.1-py27h035aef0_1         rmg
    rmgdatabase:                   2.2.0-py27_0                 rmg
```

I wouldn't think that there would be any difference in support for conda packages between Ubuntu and CentOS, though I'm not familiar with the latter at all.

You can try this command to force the RMG version:
```
conda create -c rmg --name rmg_env rmg=2.2.1
```

RMG-database is a dependency of RMG, so it should be automatically included in the environment. If this works for you, then we can also update the documentation appropriately.

**Comment by mliu49** [comment]
Closing due to inactivity
