### ISSUE TITLE
keras/theano/dde causing 'Variable' object has no attribute 'ndim' error.

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#1532]
I'm currently merging RMG master into RMG-Cat.
Almost everything is working now, but when I run `make test` I am getting three instances of this `AttributeError: 'Variable' object has no attribute 'ndim'` error, related to keras, theano, and dde:

```
======================================================================
ERROR: test suite for <class 'rmgpy.data.thermoTest.TestThermoDatabase'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/thermoTest.py", line 87, in setUpClass
    self.ml_estimator = MLEstimator(Hf298_path, S298_path, Cp_path)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/ml/estimator.py", line 60, in __init__
    self.hf298_estimator, self.hf298_uncertainty = load_estimator(hf298_path)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/ml/estimator.py", line 129, in load_estimator
    estimator.load_input(input_file)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/predictor.py", line 66, in load_input
    read_input_file(self.input_file, self)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/input.py", line 89, in read_input_file
    exec f in global_context, local_context
  File "/Users/rwest/Code/Cat/RMG-database/input/thermo/ml/main/H298/predictor_input.py", line 12, in <module>
    freeze_mol_conv=True)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/input.py", line 50, in predictor_model
    freeze_mol_conv)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/cnn_model.py", line 55, in build_model
    trainable=not freeze_mol_conv)(inputs)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/keras/engine/topology.py", line 546, in __call__
    self.build(input_shapes[0])
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/layers.py", line 74, in build
    self.W_inner = K.variable(T.tile(W_inner, (self.depth + 1, 1, 1)).eval())
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/theano/tensor/basic.py", line 5287, in tile
    ndim = builtins.max(len(reps), x.ndim)
AttributeError: 'Variable' object has no attribute 'ndim'

======================================================================
ERROR: Test that we can make a prediction using MLEstimator.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/ml/estimator_test.py", line 53, in setUp
    self.ml_estimator = MLEstimator(Hf298_path, S298_path, Cp_path)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/ml/estimator.py", line 60, in __init__
    self.hf298_estimator, self.hf298_uncertainty = load_estimator(hf298_path)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/ml/estimator.py", line 129, in load_estimator
    estimator.load_input(input_file)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/predictor.py", line 66, in load_input
    read_input_file(self.input_file, self)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/input.py", line 89, in read_input_file
    exec f in global_context, local_context
  File "/Users/rwest/Code/Cat/RMG-database/input/thermo/ml/main/H298/predictor_input.py", line 12, in <module>
    freeze_mol_conv=True)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/input.py", line 50, in predictor_model
    freeze_mol_conv)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/cnn_model.py", line 55, in build_model
    trainable=not freeze_mol_conv)(inputs)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/keras/engine/topology.py", line 546, in __call__
    self.build(input_shapes[0])
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/layers.py", line 74, in build
    self.W_inner = K.variable(T.tile(W_inner, (self.depth + 1, 1, 1)).eval())
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/theano/tensor/basic.py", line 5287, in tile
    ndim = builtins.max(len(reps), x.ndim)
AttributeError: 'Variable' object has no attribute 'ndim'

======================================================================
ERROR: Test that we can input.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/inputTest.py", line 109, in testMLEstimator
    inp.mlEstimator(thermo=True)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/input.py", line 529, in mlEstimator
    rmg.ml_estimator = MLEstimator(H298_path, S298_path, Cp_path)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/ml/estimator.py", line 60, in __init__
    self.hf298_estimator, self.hf298_uncertainty = load_estimator(hf298_path)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/ml/estimator.py", line 129, in load_estimator
    estimator.load_input(input_file)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/predictor.py", line 66, in load_input
    read_input_file(self.input_file, self)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/input.py", line 89, in read_input_file
    exec f in global_context, local_context
  File "/Users/rwest/Code/Cat/RMG-database/input/thermo/ml/main/H298/predictor_input.py", line 12, in <module>
    freeze_mol_conv=True)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/input.py", line 50, in predictor_model
    freeze_mol_conv)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/cnn_model.py", line 55, in build_model
    trainable=not freeze_mol_conv)(inputs)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/keras/engine/topology.py", line 546, in __call__
    self.build(input_shapes[0])
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/layers.py", line 74, in build
    self.W_inner = K.variable(T.tile(W_inner, (self.depth + 1, 1, 1)).eval())
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/theano/tensor/basic.py", line 5287, in tile
    ndim = builtins.max(len(reps), x.ndim)
AttributeError: 'Variable' object has no attribute 'ndim'
```

This is on Mac OS X, with a recently made conda environment using `environment_mac.yml` containing these packages:

```
# packages in environment at /Users/rwest/anaconda/envs/rmg230:
#
# Name                    Version                   Build  Channel
appnope                   0.1.0            py27hb466136_0  
backports                 1.0                      py27_1  
backports.functools_lru_cache 1.5                      py27_1  
backports.shutil_get_terminal_size 1.0.0                    py27_2  
backports_abc             0.5              py27h6972548_0  
blas                      1.0                         mkl  
bleach                    3.0.2                    py27_0  
boost                     1.56.0                   py27_4    rmg
bzip2                     1.0.6                h1de35cc_5  
ca-certificates           2018.03.07                    0  
cairo                     1.14.12              hc4e6be7_4  
cairocffi                 0.6                      py27_1    rmg
cantera                   2.3.0a3         np111py27_4_g89d0c56    rmg
certifi                   2018.11.29               py27_0  
cffi                      1.11.5           py27h6174b99_1  
configparser              3.5.0            py27hc7edf1b_0  
coolprop                  6.0.1dev                 py27_0    rmg
coverage                  4.5.2            py27h1de35cc_0  
cycler                    0.10.0           py27hfc73c78_0  
cython                    0.29.2           py27h0a44026_0  
dbus                      1.13.2               h760590f_1  
dde                       1.0.0                   py27_87    rmg
decorator                 4.3.0                    py27_0  
entrypoints               0.2.3                    py27_2  
enum34                    1.1.6                    py27_1  
expat                     2.2.6                h0a44026_0  
ffmpeg                    4.0                  h01ea3c9_0  
fontconfig                2.13.0               h5d5b041_1  
freetype                  2.9.1                hb4e5f40_0  
fribidi                   1.0.5                h1de35cc_0  
funcsigs                  1.0.2            py27hb9f6266_0  
functools32               3.2.3.2                  py27_1  
futures                   3.2.0                    py27_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.56.2               hd9629dc_0  
gprof2dot                 2015.02.03               py27_0    rmg
graphite2                 1.3.13               h2098e52_0  
graphviz                  2.40.1               hefbbd9a_2  
greenlet                  0.4.15           py27h1de35cc_0  
h5py                      2.9.0            py27h3134771_0  
harfbuzz                  1.8.8                hb8d4a28_0  
hdf5                      1.10.4               hfa1e0ec_0  
icu                       58.2                 h4b95b61_1  
intel-openmp              2019.1                      144  
ipaddress                 1.0.22                   py27_0  
ipykernel                 4.10.0                   py27_0  
ipython                   5.8.0                    py27_0  
ipython_genutils          0.2.0            py27h8b9a179_0  
ipywidgets                7.4.2                    py27_0  
jinja2                    2.10                     py27_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0            py27hd9b497e_0  
jupyter                   1.0.0                    py27_7  
jupyter_client            5.2.4                    py27_0  
jupyter_console           5.2.0                    py27_1  
jupyter_core              4.4.0                    py27_0  
keras                     1.2.2                    py27_0    rmg
kiwisolver                1.0.1            py27h0a44026_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20170329         hb402a30_2  
libffi                    3.2.1                h475c297_4  
libgcc                    4.8.5               hdbeacc1_10  
libgfortran               3.0.1                h93005f0_2  
libgpuarray               0.7.6                h1de35cc_0  
libiconv                  1.15                 hdd342a3_7  
libopus                   1.3                  h1de35cc_0  
libpng                    1.6.36               ha441bb4_0  
libprotobuf               3.6.1                hd9629dc_0  
libsodium                 1.0.16               h3efe00b_0  
libtiff                   4.0.9                hcb84e12_2  
libvpx                    1.7.0                h378b8a2_0  
libxml2                   2.9.8                hab757c2_1  
linecache2                1.0.0                    py27_0  
lpsolve                   5.5.2.5                       0    rmg
lpsolve55                 5.5                      py27_1    rmg
mako                      1.0.7                    py27_0  
markupsafe                1.1.0            py27h1de35cc_0  
matplotlib                2.2.3            py27h54f8f79_0  
mistune                   0.8.4            py27h1de35cc_0  
mkl                       2019.1                      144  
mkl-service               1.1.2            py27hfbe908c_5  
mock                      2.0.0            py27h300204c_0  
mopac                     2017                          1    rmg
mpmath                    1.1.0                    py27_0  
nbconvert                 5.3.1                    py27_0  
nbformat                  4.4.0            py27hddc86d0_0  
ncurses                   6.1                  h0a44026_1  
networkx                  2.2                      py27_1  
nose                      1.3.7                    py27_2  
notebook                  5.7.4                    py27_0  
numpy                     1.11.3          py27hacdab7b_12  
numpy-base                1.11.3          py27h6575580_12  
openbabel                 2.4.1                    py27_5    rmg
openssl                   1.1.1a               h1de35cc_0  
pandas                    0.23.4           py27h6440ff4_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py27_1  
pango                     1.42.4               h060686c_0  
pathlib2                  2.3.3                    py27_0  
pbr                       5.1.1                    py27_0  
pcre                      8.42                 h378b8a2_0  
pexpect                   4.6.0                    py27_0  
pickleshare               0.7.5                    py27_0  
pip                       18.1                     py27_0  
pixman                    0.34.0               hca0a616_3  
prometheus_client         0.5.0                    py27_0  
prompt_toolkit            1.0.15           py27h4a7b9c2_0  
protobuf                  3.6.1            py27h0a44026_0  
psutil                    5.4.8            py27h1de35cc_0  
ptyprocess                0.6.0                    py27_0  
pycparser                 2.19                     py27_0  
pydas                     1.0.2                    py27_0    rmg
pydot                     1.2.2                    py27_0    rmg
pydot-ng                  1.0.0.15                 py27_0  
pydqed                    1.0.1                    py27_0    rmg
pygments                  2.3.1                    py27_0  
pygpu                     0.7.6            py27h1d22016_0  
pymongo                   3.7.2            py27h0a44026_0  
pyparsing                 2.3.0                    py27_0  
pyqt                      5.9.2            py27h655552a_2  
pyrdl                     1.1                      py27_0    rmg
python                    2.7.15               h8f8e585_6  
python-dateutil           2.7.5                    py27_0  
pytz                      2018.7                   py27_0  
pyyaml                    3.13             py27h1de35cc_0  
pyzmq                     17.1.2           py27h1de35cc_0  
qt                        5.9.7                h468cd18_1  
qtconsole                 4.4.3                    py27_0  
quantities                0.12.1                     py_0    rmg
rdkit                     2016.03.4           np111py27_1    rmg
readline                  7.0                  h1de35cc_5  
scandir                   1.9.0            py27h1de35cc_0  
scipy                     1.1.0            py27h1410ff5_2  
scoop                     0.7                      py27_0    rmg
send2trash                1.5.0                    py27_0  
setuptools                40.6.3                   py27_0  
simplegeneric             0.8.1                    py27_2  
singledispatch            3.4.0.3          py27he22c18d_0  
sip                       4.19.8           py27h0a44026_0  
six                       1.12.0                   py27_0  
sqlite                    3.26.0               ha441bb4_0  
subprocess32              3.5.3            py27h1de35cc_0  
symmetry                  1.0.1                         0    rmg
tensorflow                1.0.0                    py27_0    rmg
terminado                 0.8.1                    py27_1  
testpath                  0.4.2                    py27_0  
theano                    0.9.0                    py27_0  
tk                        8.6.8                ha441bb4_0  
tornado                   5.1.1            py27h1de35cc_0  
tqdm                      4.28.1           py27h28b3542_0  
traceback2                1.4.0                    py27_0  
traitlets                 4.3.2            py27hcf08151_0  
unittest2                 1.1.0                    py27_0  
wcwidth                   0.1.7            py27h817c265_0  
webencodings              0.5.1                    py27_1  
wheel                     0.32.3                   py27_0  
widgetsnbextension        3.4.2                    py27_0  
xlwt                      1.2.0            py27hbeec4ae_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.5                h0a44026_1  
zlib                      1.2.11               h1de35cc_3 
```

**Comment by rwest** [comment]
I'm also getting this on the current master, FWIW
```
======================================================================
ERROR: test suite for <class 'rmgpy.data.thermoTest.TestThermoDatabase'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/rwest/Code/RMG-Py/rmgpy/data/thermoTest.py", line 87, in setUpClass
    self.ml_estimator = MLEstimator(Hf298_path, S298_path, Cp_path)
  File "/Users/rwest/Code/RMG-Py/rmgpy/ml/estimator.py", line 60, in __init__
    self.hf298_estimator, self.hf298_uncertainty = load_estimator(hf298_path)
  File "/Users/rwest/Code/RMG-Py/rmgpy/ml/estimator.py", line 129, in load_estimator
    estimator.load_input(input_file)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/predictor.py", line 66, in load_input
    read_input_file(self.input_file, self)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/input.py", line 89, in read_input_file
    exec f in global_context, local_context
  File "/Users/rwest/Code/RMG-database/input/thermo/ml/main/H298/predictor_input.py", line 12, in <module>
    freeze_mol_conv=True)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/input.py", line 50, in predictor_model
    freeze_mol_conv)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/cnn_model.py", line 55, in build_model
    trainable=not freeze_mol_conv)(inputs)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/keras/engine/topology.py", line 546, in __call__
    self.build(input_shapes[0])
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/layers.py", line 74, in build
    self.W_inner = K.variable(T.tile(W_inner, (self.depth + 1, 1, 1)).eval())
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/theano/tensor/basic.py", line 5287, in tile
    ndim = builtins.max(len(reps), x.ndim)
AttributeError: 'Variable' object has no attribute 'ndim'

======================================================================
ERROR: Test that we can make a prediction using MLEstimator.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rwest/Code/RMG-Py/rmgpy/ml/estimator_test.py", line 53, in setUp
    self.ml_estimator = MLEstimator(Hf298_path, S298_path, Cp_path)
  File "/Users/rwest/Code/RMG-Py/rmgpy/ml/estimator.py", line 60, in __init__
    self.hf298_estimator, self.hf298_uncertainty = load_estimator(hf298_path)
  File "/Users/rwest/Code/RMG-Py/rmgpy/ml/estimator.py", line 129, in load_estimator
    estimator.load_input(input_file)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/predictor.py", line 66, in load_input
    read_input_file(self.input_file, self)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/input.py", line 89, in read_input_file
    exec f in global_context, local_context
  File "/Users/rwest/Code/RMG-database/input/thermo/ml/main/H298/predictor_input.py", line 12, in <module>
    freeze_mol_conv=True)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/input.py", line 50, in predictor_model
    freeze_mol_conv)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/cnn_model.py", line 55, in build_model
    trainable=not freeze_mol_conv)(inputs)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/keras/engine/topology.py", line 546, in __call__
    self.build(input_shapes[0])
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/layers.py", line 74, in build
    self.W_inner = K.variable(T.tile(W_inner, (self.depth + 1, 1, 1)).eval())
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/theano/tensor/basic.py", line 5287, in tile
    ndim = builtins.max(len(reps), x.ndim)
AttributeError: 'Variable' object has no attribute 'ndim'

======================================================================
ERROR: Test that we can input.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rwest/Code/RMG-Py/rmgpy/rmg/inputTest.py", line 109, in testMLEstimator
    inp.mlEstimator(thermo=True)
  File "/Users/rwest/Code/RMG-Py/rmgpy/rmg/input.py", line 407, in mlEstimator
    rmg.ml_estimator = MLEstimator(H298_path, S298_path, Cp_path)
  File "/Users/rwest/Code/RMG-Py/rmgpy/ml/estimator.py", line 60, in __init__
    self.hf298_estimator, self.hf298_uncertainty = load_estimator(hf298_path)
  File "/Users/rwest/Code/RMG-Py/rmgpy/ml/estimator.py", line 129, in load_estimator
    estimator.load_input(input_file)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/predictor.py", line 66, in load_input
    read_input_file(self.input_file, self)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/input.py", line 89, in read_input_file
    exec f in global_context, local_context
  File "/Users/rwest/Code/RMG-database/input/thermo/ml/main/H298/predictor_input.py", line 12, in <module>
    freeze_mol_conv=True)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/input.py", line 50, in predictor_model
    freeze_mol_conv)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/cnn_model.py", line 55, in build_model
    trainable=not freeze_mol_conv)(inputs)
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/keras/engine/topology.py", line 546, in __call__
    self.build(input_shapes[0])
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/dde/layers.py", line 74, in build
    self.W_inner = K.variable(T.tile(W_inner, (self.depth + 1, 1, 1)).eval())
  File "/Users/rwest/anaconda/envs/rmg230/lib/python2.7/site-packages/theano/tensor/basic.py", line 5287, in tile
    ndim = builtins.max(len(reps), x.ndim)
AttributeError: 'Variable' object has no attribute 'ndim'

```

**Comment by mjohnson541** [comment]
I'm getting the same.

**Comment by mjohnson541** [comment]
@cgrambow look like an issue with theano?

**Comment by cgrambow** [comment]
I haven't tested on Mac, so I haven't encountered that error before. It works fine on Linux. According to Theano documentation (http://deeplearning.net/software/theano_versions/0.9.X/library/tensor/basic.html?highlight=ndim#theano.tensor.TensorType.ndim), Theano tensors have an `ndim` attribute so you shouldn't be getting that error. Can you verify that your Theano version is 0.9.0?

**Comment by mliu49** [comment]
Yeah, I'm pretty sure this is a Mac issue. It also happens for me.

**Comment by mliu49** [comment]
I figured out the problem (at least in my case) - KERAS_BACKEND is not properly set. On linux, activating rmg_env magically sets KERAS_BACKEND to theano, while it doesn't seem to happen on mac. (Although this could also be a result of having tensorflow installed in the environment to begin with.)

Anyway, setting KERAS_BACKEND to theano fixed the problem for me. `export KERAS_BACKEND=theano` either in command line or .bash_profile.

Answer provided by Connor: https://github.com/connorcoley/ochem_predict_nn/issues/3

**Comment by mjohnson541** [comment]
Setting the `backend` in my `keras.json` file to `theano` doesn't seem to solve the problem.

**Comment by rwest** [comment]
Thanks for figuring this out. If dde straight out won't function with the tensorflow backend, can we force it to never try that, even if it's installed? (and remove it as a dependency from the MacOS conda package?). 

I'm not familiar with dde.
