### ISSUE TITLE
atomtype error of aqueous nitric acid  

### ISSUE THREAD

**Issue by brotherdrinktea** [ReactionMechanismGenerator/RMG-Py#1583]
### Topic
atomtype error of nitric acid in the solution of water

### Context

Hi,
I want to use RMG to simulate the reaction of nitric acid and nitrogen dioxide in an aqueous solution,the following are my input document and the error message:
1.[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/3111020/input.txt)
2.error message:
Error: Could not update atomtypes for this molecule:
multiplicity 1
1 O u0 p2 c0 {4,S} {5,S}
2 O u2 p2 c-1 {4,S}
3 O u0 p2 c0 {4,D}
4 N u0 p0 c+1 {1,S} {2,S} {3,D}
5 H u0 p0 c0 {1,S}
It seems  No.2 Oxygen atom lose a pair of electrons.

### Question
1.What's the reason that cause this error?
2.How to solve it?By modifying some parameters of input.py or others.

### Installation Information
 - OS : Ubuntu 18.04
 - Installation method: installation from source with anaconda
 - RMG version information:
   - RMG-Py:  2.3.0 
   - RMG-database: 2.3.0

**Comment by alongd** [comment]
Observation: Looks like a bug related to updating atomTypes in solvation thermo (maybe also related to hypervalance heteroatoms?).
As @brotherdrinktea noted, one of the oxygens has `u2 p2 c-1` instead of having `u0 p3 c-1`.
```
Adding rate rules from training set in kinetics families...
Filling in rate rules in kinetics families by averaging...
Enabling diffusion-limited kinetics...
Setting solvent data for water
Error: Could not update atomtypes for this molecule:
multiplicity 1
1 O u0 p2 c0 {4,S} {5,S}
2 O u2 p2 c-1 {4,S}
3 O u0 p2 c0 {4,D}
4 N u0 p0 c+1 {1,S} {2,S} {3,D}
5 H u0 p0 c0 {1,S}

Traceback (most recent call last):
  File "/home/alongd/Code/RMG-Py//rmg.py", line 173, in <module>
    main()
  File "/home/alongd/Code/RMG-Py//rmg.py", line 167, in main
    rmg.execute(**kwargs)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/main.py", line 603, in execute
    self.initialize(**kwargs)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/main.py", line 543, in initialize
    submit(spec,self.solvent)
  File "/home/alongd/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 188, in submit
    spc.thermo = submit_(evaluator, spc, solventName= solventName)
  File "/home/alongd/Code/RMG-Py/rmgpy/scoop_framework/util.py", line 171, in submit_
    return func(*args, **kwargs)
  File "/home/alongd/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 174, in evaluator
    thermo = generateThermoData(spc,solventName=solventName)
  File "/home/alongd/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 157, in generateThermoData
    return processThermoData(spc, thermo0, thermoClass, solventName)
  File "/home/alongd/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 72, in processThermoData
    soluteData = solvationdatabase.getSoluteData(spc)
  File "/home/alongd/Code/RMG-Py/rmgpy/data/solvation.py", line 625, in getSoluteData
    soluteData = self.getSoluteDataFromGroups(species)
  File "/home/alongd/Code/RMG-Py/rmgpy/data/solvation.py", line 684, in getSoluteDataFromGroups
    sdata = self.estimateSoluteViaGroupAdditivity(molecule)
  File "/home/alongd/Code/RMG-Py/rmgpy/data/solvation.py", line 809, in estimateSoluteViaGroupAdditivity
    saturatedStruct, addedToPairs = self.transformLonePairs(saturatedStruct)
  File "/home/alongd/Code/RMG-Py/rmgpy/data/solvation.py", line 745, in transformLonePairs
    saturatedStruct.update()
  File "rmgpy/molecule/molecule.py", line 967, in rmgpy.molecule.molecule.Molecule.update
  File "rmgpy/molecule/molecule.py", line 1181, in rmgpy.molecule.molecule.Molecule.updateAtomTypes
  File "rmgpy/molecule/molecule.py", line 1176, in rmgpy.molecule.molecule.Molecule.updateAtomTypes
  File "rmgpy/molecule/atomtype.py", line 706, in rmgpy.molecule.atomtype.getAtomType
  File "rmgpy/molecule/atomtype.py", line 742, in rmgpy.molecule.atomtype.getAtomType
rmgpy.exceptions.AtomTypeError: Unable to determine atom type for atom O..-, which has 1 single bonds, 0 double bonds to C, 0 double bonds to O, 0 double bonds to S, 0 triple bonds, 0 benzene bonds, 0 lone pairs, and 2 charge.
```

**Comment by brotherdrinktea** [comment]
尊敬的男士/女士：您的邮件已收到，我会尽快查看并回复！谢谢！

**Comment by brotherdrinktea** [comment]
尊敬的男士/女士：您的邮件已收到，我会尽快查看并回复！谢谢！
