### ISSUE TITLE
"DatabaseError: Can't estimate thermo of vacant site" when restricting families

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#1625]
### Bug Description
Running RMG (using both updated master branches) when some of the families are restricted (e.g. `kineticsFamilies = ['!H_Abstraction', '!Disproportionation']`) results in the following error while loading the database rate rules:
```
Using Theano backend.
Traceback (most recent call last):
  File "/home/alongd/Code/RMG-Py/rmg.py", line 181, in <module>
    main()
  File "/home/alongd/Code/RMG-Py/rmg.py", line 166, in main
    cProfile.runctx(command, global_vars, local_vars, stats_file)
  File "/home/alongd/.conda/envs/rmg_env/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/home/alongd/.conda/envs/rmg_env/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/main.py", line 622, in execute
    self.initialize(**kwargs)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/main.py", line 473, in initialize
    self.loadDatabase()
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/main.py", line 394, in loadDatabase
    family.addKineticsRulesFromTrainingSet(thermoDatabase=self.database.thermo)
  File "/home/alongd/Code/RMG-Py/rmgpy/data/kinetics/family.py", line 1179, in addKineticsRulesFromTrainingSet
    product.thermo = thermoDatabase.getThermoData(product,trainingSet=True)
  File "/home/alongd/Code/RMG-Py/rmgpy/data/thermo.py", line 1133, in getThermoData
    thermo0 = self.getThermoDataForSurfaceSpecies(species)
  File "/home/alongd/Code/RMG-Py/rmgpy/data/thermo.py", line 1367, in getThermoDataForSurfaceSpecies
    raise DatabaseError("Can't estimate thermo of vacant site. Should be in library (and should be 0).")
rmgpy.exceptions.DatabaseError: Can't estimate thermo of vacant site. Should be in library (and should be 0).
```

### How To Reproduce
Run any of RMG's examples specifying `kineticsFamilies = ['!H_Abstraction', '!Disproportionation']` in the database block.

### Additional Context
Maybe when we restrict some families, we implicitly allow non-default families which cause this behaviour?

**Comment by mliu49** [comment]
This is because you are implicitly including the catalysis families, which require thermo libraries for the vacant sites.

I'm not sure what optimal solution would be. For now, I think adding `'!surface'` and `'!surface_development'` would avoid the problem.

**Comment by alongd** [comment]
Yes, it solves it. What do we think the desired behaviour should be? Maybe not loading the surface families if no X species are present in the input file, to avoid crashing in such cases?
