### ISSUE TITLE
Cannot convert str to rmgpy.kinetics.uncertainties.RateUncertainty when loading surface kinetics rules

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#1703]
### Bug Description
Running a job with heterogeneous catalysis (surface) reaction families causes a crash when loading the database:

```
oup database from /Users/rwest/Code/Cat/RMG-database/input/statmech/groups...
Loading Platts additivity group database from /Users/rwest/Code/Cat/RMG-database/input/solvation/groups...
Trimolecular reactions are turned on
Adding rate rules from training set in kinetics families...
Traceback (most recent call last):
  File "rmg.py", line 185, in <module>
    main()
  File "rmg.py", line 179, in main
    rmg.execute(**kwargs)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/main.py", line 631, in execute
    self.initialize(**kwargs)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/main.py", line 472, in initialize
    self.loadDatabase()
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/main.py", line 398, in loadDatabase
    family.addKineticsRulesFromTrainingSet(thermoDatabase=self.database.thermo)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/kinetics/family.py", line 1138, in addKineticsRulesFromTrainingSet
    data = deepcopy(entry.data)
  File "/Users/rwest/anaconda/envs/rmg241/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/Users/rwest/anaconda/envs/rmg241/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "rmgpy/kinetics/arrhenius.pyx", line 66, in rmgpy.kinetics.arrhenius.Arrhenius.__init__
    KineticsModel.__init__(self, Tmin=Tmin, Tmax=Tmax, Pmin=Pmin, Pmax=Pmax, uncertainty=uncertainty, comment=comment)
  File "rmgpy/kinetics/model.pyx", line 115, in rmgpy.kinetics.model.KineticsModel.__init__
    self.uncertainty = uncertainty
TypeError: Cannot convert str to rmgpy.kinetics.uncertainties.RateUncertainty
```

### How To Reproduce
Steps to reproduce the behavior.
```
python rmg.py examples/rmg/catalysis/ch4_o2/input.py
```
after a recent `make clean; make` on the current master RMG-Py and RMG-database.

### Installation Information
Describe your installation method and system information.
 - OS: Mac OS Mojave 10.14.5
 - Installation method: anaconda, from source
 - RMG version information:
   - RMG-Py:  2.4.0-268-g3846fcce7 commit 3846fcce701f2a5fd12dbfa429687e9fcd647298
   - RMG-database: 2.4.0-14-ge461edb9 commit e461edb934a64eb3ea9fa87ea01cf469f76c7c96

### Additional Context
Conda list:
```
# packages in environment at /Users/rwest/anaconda/envs/rmg241:
#
# Name                    Version                   Build  Channel
algopy                    0.5.7                      py_0    conda-forge
backports                 1.0                        py_2  
backports.functools_lru_cache 1.5                        py_2  
backports_abc             0.5                        py_0  
blas                      1.0                         mkl  
boost                     1.56.0                   py27_4    rmg
bzip2                     1.0.8                h1de35cc_0  
cairo                     1.14.12              hc4e6be7_4  
cairocffi                 0.9.0                    py27_0    rmg
cantera                   2.4.0               np115py27_2    cantera
certifi                   2019.6.16                py27_1  
cffi                      1.12.3           py27hb5b8e2f_0  
cloog                     0.18.0                        0  
coolprop                  6.0.1dev                 py27_0    rmg
coverage                  4.5.3            py27h1de35cc_0  
cycler                    0.10.0           py27hfc73c78_0  
cython                    0.29.12          py27h0a44026_0  
dde                       1.0.0                   py27_87    rmg
ffmpeg                    2.8.6                         2    rmg
fontconfig                2.13.0               h5d5b041_1  
freetype                  2.9.1                hb4e5f40_0  
funcsigs                  1.0.2            py27hb9f6266_0  
functools32               3.2.3.2                  py27_1  
futures                   3.3.0                    py27_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.56.2               hd9629dc_0  
gmp                       6.1.2                hb37e062_1  
gprof2dot                 2017.9.19                  py_0    rmg
graphviz                  2.38.0                        3    rmg
guppy                     0.1.10                   py27_0    rmg
h5py                      2.9.0            py27h3134771_0  
hdf5                      1.10.4               hfa1e0ec_0  
icu                       58.2                 h4b95b61_1  
intel-openmp              2019.4                      233  
isl                       0.15                          0  
jinja2                    2.10.1                   py27_0  
jpeg                      9b                   he5867d9_2  
keras                     1.2.2                    py27_0    rmg
kiwisolver                1.1.0            py27h0a44026_0  
libboost                  1.67.0               hebc422b_4  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgcc                    4.8.4                         1    rmg
libgfortran               3.0.1                h93005f0_2  
libgpuarray               0.7.6                h1de35cc_0  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.37               ha441bb4_0  
libprotobuf               3.8.0                hd9629dc_0  
libsodium                 1.0.16               h3efe00b_0  
libtiff                   4.0.10               hcb84e12_2  
libxml2                   2.9.9                hf6e021a_1  
linecache2                1.0.0                    py27_0  
lpsolve                   5.5.2.5                       2    rmg
lpsolve55                 5.5              py27h39e3cac_2    rmg
mako                      1.0.10                     py_0  
markupsafe                1.1.1            py27h1de35cc_0  
matplotlib                2.2.3            py27h54f8f79_0  
mkl                       2019.4                      233  
mkl-service               2.0.2            py27h1de35cc_0  
mkl_fft                   1.0.12           py27h5e564d8_0  
mkl_random                1.0.2            py27h27c97d8_0  
mock                      3.0.5                    py27_0  
mopac                     2017                          1    rmg
mpc                       1.1.0                h6ef4df4_1  
mpfr                      4.0.1                h3018a27_3  
mpmath                    1.1.0                    py27_0  
ncurses                   6.1                  h0a44026_1  
nose                      1.3.7                    py27_2  
numdifftools              0.9.39                     py_0    conda-forge
numpy                     1.15.4           py27hacdab7b_0  
numpy-base                1.15.4           py27h6575580_0  
olefile                   0.46                     py27_0  
openbabel                 2.4.1                    py27_6    rmg
pandas                    0.24.2           py27h0a44026_0  
patsy                     0.5.1                    py27_0  
pcre                      8.43                 h0a44026_0  
pillow                    6.1.0            py27hb68e598_0  
pip                       19.1.1                   py27_0  
pixman                    0.38.0               h1de35cc_0  
protobuf                  3.8.0            py27h0a44026_0  
psutil                    5.6.3            py27h1de35cc_0  
py-boost                  1.67.0           py27h6440ff4_4  
pycairo                   1.18.1           py27ha54c0a8_0  
pycparser                 2.19                     py27_0  
pydas                     1.0.2            py27ha6a56d5_4    rmg
pydot                     1.2.2                    py27_0    rmg
pydot-ng                  1.0.0.15                 py27_0  
pydqed                    1.0.1            py27ha6a56d5_3    rmg
pygpu                     0.7.6            py27h1d22016_0  
pymongo                   3.8.0            py27h0a44026_1  
pyparsing                 2.4.0                      py_0  
pyrdl                     1.1                      py27_0    rmg
python                    2.7.16               h97142e2_0  
python-dateutil           2.8.0                    py27_0  
pytz                      2019.1                     py_0  
pyyaml                    5.1.1            py27h1de35cc_0  
pyzmq                     18.0.0           py27h0a44026_0  
quantities                0.12.3             pyh24bf2e0_0    rmg
rdkit                     2018.09.3.0      py27h65625ec_1    rdkit
readline                  7.0                  h1de35cc_5  
rmg                       2.4.1            py27he38e130_2    rmg
rmgdatabase               2.4.0                    py27_0    rmg
scikit-learn              0.20.3           py27h27c97d8_0  
scipy                     1.2.1            py27h1410ff5_0  
setuptools                41.0.1                   py27_0  
singledispatch            3.4.0.3          py27he22c18d_0  
six                       1.12.0                   py27_0  
sqlite                    3.29.0               ha441bb4_0  
statsmodels               0.10.1           py27h1d22016_0  
subprocess32              3.5.4            py27h1de35cc_0  
symmetry                  1.0.1                         0    rmg
tensorflow                1.0.0                    py27_0    rmg
textgenrnn                0.9                      py27_0    rmg
theano                    0.9.0                    py27_0  
tk                        8.6.8                ha441bb4_0  
tornado                   5.1.1            py27h1de35cc_0  
tqdm                      4.32.1                     py_0  
traceback2                1.4.0                    py27_0  
unittest2                 1.1.0                    py27_0  
wheel                     0.33.4                   py27_0  
x264                      20131217                      0    rmg
xlwt                      1.2.0            py27hbeec4ae_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.3.1                h0a44026_3  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0  
```

**Comment by rwest** [comment]
I think 5afd8d2b1e6b17e33410d76393afefaf5c63fcd1 added the uncertainty attribute to `__init__` `__repr__` and `__reduce__` for `Arrhenius`, `ArrheniusEP`, `ArrheniusBM`, and f79512b6041a33fdcbbe45c4db959609fad3e267 did it for the base class `KineticsModel`, but it was never done for the surface kinetics types `StickingCoefficient`, `StickingCoefficientBEP`, `SurfaceArrhenius`, or `SurfaceArrheniusBEP`

**Comment by rwest** [comment]
Also, unit tests like `test_pickle`, `test_repr` were not updated

**Comment by rwest** [comment]
This issue is fixed (on the Python 2 master branch) in pull request #1705
