### ISSUE TITLE
KineticsError: Unable to calculate degeneracy for a Birad_R_Recombination reaction

### ISSUE THREAD

**Issue by shenghuiqin** [ReactionMechanismGenerator/RMG-Py#1715]
Hi, I met a problem when using rmg, 
```
Traceback (most recent call last):
  File "/home/qin.she/Code/RMG-Py/rmg.py", line 185, in <module>
    main()
  File "/home/qin.she/Code/RMG-Py/rmg.py", line 170, in main
    cProfile.runctx(command, global_vars, local_vars, stats_file)
  File "/home/qin.she/anaconda2/envs/rmg_env/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/home/qin.she/anaconda2/envs/rmg_env/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/home/qin.she/Code/RMG-Py/rmgpy/rmg/main.py", line 866, in execute
    trimolecularReact=self.trimolecularReact)
  File "/home/qin.she/Code/RMG-Py/rmgpy/rmg/model.py", line 590, in enlarge
    procnum=procnum)
  File "/home/qin.she/Code/RMG-Py/rmgpy/rmg/react.py", line 172, in react_all
    return react(spc_fam_tuples, procnum), [fam_tuple[0] for fam_tuple in spc_fam_tuples]
  File "/home/qin.she/Code/RMG-Py/rmgpy/rmg/react.py", line 70, in react
    reactions = p.map(_react_species_star, spc_fam_tuples)
  File "/home/qin.she/anaconda2/envs/rmg_env/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/qin.she/anaconda2/envs/rmg_env/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
rmgpy.exceptions.KineticsError: Unable to calculate degeneracy for reaction CC[CH]CCCC + [CH]C=C <=> C=C[CH]C(CC)CCCC in reaction family Birad_R_Recombination. Expected 1 reaction but generated 0
```
similar issue: 
[https://github.com/ReactionMechanismGenerator/RMG-Py/issues/617](url)
my last call is "pool.py", but others are "family.py"
HELP.
thanks for your time.

**Comment by alongd** [comment]
I'm not certain this is related to #617 where the error message ended with `Expected 1 reaction but generated 2`. In This case it is similar to #1249, which ends with `Expected 1 reaction but generated 0` like in this case.

Could you please verify that both RMG-Py and RMG-database repositories are up to date?
(Assuming you have the developer version, type `git checkout master`, `git fetch origin master`, `git pull origin master` in both RMG-Py and RMG-database folders. You'll also need to compile RMG-Py: `source activate rmg_env`, `make clean`, `make`)

Then try re-running RMG with the same input file?

**Comment by shenghuiqin** [comment]
I'll try that, thank you.

**Comment by mliu49** [comment]
This could be related to the fact that triplet carbenes (`[CH]C=C`) are globally forbidden.

Also, I assume you have pool as the last call because you're using multiprocessing. Is that correct?

**Comment by shenghuiqin** [comment]
> This could be related to the fact that triplet carbenes (`[CH]C=C`) are globally forbidden.
> 
> Also, I assume you have pool as the last call because you're using multiprocessing. Is that correct?

yeah, 12 processes
