### ISSUE TITLE
Assertion Error during an RMG job

### ISSUE THREAD

**Issue by saud3001** [ReactionMechanismGenerator/RMG-Py#1838]
Hello,

I am using RMG to construct an H2-O2 reaction mechanism using a custom reaction library (Mueller Flow Reactor Studies 1999). The RMG job outputs the following error:
`Saving current model core to Chemkin file...
Traceback (most recent call last):
  File "/home/saud/anaconda3/envs/rmg_env/bin/rmg.py", line 181, in <module>
    main()
  File "/home/saud/anaconda3/envs/rmg_env/bin/rmg.py", line 175, in main
    rmg.execute(**kwargs)
  File "/home/saud/anaconda3/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 699, in execute
    self.saveEverything()
  File "/home/saud/anaconda3/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 1535, in saveEverything
    self.notify()
  File "/home/saud/anaconda3/envs/rmg_env/lib/python2.7/site-packages/rmgpy/util.py", line 110, in notify
    observer.update(self)
  File "rmgpy/chemkin.pyx", line 2251, in rmgpy.chemkin.ChemkinWriter.update
  File "rmgpy/chemkin.pyx", line 2150, in rmgpy.chemkin.saveChemkinFiles
  File "rmgpy/chemkin.pyx", line 2128, in rmgpy.chemkin.saveChemkin
  File "rmgpy/chemkin.pyx", line 1975, in rmgpy.chemkin.saveChemkinFile
  File "rmgpy/chemkin.pyx", line 1696, in rmgpy.chemkin.writeKineticsEntry
AssertionError
`

**What could be going wrong here?**

Thanks!

**Comment by mjohnson541** [comment]
What version of RMG are you using?  

My guess would be that this is something related to the units in your library. They may not be consistent with the number of reactants involved in a reaction.

**Comment by saud3001** [comment]
I am using RMG 2.4.0.

It is possible that this is a units issue since I made a custom file for the kinetics library. Let me check and get back to you.

Thanks.
