### ISSUE TITLE
RMG tool generatefluxdiagram got ZeroDivisionError: float division

### ISSUE THREAD

**Issue by shenghuiqin** [ReactionMechanismGenerator/RMG-Py#1841]
hi guys, I met this error when using generateFluxDiagram
`Traceback (most recent call last):
  File "generateFluxDiagram.py", line 139, in <module>
    main()
  File "generateFluxDiagram.py", line 136, in main
    checkDuplicates=checkDuplicates)
  File "/home/shenghuiqin/Code/RMG-Py/rmgpy/tools/fluxdiagram.py", line 603, in createFluxDiagram
    time, coreSpeciesConcentrations, coreReactionRates = simulate(rmg.reactionModel, reactionSystem, settings)
  File "/home/shenghuiqin/Code/RMG-Py/rmgpy/tools/fluxdiagram.py", line 406, in simulate
    sens_atol=simulatorSettings.sens_atol, sens_rtol=simulatorSettings.sens_rtol,conditions=None)
  File "rmgpy/solver/simple.pyx", line 166, in rmgpy.solver.simple.SimpleReactor.initializeModel
  File "rmgpy/solver/simple.pyx", line 202, in rmgpy.solver.simple.SimpleReactor.initializeModel
  File "rmgpy/solver/base.pyx", line 475, in rmgpy.solver.base.ReactionSystem.set_initial_derivative
  File "rmgpy/solver/simple.pyx", line 371, in rmgpy.solver.simple.SimpleReactor.residual
ZeroDivisionError: float division`
how to solve it?
thank you

**Comment by xiaoruiDong** [comment]
@shenghuiqin, Thanks for reporting the issue. Since RMG-website is just using RMG-Py's flux diagram module, I transferred your issue here. Probably you can post your model to let us do some diagnosis.
