### ISSUE TITLE
cclib.parser error when using Gaussian for QMTP

### ISSUE THREAD

**Issue by rlawson** [ReactionMechanismGenerator/RMG-Py#1864]
General area which your question is related to.
 - [ ] Installation of RMG
 - [ ] Running an RMG job
 - [ ] Using RMG API
 - [ ] Arkane (formerly CanTherm)
 - [ ] Dependencies
 - [ ] An error message 

I'm trying to simulate a propane-air oxidation  using a simple reactor at 800K and 40 bar.

However, I encountered a problem when I used quantum mechanics for thermodynamic properties estimation which was "AttributeError: module 'cclib.parser' has no attribute 'Mopac'"

I have RMG installed on a macOS 10.15.2 
I installed using binary with anaconda
RMG version 3.0.0 with build py37he38e130_1 with the corresponding latest database.

Find attached my input file
[input.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/4061913/input.zip)

**Comment by amarkpayne** [comment]
This appears to be an issue with the on-the-fly quantum mechanics tool, QMTP. We had to update some of the code for the cclib parser when we switched to python 3, but it looks like there is an error that our unit tests didn't catch.

Looking at your input file though, it is very likely that you do not need to use the QMTP interface. In the past we relied on using this for polycyclics and fused ring species, which I don't think will arise in your system. Furthermore, I think that a lot of the improvements we have made over the past couple of years have really helped with this problem, including new algorithms for handling ring species and new groups, not to mention some of the machine learning strategies our group has implemented. I am tagging @cgrambow and @mjohnson541 who know more about these subjects than me in case they want to weigh in, but I think you should be fine if you remove the quantum mechanics block for your system.

That being said, we can continue to look at this bug in the meantime so the the functionality is there if you want/need it.

**Comment by rlawson** [comment]
Thanks Max for the prompt response. I do agree with you the species of interest does not really require the use of QMTP.  After installing v 3.0.0, this was one of the simplest cases to just check if all the modules we'll be using in future runs were ok. I plan on simulating some cyclic structures which in the past have given good results only when QMTP interface is used, that's why I was interested in using the quantum mechanics block.

**Comment by lynnrinkui** [comment]
Any update on this issue? I'm simulating a cyclic chemical combustion and need to use MOPAC to get more accurate estimates of thermo properties. Now I found out that this bug has been around for more than a year......

**Comment by xrulesin** [comment]
I am having the same issue. Any help or pointers. Here is my error. I used the same input file from rlawson

Trying GaussianMolPM3 attempt 1 of 36 on molecule C=C=CC1C=CC=CC1=C.
Traceback (most recent call last):
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/RMG-Py/rmgpy/rmg/main.py", line 667, in execute
    self.initialize(**kwargs)
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/RMG-Py/rmgpy/rmg/main.py", line 492, in initialize
    self.load_database()
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/RMG-Py/rmgpy/rmg/main.py", line 416, in load_database
    family.add_rules_from_training(thermo_database=self.database.thermo)
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 1222, in add_rules_from_training
    reactant.thermo = thermo_database.get_thermo_data(reactant, training_set=True)
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/RMG-Py/rmgpy/data/thermo.py", line 1264, in get_thermo_data
    thermo0 = quantum_mechanics.get_thermo_data(original_molecule)  # returns None if it fails
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/RMG-Py/rmgpy/qm/main.py", line 224, in get_thermo_data
    thermo0 = qm_molecule_calculator.generate_thermo_data()
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/RMG-Py/rmgpy/qm/molecule.py", line 359, in generate_thermo_data
    self.qm_data = self.generate_qm_data()
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/RMG-Py/rmgpy/qm/gaussian.py", line 265, in generate_qm_data
    success = self.run()
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/RMG-Py/rmgpy/qm/gaussian.py", line 100, in run
    return self.verify_output_file()
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/RMG-Py/rmgpy/qm/gaussian.py", line 170, in verify_output_file
    qm_data = self.parse()
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/RMG-Py/rmgpy/qm/molecule.py", line 334, in parse
    cclib_data = parser.parse()
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/logfileparser.py", line 363, in parse
    data = self.datatype(attributes=self.__dict__)
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 412, in __init__
    super(ccData_optdone_bool, self).__init__(*args, **kwargs)
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 203, in __init__
    self.setattributes(attributes)
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 416, in setattributes
    invalid = super(ccData_optdone_bool, self).setattributes(*args, **kwargs)
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 274, in setattributes
    self.arrayify()
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 232, in arrayify
    setattr(self, k, [numpy.array(x, precision) for x in getattr(self, k)])
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/data.py", line 232, in <listcomp>
    setattr(self, k, [numpy.array(x, precision) for x in getattr(self, k)])
TypeError: float() argument must be a string or a number, not 'map'

**Comment by mjohnson541** [comment]
Updating your RMG version should fix the issue.

**Comment by rwest** [comment]
Note, you will need to update your dependencies too. Recommended route is to make a whole new conda environment, rather than trying to update an existing one.

**Comment by xrulesin** [comment]
I've installed the latest RMG as a fresh install.

**Comment by mjohnson541** [comment]
I've run that input file out for a while on RMG v3.1.0 it hasn't crashed and it successfully calculated thermo for C=C=CC1C=CC=CC1=C.

**Comment by mjohnson541** [comment]
Hmm...as far as I can tell it resolved the prior issue, but now I'm eventually getting: 

```
Trying MopacMolPM3 attempt 1 of 10 on molecule CC1=CCC=CC1.
Successful MopacMolPM3 quantum result in /Users/mattjohnson/RMGCODE/RMG-Py/examples/rmg/qmtptest/QMscratch/pm3/QDXQAOGNBCOEQX-UHFFFAOYSA-N.out
Attempt 1 of 10 on species InChI=1S/C7H10/c1-7-5-3-2-4-6-7/h2-3,6H,4-5H2,1H3 succeeded.
Symmetry input file written to /Users/mattjohnson/RMGCODE/RMG-Py/examples/rmg/qmtptest/QMscratch/pm3/QDXQAOGNBCOEQX-UHFFFAOYSA-N.symm
Point group: Cs
Reading existing thermo file QMfiles/pm3/ZNKKYYNWFKHNHZ-UHFFFAOYSA-N.thermo
1 radicals on C7H9-39 exceeds limit of 0. Using HBI method.
Reading existing thermo file QMfiles/pm3/JFNLZVQOOSMTJK-UHFFFAOYSA-N.thermo
Traceback (most recent call last):
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/rmg/main.py", line 673, in execute
    self.initialize(**kwargs)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/rmg/main.py", line 496, in initialize
    self.load_database()
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/rmg/main.py", line 420, in load_database
    family.add_rules_from_training(thermo_database=self.database.thermo)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/data/kinetics/family.py", line 1269, in add_rules_from_training
    reactant.thermo = thermo_database.get_thermo_data(reactant, training_set=True, metal_to_scale_to=metal)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/data/thermo.py", line 1319, in get_thermo_data
    tdata = self.estimate_radical_thermo_via_hbi(molecule, quantum_mechanics.get_thermo_data)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/data/thermo.py", line 2019, in estimate_radical_thermo_via_hbi
    thermo_data_sat = stable_thermo_estimator(saturated_struct)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/qm/main.py", line 216, in get_thermo_data
    thermo0 = qm_molecule_calculator.generate_thermo_data()
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/qm/molecule.py", line 363, in generate_thermo_data
    self.qm_data = self.generate_qm_data()
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/qm/mopac.py", line 302, in generate_qm_data
    self.create_geometry()
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/qm/molecule.py", line 325, in create_geometry
    self.geometry.generate_rdkit_geometries()
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/qm/molecule.py", line 135, in generate_rdkit_geometries
    self.save_coordinates_from_rdmol(rdmol, min_e_id, rdatom_idx)
  File "/Users/mattjohnson/RMGCODE/RMG-Py/rmgpy/qm/molecule.py", line 173, in save_coordinates_from_rdmol
    point = rdmol.GetConformer(min_e_id).GetAtomPosition(atom.sorting_label)
ValueError: Bad Conformer Id
```

**Comment by mjohnson541** [comment]
As far as I can tell it seems that rdkit just doesn't make any conformers for the molecule: C1=C2CCC(C1)C2 in the `AllChem.EmbedMultipleConfs(rdmol, num_conf_attempts, randomSeed=1)` call with `num_conf_attempts = 70`, so when we try to get a geometry we don't have any to run the calculation on.

**Comment by xrulesin** [comment]
Oh Well.. I do not have access to mopac and try to use gaussian instead. would you be able to try that? I do see the files in QMscratch (this seems to have worked)... 

(rmg_env) bash-4.2$ ls -l pm3
total 1006
-rw-rw---- 1 insjf6 g_bngb69   1732 May 14 06:10 LSAIKWFIJPVRGV-UHFFFAOYSA-N.crude.mol
-rw-rw---- 1 insjf6 g_bngb69    850 May 14 06:10 LSAIKWFIJPVRGV-UHFFFAOYSA-N.gjf
-rw-rw---- 1 insjf6 g_bngb69 655607 May 14 06:11 LSAIKWFIJPVRGV-UHFFFAOYSA-N.log
-rw-rw---- 1 insjf6 g_bngb69   1732 May 14 06:10 LSAIKWFIJPVRGV-UHFFFAOYSA-N.refined.mol

**Comment by mjohnson541** [comment]
This is a rare rdkit conformer generation issue, which is a prerequisite the QM calculations so it should be the same regardless of the QM software. This should probably be investigated further at some point, but for now I've made a branch `qmfallback` that in these very rare events lets RMG fallback to ML or GAV thermo estimation. (depending on if ML is on). I've made a PR for this #2130. On that branch the input file runs fine and I haven't seen another instance of that error.

**Comment by xrulesin** [comment]
Hi, I just created a new environment and installed RMG just now. I am still stuck with gaussian.

> Adding rate rules from training set in kinetics families... Traceback (most recent call last): File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmg.py", line 118, in <module> main() File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmg.py", line 112, in main rmg.execute(**kwargs) File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/rmg/main.py", line 673, in execute self.initialize(**kwargs) File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/rmg/main.py", line 496, in initialize self.load_database() File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/rmg/main.py", line 420, in load_database family.add_rules_from_training(thermo_database=self.database.thermo) File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/data/kinetics/family.py", line 1269, in add_rules_from_training reactant.thermo = thermo_database.get_thermo_data(reactant, training_set=True, metal_to_scale_to=metal) File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/data/thermo.py", line 1344, in get_thermo_data thermo0 = quantum_mechanics.get_thermo_data(original_molecule) # returns None if it fails File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/qm/main.py", line 224, in get_thermo_data thermo0 = qm_molecule_calculator.generate_thermo_data() File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/qm/molecule.py", line 363, in generate_thermo_data self.qm_data = self.generate_qm_data() File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/qm/gaussian.py", line 254, in generate_qm_data if self.verify_output_file(): File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/qm/gaussian.py", line 170, in verify_output_file qm_data = self.parse() File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/qm/molecule.py", line 340, in parse qm_data = parse_cclib_data(cclib_data, radical_number + 1) # Should radical_number+1beself.molecule.multiplicity in the next line of code? It's the electronic ground state degeneracy. File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/qm/qmdata.py", line 101, in parse_cclib_data rotational_constants = (cclib_data.rotcons[-1], 'cm^-1') IndexError: list index out of range

Can you help me with this one?

**Comment by xrulesin** [comment]
Just to add. If I look at line 340 on molecule.py.. 
```
328     def parse(self):
329         """
330         Parses the results of the Mopac calculation, and returns a QMData object.
331         """
332         parser = self.get_parser(self.output_file_path)
333         parser.logger.setLevel(logging.ERROR)  # cf. http://cclib.sourceforge.net/wiki/index.php/Using_cclib#Additional_information
334         parser.rotcons = [] # give it an attribute and it won't delete it, leaving it on the parser object
335         parser.molmass = None # give it an attribute and it won't delete it, leaving it on the parser object
336         cclib_data = parser.parse()
337         radical_number = self.molecule.get_radical_count()
338         cclib_data.rotcons = parser.rotcons # this hack required because rotcons not part of a default cclib data object
339         cclib_data.molmass = parser.molmass # this hack required because rotcons not part of a default cclib data object
340         qm_data = parse_cclib_data(cclib_data, radical_number + 1)  # Should `radical_number+1` be `self.molecule.multiplicity` in the next line of code? It's the electronic ground state degeneracy.
341         return qm_data

```
The comment says it is parsing Mopac. If it not a commenting bug, it may be the issue?

**Comment by rwest** [comment]
My suspicion is that when we upgraded to using a more recent official cclib instead of our own fork, in https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2091 , we probably broke the ability to parse Gaussian files.  

You could try switching back to the old RMG version,
```
conda activate rmg_env
conda uninstall cclib
conda install -c rmg cclib
```
but it [looks like](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2091/files) there might be a discrepancy about the units it reports rotational constants in, so you might need to do (assuming you've installed from git source with the developer instructions)
```
cd RMG-Py
git pull origin master
git revert 0b19aec987a2074414f3531427dadaf12222dce5
make clean
make
```
(technically only the `git revert 0b19ae` part is required, the rest just brings you more generally up to date.

I'm not sure what is involved in getting Gaussian parsing to work with the official CCLib, either by monkey-patching, working around stuff, or contributing upstream to the official CCLib, but that is the longer term solution.

**Comment by xrulesin** [comment]
Thanks rwest, 
 tried it but it takes me back to the previous error posted by me. 
```
File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/qm/molecule.py", line 336, in parse
    cclib_data = parser.parse()
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/anaconda3/envs/rmg_env_av/lib/python3.7/site-packages/cclib/parser/logfileparser.py", line 363, in parse
    data = self.datatype(attributes=self.__dict__)
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/anaconda3/envs/rmg_env_av/lib/python3.7/site-packages/cclib/parser/data.py", line 412, in __init__
    super(ccData_optdone_bool, self).__init__(*args, **kwargs)
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/anaconda3/envs/rmg_env_av/lib/python3.7/site-packages/cclib/parser/data.py", line 203, in __init__
    self.setattributes(attributes)
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/anaconda3/envs/rmg_env_av/lib/python3.7/site-packages/cclib/parser/data.py", line 416, in setattributes
    invalid = super(ccData_optdone_bool, self).setattributes(*args, **kwargs)
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/anaconda3/envs/rmg_env_av/lib/python3.7/site-packages/cclib/parser/data.py", line 274, in setattributes
    self.arrayify()
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/anaconda3/envs/rmg_env_av/lib/python3.7/site-packages/cclib/parser/data.py", line 232, in arrayify
    setattr(self, k, [numpy.array(x, precision) for x in getattr(self, k)])
  File "/glb/ap/bngsti/proj/ir6/Softwares/RMG/anaconda3/envs/rmg_env_av/lib/python3.7/site-packages/cclib/parser/data.py", line 232, in <listcomp>
    setattr(self, k, [numpy.array(x, precision) for x in getattr(self, k)])
TypeError: float() argument must be a string or a number, not 'map'
```

**Comment by mjohnson541** [comment]
Running GaussianTest.py on v3.1.0 with G16 I get representatively: 

```
...
PGFIO/stdio: No such file or directory
PGFIO-F-/OPEN/unit=11/error code returned by host stdio - 2.
 File name = /scratch/mattsj/Gau-6091.inp
 In source file ml0.f, at line number 197
  /opt/g16/g16() [0xc88be6]
  /opt/g16/g16() [0xc89f91]
  /opt/g16/g16() [0xc89906]
  /opt/g16/g16() [0x40519b]
  /opt/g16/g16() [0x40455b]
  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x146c89a5ab97]
  /opt/g16/g16(sched_setaffinity+0xb9) [0x404469]
EEEE
======================================================================
ERROR: Test that generate_thermo_data() works correctly on gaussian PM3.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mattsj/rmgcode/RMG-Py/rmgpy/qm/gaussianTest.py", line 81, in test_generate_thermo_data
    self.assertTrue(self.qmmol1.thermo.comment.startswith('QM GaussianMolPM3 calculation'))
AttributeError: 'GaussianMolPM3' object has no attribute 'thermo'
-------------------- >> begin captured logging << --------------------
root: INFO: Creating directory /home/mattsj/rmgcode/RMG-Py/testing/qm/QMfiles/pm3 for QM files.
root: INFO: Creating directory /home/mattsj/rmgcode/RMG-Py/testing/qm/QMscratch/pm3 for QM files.
root: INFO: Output file /home/mattsj/rmgcode/RMG-Py/testing/qm/QMscratch/pm3/UFWIBTONFRDIAS-UHFFFAOYSA-N.log does not exist.
root: INFO: Trying GaussianMolPM3 attempt 1 of 36 on molecule C1=CC=C2C=CC=CC2=C1.
root: ERROR: Not all of the required keywords for success were found in the output file!
root: INFO: Trying GaussianMolPM3 attempt 2 of 36 on molecule C1=CC=C2C=CC=CC2=C1.
root: ERROR: Not all of the required keywords for success were found in the output file!
root: INFO: Trying GaussianMolPM3 attempt 3 of 36 on molecule C1=CC=C2C=CC=CC2=C1.
root: ERROR: Not all of the required keywords for success were found in the output file!
root: INFO: Trying GaussianMolPM3 attempt 4 of 36 on molecule C1=CC=C2C=CC=CC2=C1.
root: ERROR: Not all of the required keywords for success were found in the output file!
...
```

**Comment by xrulesin** [comment]
For me.. I seem to go past this step with gaussian09. I do have a log and everything in QMscratch(again look at previous comment on the files generated by gaussian in QMscratch).. It is then looking to parse the log file when it fails..

**Comment by xrulesin** [comment]
@rwest @mjohnson541 

I falled back to the examples directory provided by RMG. Got a license key for mopac and uncommented mopac block in `examples/rmg/commented/input.py`
```
# optional block allows thermo to be estimated through quantum calculations
quantumMechanics(
    # the software package for calculations...can use 'mopac' or 'gaussian' if installed
    software='mopac',
    # methods available for calculations. 'pm2' 'pm3' or 'pm7' (last for mopac only)
    method='pm3',
    # where to store calculations
    fileStore='QMfiles',
    # where to store temporary run files
    scratchDirectory=None,
    # onlyCyclics allows linear molecules to be calculated using bensen group addivity....need to verify
    onlyCyclics=True,
    # how many radicals should be utilized in the calculation.
    # If the amount of radicals is more than this, RMG will use hydrogen bond incrementation method
    maxRadicalNumber=0,
)

```


and I am now at this error. 

```
Calculating densities of states for PDepNetwork #1 network...
Using 613 grains from 586.75 to 1657.11 kJ/mol in steps of 1.75 kJ/mol to compute densities of states
Calculating phenomenological rate coefficients for H(5) + C(T)(16) <=> CH(17)...
Using 250 grains from 586.75 to 1036.69 kJ/mol in steps of 1.81 kJ/mol to compute the k(T,P) values at 343.437 K
Traceback (most recent call last):
  File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/rmg/main.py", line 733, in execute
    trimolecular_react=self.trimolecular_react)
  File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/rmg/model.py", line 648, in enlarge
    self.update_unimolecular_reaction_networks()
  File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/rmg/model.py", line 1766, in update_unimolecular_reaction_networks
    network.update(self, self.pressure_dependence)
  File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/rmg/pdep.py", line 842, in update
    K = self.calculate_rate_coefficients(Tlist, Plist, method)
  File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/pdep/network.py", line 262, in calculate_rate_coefficients
    self.set_conditions(T, P)
  File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/pdep/network.py", line 425, in set_conditions
    self.calculate_collision_model()
  File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/pdep/network.py", line 878, in calculate_collision_model
    coll_freq[i] = isomer.calculate_collision_frequency(self.T, self.P, self.bath_gas)
  File "rmgpy/pdep/configuration.pyx", line 171, in rmgpy.pdep.configuration.Configuration.calculate_collision_frequency
  File "rmgpy/pdep/configuration.pyx", line 185, in rmgpy.pdep.configuration.Configuration.calculate_collision_frequency
  File "rmgpy/species.py", line 765, in rmgpy.species.Species.get_transport_data
  File "rmgpy/species.py", line 756, in rmgpy.species.Species.generate_transport_data
  File "/glb/ap/bngsti/proj/ir6/inaveu/sw/rmg/RMG-Py/rmgpy/data/transport.py", line 341, in get_transport_properties
    transport = self.get_transport_properties_from_library(species, self.libraries[label])
KeyError: 'PrimaryTransportLibrary.py'
```

**Comment by xrulesin** [comment]
Any hopes to get QM working on RMG ? ?
