### ISSUE TITLE
Error in RMG tests

### ISSUE THREAD

**Issue by Christina-98** [ReactionMechanismGenerator/RMG-Py#1885]
Hey peeps,
I'm using RMG-Py on Linux (using a VM and Ubuntu since my PC is Windows).

While trying to run the examples in the testing folder (eg1, eg2...), I am getting the following error: (even though this input was running a few days ago)

```
Traceback (most recent call last):
  File "/home/user/RMG-Py/rmg.py", line 48, in <module>
    from rmgpy.rmg.main import RMG, initialize_log, process_profile_stats, make_profile_graph
  File "/home/user/RMG-Py/rmgpy/rmg/main.py", line 50, in <module>
    from cantera import ck2cti
ImportError: cannot import name 'ck2cti' from 'cantera' (unknown location)
```

Then I thought of redoing the tests (the "make test" syntax), and I am getting now this error: (also, all the RMG tests were working a couple of days ago)

```
Ran 94 tests in 0.209s

FAILED (errors=80)
Makefile:69: recipe for target 'test' failed
make: *** [test] Error 1

```

I can't seem to find the problem; the conda environment is working and all the RMG-Py files are in the PATH.

The rng_env is working and it has cantera. 

thanks!
_Please bear with me, I'm new here_

**Comment by mjohnson541** [comment]
Are you not activating the environment (conda activate rmg_env) in the bash before running RMG?

**Comment by Christina-98** [comment]
I am activating it and it works well

**Comment by mjohnson541** [comment]
Before you launch RMG do you have "(rmg_env)" at the beginning of the bash line?
ex:  (rmg_env) dhcp-18-20-251-189:RMG-Py mjohnson541$

If yes, in python for the rmg_env can you run "from cantera import ck2cti"?

**Comment by amarkpayne** [comment]
Hi @Christina-98 , another quick check (in addition to what Matt suggested): can you run the following and upload the whole output here?

```
conda activate rmg_env
conda list
```

Let us know how this goes!

**Comment by Christina-98** [comment]
Hi again,

@mjohnson541 I do have (rmg_env) at the beginning of every line. When I typed the other command, I got:
`from: can't read /var/mail/cantera`
which is pretty odd.
@amarkpayne in the conda list I do have cantera (and a bunch of other stuff--but no ck2cti)
Should I download ck2cti? 
Also: is there a reason why the tests and the input files running before?

Thanks a million!

**Comment by mjohnson541** [comment]
Sorry can you instead try running:
`conda activate rmg_env` (if not in the rmg_env already) 
`python -c "from cantera import ck2cti"`

and 
`which ck2cti`

If those don't work can you go to the RMG-Py directory and run

`conda deactivate` (if you are already in the rmg_env)
`conda env update -f environment.yml`

and then try that again. 

If that doesn't work or you still can't run input files can you run 
`conda activate rmg_env` (if not already in the rmg_env)
`conda list`

and paste all of the output from conda list here?

**Comment by Christina-98** [comment]
Hello! Sorry for the late reply:

After running
```
conda activate rmg_env (if not in the rmg_env already)
python -c "from cantera import ck2cti"
which ck2cti
```
I got
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'cantera

```

And after running

```
conda deactivate (if you are already in the rmg_env)
conda env update -f environment.yml
```

I still got the same errors.

The following is the conda list:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_tflow_select             2.3.0                       mkl  
absl-py                   0.8.1                    py37_0  
algopy                    0.5.7                      py_0    rmg
astor                     0.8.0                    py37_0  
attrs                     19.3.0                     py_0  
backcall                  0.1.0                    py37_0  
biopython                 1.74             py37h7b6447c_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py37_0  
boost                     1.67.0                   py37_4  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.15.0            h7b6447c_1001  
ca-certificates           2020.1.1                      0  
cairo                     1.14.12              h8948797_3  
cairocffi                 0.9.0                    py37_0    rmg
cantera                   2.4.0               np115py37_2    cantera
cclib                     1.6.1.rmg        py37h39e3cac_0    rmg
certifi                   2019.11.28               py37_0  
cffi                      1.13.2           py37h2e261b9_0  
chemprop                  0.0.1                      py_0    rmg
click                     7.0                      py37_0  
cloudpickle               1.2.2                      py_0  
coolprop                  6.2.1            py37hf484d3e_0    rmg
coverage                  5.0              py37h7b6447c_0  
cycler                    0.10.0                   py37_0  
cython                    0.29.14          py37he6710b0_0  
dbus                      1.13.12              h746ee38_0  
decorator                 4.4.1                      py_0  
defusedxml                0.6.0                      py_0  
descriptastorus           2.2.0                      py_0    rmg
eigen                     3.3.7                hfd86e86_0  
entrypoints               0.3                      py37_0  
expat                     2.2.6                he6710b0_0  
ffmpeg                    4.2                  h1a5d6f3_0  
flask                     1.1.1                      py_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
fribidi                   1.0.5                h7b6447c_0  
future                    0.18.2                   py37_0  
gast                      0.3.2                      py_0  
glib                      2.63.1               h5a9c865_0  
gmp                       6.1.2                h6c8ec71_1  
google-pasta              0.1.8                      py_0  
gprof2dot                 2017.9.19                  py_0    rmg
graphite2                 1.3.13               h23475e2_0  
graphviz                  2.40.1               h21bd128_2  
grpcio                    1.16.1           py37hf8bcb03_1  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
gunicorn                  20.0.4                   py37_0  
h5py                      2.10.0           py37h7918eee_0  
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.10.4               hb1b8bf9_0  
hyperopt                  0.2.2                      py_0    conda-forge
icu                       58.2                 h9c2bf20_1  
importlib_metadata        1.4.0                    py37_0  
intel-openmp              2019.4                      243  
ipykernel                 5.1.4            py37h39e3cac_0  
ipython                   7.11.1           py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0  
itsdangerous              1.1.0                    py37_0  
jedi                      0.16.0                   py37_0  
jinja2                    2.11.1                     py_0  
joblib                    0.14.1                     py_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.3.4                    py37_0  
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.1                    py37_0  
keras-applications        1.0.8                      py_0  
keras-preprocessing       1.1.0                      py_1  
kiwisolver                1.1.0            py37he6710b0_0  
lame                      3.100                h7b6447c_0  
lapack                    3.6.1                ha44fe06_2    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7  
libboost                  1.67.0               h46d08c1_4  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0  
libopus                   1.3                  h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.11.2               hd408876_0  
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
libuuid                   1.0.3                h1bed415_2  
libvpx                    1.7.0                h439df22_0  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                hea5a465_1  
lpsolve                   5.5.2.5                       2    rmg
lpsolve55                 5.5              py37h39e3cac_2    rmg
markdown                  3.1.1                    py37_0  
markupsafe                1.1.1            py37h7b6447c_0  
matplotlib                3.1.3                    py37_0  
matplotlib-base           3.1.3            py37hef1b27d_0  
mistune                   0.8.4            py37h7b6447c_0  
mkl                       2019.4                      243  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
mopac                     2017                          1    rmg
more-itertools            8.0.2                      py_0  
mpmath                    1.1.0                    py37_0  
muq2                      0.2.0            py37h6bb024c_0    rmg
nanoflann                 1.3.1                         0    conda-forge
nbconvert                 5.6.1                    py37_0  
nbformat                  5.0.4                      py_0  
ncurses                   6.1                  he6710b0_1  
networkx                  2.4                        py_0  
ninja                     1.9.0            py37hfd86e86_0  
nlopt                     2.6.1            py37h29f370e_1    conda-forge
nose                      1.3.7                    py37_2  
notebook                  6.0.3                    py37_0  
numdifftools              0.9.39                     py_0    rmg
numpy                     1.15.4           py37h7e9f1db_0  
numpy-base                1.15.4           py37hde5b4d6_0  
olefile                   0.46                     py37_0  
openbabel                 2.4.1            py37hf484d3e_7    rmg
openh264                  1.8.0                hd408876_0  
openssl                   1.1.1d               h7b6447c_3  
pandas                    0.25.3           py37he6710b0_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
pango                     1.42.4               h049681c_0  
parso                     0.6.0                      py_0  
patsy                     0.5.1                    py37_0  
pcre                      8.43                 he6710b0_0  
pexpect                   4.8.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    7.0.0            py37hb39fc2d_0  
pip                       20.0.2                   py37_0  
pixman                    0.38.0               h7b6447c_0  
prometheus_client         0.7.1                      py_0  
prompt_toolkit            3.0.2                      py_0  
protobuf                  3.11.2           py37he6710b0_0  
psutil                    5.6.7            py37h7b6447c_0  
ptyprocess                0.6.0                    py37_0  
py-boost                  1.67.0           py37h04863e7_4  
pycparser                 2.19                     py37_0  
pydas                     1.0.2            py37h1c1f16f_4    rmg
pydot                     1.4.1                    py37_0  
pydqed                    1.0.1            py37h1c1f16f_3    rmg
pygments                  2.5.2                      py_0  
pymongo                   3.9.0            py37he6710b0_0  
pyparsing                 2.4.6                      py_0  
pyqt                      5.9.2            py37h05f1152_2  
pyrdl                     1.1.2            py37h14c3975_0    rmg
pyrsistent                0.15.7           py37h7b6447c_0  
python                    3.7.6                h0371630_2  
python-dateutil           2.8.1                      py_0  
pytorch-cpu               1.1.0               py3.7_cpu_0    pytorch
pytz                      2019.3                     py_0  
pyyaml                    5.3              py37h7b6447c_0  
pyzmq                     18.1.0           py37he6710b0_0  
qt                        5.9.7                h5867ecd_1  
qtconsole                 4.6.0                      py_1  
quantities                0.12.3             pyh24bf2e0_0    rmg
rdkit                     2019.09.3.0      py37hc20afe1_1    rdkit
readline                  7.0                  h7b6447c_5  
scikit-learn              0.22.1           py37hd81dba3_0  
scipy                     1.4.1            py37h0b6359f_0  
send2trash                1.5.0                    py37_0  
setuptools                45.1.0                   py37_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.14.0                   py37_0  
sqlite                    3.30.1               h7b6447c_0  
statsmodels               0.11.0           py37h7b6447c_0  
sundials                  2.6.2                         0    rmg
symmetry                  1.0.1                         0    rmg
tensorboard               1.14.0           py37hf484d3e_0  
tensorboardx              2.0                        py_0    conda-forge
tensorflow                1.14.0          mkl_py37h45c423b_0  
tensorflow-base           1.14.0          mkl_py37h7ce6ba3_0  
tensorflow-estimator      1.14.0                     py_0  
termcolor                 1.1.0                    py37_1  
terminado                 0.8.3                    py37_0  
testpath                  0.4.4                      py_0  
tk                        8.6.8                hbc83047_0  
torchvision-cpu           0.3.0             py37_cuNone_1    pytorch
tornado                   6.0.3            py37h7b6447c_0  
tqdm                      4.42.0                     py_0  
traitlets                 4.3.3                    py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.16.0                     py_0  
wheel                     0.33.6                   py37_0  
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.11.2           py37h7b6447c_0  
x264                      1!152.20180806       h7b6447c_0  
xlwt                      1.3.0                    py37_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.3.1                he6710b0_3  
zipp                      0.6.0                      py_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0 
```

Thanks a lot!

**Comment by amarkpayne** [comment]
This is very strange. My best guess at this point is that there is a path issue (for example, there might be a different python interpreter that is higher up on your path, and thus you are only accessing its python library instead of your conda one).

Can you activate your RMG environment and then type `which python`, and then type `which conda`? Can you upload a screen capture (crop it, we just need to see the terminal) so that we can both see the output and also check that everything else from the terminal looks okay?

**Comment by Christina-98** [comment]
Hello!
Here's the screen capture:
![Screenshot from 2020-02-12 09-44-43](https://user-images.githubusercontent.com/60776524/74313424-55439f80-4d7c-11ea-9d04-29c8048f8ecd.png)

**Comment by mjohnson541** [comment]
Okay, you're clearly in the rmg_env, but the python accessed in the rmg_env is not the rmg_env python. 

Do you have anything in your .bashrc or .bash_profile or any other anaconda installations that might be affecting this?  To fix this you might try deleting and reinstalling anaconda and rmg.  

However, in theory, if you've installed from source (which I think you have?) I think you should be able to run RMG using the syntax:  
/home/user/anaconda3/envs/rmg_env/bin/python rmg.py input.py

where rmg.py is replaced with the path to the rmg.py executable in the RMG-Py directory and  input.py is replaced with the path to the RMG input file.

**Comment by amarkpayne** [comment]
Just to follow-up with what Matt said, I think we both agree that this is almost certainly a PATH issue due to something in your .bashrc or .bash_profile. Specifically, there is probably a line like `PATH = /home/user/anaconda3/bin:$PATH`, which put this location at the very front of your path. I would try commenting out this line (and close and re-open your terminal to reload the .bashrc file) OR I would change it to the following: `PATH = $PATH:/home/user/anaconda3/bin:`, which appends this to the end of your path so that it does not take priority always.

**Comment by JacksonBurns** [comment]
This installation approach is not longer supported and this issue is stale. Closing.
