### ISSUE TITLE
Problem during restarting a file from seed

### ISSUE THREAD

**Issue by arnab37** [ReactionMechanismGenerator/RMG-Py#1902]
Hi,

I was trying to understand how restarting works in rmg using ethane oyrolysis input file from rmg webste. To understand that, I initially ran that without "restartFromSeed(path='seed')" and after that I ran another file after adding  "restartFromSeed(path='seed')" before the data sources.

I am getting the following error message:

 Error: The input file "/home/abose/input.py" was invalid:
Error: name 'restartFromSeed' is not defined
Traceback (most recent call last):
  File "/home/abose/yes/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/input.py", line 541, in readInputFile
    exec f in global_context, local_context
  File "/home/abose/input.py", line 1, in <module>
    restartFromSeed(path='seed')
NameError: name 'restartFromSeed' is not defined
Traceback (most recent call last):
  File "/home/abose/yes/envs/rmg_env/bin/rmg.py", line 173, in <module>
    main()
  File "/home/abose/yes/envs/rmg_env/bin/rmg.py", line 167, in main
    rmg.execute(**kwargs)
  File "/home/abose/yes/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 599, in execute
    self.initialize(**kwargs)
  File "/home/abose/yes/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 422, in initialize
    self.loadInput(self.inputFile)
  File "/home/abose/yes/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 223, in loadInput
    readInputFile(path, self)
  File "/home/abose/yes/envs/rmg_env/lib/python2.7/site-packages/rmgpy/rmg/input.py", line 541, in readInputFile
    exec f in global_context, local_context
  File "/home/abose/input.py", line 1, in <module>
    restartFromSeed(path='seed')
NameError: name 'restartFromSeed' is not defined

I would really appreciate if anybody could help me with this issue.
Thanks,
Arnab

**Comment by amarkpayne** [comment]
Hi Arnab,

Based on the traceback, it looks like you are using an old python 2 version of RMG-Py. Unfortunately, this feature did not become available until recently with python 3. We did incorporate these changes into our legacy python 2 branch `v2.5.0`, but if possible I highly recommend upgrading to RMG-Py 3.0.0. You can find instructions for updating your RMG installation [here](https://github.com/ReactionMechanismGenerator/RMG-Py/wiki/Transitioning-from-RMG-2-to-RMG-3).

Let us know how this goes!
