### ISSUE TITLE
Problem in Surface_Adsorption_Abstraction_vdW causing charged N adsorbate

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#2038]
### Bug Description

This minimal input file below leads to this crash caused by the reaction family Surface_Adsorption_Abstraction_vdW:

```
Generating initial reactions...
For reaction generation 1 process is used.
Error: Could not update atomtypes for this molecule:
multiplicity -187
1 *4 N u0 p1 c+1 {2,D}
2 *6 X u0 p0 c0 {1,D}

Error: Problem family: Surface_Adsorption_Abstraction_vdW
Error: Problem reactants: (Molecule(smiles="N#N.[Pt]"), Molecule(smiles="[Pt]N=N"))
Error: <Molecule "N#N.[Pt]">
1 *2 N u0 p1 c0 {2,T}
2 *3 N u0 p1 c0 {1,T}
3 *1 X u0 p0 c0

Error: <Molecule "[Pt]N=N">
1 *4 N u0 p1 c0 {2,D} {4,S}
2 *5 N u0 p1 c0 {1,D} {3,S}
3    H u0 p0 c0 {2,S}
4 *6 X u0 p0 c0 {1,S}

Traceback (most recent call last):
  File "/Users/rwest/Code/Cat/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/Users/rwest/Code/Cat/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/main.py", line 732, in execute
    trimolecular_react=self.trimolecular_react)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/model.py", line 599, in enlarge
    procnum=procnum)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/react.py", line 172, in react_all
    return react(spc_fam_tuples, procnum), [fam_tuple[0] for fam_tuple in spc_fam_tuples]
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/react.py", line 66, in react
    reactions = list(map(_react_species_star, spc_fam_tuples))
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/react.py", line 79, in _react_species_star
    return react_species(*args)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/rmg/react.py", line 94, in react_species
    reactions = get_db('kinetics').generate_reactions_from_families(species_tuple, only_families=only_families)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/kinetics/database.py", line 534, in generate_reactions_from_families
    prod_resonance=resonance))
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/kinetics/database.py", line 561, in react_molecules
    prod_resonance=prod_resonance))
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/kinetics/family.py", line 1710, in generate_reactions
    self._generate_reactions(reactants, products=products, forward=True, prod_resonance=prod_resonance))
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/kinetics/family.py", line 1993, in _generate_reactions
    [map_b, map_a], forward)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/kinetics/family.py", line 1588, in _generate_product_structures
    product_structures = self.apply_recipe(reactant_structures, forward=forward)
  File "/Users/rwest/Code/Cat/RMG-Py/rmgpy/data/kinetics/family.py", line 1517, in apply_recipe
    struct.update(sort_atoms=not self.save_order)
  File "rmgpy/molecule/molecule.py", line 1130, in rmgpy.molecule.molecule.Molecule.update
  File "rmgpy/molecule/molecule.py", line 1355, in rmgpy.molecule.molecule.Molecule.update_atomtypes
  File "rmgpy/molecule/molecule.py", line 1350, in rmgpy.molecule.molecule.Molecule.update_atomtypes
  File "rmgpy/molecule/atomtype.py", line 729, in rmgpy.molecule.atomtype.get_atomtype
  File "rmgpy/molecule/atomtype.py", line 757, in rmgpy.molecule.atomtype.get_atomtype
rmgpy.exceptions.AtomTypeError: Unable to determine atom type for atom N+, which has 0 single bonds, 1 double bonds (0 to O, 0 to S, 1 others), 0 triple bonds, 0 quadruple bonds, 0 benzene bonds, 1 lone pairs, and +1 charge.
(rmg3) Richards-iMac:broken rwest$ 

```

### How To Reproduce
Try this input file:
```python

database(
    thermoLibraries=['surfaceThermoPt111', 'primaryThermoLibrary'],
    reactionLibraries = [], 
    seedMechanisms = [],
    kineticsDepositories = ['training'],
    kineticsFamilies = ['Surface_Adsorption_Abstraction_vdW'], # <<<<< ONLY ONE REACTION FAMILY
    kineticsEstimator = 'rate rules',

)

catalystProperties(
    bindingEnergies= {
                         'H':(-2.75367887E+00, 'eV/molecule'),
                         'C':(-7.02515507E+00, 'eV/molecule'),
                         'N':(-4.63224568E+00, 'eV/molecule'),
                         'O':(-3.81153179E+00, 'eV/molecule'),
                      },
    surfaceSiteDensity=(2.483E-09, 'mol/cm^2'),
)

species(
   label='N#N.[Pt]',
   reactive=True,
   structure=adjacencyList(
       """
1  N u0 p1 c0 {2,T}
2  N u0 p1 c0 {1,T}
3  X u0 p0 c0
"""),
)

species(
   label='[Pt]N=N',
   reactive=True,
   structure=adjacencyList(
       """
1  N u0 p1 c0 {2,D} {4,S}
2  N u0 p1 c0 {1,D} {3,S}
3  H u0 p0 c0 {2,S}
4  X u0 p0 c0 {1,S}
"""),
)


species(
    label='N2',
    reactive=False,
    structure=SMILES("N#N"),
)

species(
    label='vacantX',
    reactive=True,
    structure=adjacencyList("1 X u0"),
)
#----------
# Reaction systems
surfaceReactor(
    temperature=(800,'K'),
    initialPressure=(1.0, 'bar'),
    initialGasMoleFractions={
        "N2": 1.0,
    },
    initialSurfaceCoverages={
        "vacantX": 0.5,
        "N#N.[Pt]": 0.25,
        "[Pt]N=N": 0.25
    },
    surfaceVolumeRatio=(1.e5, 'm^-1'),
    terminationTime=(0.1, 's'),
)

simulator(
    atol=1e-18,
    rtol=1e-12,
)

model(
    toleranceKeepInEdge=0.0,
    toleranceMoveToCore=1e-5,
    toleranceInterruptSimulation=0.1,
    maximumEdgeSpecies=100000,
)

options(
    units='si',
    generateOutputHTML=True,
    generatePlots=False,
    saveEdgeSpecies=True,
    saveSimulationProfiles=True,
)

```

### Expected Behavior
It wouldn't crash.

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): macOS X
 - Installation method: from source in anaonda environment
 - RMG version information:
   
   - RMG-Py: the `debugmessages` branch (for additional diagnonstic messages)  https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2035  (hopefully merged soon)
   - RMG-database: current master.  3.0.0-110-g84f5dd8e4 

### Additional Context
@Tingchenlee discovered this problem.  It is https://github.com/comocheng/wiki/issues/610 in the Northeastern CoMoChEng Kanban

**Comment by mazeau** [comment]
This is an issue with the database, not RMG-Py. This should fix the errors. https://github.com/ReactionMechanismGenerator/RMG-database/tree/surface_vdw_fix without having to add forbidden species

**Comment by rwest** [comment]
Should be addressed by https://github.com/ReactionMechanismGenerator/RMG-database/pull/446

**Comment by Tingchenlee** [comment]
https://github.com/ReactionMechanismGenerator/RMG-database/pull/446 works for me

**Comment by rwest** [comment]
Great! Please can you also make a comment to that effect (and/or an "approving" review) on that PR? Thanks
