### ISSUE TITLE
ValueError: No valid NASA polynomial at temperature 1500 K.

### ISSUE THREAD

**Issue by shikharnigam8** [ReactionMechanismGenerator/RMG-Py#2109]
### Bug Description
I am trying to simulate the mechanism for chlorinated carbon compounds. However, I encountered the following error during RMG simulation "ValueError: No valid NASA polynomial at temperature 1500 K." 

Although CdCCl2  species is already present in the Chlorinated Carbon Thermo Library (inbuilt).

### How To Reproduce
Error message attached. 

### Expected Behavior
RMG simulation should terminate without any error.

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): Ubuntu OS
 - Installation method: Source with Anaconda
 - RMG version information:
   
   - RMG-Py:  Latest version
   - RMG-database: Latest database

### Additional Context

For reaction generation 1 process is used.
Generating thermo for new species...
Species ClC=CCl renamed C(Cl)dCCl based on thermo library name
Species C=C(Cl)Cl renamed CdCCl2 based on thermo library name
Traceback (most recent call last):
  File "/home/dr/RMG/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/home/dr/RMG/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/dr/RMG/RMG-Py/rmgpy/rmg/main.py", line 922, in execute
    trimolecular_react=self.trimolecular_react)
  File "/home/dr/RMG/RMG-Py/rmgpy/rmg/model.py", line 614, in enlarge
    self.apply_thermo_to_species(procnum)
  File "/home/dr/RMG/RMG-Py/rmgpy/rmg/model.py", line 824, in apply_thermo_to_species
    self.generate_thermo(spc, rename=True)
  File "/home/dr/RMG/RMG-Py/rmgpy/rmg/model.py", line 831, in generate_thermo
    submit(spc, self.solvent_name)
  File "/home/dr/RMG/RMG-Py/rmgpy/thermo/thermoengine.py", line 175, in submit
    spc.thermo = evaluator(spc, solvent_name=solvent_name)
  File "/home/dr/RMG/RMG-Py/rmgpy/thermo/thermoengine.py", line 160, in evaluator
    thermo = generate_thermo_data(spc, solvent_name=solvent_name)
  File "/home/dr/RMG/RMG-Py/rmgpy/thermo/thermoengine.py", line 125, in generate_thermo_data
    thermo0 = thermodb.get_thermo_data(spc)
  File "/home/dr/RMG/RMG-Py/rmgpy/data/thermo.py", line 1311, in get_thermo_data
    tdata = self.estimate_radical_thermo_via_hbi(molecule, self.get_thermo_data_from_libraries)
  File "/home/dr/RMG/RMG-Py/rmgpy/data/thermo.py", line 1927, in estimate_radical_thermo_via_hbi
    thermo_data_sat = thermo_data_sat.to_thermo_data()
  File "rmgpy/thermo/nasa.pyx", line 331, in rmgpy.thermo.nasa.NASA.to_thermo_data
  File "rmgpy/thermo/nasa.pyx", line 340, in rmgpy.thermo.nasa.NASA.to_thermo_data
  File "rmgpy/thermo/nasa.pyx", line 308, in rmgpy.thermo.nasa.NASA.get_heat_capacity
  File "rmgpy/thermo/nasa.pyx", line 301, in rmgpy.thermo.nasa.NASA.select_polynomial
ValueError: No valid NASA polynomial at temperature 1500 K.

**Comment by alongd** [comment]
The thermo data for CdCCl2 in the Chlorinated_Hydrocarbons thermo library is indeed only defined [up to 1500K](https://github.com/ReactionMechanismGenerator/RMG-database/blob/master/input/thermo/libraries/Chlorinated_Hydrocarbons.py#L1233).
If you do not require T > 1500 K, make sure that the RMG input file is set accordingly (including the PressureDependent block).
If you do require high temperatures, you can either:
1. search and incorporate literature data more relevant to your working conditions, if available
2.  **assume** that the thermo for CdCCl2 follows the same trend beyond 1500 K, and manually increase the upper limit in that library (introducing higher uncertainty, but not to bad if T is close to 1500 K)
3. use GAV instead of the library (by removing this entry from the library). Option number 1 is better, though
4. compute the thermo for this species using a reasonable level of theory

If you really require T >> 1500 K, it is possible that you'll get more errors like this after the case for CdCCl2 is resolved.
You can use [ARC](https://reactionmechanismgenerator.github.io/ARC/index.html) for option 4 if you have access to a server with an electronic structure software such as Gaussian.

**Comment by shikharnigam8** [comment]
Thank you Alon.
