### ISSUE TITLE
RMG Script file is not able to generate reaction library from Chemkin files.  

### ISSUE THREAD

**Issue by shikharnigam8** [ReactionMechanismGenerator/RMG-Py#2116]
### Bug Description
I am trying to generate RMG-Py format reaction library from the chemkin files (generated by RMG-Py). 
However,  I am facing the IndexError: list index out of range, while running the importChemkinLibrary.py script file.
I understand the similar error was faced by one of the RMG user in the past ( issue no #2058)
However, this issue did not provide the complete solution to get rid off this error. 

@rwest 
You previously asked me to check if there is any bug in this script file. (issue no #2100) 

### How To Reproduce
chem.inp and species_dictionary.txt files are attached

### Expected Behavior
The script file should be able to give the desired reaction and thermo library.

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): Ubuntu
 - Installation method: Source with anaconda
 - RMG version information:
   
   - RMG-Py:  Latest version
   - RMG-database: Latest database

### Additional Context
Traceback (most recent call last):
  File "importChemkinLibrary.py", line 35, in <module>
    species_list, reaction_list = load_chemkin_file(chemkin_path, dictionary_path)
  File "rmgpy/chemkin.pyx", line 909, in rmgpy.chemkin.load_chemkin_file
  File "rmgpy/chemkin.pyx", line 931, in rmgpy.chemkin.load_chemkin_file
  File "rmgpy/chemkin.pyx", line 1380, in rmgpy.chemkin.read_reactions_block
  File "rmgpy/chemkin.pyx", line 199, in rmgpy.chemkin.read_kinetics_entry
  File "rmgpy/chemkin.pyx", line 328, in rmgpy.chemkin._read_kinetics_reaction
IndexError: list index out of range
[scripts.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/6409454/scripts.zip)

**Comment by shikharnigam8** [comment]
We need to reduce the number of reactions from the chemkin file. only then this script works.
