### ISSUE TITLE
rmg not working after updating source code

### ISSUE THREAD

**Issue by Jakubanoo** [ReactionMechanismGenerator/RMG-Py#2183]
Hey guys,

Today i updated RMG-Py source code using:
```
git pull https://github.com/ReactionMechanismGenerator/RMG-Py.git master
git pull https://github.com/ReactionMechanismGenerator/RMG-database.git master
```
as said in RMG user's guide.

Now i can't run even simplest test job (butane).
I get this error in all jobs:
```
Loading transport group database from /home/jakub/RMG/RMG-database/input/transport/groups...
Error: Error while reading database '/home/jakub/RMG/RMG-database/input/kinetics/families/Diels_alder_addition/rules.py'.
Error: Error when loading reaction family '/home/jakub/RMG/RMG-database/input/kinetics/families/Diels_alder_addition'
Traceback (most recent call last):
  File "rmg.py", line 118, in <module>
    main()
  File "rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/jakub/RMG/RMG-Py/rmgpy/rmg/main.py", line 673, in execute
    self.initialize(**kwargs)
  File "/home/jakub/RMG/RMG-Py/rmgpy/rmg/main.py", line 496, in initialize
    self.load_database()
  File "/home/jakub/RMG/RMG-Py/rmgpy/rmg/main.py", line 374, in load_database
    depository=False,  # Don't bother loading the depository information, as we don't use it
  File "/home/jakub/RMG/RMG-Py/rmgpy/data/rmg.py", line 103, in load
    kinetics_depositories
  File "/home/jakub/RMG/RMG-Py/rmgpy/data/rmg.py", line 172, in load_kinetics
    depositories=kinetics_depositories
  File "/home/jakub/RMG/RMG-Py/rmgpy/data/kinetics/database.py", line 111, in load
    self.load_families(os.path.join(path, 'families'), families, depositories)
  File "/home/jakub/RMG/RMG-Py/rmgpy/data/kinetics/database.py", line 215, in load_families
    family.load(family_path, self.local_context, self.global_context, depository_labels=depositories)
  File "/home/jakub/RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 755, in load
    self.rules.load(os.path.join(path, 'rules.py'), local_context, global_context)
  File "/home/jakub/RMG/RMG-Py/rmgpy/data/base.py", line 241, in load
    exec(f.read(), global_context, local_context)
  File "<string>", line 12, in <module>
  File "rmgpy/kinetics/uncertainties.pyx", line 48, in rmgpy.kinetics.uncertainties.RateUncertainty.__init__
    
TypeError: __init__() got an unexpected keyword argument 'data_mean'
(rmg_env) jakub@jakub-VirtualBox:~/RMG/RMG-Py$ 
```
I have no idea what to do, thanks.

**Comment by Jakubanoo** [comment]
I installed RMG again, and ditched the previous one- it works now.

Any idea why the update crashed the RMG?

**Comment by amarkpayne** [comment]
Did you run `make clean` and `make` after you pulled? Given that the error is from a cython file (.pyx extension) I think this is probably the cause

**Comment by Jakubanoo** [comment]
I did not, i am not familiar with linux etc.
Thank you for answering.
