### ISSUE TITLE
RMG Update 

### ISSUE THREAD

**Issue by laubapires** [ReactionMechanismGenerator/RMG-Py#2206]
### Bug Description
Hi Guys! So, I had RMG installed, and worked perfectly! However, I've updated it and, since then, I've been getting the following error "name 'rms' is not defined". To solve it, I've tried to "make clean", update rms, and so on. Additionally, I've also removed the environment and installed all of it once more; but it didn't solve it. What should I do? 

### How To Reproduce
The error is coming specifically for "**rad = rms.getspeciesradius(atomnums, bondnum)"**

### Installation Information
Describe your installation method and system information.
 - Windows 10, with anaconda

**Comment by mjohnson541** [comment]
The installation instructions have changed a bit see here: http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html

I can't really tell what your exact issue is without seeing the error trace, I would've expected it to error when importing rms if it wasn't installed right.

**Comment by laubapires** [comment]
Hi! So, yes, that was what I thought as well. That's why I've removed the environment and created a new one. I've followed step by step as indicated by the weblink.

**Comment by mjohnson541** [comment]
Can you post the error traceback?

**Comment by laubapires** [comment]
(...)


Loading transport library from NOx2018.py in /home/laura/RMG-database/input/transport/libraries...
Loading transport library from PrimaryTransportLibrary.py in /home/laura/RMG-database/input/transport/libraries...
Loading transport library from OneDMinN2.py in /home/laura/RMG-database/input/transport/libraries...
Loading transport library from NIST_Fluorine.py in /home/laura/RMG-database/input/transport/libraries...
Loading transport library from GRI-Mech.py in /home/laura/RMG-database/input/transport/libraries...
Loading transport group database from /home/laura/RMG-database/input/transport/groups...
Loading frequencies group database from /home/laura/RMG-database/input/statmech/groups...
Loading solvation thermodynamics group database from /home/laura/RMG-database/input/solvation/groups...
Loading thermodynamics library from primaryThermoLibrary.py in /home/laura/RMG-database/input/thermo/libraries...
Loading thermodynamics group database from /home/laura/RMG-database/input/thermo/groups...
Adding rate rules from training set in kinetics families...
Filling in rate rules in kinetics families by averaging...
Traceback (most recent call last):
  File "/home/laura/anaconda3/envs/rmg_env/bin/rmg.py", line 118, in <module>
    main()
  File "/home/laura/anaconda3/envs/rmg_env/bin/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/laura/RMG-Py/rmgpy/rmg/main.py", line 695, in execute
    self.initialize(**kwargs)
  File "/home/laura/RMG-Py/rmgpy/rmg/main.py", line 507, in initialize
    self.reaction_model.add_species_to_edge(spec)
  File "/home/laura/RMG-Py/rmgpy/rmg/model.py", line 1142, in add_species_to_edge
    self.edge.phase_system.phases["Default"].add_species(spec)
  File "/home/laura/RMG-Py/rmgpy/rmg/reactors.py", line 232, in add_species
    spec = to_rms(spc)
  File "/home/laura/RMG-Py/rmgpy/rmg/reactors.py", line 453, in to_rms
    rad = rms.getspeciesradius(atomnums, bondnum)
NameError: name 'rms' is not defined

**Comment by mjohnson541** [comment]
Are you launching the RMG job with python-jl?

**Comment by laubapires** [comment]
Well, I guess so. I can run Julia smoothly. And I've installed/linked Julia
dependencies as recommended. However, I hate pycall, it is always executed
with errors, but, anyway, even like this, it used to run.

**Comment by mjohnson541** [comment]
Hmm...what happens when you run: 
```
python-jl -c "from pyrms import rms"
```

and if that doesn't work: 
```
python-jl -c "from julia import Main"
```

**Comment by laubapires** [comment]
Nothing happens, hahaha! I guess it seems ok.

**Comment by mjohnson541** [comment]
What command are you using to launch RMG?

**Comment by laubapires** [comment]
I'm using the virtual environment (conda activate rmg_env); following the
basic command, e.g.  rmg.py input.p <http://input.py/>y.
So, nothing unusual. Is this the question?

**Comment by mjohnson541** [comment]
Yes, I think that syntax likely doesn't work anymore. Calling it this way, inserting an appropriate path should work: 
```
python-jl /path/to/RMG/executable input.py
```

**Comment by mjohnson541** [comment]
It should theoretically be possible to adjust rmg.py so that syntax works, but I think I tested doing that before and it isn't simply a matter of substituting python-jl at the top of the file.

**Comment by laubapires** [comment]
Hi Matt, thanks! This has worked! 
The error would never make me notice this, instead, I was thinking it had something to do with Julia as well.

**Comment by amarkpayne** [comment]
Does replacing it with `/usr/bin/env python-jl` work? I am trying this out on my end now

**Comment by amarkpayne** [comment]
Thanks for checking this, @laubapires ! We'll update this file and the documentation accordingly

**Comment by laubapires** [comment]
Hi guys! I'm facing this error again (name 'rms' is not defined)! Hahaha! But have tried every command already. Also using the latest version
