### ISSUE TITLE
to_rms issue

### ISSUE THREAD

**Issue by NUSCondy** [ReactionMechanismGenerator/RMG-Py#2214]
Hi @alongd ,

This issue seems to be related with RMS module. I have tried two different tests, one use AramcoMech_2.0 and the other is an example case. Both encountered bugs, shown below:

**Traceback (most recent call last):
  File "/home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 308, in main
    python(**vars(ns))
  File "/home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 59, in python
    scope = runpy.run_path(script, run_name="__main__")
  File "/home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhuqiren/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/home/zhuqiren/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/zhuqiren/RMG-Py/rmgpy/rmg/main.py", line 755, in execute
    trimolecular_react=self.trimolecular_react)
  File "/home/zhuqiren/RMG-Py/rmgpy/rmg/model.py", line 679, in enlarge
    self.update_unimolecular_reaction_networks()
  File "/home/zhuqiren/RMG-Py/rmgpy/rmg/model.py", line 1872, in update_unimolecular_reaction_networks
    network.update(self, self.pressure_dependence)
  File "/home/zhuqiren/RMG-Py/rmgpy/rmg/pdep.py", line 893, in update
    reaction_model.add_reaction_to_edge(net_reaction)
  File "/home/zhuqiren/RMG-Py/rmgpy/rmg/model.py", line 1478, in add_reaction_to_edge
    self.edge.phase_system.phases["Default"].add_reaction(rxn)
  File "/home/zhuqiren/RMG-Py/rmgpy/rmg/reactors.py", line 217, in add_reaction
    self.reactions.append(to_rms(rxn, species_names=self.names, rms_species_list=self.species))
  File "/home/zhuqiren/RMG-Py/rmgpy/rmg/reactors.py", line 467, in to_rms
    kinetics = to_rms(obj.kinetics)
  File "/home/zhuqiren/RMG-Py/rmgpy/rmg/reactors.py", line 483, in to_rms
    raise ValueError(f"Couldn't convert object of type {errortype} to an RMS object")
ValueError: Couldn't convert object of type <class 'NoneType'> to an RMS object**

****Traceback (most recent call last):
File "/home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 308, in main
python(**vars(ns))
File "/home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 59, in python
scope = runpy.run_path(script, run_name="main")
File "/home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 263, in run_path
pkg_name=pkg_name, script_name=fname)
File "/home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 96, in _run_module_code
mod_name, mod_spec, pkg_name, script_name)
File "/home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/zhuqiren/RMG-Py/rmg.py", line 118, in
main()
File "/home/zhuqiren/RMG-Py/rmg.py", line 112, in main
rmg.execute(**kwargs)
File "/home/zhuqiren/RMG-Py/rmgpy/rmg/main.py", line 695, in execute
self.initialize(kwargs)
File "/home/zhuqiren/RMG-Py/rmgpy/rmg/main.py", line 577, in initialize
self.reaction_model.add_reaction_library_to_edge(library)
File "/home/zhuqiren/RMG-Py/rmgpy/rmg/model.py", line 1725, in add_reaction_library_to_edge
self.add_reaction_to_edge(rxn)
File "/home/zhuqiren/RMG-Py/rmgpy/rmg/model.py", line 1478, in add_reaction_to_edge
self.edge.phase_system.phases["Default"].add_reaction(rxn)
File "/home/zhuqiren/RMG-Py/rmgpy/rmg/reactors.py", line 217, in add_reaction
self.reactions.append(to_rms(rxn, species_names=self.names, rms_species_list=self.species))
File "/home/zhuqiren/RMG-Py/rmgpy/rmg/reactors.py", line 467, in to_rms
kinetics = to_rms(obj.kinetics)
File "/home/zhuqiren/RMG-Py/rmgpy/rmg/reactors.py", line 416, in to_rms
efficiencies = {spc.label: float(val) for spc, val in obj.efficiencies.items() if val != 1}
File "/home/zhuqiren/RMG-Py/rmgpy/rmg/reactors.py", line 416, in
efficiencies = {spc.label: float(val) for spc, val in obj.efficiencies.items() if val != 1}
AttributeError: 'rmgpy.molecule.molecule.Molecule' object has no attribute 'label'**

The input files are attached
[input1.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/7350920/input1.txt)
[inputAramco.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/7350921/inputAramco.txt)
:

**Comment by NUSCondy** [comment]
Hi,
FYI, for the ethane example case, if I comment the pressure dependence options, it becomes good again.
For the one using AramcoMech_2.0, such a change doesn't work.

**Comment by NUSCondy** [comment]
Hi,

FYI, I have tried to build an ethane oxidation mechanism using Aramcomech_2.0 thermo and kinetics library with RMG I installed in Sept 2020. It seems that it is okay with that old version.

**Comment by NUSCondy** [comment]
Hi @mjohnson541,
Is this issue fixed on the latest version or on other branch?
