### ISSUE TITLE
Attribute error while adding reaction library to edge

### ISSUE THREAD

**Issue by sevyharris** [ReactionMechanismGenerator/RMG-Py#2230]
### Bug Description
RMG tries to access nonexistent kinetics while adding a reaction library to the edge. It errors out because there is no `kinetics` attribute.

### How To Reproduce
Run RMG on the main branch using the input file copied below.

### Expected Behavior
I expect RMG to add the library to the edge without erroring out. This can be fixed with an extra check for the kinetics attribute before accessing it (or I've heard it's more Pythonic to use try/except). I'll check that the library itself is correctly formed, but I've run this exact input without this error before, so it's probably not the library.

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): Ubuntu 18.04.5 LTS
 - Installation method: source
 - RMG version information: 3.1.0-372-g9da4e5d17
   
   - RMG-Py: 9da4e5d1745f40a3ff5d4199dff911623dac130e
   - RMG-database: 486800be90ddf1e8ef5f2b09b23b766f2efaa9b0

### Additional Context
Error message:
```
Traceback (most recent call last):
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 308, in main
    python(**vars(ns))
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 59, in python
    scope = runpy.run_path(script, run_name="__main__")
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sevy/rmg/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/home/sevy/rmg/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/sevy/rmg/RMG-Py/rmgpy/rmg/main.py", line 707, in execute
    self.initialize(**kwargs)
  File "/home/sevy/rmg/RMG-Py/rmgpy/rmg/main.py", line 589, in initialize
    self.reaction_model.add_reaction_library_to_edge(library)
  File "/home/sevy/rmg/RMG-Py/rmgpy/rmg/model.py", line 1673, in add_reaction_library_to_edge
    if getattr(r.kinetics, 'coverage_dependence', None):
AttributeError: 'NoneType' object has no attribute 'kinetics'
```

Input file:
```
# Data sources
database(
    thermoLibraries = ['BurkeH2O2', 'CurranPentane','FFCM1(-)','primaryThermoLibrary', 'thermo_DFT_CCSDTF12_BAC', 'DFT_QCI_thermo', 'CBS_QB3_1dHR'],
    reactionLibraries = ['CurranPentane','FFCM1(-)','combustion_core/version5'],
    seedMechanisms = ['BurkeH2O2inN2','BurkeH2O2inArHe', 'C2H4+O_Klipp2017'],#added BurkeH2O2inAr and BurkeH2O2inN2 for bath gases
    kineticsDepositories = ['training'],
    kineticsFamilies = 'default',
    kineticsEstimator = 'rate rules',
)
# List of species 
species(
    label = 'nheptane',
    reactive = True,
    structure = SMILES("CCCCCCC"),
)

species(
    label = 'O2',
    reactive = True,
    structure = SMILES("[O][O]"),
)

species(
    label = 'N2',
    reactive = False,
    structure = SMILES("N#N"),
)

species(
    label = 'Ar',
    reactive = False,
    structure = SMILES("[Ar]"),
)


# We want CH, C2H and O to be forced into the core,
# and to have known (reproducible) species numbers
# because we use them when post-processing ignition
# delay simulations.

species(
    label = 'CH',
    reactive = True,
    structure = SMILES("[CH]"),
)

species(
    label = 'C2H',
    reactive = True,
    structure = SMILES("[C]#C"),
)

species(
    label = 'O',
    reactive = True,
    structure = SMILES("[O]"),
)


#Species that typically show up in JSR reactors based on Dagaut 2014
species(
    label = 'CO',
    reactive = True,
    structure = SMILES("[C-]#[O+]"),
)

species(
    label = 'CO2',
    reactive = True,
    structure = SMILES("O=C=O"),
)

species(
    label = 'H2O',
    reactive = True,
    structure = SMILES("O"),
)

species(
    label = 'CH2O',
    reactive = True,
    structure = SMILES("C=O"),
)

species(
    label = 'CH4',
    reactive = True,
    structure = SMILES("C"),
)

species(
    label = 'C2H4',
    reactive = True,
    structure = SMILES("C=C"),
)

species(
    label = 'C3H6',
    reactive = True,
    structure = SMILES("C=CC"),
)

species(
    label = 'H2',
    reactive = True,
    structure = SMILES("[H][H]"),
)


# Reaction systems 1 for the high temperature range with Argon as the bath gas 
simpleReactor(
    temperature=[(550,'K'),(1500,'K')],#max reactor temperature must always be less than max pdep temperature
    pressure=[(1.0,'bar'),(40.0,'bar')],
    nSims=5,
    initialMoleFractions={
        # "nheptane": 0.003747, # phi = 1
        "nheptane": [0.003747/2, 0.003747*2], # range of 0.5 < phi < 2
        "Ar":0.955040,
        "O2": 0.041213,
        },
    terminationTime=(1.0, 's'),
    terminationRateRatio=0.01,
)

# Reaction systems 2 for the high temperature range with Nitrogen as the bath gas 
simpleReactor(
    temperature=[(550,'K'),(1500,'K')],#max reactor temperature must always be less than max pdep temperature
    pressure=[(1.0,'bar'),(40.0,'bar')],
    nSims=5,
    initialMoleFractions={
        # "nheptane": 0.003747, # phi = 1
        "nheptane": [0.003747/2, 0.003747*2], # range of 0.5 < phi < 2
        "N2": 0.955040,
        "O2": 0.041213,
        },
    terminationTime=(1.0, 's'),
    terminationRateRatio=0.01,
)

# Reaction system 3 for the low temperature range with Argon as the bath gas
simpleReactor(
    temperature=[(550,'K'),(800,'K')],
    pressure=[(1.0,'bar'),(40.0,'bar')],
    nSims=17,
    initialMoleFractions={
        # "nheptane": 0.003747, # phi = 1
        "nheptane": [ 0.003747/2, 0.003747*2], # range of 0.5 < phi < 2
        "Ar": 0.955040,
        "O2": 0.041213,
        },
    terminationTime=(1.0, 's'),
    terminationRateRatio=0.01,
)


# Reaction system 4 for the low temperature range with Nitrogen as the bath gas
simpleReactor(
    temperature=[(550,'K'),(800,'K')],
    pressure=[(1.0,'bar'),(40.0,'bar')],
    nSims=17,
    initialMoleFractions={
        # "nheptane": 0.003747, # phi = 1
        "nheptane": [ 0.003747/2, 0.003747*2], # range of 0.5 < phi < 2
        "N2": 0.955040,
        "O2": 0.041213,
        },
    terminationTime=(1.0, 's'),
    terminationRateRatio=0.01,
)

# Introducing staging into the model and simulator blocks

# first stage with a higher tolerance
simulator(
    atol=1e-16,
    rtol=1e-8,
)

# second stage with a lower tolerance 
simulator(
    atol=1e-16,
    rtol=1e-8,
)

# first stage with a lower maxNumSpecies=300
model(
    toleranceKeepInEdge=0.0055,
    toleranceMoveToCore=0.1,
    filterReactions = True,
    filterThreshold = 5e8, # Default is 5e8
    maximumEdgeSpecies=100000,
    maxNumObjsPerIter=1,# number of objects (species, reactions, PDepNetworks) that can be taken from one simulation
    maxNumSpecies = 300,
)


# first stage with a lower maxNumSpecies=500

model(
    toleranceKeepInEdge=0.0055,
    toleranceMoveToCore=0.1,
    filterReactions = True,
    filterThreshold = 5e8, # Default is 5e8
    maximumEdgeSpecies=100000,
    maxNumObjsPerIter=3,
    maxNumSpecies = 500,
)

pressureDependence(
        method='modified strong collision',
        maximumGrainSize=(0.5,'kcal/mol'),
        minimumNumberOfGrains=250,
        temperatures=(300,2000,'K',8),#due to thermo library max pdep=2500K cannot go to 3000K
        pressures=(0.01,100,'bar',5),
        interpolation=('Chebyshev', 6, 4),
        maximumAtoms=16,
)

options(
    units='si',
    saveRestartPeriod=None,
    generateOutputHTML=True,
    generatePlots=False,
    saveEdgeSpecies=True,
    saveSimulationProfiles=True,
 )
# Introduced the species constraint for the mechanism. Set the maximumRadicalElectrons to 2 for N2
generatedSpeciesConstraints(
    allowed=['input species','seed mechanisms','reaction libraries'],
    maximumCarbonAtoms=10,
    maximumRadicalElectrons=2,
)


```

**Comment by sevyharris** [comment]
Turns out it is the library's fault. It looks like the offending reaction is this one from CurranPentane:
rxn=H(14) + C3H2(S)(174) <=> H(14) + C3H2(S)(174)

```
entry(
    index = 847,
    label = "C3H2(S) + H <=> C3H2(S) + H",
    degeneracy = 1,
    kinetics = Arrhenius(A=(1e+13, 'cm^3/(mol*s)'), n=0, Ea=(0, 'cal/mol'), T0=(1, 'K')),
    shortDesc = u"""""",
)
```
It fails to get the kinetics and then errors out when it tries to access the missing attribute. 
I have already run into trouble from this reaction before, see [issue 526](https://github.com/ReactionMechanismGenerator/RMG-database/issues/526).
Maybe this reaction should be commented out until the library is fixed to handle the two different species.

**Comment by sevyharris** [comment]
This is a database issue, not an RMG-Py one, so I'm going to close it. There's a link to this issue in the RMG-database one.
