### ISSUE TITLE
`make eg2` (1,3-hexadiene) fails with InvalidMicrocanonicalRateError

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#224]
On (what I believe is) the current master RMG-Py and RMG-Database, the 1,3-hexadiene example, which can be run via `make eg2`, does not work but gives an InvalidMicrocanonicalRateError:

I think the trouble is with PDep Network number 3:

```
3 network information
---------------------
Isomers:
    C=C[CH]C(CC)C(C=C)[CH]CC(26)                          238.871 kJ/mol
Reactant channels:
    HXD13(1) + HXD13(1)                                   70.5003 kJ/mol
Product channels:
    [CH2]C=CC(CC)C1C([CH2])C1CC(150)                      273.168 kJ/mol
    [CH2][CH]C1C(CC)C(C=C)C1CC(151)                       275.034 kJ/mol
    [CH2]C1CC=CC(CC)C1[CH]CC(152)                         218.773 kJ/mol
    [H](12) + [CH2]C=CC(CC)C(C=C)C=CC(153)                371.143 kJ/mol
    [H](12) + C=C=CC(CC)C(C=C)[CH]CC(154)                 475.801 kJ/mol
    [H](12) + [CH2]C=CC(CC)C(C=C)=CCC(155)                350.235 kJ/mol
    [CH3](8) + C=C[CH]C(CC)C(C=C)C=C(99)                  331.763 kJ/mol
    HXD13(1) + [CH2][CH]C=CCC(20)                         251.534 kJ/mol
    [CH]=C(15) + [CH2]C=CC(C=CCC)CC(156)                  377.769 kJ/mol
    [CH2](5) + [CH2]C=CC(C)C(C=C)[CH]CC(157)              681.742 kJ/mol
    [CH2](5) + [CH2]C=CC(CC)C([CH]C)C=C(158)              681.742 kJ/mol
    [CH3](8) + [CH2]C=CC([CH2])C(C=C)[CH]CC(73)           604.153 kJ/mol
    [H](12) + [CH2]C=CC([CH]C)C(C=C)[CH]CC(159)           645.238 kJ/mol
    C[CH2](10) + [CH2]C=C[CH]C(C=C)[CH]CC(160)            542.471 kJ/mol
    [CH3](8) + [CH2][CH]C(C=C)C([CH]C=C)CC(78)            604.317 kJ/mol
    [H](12) + [CH2]C=CC(CC)C(C=C)[CH][CH]C(161)           645.142 kJ/mol
    [H](12) + [CH2]C=CC(C[CH2])C(C=C)[CH]CC(162)          655.942 kJ/mol
    [H](12) + [CH2]C=CC(CC)C(C=C)[CH]C[CH2](163)          655.942 kJ/mol
    [H](12) + [CH2]C=C[C](CC)C(C=C)[CH]CC(164)            582.677 kJ/mol
    [H](12) + [CH2]C=CC(CC)[C](C=C)[CH]CC(165)            529.804 kJ/mol
    [H](12) + [CH2]C=CC(CC)C([C]=C)[CH]CC(166)            688.538 kJ/mol
    [H](12) + [CH2]C=[C]C(CC)C(C=C)[CH]CC(167)            688.538 kJ/mol
    [H](12) + [CH2][C]=CC(CC)C(C=C)[CH]CC(168)            688.538 kJ/mol
    [H](12) + [CH]=CC([CH]CC)C(C=C[CH2])CC(169)           697.792 kJ/mol
    [CH2][CH]C=CCC(20) + [CH2][CH]C=CCC(20)               432.568 kJ/mol
    [CH]=C(15) + [CH2]C=CC([CH][CH]CC)CC(170)             650.646 kJ/mol
    [CH]=C[CH2](56) + C=CC([CH]CC)[CH]CC(171)             622.498 kJ/mol
    C=CC([CH]CC)C(CC)C1[CH]C1(172)                        381.584 kJ/mol
    [CH2]C=CC(CC)C1[CH]CC1CC(173)                         211.906 kJ/mol
    [CH2]C1[CH]C(CC)C(C=C)C1CC(174)                       232.465 kJ/mol
    CC[CH]C1[CH]CCC=CC1CC(175)                            221.705 kJ/mol
    [CH2]C=CC(CC)C(C=C)C[CH]C(176)                        238.808 kJ/mol
    C=CC([CH]CC)C(C=[C]C)CC(177)                          325.213 kJ/mol
    [CH2]C=CC(CC)[C](C=C)CCC(178)                         176.343 kJ/mol
    [CH2]C=CC(CC)C(C=C)CC[CH2](179)                       249.608 kJ/mol
    C=CC([CH]CC)C([C]=CC)CC(180)                          325.213 kJ/mol
    [CH2]C=C[C](CC)C(C=C)CCC(181)                         176.343 kJ/mol
    [CH2]C=CC(CC)C([C]=C)CCC(182)                         282.204 kJ/mol
    C=CC([CH]CC)[C](C=CC)CC(183)                          219.385 kJ/mol
    [CH2]C=CC([CH]C)C(C=C)CCC(184)                        238.904 kJ/mol
    [CH2]C=[C]C(CC)C(C=C)CCC(185)                          282.17 kJ/mol
    [CH]=CC(CCC)C(C=C[CH2])CC(186)                        291.425 kJ/mol
    C=CC([CH]CC)C([CH]C)C=CC(187)                         281.914 kJ/mol
    C=C[C]([CH]CC)C(C=CC)CC(188)                          166.513 kJ/mol
    [CH2]C=CC(C[CH2])C(C=C)CCC(189)                       249.575 kJ/mol
    [CH2][C]=CC(CC)C(C=C)CCC(190)                          282.17 kJ/mol
    [CH2]CC(C=CC)C(C=C)[CH]CC(191)                        292.618 kJ/mol
    C=[C]C([CH]CC)C(C=CC)CC(192)                          325.213 kJ/mol
    C=CC([CH][CH]C)C(C=CC)CC(193)                         281.818 kJ/mol
    [CH]=CC([CH]CC)C(C=CC)CC(194)                         334.468 kJ/mol
    C=CC1C(CC)C=CCC1CC(35)                               -45.9723 kJ/mol
    [CH2][CH]C([CH]CC)C(C=C[CH2])CC(195)                  519.849 kJ/mol
    [CH2]C1[CH]C(CC)C([CH]CC)[CH]C1(196)                  491.871 kJ/mol
    [CH2]C1C(C=C)C(CC)C1[CH]CC(197)                       273.474 kJ/mol
    [H](12) + C=CC=C(CC)C(C=C)[CH]CC(198)                 404.059 kJ/mol
    C[CH2](10) + C=CC=CC(C=C)[CH]CC(199)                  360.889 kJ/mol
    [H](12) + [CH]=C[CH]C(CC)C(C=C)[CH]CC(200)            669.881 kJ/mol
    C=CC1C[CH]C([CH]CC)C1CC(201)                          223.353 kJ/mol
    C=CC1C(CC)[CH][CH]CC1CC(202)                          221.111 kJ/mol
    C=CC[C](CC)C(C=C)[CH]CC(203)                          290.698 kJ/mol
    C=[C]CC(CC)C(C=C)[CH]CC(204)                          343.083 kJ/mol
    C=CCC([CH]C)C(C=C)[CH]CC(205)                         299.817 kJ/mol
    C=CCC(CC)[C](C=C)[CH]CC(206)                           183.49 kJ/mol
    [CH]=CCC(CC)C(C=C)[CH]CC(207)                         352.371 kJ/mol
    [CH2]CC(CC=C)C(C=C)[CH]CC(208)                        310.488 kJ/mol
    C=[C]C([CH]CC)C(CC)CC=C(209)                          343.083 kJ/mol
    [CH]=CC([CH]CC)C(CC)CC=C(210)                         352.338 kJ/mol
    C=CCC(CC)C(C=C)[CH][CH]C(211)                         299.688 kJ/mol
    [CH2]C[CH]C(C=C)C(CC)CC=C(212)                        310.488 kJ/mol
    [CH]=C[CH]C(CC)C(C=C)CCC(213)                         263.514 kJ/mol
    C=CC1C(CC)C(C=C)C1CC(43)                              6.48447 kJ/mol
Path reactions:
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> HXD13(1) + HXD13(1)      238.871 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2]C=CC(CC)C1C([CH2])C1CC(150)      276.527 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2][CH]C1C(CC)C(C=C)C1CC(151)      434.891 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2]C1CC=CC(CC)C1[CH]CC(152)      354.445 kJ/mol
    [H](12) + [CH2]C=CC(CC)C(C=C)C=CC(153) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      376.875 kJ/mol
    [H](12) + C=C=CC(CC)C(C=C)[CH]CC(154) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)        487.6 kJ/mol
    [H](12) + [CH2]C=CC(CC)C(C=C)=CCC(155) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      361.364 kJ/mol
    [CH3](8) + C=C[CH]C(CC)C(C=C)C=C(99) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      354.022 kJ/mol
    HXD13(1) + [CH2][CH]C=CCC(20) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)       305.09 kJ/mol
    [CH]=C(15) + [CH2]C=CC(C=CCC)CC(156) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      390.196 kJ/mol
    [CH2](5) + [CH2]C=CC(C)C(C=C)[CH]CC(157) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      681.742 kJ/mol
    [CH2](5) + [CH2]C=CC(CC)C([CH]C)C=C(158) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      681.742 kJ/mol
    [CH3](8) + [CH2]C=CC([CH2])C(C=C)[CH]CC(73) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      604.153 kJ/mol
    [H](12) + [CH2]C=CC([CH]C)C(C=C)[CH]CC(159) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      645.238 kJ/mol
    C[CH2](10) + [CH2]C=C[CH]C(C=C)[CH]CC(160) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      542.471 kJ/mol
    [CH3](8) + [CH2][CH]C(C=C)C([CH]C=C)CC(78) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      604.317 kJ/mol
    [H](12) + [CH2]C=CC(CC)C(C=C)[CH][CH]C(161) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      645.142 kJ/mol
    [H](12) + [CH2]C=CC(C[CH2])C(C=C)[CH]CC(162) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      655.942 kJ/mol
    [H](12) + [CH2]C=CC(CC)C(C=C)[CH]C[CH2](163) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      655.942 kJ/mol
    [H](12) + [CH2]C=C[C](CC)C(C=C)[CH]CC(164) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      582.677 kJ/mol
    [H](12) + [CH2]C=CC(CC)[C](C=C)[CH]CC(165) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      529.804 kJ/mol
    [H](12) + [CH2]C=CC(CC)C([C]=C)[CH]CC(166) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      688.538 kJ/mol
    [H](12) + [CH2]C=[C]C(CC)C(C=C)[CH]CC(167) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      688.538 kJ/mol
    [H](12) + [CH2][C]=CC(CC)C(C=C)[CH]CC(168) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      688.538 kJ/mol
    [H](12) + [CH]=CC([CH]CC)C(C=C[CH2])CC(169) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      697.792 kJ/mol
    [CH2][CH]C=CCC(20) + [CH2][CH]C=CCC(20) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      432.568 kJ/mol
    [CH]=C(15) + [CH2]C=CC([CH][CH]CC)CC(170) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      650.646 kJ/mol
    [CH]=C[CH2](56) + C=CC([CH]CC)[CH]CC(171) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      622.498 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> C=CC([CH]CC)C(CC)C1[CH]C1(172)      464.807 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2]C=CC(CC)C1[CH]CC1CC(173)      373.972 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2]C1[CH]C(CC)C(C=C)C1CC(174)      395.942 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> CC[CH]C1[CH]CCC=CC1CC(175)      441.852 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2]C=CC(CC)C(C=C)C[CH]C(176)      397.863 kJ/mol
    C=CC([CH]CC)C(C=[C]C)CC(177) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      498.012 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2]C=CC(CC)[C](C=C)CCC(178)      360.625 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2]C=CC(CC)C(C=C)CC[CH2](179)      400.373 kJ/mol
    C=CC([CH]CC)C([C]=CC)CC(180) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      487.134 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2]C=C[C](CC)C(C=C)CCC(181)      402.465 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2]C=CC(CC)C([C]=C)CCC(182)      416.691 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> C=CC([CH]CC)[C](C=CC)CC(183)      572.817 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2]C=CC([CH]C)C(C=C)CCC(184)      325.479 kJ/mol
    [CH2]C=[C]C(CC)C(C=C)CCC(185) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      408.128 kJ/mol
    [CH]=CC(CCC)C(C=C[CH2])CC(186) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      417.382 kJ/mol
    C=CC([CH]CC)C([CH]C)C=CC(187) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      332.414 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> C=C[C]([CH]CC)C(C=CC)CC(188)      364.828 kJ/mol
    [CH2]C=CC(C[CH2])C(C=C)CCC(189) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      309.322 kJ/mol
    [CH2][C]=CC(CC)C(C=C)CCC(190) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      408.128 kJ/mol
    [CH2]CC(C=CC)C(C=C)[CH]CC(191) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      418.575 kJ/mol
    C=[C]C([CH]CC)C(C=CC)CC(192) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      451.171 kJ/mol
    C=CC([CH][CH]C)C(C=CC)CC(193) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      407.775 kJ/mol
    [CH]=CC([CH]CC)C(C=CC)CC(194) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      460.425 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> C=CC1C(CC)C=CCC1CC(35)      247.071 kJ/mol
    [CH2][CH]C([CH]CC)C(C=C[CH2])CC(195) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      519.849 kJ/mol
    [CH2]C1[CH]C(CC)C([CH]CC)[CH]C1(196) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      491.871 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2]C1C(C=C)C(CC)C1[CH]CC(197)      348.031 kJ/mol
    [H](12) + C=CC=C(CC)C(C=C)[CH]CC(198) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      408.996 kJ/mol
    C[CH2](10) + C=CC=CC(C=C)[CH]CC(199) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)       375.24 kJ/mol
    [H](12) + [CH]=C[CH]C(CC)C(C=C)[CH]CC(200) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      669.881 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> C=CC1C[CH]C([CH]CC)C1CC(201)      334.977 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> C=CC1C(CC)[CH][CH]CC1CC(202)      441.852 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> C=CC[C](CC)C(C=C)[CH]CC(203)      415.854 kJ/mol
    C=[C]CC(CC)C(C=C)[CH]CC(204) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      499.983 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> C=CCC([CH]C)C(C=C)[CH]CC(205)      431.753 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> C=CCC(CC)[C](C=C)[CH]CC(206)      364.828 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH]=CCC(CC)C(C=C)[CH]CC(207)      507.065 kJ/mol
    [CH2]CC(CC=C)C(C=C)[CH]CC(208) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      344.211 kJ/mol
    C=[C]C([CH]CC)C(CC)CC=C(209) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      469.041 kJ/mol
    [CH]=CC([CH]CC)C(CC)CC=C(210) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      478.295 kJ/mol
    C=CCC(CC)C(C=C)[CH][CH]C(211) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      350.189 kJ/mol
    [CH2]C[CH]C(C=C)C(CC)CC=C(212) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      436.446 kJ/mol
    [CH]=C[CH]C(CC)C(C=C)CCC(213) <=> C=C[CH]C(CC)C(C=C)[CH]CC(26)      389.471 kJ/mol
    C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> C=CC1C(CC)C(C=C)C1CC(43)      247.155 kJ/mol
========================================================================

Calculating densities of states for PDepNetwork #3...
Using 675 grains from -45.97 to 1364.04 kJ/mol in steps of 2.09 kJ/mol to compute densities of states
Calculating phenomenological rate coefficients for PDepNetwork #3...
```

After many warnings like this...

```
Warning: Increasing number of grains, decreasing grain size and trying again. (Current badness: 0.5)
Using 42054 grains from -45.97 to 1328.63 kJ/mol in steps of 0.03 kJ/mol to compute the k(T,P) values at 1896.74 K
Warning: For path reaction C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2][CH]C1C(CC)C(C=C)C1CC(151):
Warning:     Expected kf(1896.74 K) = 39982.3
Warning:       Actual kf(1896.74 K) = 30691.1
Warning:     Expected Keq(1896.74 K) = 1.80552e-05
Warning:       Actual Keq(1896.74 K) = 0
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2][CH]C1C(CC)C(C=C)C1CC(151)".
Warning: For path reaction C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> C=CC([CH]CC)C(CC)C1[CH]C1(172):
Warning:     Expected kf(1896.74 K) = 508871
Warning:       Actual kf(1896.74 K) = 327697
Warning:     Expected Keq(1896.74 K) = 3.00837e-08
Warning:       Actual Keq(1896.74 K) = 0
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> C=CC([CH]CC)C(CC)C1[CH]C1(172)".
Warning: For path reaction C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> CC[CH]C1[CH]CCC=CC1CC(175):
Warning:     Expected kf(1896.74 K) = 4.37813e+06
Warning:       Actual kf(1896.74 K) = 3.124e+06
Warning:     Expected Keq(1896.74 K) = 3.91143e-06
Warning:       Actual Keq(1896.74 K) = 0
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> CC[CH]C1[CH]CCC=CC1CC(175)".
Warning: For path reaction C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2]C=CC(CC)C(C=C)CC[CH2](179):
Warning:     Expected kf(1896.74 K) = 2.70448e+08
Warning:       Actual kf(1896.74 K) = 2.15151e+08
Warning:     Expected Keq(1896.74 K) = 0.453741
Warning:       Actual Keq(1896.74 K) = 0
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2]C=CC(CC)C(C=C)CC[CH2](179)".
Warning: For path reaction C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2]C=CC(CC)C([C]=C)CCC(182):
Warning:     Expected kf(1896.74 K) = 1.78938e+07
Warning:       Actual kf(1896.74 K) = 1.35369e+07
Warning:     Expected Keq(1896.74 K) = 0.0250217
Warning:       Actual Keq(1896.74 K) = 0
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> [CH2]C=CC(CC)C([C]=C)CCC(182)".
Warning: For path reaction C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> C=CC([CH]CC)[C](C=CC)CC(183):
Warning:     Expected kf(1896.74 K) = 23.0287
Warning:       Actual kf(1896.74 K) = 8.09908
Warning:     Expected Keq(1896.74 K) = 0.650192
Warning:       Actual Keq(1896.74 K) = 0
```

it finally gives this error:

``` python
Error: Invalid k(E) values computed for path reaction "C=C[CH]C(CC)C(C=C)[CH]CC(26) <=> C=CC([CH]CC)[C](C=CC)CC(183)".
Error: Increasing number of grains did not decrease error enough (Current badness: 0.5, previous 0.5). Something must be wrong with network 3
Traceback (most recent call last):
  File "rmg.py", line 139, in <module>
    cProfile.runctx(command, global_vars, local_vars, stats_file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/Users/Shared/Code/RMG-Py/rmgpy/rmg/main.py", line 453, in execute
    self.reactionModel.enlarge(objectsToEnlarge)
  File "/Users/Shared/Code/RMG-Py/rmgpy/rmg/model.py", line 760, in enlarge
    self.updateUnimolecularReactionNetworks(database)
  File "/Users/Shared/Code/RMG-Py/rmgpy/rmg/model.py", line 1526, in updateUnimolecularReactionNetworks
    network.update(self, database, self.pressureDependence)
  File "/Users/Shared/Code/RMG-Py/rmgpy/rmg/pdep.py", line 559, in update
    K = self.calculateRateCoefficients(Tlist, Plist, method)
  File "/Users/Shared/Code/RMG-Py/rmgpy/pdep/network.py", line 210, in calculateRateCoefficients
    self.setConditions(T, P)
  File "/Users/Shared/Code/RMG-Py/rmgpy/pdep/network.py", line 325, in setConditions
    raise error
InvalidMicrocanonicalRateError
make: *** [eg2] Error 1
```

It is bad for our "out of the box" example file to fail :unamused:

**Comment by goldmanm** [comment]
eg2 has been passing for a while on RMG-tests, so I presume this issue has been solved?
