### ISSUE TITLE
ethane example errors out while generating resonance structure of forbidden input

### ISSUE THREAD

**Issue by sevyharris** [ReactionMechanismGenerator/RMG-Py#2241]
### Bug Description
The basic [ethane example](https://github.com/ReactionMechanismGenerator/RMG-tests/blob/main/tests/examples/eg1/input.py) errors out while generating resonance structure of forbidden input

### How To Reproduce
Run basic ethane example on latest main branch of RMG and it will crash.

### Installation Information
Describe your installation method and system information.
 - OS: CentOS Linux release 7.9.2009 (Core)
 - Installation method: source
 - RMG version information:
   
   - RMG-Py: 3.1.0-389-g378ceb9
   - RMG-database: 3.0.0-460-g9fc77df

### Additional Context
RMG main commit: 378ceb96a83430cedcdcb7232a1bc30b21152bcf

RMG Log:
```
:root:Removing old /home/harris.se/rmg/examples/ethane/RMG_backup.log
:root:Moving /home/harris.se/rmg/examples/ethane/RMG.log to /home/harris.se/rmg/examples/ethane/RMG_backup.log

Global RMG Settings:
   database.directory   = /home/harris.se/rmg/RMG-database/input (Default, relative to RMG-Py source code)
   test_data.directory  = /home/harris.se/rmg/RMG-Py/rmgpy/test_data (Default, relative to RMG-Py source code)
RMG execution initiated at Tue Dec  7 08:45:45 2021

#########################################################
# RMG-Py - Reaction Mechanism Generator in Python       #
# Version: 3.1.0                                        #
# Authors: RMG Developers (rmg_dev@mit.edu)             #
# P.I.s:   William H. Green (whgreen@mit.edu)           #
#          Richard H. West (r.west@neu.edu)             #
# Website: http://reactionmechanismgenerator.github.io/ #
#########################################################

The current git HEAD for RMG-Py is:
        b'378ceb96a83430cedcdcb7232a1bc30b21152bcf'
        b'Thu Dec 2 14:27:00 2021 -0500'

The current git HEAD for RMG-database is:
        b'9fc77dfc15f4f7c9bf585ef6c559c368d8327410'
        b'Fri Dec 3 11:15:58 2021 -0500'

Reading input file "/home/harris.se/rmg/examples/ethane/input.py"...
# Data sources
database(
    thermoLibraries = ['primaryThermoLibrary'],
    reactionLibraries = [],
    seedMechanisms = [],
    kineticsDepositories = ['training'],
    kineticsFamilies = 'default',
    kineticsEstimator = 'rate rules',
)

# List of species
species(
    label='ethane',
    reactive=True,
    structure=SMILES("CC"),
)

# Reaction systems
simpleReactor(
    temperature=(1350,'K'),
    pressure=(1.0,'bar'),
    initialMoleFractions={
        "ethane": 1.0,
    },
    terminationConversion={
        'ethane': 0.9,
    },
    terminationTime=(1e6,'s'),
)

simulator(
    atol=1e-16,
    rtol=1e-8,
)

model(
    toleranceKeepInEdge=0.0,
    toleranceMoveToCore=0.1,
    toleranceInterruptSimulation=0.1,
    maximumEdgeSpecies=100000,
    filterReactions=True,
)

options(
    units='si',
    generateOutputHTML=True,
    generatePlots=False,
    saveEdgeSpecies=True,
    saveSimulationProfiles=True,
)


Warning: Generate Output HTML option was turned on. Note that this will slow down model generation.
Warning: Edge species saving was turned on. This will slow down model generation for large simulations.

Loading transport library from PrimaryTransportLibrary.py in /home/harris.se/rmg/RMG-database/input/transport/libraries...
Loading transport library from GRI-Mech.py in /home/harris.se/rmg/RMG-database/input/transport/libraries...
Loading transport library from NOx2018.py in /home/harris.se/rmg/RMG-database/input/transport/libraries...
Loading transport library from NIST_Fluorine.py in /home/harris.se/rmg/RMG-database/input/transport/libraries...
Loading transport library from OneDMinN2.py in /home/harris.se/rmg/RMG-database/input/transport/libraries...
Loading transport group database from /home/harris.se/rmg/RMG-database/input/transport/groups...
Error: Error while reading database '/home/harris.se/rmg/RMG-database/input/forbiddenStructures.py'.
Traceback (most recent call last):
  File "/home/harris.se/anaconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 308, in main
    python(**vars(ns))
  File "/home/harris.se/anaconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 59, in python
    scope = runpy.run_path(script, run_name="__main__")
  File "/home/harris.se/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/harris.se/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/harris.se/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/harris.se/rmg/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/home/harris.se/rmg/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/harris.se/rmg/RMG-Py/rmgpy/rmg/main.py", line 707, in execute
    self.initialize(**kwargs)
  File "/home/harris.se/rmg/RMG-Py/rmgpy/rmg/main.py", line 516, in initialize
    self.load_database()
  File "/home/harris.se/rmg/RMG-Py/rmgpy/rmg/main.py", line 383, in load_database
    depository=False,  # Don't bother loading the depository information, as we don't use it
  File "/home/harris.se/rmg/RMG-Py/rmgpy/data/rmg.py", line 98, in load
    self.load_forbidden_structures(os.path.join(path, 'forbiddenStructures.py'))
  File "/home/harris.se/rmg/RMG-Py/rmgpy/data/rmg.py", line 141, in load_forbidden_structures
    self.forbidden_structures.load(path)
  File "/home/harris.se/rmg/RMG-Py/rmgpy/data/base.py", line 241, in load
    exec(f.read(), global_context, local_context)
  File "<string>", line 172, in <module>
  File "/home/harris.se/rmg/RMG-Py/rmgpy/data/base.py", line 1387, in load_entry
    item.generate_resonance_structures()
  File "rmgpy/species.py", line 266, in rmgpy.species.Species.generate_resonance_structures
  File "rmgpy/species.py", line 277, in rmgpy.species.Species.generate_resonance_structures
  File "rmgpy/molecule/molecule.py", line 2171, in rmgpy.molecule.molecule.Molecule.generate_resonance_structures
  File "rmgpy/molecule/molecule.py", line 2173, in rmgpy.molecule.molecule.Molecule.generate_resonance_structures
  File "rmgpy/molecule/resonance.py", line 150, in rmgpy.molecule.resonance.generate_resonance_structures
  File "rmgpy/molecule/resonance.py", line 246, in rmgpy.molecule.resonance.generate_resonance_structures
  File "rmgpy/molecule/resonance.py", line 255, in rmgpy.molecule.resonance._generate_resonance_structures
  File "rmgpy/molecule/resonance.py", line 293, in rmgpy.molecule.resonance._generate_resonance_structures
  File "rmgpy/molecule/resonance.py", line 422, in rmgpy.molecule.resonance.generate_adj_lone_pair_radical_resonance_structures
  File "rmgpy/molecule/resonance.py", line 441, in rmgpy.molecule.resonance.generate_adj_lone_pair_radical_resonance_structures
  File "rmgpy/molecule/molecule.py", line 502, in rmgpy.molecule.molecule.Atom.decrement_lone_pairs
rmgpy.exceptions.ActionError: Unable to update Atom due to LOSE_PAIR action: Invalid lone electron pairs set "-1".
```

**Comment by sevyharris** [comment]
I believe this is the commit that causes the issue: 3332161a679c21e62d31e53a5c3de2f2635a678c
the one right before it, a21a70cd42c29d1588e5dfeee8141fb31228e814, runs without issue.

**Comment by sevyharris** [comment]
I think I ran this without rebuilding the .pyx files properly.
