### ISSUE TITLE
name error running superminimal from most recent RMG commit

### ISSUE THREAD

**Issue by vbarber820** [ReactionMechanismGenerator/RMG-Py#2245]
### Bug Description
I have just pulled the most recent RMG-Py and RMG-Database from git. when I run the superminimal example, I get the following error (full text below). Prior to this, my install was working (for both superminimal example and any other input files I generated)

NameError: name 'rms' is not defined

### How To Reproduce
- run git pull on RMG-Py and RMG-Database
- cd RMG-Py/examples/rmg/superminimal
- rmg.py input.py

### Expected Behavior
should run superminimal example without issue.

### Installation Information
 - Installed from source code with anaconda on Linux subsystem for windows
 - RMG version information:
   - RMG-Py: 3.1.0-330-g7fbb9e4a6
   - RMG-database: 3.0.0-367-ga929cf539

### Additional Context
RMG.log file and input.py file attached

full error message:

Traceback (most recent call last):
  File "/home/tori/anaconda3/envs/rmg_env/bin/rmg.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/tori/RMG/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/home/tori/RMG/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/tori/RMG/RMG-Py/rmgpy/rmg/main.py", line 695, in execute
    self.initialize(**kwargs)
  File "/home/tori/RMG/RMG-Py/rmgpy/rmg/main.py", line 507, in initialize
    self.reaction_model.add_species_to_edge(spec)
  File "/home/tori/RMG/RMG-Py/rmgpy/rmg/model.py", line 1142, in add_species_to_edge
    self.edge.phase_system.phases["Default"].add_species(spec)
  File "/home/tori/RMG/RMG-Py/rmgpy/rmg/reactors.py", line 232, in add_species
    spec = to_rms(spc)
  File "/home/tori/RMG/RMG-Py/rmgpy/rmg/reactors.py", line 453, in to_rms
    rad = rms.getspeciesradius(atomnums, bondnum)
NameError: name 'rms' is not defined
[RMG.log](https://github.com/ReactionMechanismGenerator/RMG-Py/files/7746228/RMG.log)

**Comment by vbarber820** [comment]
Thanks for responding so quickly! the fix worked and it's running as expected now.
