### ISSUE TITLE
UndeterminableKineticsError in c3h4 example

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#225]
RMG-py at 1bdcdc05804697a6a91ee042a618e95c4b42b805
and other rmg-dependencies fetched June 12 2014.

Running the c3h4 example of 
yields the following **UndeterminableKineticsError**:

``` python
Adding species [CH]=C[CH2](254) to model core
Traceback (most recent call last):
  File "/home/nickvandewiele/RMG-Py/rmg.py", line 147, in <module>
    rmg.execute(args)
  File "/home/nickvandewiele/RMG-Py/rmgpy/rmg/main.py", line 453, in execute
    self.reactionModel.enlarge(objectsToEnlarge)
  File "/home/nickvandewiele/RMG-Py/rmgpy/rmg/model.py", line 660, in enlarge
    newReactions.extend(self.react(database, newSpecies))
  File "/home/nickvandewiele/RMG-Py/rmgpy/rmg/model.py", line 608, in react
    reactionList.extend(database.kinetics.generateReactions([moleculeA], failsSpeciesConstraints=self.failsSpeciesConstraints))
  File "/home/nickvandewiele/RMG-Py/rmgpy/data/kinetics/__init__.py", line 343, in generateReactions
    reactionList.extend(self.generateReactionsFromFamilies(reactants, products, failsSpeciesConstraints=failsSpeciesConstraints))
  File "/home/nickvandewiele/RMG-Py/rmgpy/data/kinetics/__init__.py", line 399, in generateReactionsFromFamilies
    reactionList.extend(family.generateReactions(reactants, failsSpeciesConstraints=failsSpeciesConstraints))
  File "/home/nickvandewiele/RMG-Py/rmgpy/data/kinetics/family.py", line 1404, in generateReactions
    reactionList.extend(self.__generateReactions(reactants, forward=False, failsSpeciesConstraints=failsSpeciesConstraints))
  File "/home/nickvandewiele/RMG-Py/rmgpy/data/kinetics/family.py", line 1636, in __generateReactions
    reaction.template = self.getReactionTemplate(reaction)
  File "/home/nickvandewiele/RMG-Py/rmgpy/data/kinetics/family.py", line 1744, in getReactionTemplate
    return self.groups.getReactionTemplate(reaction)
  File "/home/nickvandewiele/RMG-Py/rmgpy/data/kinetics/groups.py", line 168, in getReactionTemplate
    raise UndeterminableKineticsError(reaction, message=msg)
rmgpy.data.kinetics.common.UndeterminableKineticsError: (Reaction(reactants=[Molecule(SMILES="C#C"), Molecule(SMILES="[CH2]")], products=[Molecule(SMILES="[CH]=C[CH2]")], pairs=[[Molecule(SMILES="C#C"), Molecule(SMILES="[CH]=C[CH2]")], [Molecule(SMILES="[CH2]"), Molecule(SMILES="[CH]=C[CH2]")]]), 'Kinetics could not be determined. Unable to find matching template for reaction <Molecule "C#C"> + <Molecule "[CH2]"> <=> <Molecule "[CH]=C[CH2]"> in reaction family <KineticsGroups "R_Addition_MultipleBond/groups">.Trying to match [<Entry index=1 label="R_R">, <Entry index=2 label="YJ">] but matched [<Entry index=840 label="Ct-H_Ct-H">]')
```

It occurs for the R_Add_Multiple_Bond reaction between ethyne and methylene:
C#C + CH2 = ...

and did not find a match for the methylene biradical.

From my understanding, it should match the **Y_1centerbirad** node, 

```
1 *3 R!H 2T
```

The reaction was generated from the [CH]=C[CH2] biradical product side.

Is this maybe related to the recent changes in adjacency list representation for spin multiplicities?

**Comment by JacksonBurns** [comment]
This has since been resolved. Closing as stale/resolved.
