### ISSUE TITLE
PDep Network Error in Arkane: "TypeError: 'float' object cannot be interpreted as an integer"

### ISSUE THREAD

**Issue by hram27** [ReactionMechanismGenerator/RMG-Py#2256]
### Bug Description
I'm conducting a pressure dependent network calculation to obtain k(T,P) in Arkane. I have Gaussian LOG files for the reaction n-C3H7 <=> CH3 + C2H4, including the transition state, and I followed the documentation to create an input file for the calculation. Upon running in Arkane, I get the following error: "TypeError: 'float' object cannot be interpreted as an integer". It occurs during the "Calculating densities of states for pdep network..." step. Here is the complete arkane.log file for reference. 

[arkane.log](https://github.com/ReactionMechanismGenerator/RMG-Py/files/7831652/arkane.log)

### How To Reproduce
I will provide here my Gaussian LOG files, my .py files for each species, and my .py file for the Arkane input, all in the ZIP folder below. The error can also be reproduced with the example input provided within the Arkane package (the n-butanol dehydration example). 

[Arkane issue reporting.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/7831669/Arkane.issue.reporting.zip)

### Installation Information

- OS (Windows 11, Ubuntu VM through VirtualBox)
- Installation method: installation from binary with Anaconda3

**Comment by mjohnson541** [comment]
My first guess is this is a simple input issue. Python interprets numbers without a decimal point as integers so I think a number in your input files that should be a float may be being interpreted as an integer. This can be fixed by simply adding a `.0` to the number. Given this is occurring in density of states an energy is probably a good candidate. If that doesn't work please post the traceback you get (the part where the error happens with the line numbers).

**Comment by hram27** [comment]
Unfortunately, this didn't work. I've changed everything to float except for inputs that must be integers (Tcount, Pcount, etc.) and the traceback still occurs. Here it is below:

Traceback (most recent call last):
  File "/home/hram/anaconda3/envs/rmg_env/bin/Arkane.py", line 59, in <module>
    arkane.execute()
  File "/home/hram/anaconda3/envs/rmg_env/lib/python3.7/site-packages/arkane/main.py", line 283, in execute
    job.execute(output_file=output_file, plot=self.plot)
  File "/home/hram/anaconda3/envs/rmg_env/lib/python3.7/site-packages/arkane/pdep.py", line 270, in execute
    self.initialize()
  File "/home/hram/anaconda3/envs/rmg_env/lib/python3.7/site-packages/arkane/pdep.py", line 367, in initialize
    rmgmode=self.rmgmode,
  File "/home/hram/anaconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/pdep/network.py", line 240, in initialize
    self.calculate_densities_of_states()
  File "/home/hram/anaconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/pdep/network.py", line 539, in calculate_densities_of_states
    active_j_rotor=self.active_j_rotor, rmgmode=self.rmgmode)
  File "rmgpy/pdep/configuration.pyx", line 223, in rmgpy.pdep.configuration.Configuration.calculate_density_of_states
  File "rmgpy/pdep/configuration.pyx", line 334, in rmgpy.pdep.configuration.Configuration.calculate_density_of_states
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/hram/anaconda3/envs/rmg_env/lib/python3.7/site-packages/numpy/core/function_base.py", line 120, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

Is there anything else I can try?

Thanks,
Hrishi Ram

**Comment by mjohnson541** [comment]
So I'm entirely baffled why you're getting this error and no one else seems to be, but it looks to me like in "rmgpy/pdep/configuration.pyx", line 334 a float is being input as the number of points for numpy.linspace instead of an integer.

**Comment by hram27** [comment]
I'm not sure why I'm getting this issue, but I've run the calculation unsuccessfully on multiple devices, and a colleague of mine also tried it and ran into the same error. I see the pull request, what do I have to do to update my version of Arkane once the issue is closed?
