### ISSUE TITLE
psi4 dependence buried inside cclib

### ISSUE THREAD

**Issue by sevyharris** [ReactionMechanismGenerator/RMG-Py#2266]
### Bug Description
I was trying to run some of the ess tests in Arkane, and I kept getting an error that psi4 isn't installed:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/__init__.py", line 30, in <module>
    from cclib import parser
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/__init__.py", line 38, in <module>
    from cclib.io.ccio import ccopen
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/io/__init__.py", line 11, in <module>
    from cclib.io.cjsonwriter import CJSON as CJSONWriter
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/io/cjsonwriter.py", line 14, in <module>
    from cclib.io import filewriter
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/io/filewriter.py", line 21, in <module>
    from cclib.bridge import makeopenbabel
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/bridge/__init__.py", line 22, in <module>
    from cclib.bridge.cclib2psi4 import makepsi4
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/bridge/cclib2psi4.py", line 14, in <module>
    from psi4.core import Molecule
ModuleNotFoundError: No module named 'psi4.core'; 'psi4' is not a package
```

### How To Reproduce
run one of the ess tests:
`python ~/rmg/RMG-Py/arkane/ess/gaussianTest.py `

or even more simply, try to import cclib inside python if you don't have psi4 installed:
`import cclib`

### Expected Behavior
I would not expect cclib to be dependent on psi4. psi4 is a big clunky program. I shouldn't have to install it just to run test on calculations from other electronic structure calculators. I don't think anyone intended that, it's just that there's something wrong with the code checking whether it's already installed or not:

If you look in the anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/bridge/\_\_init\_\_.py, there's code that's supposed to skip importing psi4:
```
if find_package("psi4"):
    from cclib.bridge.cclib2psi4 import makepsi4
```

Commenting this out fixes the issue, but that's a temporary fix and I'd like to know why it thinks I have psi4 installed.

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): Windows Subsytem Linux
 - Installation method: source
 - RMG version information: 3.1.0-414-gc4ba26c4e
   - RMG-Py: c4ba26c4e0bde03d9d8d5867875e2df2ce5d4079
   - RMG-database: bbd3f21662dc816b54b2a1119445e94350f43c76

**Comment by alongd** [comment]
Thanks for reporting, I also bumped into this a few times.
Can you try running in your rmg_env the following?

```python
from cclib.parser.utils import find_package
print(find_package("psi4"))
```

You should get `False` on an unmodified rmg_env

**Comment by sevyharris** [comment]
I got `False` when I ran it in my home directory, but then it's `True` when I run it in RMG-Py/arkane/ess

There's a psi4.py file in RMG-Py/arkane/ess, so maybe it thinks that's the full psi4 package?

It looks like I can avoid the issue by running the tests from a different directory, so if that's the fix, I guess the question is can we prevent people from running into this issue in the future?

Maybe a warning next to `import cclib` in RMG-Py/rmgpy/qm/gaussian.py, line 37 (that's where it breaks for me)? I'd rather not change the names of the ESSAdaptor files, and changing cclib is probably more effort than it's worth.


Here's the actual error log when I try to run gaussianTest.py, since the above is just the error for `import cclib`
```
  File "gaussianTest.py", line 43, in <module>
    from arkane.ess.gaussian import GaussianLog
  File "/home/sevy/rmg/RMG-Py/arkane/__init__.py", line 35, in <module>
    from arkane.explorer import ExplorerJob
  File "/home/sevy/rmg/RMG-Py/arkane/explorer.py", line 44, in <module>
    from rmgpy.rmg.main import RMG
  File "/home/sevy/rmg/RMG-Py/rmgpy/rmg/main.py", line 68, in <module>
    from rmgpy.qm.main import QMDatabaseWriter
  File "/home/sevy/rmg/RMG-Py/rmgpy/qm/main.py", line 34, in <module>
    import rmgpy.qm.gaussian
  File "/home/sevy/rmg/RMG-Py/rmgpy/qm/gaussian.py", line 37, in <module>
    import cclib
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/__init__.py", line 30, in <module>
    from cclib import parser
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/parser/__init__.py", line 38, in <module>
    from cclib.io.ccio import ccopen
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/io/__init__.py", line 11, in <module>
    from cclib.io.cjsonwriter import CJSON as CJSONWriter
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/io/cjsonwriter.py", line 14, in <module>
    from cclib.io import filewriter
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/io/filewriter.py", line 21, in <module>
    from cclib.bridge import makeopenbabel
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/bridge/__init__.py", line 22, in <module>
    from cclib.bridge.cclib2psi4 import makepsi4
  File "/home/sevy/anaconda3/envs/rmg_env/lib/python3.7/site-packages/cclib/bridge/cclib2psi4.py", line 14, in <module>
    from psi4.core import Molecule
ModuleNotFoundError: No module named 'psi4.core'; 'psi4' is not a package
```

**Comment by sevyharris** [comment]
It looks like I jumped the gun on that fix. Changing the directory is not fixing the issue. I'll keep investigating.

**Comment by alongd** [comment]
Perhaps we should rename `psi4.py` as `psi_4.py` in Arkane?

**Comment by JacksonBurns** [comment]
@sevyharris can you try and reproduce this with 3.1.1 or 3.2.0?
