### ISSUE TITLE
Problem with merging models

### ISSUE THREAD

**Issue by rlawson** [ReactionMechanismGenerator/RMG-Py#2267]
I am currently running RMG 3.0.0 and trying to merge models using the associated script. However I keep getting this error

Traceback (most recent call last):
  File "mergeModels.py", line 52, in <module>
    main()
  File "mergeModels.py", line 48, in main
    merge_models.main()
  File "/home1/rlawson/.conda/envs/rmg_env3/lib/python3.7/site-packages/rmgpy/tools/mergemodels.py", line 94, in main
    execute(input_model_files, **kwargs)
  File "/home1/rlawson/.conda/envs/rmg_env3/lib/python3.7/site-packages/rmgpy/tools/mergemodels.py", line 109, in execute
    models = get_models_to_merge(input_model_files)
  File "/home1/rlawson/.conda/envs/rmg_env3/lib/python3.7/site-packages/rmgpy/tools/mergemodels.py", line 133, in get_models_to_merge
    model.species, model.reactions = load_chemkin_file(chemkin, species_path, transport_path=transport_path)
  File "rmgpy/chemkin.pyx", line 907, in rmgpy.chemkin.load_chemkin_file
  File "rmgpy/chemkin.pyx", line 806, in rmgpy.chemkin.load_species_dictionary
  File "rmgpy/chemkin.pyx", line 811, in rmgpy.chemkin.load_species_dictionary
  File "rmgpy/species.py", line 336, in rmgpy.species.Species.from_adjacency_list
  File "rmgpy/species.py", line 343, in rmgpy.species.Species.from_adjacency_list
  File "rmgpy/molecule/molecule.py", line 1690, in rmgpy.molecule.molecule.Molecule.from_adjacency_list
  File "/home1/rlawson/.conda/envs/rmg_env3/lib/python3.7/site-packages/rmgpy/molecule/adjlist.py", line 720, in from_adjacency_list
    if order[0] == '[':
IndexError: string index out of range

Any help will be greatly appreciated. Thank you

**Comment by xiaoruiDong** [comment]
It seems RMG has trouble reading the species dictionary of one of the models. Can you upload your species dictionaries for check?

**Comment by rlawson-mm** [comment]
I was able to figure the problem out. I made an error with a species' adjacency list. Thanks anyway for your help.
