### ISSUE TITLE
AttributeError: 'Fragment' object has no attribute 'count_internal_rotors'

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#2324]
While generating a model, I got the following trace:

```
Traceback (most recent call last):
  File "/home/alongd/anaconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 308, in main
    python(**vars(ns))
  File "/home/alongd/anaconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 59, in python
    scope = runpy.run_path(script, run_name="__main__")
  File "/home/alongd/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/alongd/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/alongd/anaconda3/envs/rmg_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/alongd/Code/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/home/alongd/Code/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/main.py", line 1026, in execute
    trimolecular_react=self.trimolecular_react)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/model.py", line 709, in enlarge
    self.update_unimolecular_reaction_networks()
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/model.py", line 1918, in update_unimolecular_reaction_networks
    network.update(self, self.pressure_dependence)
  File "/home/alongd/Code/RMG-Py/rmgpy/rmg/pdep.py", line 786, in update
    spec.generate_statmech()
  File "rmgpy/species.py", line 821, in rmgpy.species.Species.generate_statmech
  File "/home/alongd/Code/RMG-Py/rmgpy/data/statmech.py", line 682, in get_statmech_data
    statmech_model = self.get_statmech_data_from_groups(molecule, thermo_model)
  File "/home/alongd/Code/RMG-Py/rmgpy/data/statmech.py", line 716, in get_statmech_data_from_groups
    return self.groups['groups'].get_statmech_data(molecule, thermo_model)
  File "/home/alongd/Code/RMG-Py/rmgpy/data/statmech.py", line 387, in get_statmech_data
    num_rotors = molecule.count_internal_rotors()
AttributeError: 'Fragment' object has no attribute 'count_internal_rotors'
```

I did not asked for an AFM run (if I understand the error message correctly).

Adding some debug print statements in statmech.py before calling `molecule.count_internal_rotors()` on line 386, I get:

```
calling count_internal_rotors()
on type <class 'rmgpy.molecule.fragment.Fragment'>
object: 
```

The object type passes to `molecule` is indeed a `Fragment` instance, but it seems to be empty (i.e., no label nor index).

We should check why a `Fragment` was passed to statmech, also perhaps why it was formed in the first place.

**Comment by kfir4444** [comment]
Hey @alongd, we are getting a similar error.
our input is:
```python
# Data sources
database(
    thermoLibraries = ["primaryThermoLibrary","CHOCl_G4" ,"thermo_DFT_CCSDTF12_BAC", "BurkeH2O2", "Chlorinated_Hydrocarbons", "Klippenstein_Glarborg2016", "NOx2018"],
    reactionLibraries = ['CH3Cl','BurkeH2O2inArHe','GRI-Mech3.0','Glarborg/C1', "FFCM1(-)"],
    seedMechanisms = [],
    kineticsDepositories = ['training'],
    kineticsFamilies = 'default',
    kineticsEstimator = 'rate rules',
)
# List of species
species(
    label='CH3Cl',
    reactive=True,
    structure=SMILES("CCl"),
)
species(
    label='O2',
    reactive=True,
    structure=SMILES("[O][O]"),
)
species(
    label='Ar',
    reactive=False,
    structure=SMILES("[Ar]"),
)



# Reaction systems
simpleReactor(
    temperature=[(800,'K'),(1200,'K')],
    pressure=[(0.4,'bar'),(0.8,'bar')],
    initialMoleFractions={
        'CH3Cl':0.0732,
        'O2': 0.0205,
        'Ar': 0.906,
    },
    terminationRateRatio=0.01,
    terminationTime=(600, 's'),
    sensitivity=['CH3Cl'],
    sensitivityThreshold=0.05,
)
simulator(
    atol=1e-16,
    rtol=1e-8,
)
model(
    toleranceKeepInEdge=0.01,
    toleranceMoveToCore=0.03,
    toleranceInterruptSimulation=0.05,
    maximumEdgeSpecies=100000,
    filterReactions=True,
)
pressureDependence(
        method='modified strong collision',
        maximumGrainSize=(0.5,'kcal/mol'),
        minimumNumberOfGrains=250,
        temperatures=(750,1250,'K',8),
        pressures=(0.3,1,'bar',5),
        interpolation=('Chebyshev', 6, 4),
        maximumAtoms=8,
)
generatedSpeciesConstraints(
    allowed=['input species','seed mechanisms','reaction libraries'],
    maximumCarbonAtoms=5,
    maximumOxygenAtoms=4,
    maximumNitrogenAtoms=0,
    maximumSiliconAtoms=0,
    maximumSulfurAtoms=0,
    maximumHeavyAtoms=6,
    maximumSurfaceSites=0,
    maximumRadicalElectrons=4,
    maximumSingletCarbenes=2,
    maximumCarbeneRadicals=0,
    allowSingletO2=True,
)
options(
    units='si',
    generateOutputHTML=True,
    generatePlots=True,
    saveEdgeSpecies=True,
    saveSimulationProfiles=True,
)
```

**Comment by Laxzal** [comment]
So in the case of Kfir's issue, I was able to track which species was causing the issue:

```python
smiles = 'Cl[CH]Cl'
label = 'CHCL2'
molecule = <rmgpy.molecule.fragment.Fragment object at 0x7f62ff8b0d10>
fingerprint = ''C01H01N00O00S00Cl02''
reactive= True
thermo.comment = 'Thermo library: CHOCl_G4'
```

Obviously, when the statmech is calling on the molecule, its getting the fragment object instead and then failing there. However, if we do molecule.mol_repr.count_internal_rotors(), then it works.

If someone has some insight on what we should be expecting, I can try make the necessary changes.
