### ISSUE TITLE
multiprocessing: TypeError: __init__() takes from 1 to 7 positional arguments but 8 were given

### ISSUE THREAD

**Issue by NUSCondy** [ReactionMechanismGenerator/RMG-Py#2342]
### Bug Description
Traceback (most recent call last):
  File "//home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "//home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "//home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "//home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/multiprocessing/queues.py", line 354, in get
    return _ForkingPickler.loads(res)
TypeError: __init__() takes from 1 to 7 positional arguments but 8 were given
Traceback (most recent call last):
  File "//home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "//home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "//home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "//home/zhuqiren/anaconda3/envs/rmg_env/lib/python3.7/multiprocessing/queues.py", line 354, in get
    return _ForkingPickler.loads(res)
TypeError: __init__() takes from 1 to 7 positional arguments but 8 were given

### How To Reproduce
Just after I run RMG

### Expected Behavior
This seems to be an error about multiprocess since it successfully read the reaction lib and other property but fail to run.

### Installation Information
Describe your installation method and system information.
 - OS (include version if known): (e.g. Windows 10, Ubuntu 18, macOS 10.13, etc.)
 - Installation method: (e.g. installation from binary or source, with or without anaconda)
 - RMG version information:
   
   - RMG-Py: 3.1.0
   - RMG-database: Updated

**Comment by JacksonBurns** [comment]
Though it doesn't look like it, this is a MOPAC error. This has been resolved in the latest versions since #2417 switches to OpenMOPAC.

@NUSCondy please follow the updated installation instructions and this should no longer be an issue.

Closing as resolved.
