### ISSUE TITLE
Can't Create Pressure Dependent Networks

### ISSUE THREAD

**Issue by cclairemurphy** [ReactionMechanismGenerator/RMG-Py#2527]
I tried running some pressure dependence calculations for my own system and kept getting the error below. I updated my version of RMG and then tried running the example files as well and get the same error for all of them, shared below (specifically the 'acetyl + O2' example). I've included the entire printout in case that's helpful. I'm running it on an Ubuntu machine, version included in the appropriate section below.

### Bug Description
```

(base) claire@Claires-Laptop:~/RMG-Py/examples/arkane/networks/acetyl+O2$ conda activate rmg_env
(rmg_env) claire@Claires-Laptop:~/RMG-Py/examples/arkane/networks/acetyl+O2$ Arkane.py input.py
Arkane execution initiated at Mon Aug 14 14:21:14 2023

################################################################
#                                                              #
# Automated Reaction Kinetics and Network Exploration (Arkane) #
#                                                              #
#   Version: 3.1.0                                             #
#   Authors: RMG Developers (rmg_dev@mit.edu)                  #
#   P.I.s:   William H. Green (whgreen@mit.edu)                #
#            Richard H. West (r.west@neu.edu)                  #
#   Website: http://reactionmechanismgenerator.github.io/      #
#                                                              #
################################################################

Databases not found. Making databases
Loading frequencies group database from /home/claire/anaconda3/envs/rmg_env/share/rmgdatabase/statmech/groups...
Loading transport library from GRI-Mech.py in /home/claire/anaconda3/envs/rmg_env/share/rmgdatabase/transport/libraries...
Loading transport library from PrimaryTransportLibrary.py in /home/claire/anaconda3/envs/rmg_env/share/rmgdatabase/transport/libraries...
Loading transport library from OneDMinN2.py in /home/claire/anaconda3/envs/rmg_env/share/rmgdatabase/transport/libraries...
Loading transport library from NOx2018.py in /home/claire/anaconda3/envs/rmg_env/share/rmgdatabase/transport/libraries...
Loading transport group database from /home/claire/anaconda3/envs/rmg_env/share/rmgdatabase/transport/groups...
Loading species acetylperoxy...
Loading species hydroperoxylvinoxy...
Loading species acetyl...
Loading species oxygen...
Loading species ketene...
Loading species lactone...
Loading species hydroxyl...
Loading species hydroperoxyl...
Loading species nitrogen...
Loading transition state entrance1...
Loading transition state isom1...
Loading transition state exit1...
Loading transition state exit2...
Loading transition state exit3...
Loading reaction entrance1...
Loading reaction isom1...
Loading reaction exit1...
Loading reaction exit2...
Loading reaction exit3...
Loading network acetyl + O2...



========================================================================
acetyl + O2 network information
-------------------------------
Isomers:
    acetylperoxy                                         -144.766 kJ/mol
    hydroperoxylvinoxy                                   -135.562 kJ/mol
Reactant channels:
    oxygen + acetyl                                             0 kJ/mol
    hydroperoxyl + ketene                                -27.6144 kJ/mol
    hydroxyl + lactone                                   -128.867 kJ/mol
Product channels:
Path reactions:
    oxygen + acetyl <=> acetylperoxy                            0 kJ/mol
    acetylperoxy <=> hydroperoxylvinoxy                  -24.2672 kJ/mol
    acetylperoxy <=> hydroperoxyl + ketene                 2.5104 kJ/mol
    hydroperoxylvinoxy <=> hydroperoxyl + ketene         -19.2464 kJ/mol
    hydroperoxylvinoxy <=> hydroxyl + lactone            -30.1248 kJ/mol
Net reactions:
========================================================================

Calculating densities of states for acetyl + O2 network...
Using 820 grains from -144.77 to 667.82 kJ/mol in steps of 0.99 kJ/mol to compute densities of states
Traceback (most recent call last):
  File "/home/claire/anaconda3/envs/rmg_env/bin/Arkane.py", line 59, in <module>
    arkane.execute()
  File "/home/claire/anaconda3/envs/rmg_env/lib/python3.7/site-packages/arkane/main.py", line 283, in execute
    job.execute(output_file=output_file, plot=self.plot)
  File "/home/claire/anaconda3/envs/rmg_env/lib/python3.7/site-packages/arkane/pdep.py", line 270, in execute
    self.initialize()
  File "/home/claire/anaconda3/envs/rmg_env/lib/python3.7/site-packages/arkane/pdep.py", line 367, in initialize
    rmgmode=self.rmgmode,
  File "/home/claire/anaconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/pdep/network.py", line 240, in initialize
    self.calculate_densities_of_states()
  File "/home/claire/anaconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/pdep/network.py", line 539, in calculate_densities_of_states
    active_j_rotor=self.active_j_rotor, rmgmode=self.rmgmode)
  File "rmgpy/pdep/configuration.pyx", line 223, in rmgpy.pdep.configuration.Configuration.calculate_density_of_states
  File "rmgpy/pdep/configuration.pyx", line 334, in rmgpy.pdep.configuration.Configuration.calculate_density_of_states
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/claire/anaconda3/envs/rmg_env/lib/python3.7/site-packages/numpy/core/function_base.py", line 120, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer
```

### Installation Information
Describe your installation method and system information.
 - Ubuntu 22.04.2 LTS
 - installation from from source with Anaconda, updated to latest version
 - RMG version information:
   - RMG-Py: 3.1.0
   - RMG-database:

**Comment by JacksonBurns** [comment]
Hi @cclairemurphy thank you for the report. Could you provide your `input.py`, or as much of it as you can share, to help us find the issue?
