### ISSUE TITLE
Error Writing Seed Mechanism

### ISSUE THREAD

**Issue by emccaughey** [ReactionMechanismGenerator/RMG-Py#2548]
### Bug Description
After running for a short time, the mechanism stops due to "Error: Error in writing the seed mechanism for the current iteration. The seed mechanism from the previous iteration has been restored". I have tried changing some settings within the input file to see if various parts were the cause, but have had no luck. 
*It always stops when the core reaches 18 species and 54 reactions within this mechanism.

Here is the full error:
```
Making seed mechanism...
2023-09-22 13:05:11 Error: Error in writing the seed mechanism for the current iteration. The seed mechanism from the previous iteration has been restored
2023-09-22 13:05:11 Traceback (most recent call last):
2023-09-22 13:05:11   File "/miniconda/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 308, in main
2023-09-22 13:05:11     python(**vars(ns))
2023-09-22 13:05:11   File "/miniconda/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 59, in python
2023-09-22 13:05:11     scope = runpy.run_path(script, run_name="__main__")
2023-09-22 13:05:11   File "/miniconda/envs/rmg_env/lib/python3.7/runpy.py", line 263, in run_path
2023-09-22 13:05:11     pkg_name=pkg_name, script_name=fname)
2023-09-22 13:05:11   File "/miniconda/envs/rmg_env/lib/python3.7/runpy.py", line 96, in _run_module_code
2023-09-22 13:05:11     mod_name, mod_spec, pkg_name, script_name)
2023-09-22 13:05:11   File "/miniconda/envs/rmg_env/lib/python3.7/runpy.py", line 85, in _run_code
2023-09-22 13:05:11     exec(code, run_globals)
2023-09-22 13:05:11   File "rmg.py", line 118, in <module>
2023-09-22 13:05:11     main()
2023-09-22 13:05:11   File "rmg.py", line 112, in main
2023-09-22 13:05:11     rmg.execute(**kwargs)
2023-09-22 13:05:11   File "/rmg/RMG-Py/rmgpy/rmg/main.py", line 866, in execute
2023-09-22 13:05:11     self.make_seed_mech()
2023-09-22 13:05:11   File "/rmg/RMG-Py/rmgpy/rmg/main.py", line 1657, in make_seed_mech
2023-09-22 13:05:11     raise e
2023-09-22 13:05:11   File "/rmg/RMG-Py/rmgpy/rmg/main.py", line 1618, in make_seed_mech
2023-09-22 13:05:11     edge_kinetics_library.save(os.path.join(seed_dir, "seed_edge", "reactions.py"))
2023-09-22 13:05:11   File "/rmg/RMG-Py/rmgpy/data/kinetics/library.py", line 609, in save
2023-09-22 13:05:11     self.save_dictionary(os.path.join(os.path.split(path)[0], 'dictionary.txt'))
2023-09-22 13:05:11   File "/rmg/RMG-Py/rmgpy/data/base.py", line 352, in save_dictionary
2023-09-22 13:05:11     f.write(species_dict[label].molecule[0].to_adjacency_list(label=label, remove_h=False))
2023-09-22 13:05:11   File "/rmg/RMG-Py/rmgpy/molecule/fragment.py", line 1314, in to_adjacency_list
2023-09-22 13:05:11     old_style=old_style)
2023-09-22 13:05:11   File "/rmg/RMG-Py/rmgpy/molecule/adjlist.py", line 1011, in to_adjacency_list
2023-09-22 13:05:11     if atom.site:
2023-09-22 13:05:11 AttributeError: 'CuttingLabel' object has no attribute 'site'
```

The input file being used is: 
```
# Data sources
database(
    thermoLibraries = ['primaryThermoLibrary'],
    reactionLibraries = [],
    seedMechanisms = [],
    kineticsDepositories = ['training'],
    kineticsFamilies = ['default', 'ch_pyrolysis'], 
    kineticsEstimator = 'rate rules',
)

generatedSpeciesConstraints(
    maximumCarbonAtoms=24,
    maximumRadicalElectrons=1,
)

# List of species
species(
    label='C2H4',
    reactive=True,
    structure=SMILES("C=C"),
)
species(
   label='Naphthalene',
   reactive=True,
   structure=SMILES("C1=CC2=C(C=C1)C=CC=C2"),
)
species(
   label='H2',
   reactive=True,
   structure=SMILES("[H][H]"),
)
species(
   label='H',
   reactive=True,
   structure=SMILES("[H]"),
)


# Reaction systems 
simpleReactor(
    temperature=(1000,'K'),
    pressure=(1.0,'bar'),
    initialMoleFractions={
        'C2H4':0.5, 'H2':0.1, 'H':0.001, 'Naphthalene':0.5 
    },
    terminationTime=(1e6,'s'),
)

simulator(
    atol=1e-16,
    rtol=1e-8,
)

model(
    toleranceKeepInEdge=0.0,
    toleranceMoveToCore=0.001,
    toleranceInterruptSimulation=0.001,
    maximumEdgeSpecies=100000,
)

options(
    units='si',
    saveRestartPeriod=None,
    generatePlots=False,
    saveEdgeSpecies=True,
)
```

RMG is running on macSO 12.6.8. RMG version 3.2.0 was installed via docker using the instruction in the  user's guide.

**Comment by JacksonBurns** [comment]
Hi @emccaughey thank you for the thorough report! This is actually a known issue, and we have a pull request open (https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2413) that should resolve it. Given that it is affecting the main release, we will try and get this fix implemented ASAP.

I will provide an update when things progress!

**Comment by JacksonBurns** [comment]
@emccaughey I think this is resolved now - could you let us know if the error still comes up?
