### ISSUE TITLE
Chemical simulation of a uspto patented reaction with methanol as solvent is throwing an error.

### ISSUE THREAD

**Issue by joel-brelson** [ReactionMechanismGenerator/RMG-Py#2564]
I was trying to run a uspto reaction with methanol as a solvent but it threw me an error like this
Filling in rate rules in kinetics families by averaging...
Traceback (most recent call last):
  File "rmg.py", line 118, in <module>
    main()
  File "rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/rmg/RMG-Py/rmgpy/rmg/main.py", line 751, in execute
    self.initialize(**kwargs)
  File "/rmg/RMG-Py/rmgpy/rmg/main.py", line 585, in initialize
    self.reaction_model.core.phase_system.phases["Default"].set_solvent(solvent_data)
  File "/rmg/RMG-Py/rmgpy/rmg/reactors.py", line 238, in set_solvent
    self.solvent = to_rms(solvent)
  File "/rmg/RMG-Py/rmgpy/rmg/reactors.py", line 767, in to_rms
    return rms.Solvent("solvent", rms.RiedelViscosity(float(obj.A), float(obj.B), float(obj.C), float(obj.D), float(obj.E)))
**TypeError: float() argument must be a string or a number, not 'NoneType'**

**Could someone help me regarding how could i rectify the error for this**
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/13186855/input.txt)

**Comment by JacksonBurns** [comment]
Hi @joel-brelson thank you for the report!

I can confirm that I was able to reproduce this error on RMG-Py v3.2.0 using the provided input. Unfortunately this will be difficult to solve quickly. If you take a look at [this link to our database](https://github.com/ReactionMechanismGenerator/RMG-database/blob/b7ff16364a07c9a51a34303aa28407a83455a3e4/input/solvation/libraries/solvent.py#L1070), we don't have the Riedel equation A, B, C, D, and E values for methanol, which are required for the backend simulator RMS. Now, this simulation does not use RMS so we may be able to skip this step (so this would be solved by #2539, which we are still working on).

I've asked one of the other developers if we can skip this step so your simulation can proceed. I will follow up about that.

In the meantime, you can go your installation of RMG and open the RMG-database/input/solvation/libraries/solvent.py file and fill in some 'placeholder' values for A, B, C, D, and E for methanol, around line 1087 in the file. This should allow your simulation to run, but don't use any RMS-based reactors (stick to liquid reactor). Let me know if you need additional help with this!

**Comment by joel-brelson** [comment]
Hello @JacksonBurns thanks for the reply the code ran without any errors after filling them with some placeholder values

**Comment by JacksonBurns** [comment]
Glad to hear it @joel-brelson! Keep in mind that the results may be unphysical with just placeholder values. If that is the case you may need to dig them up/estimate them somehow to get better results. We will also work on this from our end.

I'm going to update the title of this issue and open a corresponding issue on RMG-database so we can track the work.
