### ISSUE TITLE
InvalidMicrocanonicalRateError

### ISSUE THREAD

**Issue by PoojaNem** [ReactionMechanismGenerator/RMG-Py#2652]
Hello Everyone,

I am working on kinetic model generation for n-decane combustion in air. Based on the reactor pressure, temperature and mixture composition I intend to produce a mechanism with pressure dependence. While running this case, I end up with the error (shown below):

<img width="866" alt="image" src="https://github.com/ReactionMechanismGenerator/RMG-Py/assets/131012151/738327a7-5b1c-48ed-b973-817d95097e9c">

I have looked into several similar issues previously reported on GitHub, but could not understand the source of the error.

Any suggestion to resolve this concern will be helpful. I have attached the RMG input, error and thermo database file (slightly different from existing file in RMG database). Let me know if further details are needed from my end.

[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/15026441/input.txt)
[error.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/15026500/error.txt)
[JetSurF2.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/15026464/JetSurF2.txt)

Installation Information
OS: Windows 11, WSL2, Ubuntu 22.04
Installation method: Installation by Source Using Anaconda Environment for Unix-based Systems: Linux and Mac OSX
RMG version information:
RMG-Py: Latest version
RMG-database: Latest database

**Comment by JacksonBurns** [comment]
Here's the complete text of the error, which I think shows the actual problem:

```
Updating PDepNetwork #523
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'O_R0' and all its parents have data = None
Warning: Statmech node 'C_R0' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C(CCCCCCC)C([O])=O.
Warning: Statmech node 'O_R0' and all its parents have data = None
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C=C([O])OCCCCCCC.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for CCCCCCCC=C([O])[O].
Warning: Statmech node 'O_R0' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C([C]=O)CCCCCCC.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'O_R0' and all its parents have data = None
Warning: Statmech node 'C_R0' and all its parents have data = None
Warning: Statmech node 'RsCHrr' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH]C(CCCCCCC)C([O])=O.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2][C](CCCCCCC)C([O])[O].
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C([CH]CCCCCC)C([O])[O].
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C([CH]CCCCCC)[C]([O])O.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C(C[CH]CCCCC)C([O])[O].
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C(C[CH]CCCCC)[C]([O])O.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C(CC[CH]CCCC)C([O])[O].
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C(CC[CH]CCCC)[C]([O])O.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C(CCC[CH]CCC)C([O])[O].
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C(CCC[CH]CCC)[C]([O])O.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C(CCCC[CH]CC)C([O])[O].
Warning: Statmech node 'O_R0' and all its parents have data = None
Warning: Statmech node 'C_R0' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2][C](CCCCCCC)C(=O)O.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'O_R0' and all its parents have data = None
Warning: Statmech node 'C_R0' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for C=C(CCCCCCC)C([O])=O.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C(CCCCCCC)=C([O])[O].
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'O_R0' and all its parents have data = None
Warning: Statmech node 'C_R0' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C([CH]CCCCCC)C([O])=O.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'O_R0' and all its parents have data = None
Warning: Statmech node 'C_R0' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C(CC[CH]CCCC)C([O])=O.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'O_R0' and all its parents have data = None
Warning: Statmech node 'C_R0' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C(CCC[CH]CCC)C([O])=O.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'O_R0' and all its parents have data = None
Warning: Statmech node 'C_R0' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C(CCCC[CH]CC)C([O])=O.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'O_R0' and all its parents have data = None
Warning: Statmech node 'C_R0' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C(C[CH]CCCCC)C([O])=O.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'O_R0' and all its parents have data = None
Warning: Statmech node 'C_R0' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C(CCCCC[CH]C)C([O])=O.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'O_R0' and all its parents have data = None
Warning: Statmech node 'C_R0' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]CCCCCCC([CH2])C([O])=O.
Warning: Statmech node 'Oxy' and all its parents have data = None
Warning: Statmech node 'O_R0' and all its parents have data = None
Warning: Statmech node 'C_R0' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for CCCCCCC[C](C)C([O])=O.
Warning: Statmech node 'O_R0' and all its parents have data = None
Warning: Statmech node 'C_R0' and all its parents have data = None
Warning: Maximum number of iterations reached when fitting spectral data for [CH2]C([CH]CCCCCC)C(=O)O.
Calculating densities of states for PDepNetwork #523 network...
Using 718 grains from -536.40 to 963.56 kJ/mol in steps of 2.09 kJ/mol to compute densities of states
Calculating phenomenological rate coefficients for [CH2]C(CCCCCCC)C([O])=O(2772) <=> C[CH]CCCCCC(C)C([O])=O(4314)...
Using 718 grains from -536.40 to 963.56 kJ/mol in steps of 2.09 kJ/mol to compute the k(T,P) values at 2100 K
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CCCCCCC)C([O])=O(2772) <=> CCCCCCCCC=C([O])[O](4276)".
Warning: For path reaction [CH2]C(CCCCCCC)C([O])=O(2772) <=> [CH2]C(CCCCCCC)[C]1OO1(4290):
Warning:     Expected kf(2100 K) = 22938.6
Warning:       Actual kf(2100 K) = 7734.82
Warning:     Expected Keq(2100 K) = 1.20613e-09
Warning:       Actual Keq(2100 K) = 0
Warning: Increasing number of grains, decreasing grain size and trying again. (Current badness: 0.5)
Using 1434 grains from -536.40 to 962.51 kJ/mol in steps of 1.05 kJ/mol to compute the k(T,P) values at 2100 K
Warning: For path reaction [CH2]C(CCCCCCC)C([O])=O(2772) <=> [CH2]C(CCCCCCC)[C]1OO1(4290):
Warning:     Expected kf(2100 K) = 22938.6
Warning:       Actual kf(2100 K) = 7646.57
Warning:     Expected Keq(2100 K) = 1.20613e-09
Warning:       Actual Keq(2100 K) = 0
Warning: Increasing number of grains, decreasing grain size and trying again. (Current badness: 0.5)
Using 2866 grains from -536.40 to 961.99 kJ/mol in steps of 0.52 kJ/mol to compute the k(T,P) values at 2100 K
Warning: For path reaction [CH2]C(CCCCCCC)C([O])=O(2772) <=> [CH2]C(CCCCCCC)[C]1OO1(4290):
Warning:     Expected kf(2100 K) = 22938.6
Warning:       Actual kf(2100 K) = 7602.51
Warning:     Expected Keq(2100 K) = 1.20613e-09
Warning:       Actual Keq(2100 K) = 0
Warning: Increasing number of grains, decreasing grain size and trying again. (Current badness: 0.5)
Using 5731 grains from -536.40 to 961.99 kJ/mol in steps of 0.26 kJ/mol to compute the k(T,P) values at 2100 K
Warning: For path reaction [CH2]C(CCCCCCC)C([O])=O(2772) <=> [CH2]C(CCCCCCC)[C]1OO1(4290):
Warning:     Expected kf(2100 K) = 22938.6
Warning:       Actual kf(2100 K) = 7595.19
Warning:     Expected Keq(2100 K) = 1.20613e-09
Warning:       Actual Keq(2100 K) = 0
Warning: Increasing number of grains, decreasing grain size and trying again. (Current badness: 0.5)
Using 11461 grains from -536.40 to 961.99 kJ/mol in steps of 0.13 kJ/mol to compute the k(T,P) values at 2100 K
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "[CH2]C(CCCCCCC)C([O])=O(2772) <=> CCCCCCCCC=C([O])[O](4276)".
Warning: For path reaction [CH2]C(CCCCCCC)C([O])=O(2772) <=> [CH2]C(CCCCCCC)[C]1OO1(4290):
Warning:     Expected kf(2100 K) = 22938.6
Warning:       Actual kf(2100 K) = 7591.52
Warning:     Expected Keq(2100 K) = 1.20613e-09
Warning:       Actual Keq(2100 K) = 0
Error: Invalid k(E) values computed for path reaction "[CH2]C(CCCCCCC)C([O])=O(2772) <=> [CH2]C(CCCCCCC)[C]1OO1(4290)".
Error: Increasing number of grains did not decrease error enough (Current badness: 0.5, previous 0.5). Something must be wrong with network PDepNetwork #523
Traceback (most recent call last):
  File "/home/pnema/miniconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 308, in main
    python(**vars(ns))
  File "/home/pnema/miniconda3/envs/rmg_env/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 59, in python
    scope = runpy.run_path(script, run_name="__main__")
  File "/home/pnema/miniconda3/envs/rmg_env/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/pnema/miniconda3/envs/rmg_env/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/pnema/miniconda3/envs/rmg_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pnema/RMG/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/home/pnema/RMG/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/pnema/RMG/RMG-Py/rmgpy/rmg/main.py", line 944, in execute
    self.reaction_model.enlarge(objectToEnlarge)
  File "/home/pnema/RMG/RMG-Py/rmgpy/rmg/model.py", line 709, in enlarge
    self.update_unimolecular_reaction_networks()
  File "/home/pnema/RMG/RMG-Py/rmgpy/rmg/model.py", line 1919, in update_unimolecular_reaction_networks
    network.update(self, self.pressure_dependence)
  File "/home/pnema/RMG/RMG-Py/rmgpy/rmg/pdep.py", line 879, in update
    K = self.calculate_rate_coefficients(Tlist, Plist, method)
  File "/home/pnema/RMG/RMG-Py/rmgpy/pdep/network.py", line 268, in calculate_rate_coefficients
    self.set_conditions(T, P)
  File "/home/pnema/RMG/RMG-Py/rmgpy/pdep/network.py", line 411, in set_conditions
    raise error
  File "/home/pnema/RMG/RMG-Py/rmgpy/pdep/network.py", line 399, in set_conditions
    self.calculate_microcanonical_rates()
  File "/home/pnema/RMG/RMG-Py/rmgpy/pdep/network.py", line 841, in calculate_microcanonical_rates
    'Invalid k(E) values computed for path reaction "{0}".'.format(rxn), k_ratio, Keq_ratio)
rmgpy.exceptions.InvalidMicrocanonicalRateError: ('Invalid k(E) values computed for path reaction "[CH2]C(CCCCCCC)C([O])=O(2772) <=> [CH2]C(CCCCCCC)[C]1OO1(4290)".', 3.0216075010375487, 1.0)
```

The `Warning:       Actual Keq(2100 K) = 0` which comes up after `Warning: Statmech node 'Oxy' and all its parents have data = None` leads me to believe that one of these species contains some group that Arkane just can't estimate something for, though I don't know much detail beyond that. @oscarwumit have you seen something like this before?
