### ISSUE TITLE
DatabaseError with Thermo Parameters for F

### ISSUE THREAD

**Issue by studies9** [ReactionMechanismGenerator/RMG-Py#2713]
DatabaseError related to thermo parameter estimation for fluorine-containing molecules in RMG-Py. Specifically, the error message is:
DatabaseError: Unable to determine thermo parameters for atom {'*': <Atom 'F'>} in molecule <Molecule "OOC(F)F">: no data for node R or any of its ancestors in database group.

I encounter this issue both with and without a seed mechanism. For instance, when using a seed mechanism, I receive the following error:
DatabaseError: Unable to determine thermo parameters for atom {'*': <Atom 'F'>} in molecule <Molecule "OCF">: no data for node R or any of its ancestors in database group.

**Comment by JacksonBurns** [comment]
Searching this molecule on rmg.mit.edu [yields results](https://rmg.mit.edu/database/thermo/molecule/1%20O%20u0%20p2%20c0%20%7B2,S%7D%20%7B6,S%7D%0A2%20O%20u0%20p2%20c0%20%7B1,S%7D%20%7B3,S%7D%0A3%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B4,S%7D%20%7B5,S%7D%20%7B7,S%7D%0A4%20F%20u0%20p3%20c0%20%7B3,S%7D%0A5%20F%20u0%20p3%20c0%20%7B3,S%7D%0A6%20H%20u0%20p0%20c0%20%7B1,S%7D%0A7%20H%20u0%20p0%20c0%20%7B3,S%7D%0A) - do you have the `Fluorine` library included in your `thermoLibraries`?

**Comment by studies9** [comment]
# Data sources
database(
    thermoLibraries = ['primaryThermoLibrary', 'Fluorine'],
    reactionLibraries = [],
    seedMechanisms = [],
    kineticsDepositories = ['training'],
    kineticsFamilies = 'default',
    kineticsEstimator = 'rate rules',
)

# List of species
species(
    label='CH2F2',
    reactive=True,
    structure=SMILES("FCF"),
)
species(
    label='O2',
    reactive=True,
    structure=SMILES("[O][O]"),
)

species(
    label='Ar',
    reactive=True,
    structure=SMILES("[Ar]"),
)


# Reaction systems
simpleReactor(
    temperature=(600,'K'),
    pressure=(1.0,'bar'),
    initialMoleFractions={
        "CH2F2": 0.025, "Ar": 0.95, "O2": 0.025,
    },
    terminationConversion={
        'O2': 0.9999,
    },
    terminationTime=(1e12,'s'),
)

simulator(
    atol=1e-16,
    rtol=1e-8,
)

model(
    toleranceKeepInEdge=1e-5,
    toleranceMoveToCore=0.01,
    toleranceInterruptSimulation=0.1,
    maximumEdgeSpecies=100000
)

options(
    units='si',
    generateOutputHTML=False,
    generatePlots=False,
    saveEdgeSpecies=True,
    saveSimulationProfiles=True,
)

**Comment by JacksonBurns** [comment]
Try adding the `CHOF_G4` thermo library as well

**Comment by studies9** [comment]
The CHOF_G4 library is not available in our current RMG version. How can I obtain it?

**Comment by rwest** [comment]
You probably need to update RMG-Py also, in order to read the new database.
The stack trace you post says the error is in `File "/home/ubuntu/miniconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/data/base.py", line 239, in load
exec(f.read(), global_context, local_context)`
But I think line 239 of the file `rmgpy/data/base.py` hasn't contained the code `exec(f.read(), global_context, local_context)` since May 2021.

In my experience, easiest to install an entire new version, in a brand new environment (give it a new name, not `rmg_env`). This greatly increases the chance of it working, and also decreases the chance of you messing up your old version.

**Comment by studies9** [comment]
Traceback (most recent call last):
  File "/home/ubuntu/Downloads/RMG-Py/rmg.py", line 118, in <module>
    main()
  File "/home/ubuntu/Downloads/RMG-Py/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/ubuntu/Downloads/RMG-Py/rmgpy/rmg/main.py", line 752, in execute
    self.initialize(**kwargs)
  File "/home/ubuntu/Downloads/RMG-Py/rmgpy/rmg/main.py", line 553, in initialize
    self.reaction_model.add_species_to_edge(spec)
  File "/home/ubuntu/Downloads/RMG-Py/rmgpy/rmg/model.py", line 1178, in add_species_to_edge
    self.edge.phase_system.phases["Default"].add_species(spec)
  File "/home/ubuntu/Downloads/RMG-Py/rmgpy/rmg/reactors.py", line 294, in add_species
    spec = to_rms(spc)
  File "/home/ubuntu/Downloads/RMG-Py/rmgpy/rmg/reactors.py", line 699, in to_rms
    rad = rms.getspeciesradius(atomnums, bondnum)
NameError: name 'rms' is not defined
i have installed an entire new version, but then too this error comes up

**Comment by JacksonBurns** [comment]
It looks like you missed steps 11. and/or 12. in the installation instructions here: https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html
or you are not running RMG-Py from inside the correct `conda` environment.

An alternative is to install the Docker image, which avoids having to do this manual installation: https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/index.html#recommended-install-docker
