### ISSUE TITLE
An AssertionError on Saving current model core to Chemkin file

### ISSUE THREAD

**Issue by Academics32** [ReactionMechanismGenerator/RMG-Py#2714]
After model enlargement:
    The model core has 128 species and 4066 reactions
    The model edge has 11941 species and 29093 reactions

Completed initial enlarge edge step.
Saving current model core to Chemkin file...
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/rmg_env/bin/rmg.py", line 118, in <module>
    main()
  File "/home/ubuntu/miniconda3/envs/rmg_env/bin/rmg.py", line 112, in main
    rmg.execute(**kwargs)
  File "/home/ubuntu/miniconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/rmg/main.py", line 749, in execute
    self.save_everything()
  File "/home/ubuntu/miniconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/rmg/main.py", line 1849, in save_everything
    self.notify()
  File "/home/ubuntu/miniconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/util.py", line 113, in notify
    observer.update(self)
  File "rmgpy/chemkin.pyx", line 2396, in rmgpy.chemkin.ChemkinWriter.update
  File "rmgpy/chemkin.pyx", line 2292, in rmgpy.chemkin.save_chemkin_files
  File "rmgpy/chemkin.pyx", line 2268, in rmgpy.chemkin.save_chemkin
  File "rmgpy/chemkin.pyx", line 2107, in rmgpy.chemkin.save_chemkin_file
  File "rmgpy/chemkin.pyx", line 1875, in rmgpy.chemkin.write_kinetics_entry
AssertionError

Can someone please guide me

**Comment by Academics32** [comment]
I am completely stuck at this point. Can someone please help me to move forward.

**Comment by JacksonBurns** [comment]
It looks like you are failing one of the `assert` statement checks in [this function](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/main/rmgpy/chemkin.pyx#L1715) but I can't tell which one since the line numbers don't match up. You might be running an outdated version of RMG-Py, so I recommend upgrading.

Those functions should also give more descriptive output about why they failed - check your terminal and logfiles to see if there is anything else.
