### ISSUE TITLE
Many warnings when building documentation with sphinx

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#277]
Although these are only warnings (with Sphinx v1.2.2), they should be fixed, because (1) they may be rendering strangely, and (2) sometimes a bug in Sphinx can mean the warning becomes an error and the build fails (our entire documentation website was down for a week because of this - the automatic build robot was running a different version of Sphinx to the one people had tested with).

A clean build (remove the build folder first) will reveal 94 warnings:

```
Running Sphinx v1.2.2
loading pickled environment... not yet created
building [html]: targets for 182 source files that are out of date
updating environment: 182 added, 0 changed, 0 removed
reading sources... [100%] users/rmg/thermo                                        
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/chemkin.py:docstring of rmgpy.chemkin.saveTransportFile:7: WARNING: Definition list ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/chemkin.py:docstring of rmgpy.chemkin.saveTransportFile:16: WARNING: Enumerated list ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/base.py:docstring of rmgpy.data.base.Database.matchNodeToStructure:15: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/base.py:docstring of rmgpy.data.base.Database.matchNodeToStructure:17: ERROR: Unexpected indentation.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/kinetics/depository.py:docstring of rmgpy.data.kinetics.KineticsDepository.matchNodeToStructure:15: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/kinetics/depository.py:docstring of rmgpy.data.kinetics.KineticsDepository.matchNodeToStructure:17: ERROR: Unexpected indentation.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/kinetics/family.py:docstring of rmgpy.data.kinetics.KineticsFamily.matchNodeToStructure:15: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/kinetics/family.py:docstring of rmgpy.data.kinetics.KineticsFamily.matchNodeToStructure:17: ERROR: Unexpected indentation.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/kinetics/groups.py:docstring of rmgpy.data.kinetics.KineticsGroups.matchNodeToStructure:15: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/kinetics/groups.py:docstring of rmgpy.data.kinetics.KineticsGroups.matchNodeToStructure:17: ERROR: Unexpected indentation.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/kinetics/library.py:docstring of rmgpy.data.kinetics.KineticsLibrary.matchNodeToStructure:15: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/kinetics/library.py:docstring of rmgpy.data.kinetics.KineticsLibrary.matchNodeToStructure:17: ERROR: Unexpected indentation.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/kinetics/rules.py:docstring of rmgpy.data.kinetics.KineticsRules.matchNodeToStructure:15: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/kinetics/rules.py:docstring of rmgpy.data.kinetics.KineticsRules.matchNodeToStructure:17: ERROR: Unexpected indentation.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmech.py:docstring of rmgpy.data.statmech.StatmechDepository.matchNodeToStructure:15: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmech.py:docstring of rmgpy.data.statmech.StatmechDepository.matchNodeToStructure:17: ERROR: Unexpected indentation.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.DirectFit.initialize:16: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.DirectFit.initialize:19: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.DirectFit.initialize:21: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.DirectFit.initialize:24: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.DirectFit.initialize:26: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.DirectFit.initialize:29: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.PseudoRotorFit.initialize:16: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.PseudoRotorFit.initialize:19: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.PseudoRotorFit.initialize:21: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.PseudoRotorFit.initialize:24: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.PseudoRotorFit.initialize:26: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.PseudoRotorFit.initialize:29: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.PseudoFit.initialize:16: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.PseudoFit.initialize:19: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.PseudoFit.initialize:21: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.PseudoFit.initialize:24: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.PseudoFit.initialize:26: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmechfit.py:docstring of rmgpy.data.statmechfit.PseudoFit.initialize:29: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmech.py:docstring of rmgpy.data.statmech.StatmechGroups.matchNodeToStructure:15: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmech.py:docstring of rmgpy.data.statmech.StatmechGroups.matchNodeToStructure:17: ERROR: Unexpected indentation.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmech.py:docstring of rmgpy.data.statmech.StatmechLibrary.matchNodeToStructure:15: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/statmech.py:docstring of rmgpy.data.statmech.StatmechLibrary.matchNodeToStructure:17: ERROR: Unexpected indentation.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/thermo.py:docstring of rmgpy.data.thermo.ThermoDepository.matchNodeToStructure:15: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/thermo.py:docstring of rmgpy.data.thermo.ThermoDepository.matchNodeToStructure:17: ERROR: Unexpected indentation.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/thermo.py:docstring of rmgpy.data.thermo.ThermoGroups.matchNodeToStructure:15: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/thermo.py:docstring of rmgpy.data.thermo.ThermoGroups.matchNodeToStructure:17: ERROR: Unexpected indentation.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/thermo.py:docstring of rmgpy.data.thermo.ThermoLibrary.matchNodeToStructure:15: WARNING: Block quote ends without a blank line; unexpected unindent.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/data/thermo.py:docstring of rmgpy.data.thermo.ThermoLibrary.matchNodeToStructure:17: ERROR: Unexpected indentation.
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/reference/molecule/adjlist.rst:84: ERROR: Unexpected indentation.
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/reference/molecule/adjlist.rst:86: WARNING: Block quote ends without a blank line; unexpected unindent.
docstring of rmgpy.molecule.AtomType:21: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/reference/pdep/lennardjones.rst:5: WARNING: autodoc: failed to import class u'LennardJones' from module u'rmgpy.pdep'; the following exception was raised:
Traceback (most recent call last):
  File "/export/thishost/comocheng/virtualenvs/rmgweb/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 342, in import_object
    obj = self.get_attr(obj, part)
  File "/export/thishost/comocheng/virtualenvs/rmgweb/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 241, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/export/thishost/comocheng/virtualenvs/rmgweb/local/lib/python2.7/site-packages/sphinx/util/inspect.py", line 114, in safe_getattr
    raise AttributeError(name)
AttributeError: LennardJones
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/qm/gaussian.py:docstring of rmgpy.qm.gaussian.GaussianMol.inputFileKeywords:3: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/qm/gaussian.py:docstring of rmgpy.qm.gaussian.GaussianMol.writeInputFile:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/qm/gaussian.py:docstring of rmgpy.qm.gaussian.GaussianMolPM3.inputFileKeywords:3: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/qm/gaussian.py:docstring of rmgpy.qm.gaussian.GaussianMolPM3.writeInputFile:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/qm/gaussian.py:docstring of rmgpy.qm.gaussian.GaussianMolPM6.inputFileKeywords:3: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/qm/gaussian.py:docstring of rmgpy.qm.gaussian.GaussianMolPM6.writeInputFile:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/qm/mopac.py:docstring of rmgpy.qm.mopac.MopacMol.writeInputFile:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/qm/mopac.py:docstring of rmgpy.qm.mopac.MopacMolPM3.inputFileKeywords:3: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/qm/mopac.py:docstring of rmgpy.qm.mopac.MopacMolPM3.writeInputFile:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/qm/mopac.py:docstring of rmgpy.qm.mopac.MopacMolPM6.inputFileKeywords:3: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/qm/mopac.py:docstring of rmgpy.qm.mopac.MopacMolPM6.writeInputFile:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/qm/mopac.py:docstring of rmgpy.qm.mopac.MopacMolPM7.inputFileKeywords:3: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/rmgpy/qm/mopac.py:docstring of rmgpy.qm.mopac.MopacMolPM7.writeInputFile:1: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/theory/measure/master_equation.rst:412: WARNING: duplicate citation Gilbert1990, other instance in /export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/reference/pdep/mastereqn.rst
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/theory/measure/master_equation.rst:415: WARNING: duplicate citation Baer1996, other instance in /export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/reference/pdep/mastereqn.rst
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/theory/measure/master_equation.rst:418: WARNING: duplicate citation Holbrook1996, other instance in /export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/reference/pdep/mastereqn.rst
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/theory/measure/master_equation.rst:421: WARNING: duplicate citation Forst2003, other instance in /export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/reference/pdep/mastereqn.rst
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/theory/measure/master_equation.rst:424: WARNING: duplicate citation Pilling2003, other instance in /export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/reference/pdep/mastereqn.rst
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/database/modification.rst:192: WARNING: Inline emphasis start-string without end-string.
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:23: WARNING: Title underline too short.

Thermo Libraries
---------------
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:56: WARNING: Title underline too short.

Reaction Libraries
-----------------
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:56: WARNING: Title underline too short.

Reaction Libraries
-----------------
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:93: WARNING: Title underline too short.

Seed Mechanisms
--------------
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:93: WARNING: Title underline too short.

Seed Mechanisms
--------------
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:130: WARNING: Title underline too short.

Kinetics Families
----------------
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:130: WARNING: Title underline too short.

Kinetics Families
----------------
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:139: WARNING: Title underline too short.

Kinetics Estimator
-----------------
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:139: WARNING: Title underline too short.

Kinetics Estimator
-----------------
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:302: WARNING: Literal block expected; none found.
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:315: WARNING: duplicate citation Chang2000, other instance in /export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/reference/pdep/singleexponentialdown.rst
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/species.rst:5: WARNING: duplicate label species, other instance in /export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/thermo.rst:273: WARNING: duplicate citation RDKit, other instance in /export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] users/rmg/thermo                                         
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:36: WARNING: undefined label: editingthermodatabase (if the link has no caption the label must precede a section header)
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:86: WARNING: undefined label: irreversiblekinetics (if the link has no caption the label must precede a section header)
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:94: WARNING: undefined label: list of species (if the link has no caption the label must precede a section header)
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:243: WARNING: undefined label: tolerancekeepinedge (if the link has no caption the label must precede a section header)
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:243: WARNING: undefined label: toleranceinterruptsimulation (if the link has no caption the label must precede a section header)
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:243: WARNING: undefined label: terminationconversion (if the link has no caption the label must precede a section header)
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:243: WARNING: undefined label: terminationtime (if the link has no caption the label must precede a section header)
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:243: WARNING: undefined label: maximumedgespecies (if the link has no caption the label must precede a section header)
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:248: WARNING: undefined label: maximumedgespecies (if the link has no caption the label must precede a section header)
/export/thishost/comocheng/build/greengroup-rmg-py/documentation/source/users/rmg/input.rst:248: WARNING: undefined label: toleranceinterruptsimulation (if the link has no caption the label must precede a section header)
None:66: WARNING: citation not found: Abraham1999
None:66: WARNING: citation not found: Abraham1999
None:66: WARNING: citation not found: Abraham1990
None:66: WARNING: citation not found: Abraham1999
writing additional files... genindex py-modindex search index
copying images... [100%] users/rmg/images/Fallup.png                              
copying static files... done
copying extra files... done
dumping search index... done
dumping object inventory... done
build succeeded, 94 warnings.

Build finished. The HTML pages are in build/html.
```

**Comment by connie** [comment]
This is now outdated.  There are far fewer warnings now.
