### ISSUE TITLE
RMG generated network failing due to NASA polynomial ValueError

### ISSUE THREAD

**Issue by enochd** [ReactionMechanismGenerator/RMG-Py#331]
I wanted to document this, but will try and troubleshoot at some point. Perhaps someone else has seen this already though? RMG is failing after generating a network, and looks like it keeps trying to access thermo at lower and lower temperatures.

``` python
101 network information

Isomers:
    C3H6(50)                                              6.62321 kJ/mol
Reactant channels:
Product channels:
    H(4) + CH3CHCH(44)                                    466.251 kJ/mol
    C2H4(31) + CH2(S)(24)                                 460.953 kJ/mol
    CH3CCH2(43) + H(4)                                    451.558 kJ/mol
    [CH2][CH]C(157)                                       279.046 kJ/mol
Path reactions:
    H(4) + CH3CHCH(44) <=> C3H6(50)                       466.251 kJ/mol
    C2H4(31) + CH2(S)(24) <=> C3H6(50)                    460.953 kJ/mol
    CH3CCH2(43) + H(4) <=> C3H6(50)                       451.558 kJ/mol
    [CH2][CH]C(157) <=> C3H6(50)                          279.046 kJ/mol


Calculating densities of states for <rmgpy.pdep.network.Network instance at 0x382db48>...
Using 525 grains from 6.62 to 1102.83 kJ/mol in steps of 2.09 kJ/mol to compute densities of states
Calculating phenomenological rate coefficients for <rmgpy.pdep.network.Network instance at 0x382db48>...
Using 277 grains from 6.62 to 584.01 kJ/mol in steps of 2.09 kJ/mol to compute the k(T,P) values at 352.796 K
Exception ValueError: ValueError('No valid NASA polynomial at temperature 297.872 K.',) in 'rmgpy.reaction.Reaction.getFreeEnergyOfReaction' ignored
Exception ValueError: ValueError('No valid NASA polynomial at temperature 291.667 K.',) in 'rmgpy.reaction.Reaction.getFreeEnergyOfReaction' ignored
Exception ValueError: ValueError('No valid NASA polynomial at temperature 285.714 K.',) in 'rmgpy.reaction.Reaction.getFreeEnergyOfReaction' ignored
Exception ValueError: ValueError('No valid NASA polynomial at temperature 280 K.',) in 'rmgpy.reaction.Reaction.getFreeEnergyOfReaction' ignored
Exception ValueError: ValueError('No valid NASA polynomial at temperature 274.51 K.',) in 'rmgpy.reaction.Reaction.getFreeEnergyOfReaction' ignored
Exception ValueError: ValueError('No valid NASA polynomial at temperature 269.231 K.',) in 'rmgpy.reaction.Reaction.getFreeEnergyOfReaction' ignored
Exception ValueError: ValueError('No valid NASA polynomial at temperature 264.151 K.',) in 'rmgpy.reaction.Reaction.getFreeEnergyOfReaction' ignored
Exception ValueError: ValueError('No valid NASA polynomial at temperature 259.259 K.',) in 'rmgpy.reaction.Reaction.getFreeEnergyOfReaction' ignored
Exception ValueError: ValueError('No valid NASA polynomial at temperature 254.545 K.',) in 'rmgpy.reaction.Reaction.getFreeEnergyOfReaction' ignored
Exception ValueError: ValueError('No valid NASA polynomial at temperature 250 K.',) in 'rmgpy.reaction.Reaction.getFreeEnergyOfReaction' ignored
/home/enoch/RMG-Py/rmgpy/pdep/network.py:574: RuntimeWarning: invalid value encountered in divide
  kf, kr = rxn.calculateMicrocanonicalRateCoefficient(self.Elist, self.Jlist, reacDensStates, prodDensStates, T)
Traceback (most recent call last):
  File "/home/enoch/RMG-Py/cantherm.py", line 61, in <module>
    cantherm.execute()
  File "/home/enoch/RMG-Py/rmgpy/cantherm/main.py", line 235, in execute
    job.execute(outputFile=outputFile, plot=self.plot)
  File "/home/enoch/RMG-Py/rmgpy/cantherm/pdep.py", line 231, in execute
    self.K = self.network.calculateRateCoefficients(self.Tlist.value_si, self.Plist.value_si, self.method)
  File "/home/enoch/RMG-Py/rmgpy/pdep/network.py", line 210, in calculateRateCoefficients
    self.setConditions(T, P)
  File "/home/enoch/RMG-Py/rmgpy/pdep/network.py", line 317, in setConditions
    self.calculateMicrocanonicalRates()
  File "/home/enoch/RMG-Py/rmgpy/pdep/network.py", line 578, in calculateMicrocanonicalRates
    raise NetworkError('One or more k(E) values is NaN for path reaction "{0}".'.format(rxn))
rmgpy.pdep.network.NetworkError: One or more k(E) values is NaN for path reaction "C2H4(31) + CH2(S)(24) <=> C3H6(50)".
```

Here is the input file:

``` python
species(
    label = 'C3H6(50)',
    structure = SMILES('C=CC'),
    E0 = (6.62321,'kJ/mol'),
    modes = [
        HarmonicOscillator(frequencies=([2750,2800,2850,1350,1500,750,1050,1375,1000,3010,987.5,1337.5,450,1655,2950,3100,1380,975,1025,1650],'cm^-1')),
        HinderedRotor(inertia=(0.581663,'amu*angstrom^2'), symmetry=1, barrier=(13.3736,'kJ/mol'), semiclassical=False),
    ],
    spinMultiplicity = 1,
    opticalIsomers = 1,
    molecularWeight = (42.0797,'amu'),
    collisionModel = TransportData(shapeIndex=2, epsilon=(2218.31,'J/mol'), sigma=(4.982,'angstroms'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=1.0, comment="""GRI-Mech"""),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[1.49331,0.0209252,4.48679e-06,-1.66891e-08,7.15815e-12,1074.83,16.1453], Tmin=(298,'K'), Tmax=(1000,'K')), NASAPolynomial(coeffs=[6.73226,0.0149083,-4.9499e-06,7.21202e-10,-3.7662e-14,-923.57,-13.3133], Tmin=(1000,'K'), Tmax=(5000,'K'))], Tmin=(298,'K'), Tmax=(5000,'K'), E0=(6.62321,'kJ/mol'), comment="""Thermo library: DME"""),
)

species(
    label = 'CH3CCH2(43)',
    structure = SMILES('C=[C]C'),
    E0 = (239.753,'kJ/mol'),
    modes = [
        HarmonicOscillator(frequencies=([2750,2800,2850,1350,1500,750,1050,1375,1000,1685,370,2950,3100,1380,975,1025,1650],'cm^-1')),
        HinderedRotor(inertia=(1.28332,'amu*angstrom^2'), symmetry=1, barrier=(29.506,'kJ/mol'), semiclassical=False),
    ],
    spinMultiplicity = 2,
    opticalIsomers = 1,
    molecularWeight = (41.0718,'amu'),
    collisionModel = TransportData(shapeIndex=2, epsilon=(2161.77,'J/mol'), sigma=(4.85,'angstroms'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=1.0, comment="""GRI-Mech"""),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[1.73292,0.0223946,-5.14906e-06,-6.75965e-09,3.82532e-12,29040.5,16.5689], Tmin=(298,'K'), Tmax=(1000,'K')), NASAPolynomial(coeffs=[5.42555,0.0155111,-5.66784e-06,7.92244e-10,-1.6878e-14,27843,-3.35272], Tmin=(1000,'K'), Tmax=(3000,'K'))], Tmin=(298,'K'), Tmax=(3000,'K'), E0=(239.753,'kJ/mol'), comment="""Thermo library: DME"""),
)

species(
    label = 'H(4)',
    structure = SMILES('[H]'),
    E0 = (211.805,'kJ/mol'),
    spinMultiplicity = 1,
    opticalIsomers = 1,
    molecularWeight = (1.00794,'amu'),
    collisionModel = TransportData(shapeIndex=0, epsilon=(1205.6,'J/mol'), sigma=(2.05,'angstroms'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=0.0, comment="""GRI-Mech"""),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[2.5,-2.38914e-13,3.12709e-16,-1.33367e-19,1.7499e-23,25474.2,-0.444973], Tmin=(100,'K'), Tmax=(4383.16,'K')), NASAPolynomial(coeffs=[2.50003,-3.04997e-08,1.01101e-11,-1.48797e-15,8.20356e-20,25474.2,-0.445191], Tmin=(4383.16,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(211.805,'kJ/mol'), comment="""Thermo library: primaryThermoLibrary"""),
)

species(
    label = 'CH3CHCH(44)',
    structure = SMILES('[CH]=CC'),
    E0 = (254.446,'kJ/mol'),
    modes = [
        HarmonicOscillator(frequencies=([2750,2800,2850,1350,1500,750,1050,1375,1000,3120,650,792.5,1650,346.156,346.212,1155.85,2054.72],'cm^-1')),
        HinderedRotor(inertia=(0.00140794,'amu*angstrom^2'), symmetry=1, barrier=(0.11979,'kJ/mol'), semiclassical=False),
    ],
    spinMultiplicity = 2,
    opticalIsomers = 1,
    molecularWeight = (41.0718,'amu'),
    collisionModel = TransportData(shapeIndex=2, epsilon=(2161.77,'J/mol'), sigma=(4.85,'angstroms'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=1.0, comment="""GRI-Mech"""),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[0.913729,0.0264323,-1.1759e-05,-2.30357e-09,2.77155e-12,30916.9,19.9893], Tmin=(298,'K'), Tmax=(1000,'K')), NASAPolynomial(coeffs=[5.37253,0.0157805,-5.99229e-06,9.30897e-10,-3.6551e-14,29614.8,-3.41865], Tmin=(1000,'K'), Tmax=(3000,'K'))], Tmin=(298,'K'), Tmax=(3000,'K'), E0=(254.446,'kJ/mol'), comment="""Thermo library: DME"""),
)

species(
    label = 'C2H4(31)',
    structure = SMILES('C=C'),
    E0 = (41.8617,'kJ/mol'),
    modes = [
        HarmonicOscillator(frequencies=([2950,3000,3050,3100,1330,1430,900,1050,1000,1050,1600,1700],'cm^-1')),
    ],
    spinMultiplicity = 1,
    opticalIsomers = 1,
    molecularWeight = (28.0532,'amu'),
    collisionModel = TransportData(shapeIndex=2, epsilon=(2334.71,'J/mol'), sigma=(3.971,'angstroms'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=1.5, comment="""GRI-Mech"""),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[3.9592,-0.00757051,5.7099e-05,-6.91588e-08,2.69884e-11,5089.78,4.0973], Tmin=(298,'K'), Tmax=(1000,'K')), NASAPolynomial(coeffs=[3.99183,0.0104834,-3.71721e-06,5.94628e-10,-3.5363e-14,4268.66,-0.269082], Tmin=(1000,'K'), Tmax=(6000,'K'))], Tmin=(298,'K'), Tmax=(6000,'K'), E0=(41.8617,'kJ/mol'), comment="""Thermo library: DME"""),
)

species(
    label = 'CH2(S)(24)',
    structure = SMILES('C'),
    E0 = (419.091,'kJ/mol'),
    modes = [
        HarmonicOscillator(frequencies=([1369.93,2896.01,2896.03],'cm^-1')),
    ],
    spinMultiplicity = 1,
    opticalIsomers = 1,
    molecularWeight = (14.0266,'amu'),
    collisionModel = TransportData(shapeIndex=2, epsilon=(1197.29,'J/mol'), sigma=(3.8,'angstroms'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=0.0, comment="""GRI-Mech"""),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[4.10265,-0.0014407,5.45074e-06,-3.58007e-09,7.56208e-13,50400.6,-0.411772], Tmin=(100,'K'), Tmax=(1442.34,'K')), NASAPolynomial(coeffs=[2.62644,0.00394768,-1.49927e-06,2.54545e-10,-1.62961e-14,50691.8,6.784], Tmin=(1442.34,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(419.091,'kJ/mol'), comment="""Thermo library: primaryThermoLibrary"""),
)

species(
    label = '[CH2][CH]C(157)',
    structure = SMILES('[CH2][CH]C'),
    E0 = (279.046,'kJ/mol'),
    modes = [
        HarmonicOscillator(frequencies=([2750,2800,2850,1350,1500,750,1050,1375,1000,3025,407.5,1350,352.5,3000,3100,440,815,1455,1000],'cm^-1')),
        HinderedRotor(inertia=(0.00418544,'amu*angstrom^2'), symmetry=1, barrier=(6.91844,'kJ/mol'), semiclassical=False),
        HinderedRotor(inertia=(0.00418541,'amu*angstrom^2'), symmetry=1, barrier=(6.9184,'kJ/mol'), semiclassical=False),
    ],
    spinMultiplicity = 3,
    opticalIsomers = 1,
    molecularWeight = (42.0797,'amu'),
    collisionModel = TransportData(shapeIndex=2, epsilon=(2737.71,'J/mol'), sigma=(5.09232,'angstroms'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=0, comment="""Epsilon & sigma estimated with Tc=427.62 K, Pc=47.04 bar (from Joback method)"""),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[3.25505,0.0137286,1.00536e-05,-1.43787e-08,4.38748e-12,33590.4,14.1736], Tmin=(100,'K'), Tmax=(1201.86,'K')), NASAPolynomial(coeffs=[3.74314,0.0203096,-8.40104e-06,1.5386e-09,-1.05137e-13,32880.4,9.26365], Tmin=(1201.86,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(279.046,'kJ/mol'), comment="""Thermo group additivity estimation: group(Cs-CsCsHH) + gauche(Cs(CsCsRR)) + other(R) + group(Cs-CsHHH) + gauche(Cs(Cs(CsRR)RRR)) + other(R) + group(Cs-CsHHH) + gauche(Cs(Cs(CsRR)RRR)) + other(R) + radical(RCCJ) + radical(CCJC)"""),
)

species(
    label = 'He',
    structure = SMILES('[He]'),
    E0 = (-6.19738,'kJ/mol'),
    spinMultiplicity = 1,
    opticalIsomers = 1,
    molecularWeight = (4.0026,'amu'),
    collisionModel = TransportData(shapeIndex=2, epsilon=(1.23553,'kJ/mol'), sigma=(3.758e-10,'m'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=0, comment="""Epsilon & sigma estimated with fixed Lennard Jones Parameters. This is the fallback method! Try improving transport databases!"""),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[2.5,0,0,0,0,-745.375,0.928724], Tmin=(200,'K'), Tmax=(1000,'K')), NASAPolynomial(coeffs=[2.5,0,0,0,0,-745.375,0.928724], Tmin=(1000,'K'), Tmax=(6000,'K'))], Tmin=(200,'K'), Tmax=(6000,'K'), E0=(-6.19738,'kJ/mol'), comment="""Thermo library: primaryThermoLibrary"""),
)

species(
    label = 'Ne',
    structure = SMILES('[Ne]'),
    E0 = (-6.19738,'kJ/mol'),
    spinMultiplicity = 1,
    opticalIsomers = 1,
    molecularWeight = (20.1797,'amu'),
    collisionModel = TransportData(shapeIndex=2, epsilon=(1.23553,'kJ/mol'), sigma=(3.758e-10,'m'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=0, comment="""Epsilon & sigma estimated with fixed Lennard Jones Parameters. This is the fallback method! Try improving transport databases!"""),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[2.5,0,0,0,0,-745.375,3.35532], Tmin=(200,'K'), Tmax=(1000,'K')), NASAPolynomial(coeffs=[2.5,0,0,0,0,-745.375,3.35532], Tmin=(1000,'K'), Tmax=(6000,'K'))], Tmin=(200,'K'), Tmax=(6000,'K'), E0=(-6.19738,'kJ/mol'), comment="""Thermo library: primaryThermoLibrary"""),
)

species(
    label = 'N2',
    structure = SMILES('N#N'),
    E0 = (-8.64289,'kJ/mol'),
    spinMultiplicity = 1,
    opticalIsomers = 1,
    molecularWeight = (28.0135,'amu'),
    collisionModel = TransportData(shapeIndex=1, epsilon=(810.913,'J/mol'), sigma=(3.621,'angstroms'), dipoleMoment=(0,'C*m'), polarizability=(1.76,'angstroms^3'), rotrelaxcollnum=4.0, comment="""GRI-Mech"""),
    energyTransferModel = SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85),
    thermo = NASA(polynomials=[NASAPolynomial(coeffs=[3.53101,-0.000123661,-5.02999e-07,2.43531e-09,-1.40881e-12,-1046.98,2.96747], Tmin=(200,'K'), Tmax=(1000,'K')), NASAPolynomial(coeffs=[2.95258,0.0013969,-4.92632e-07,7.8601e-11,-4.60755e-15,-923.949,5.87189], Tmin=(1000,'K'), Tmax=(6000,'K'))], Tmin=(200,'K'), Tmax=(6000,'K'), E0=(-8.64289,'kJ/mol'), comment="""Thermo library: primaryThermoLibrary"""),
)

transitionState(
    label = 'TS1',
    E0 = (451.558,'kJ/mol'),
    spinMultiplicity = 1,
    opticalIsomers = 1,
)

transitionState(
    label = 'TS2',
    E0 = (466.251,'kJ/mol'),
    spinMultiplicity = 1,
    opticalIsomers = 1,
)

transitionState(
    label = 'TS3',
    E0 = (460.953,'kJ/mol'),
    spinMultiplicity = 1,
    opticalIsomers = 1,
)

transitionState(
    label = 'TS4',
    E0 = (279.046,'kJ/mol'),
    spinMultiplicity = 1,
    opticalIsomers = 1,
)

reaction(
    label = 'reaction1',
    reactants = ['CH3CCH2(43)', 'H(4)'],
    products = ['C3H6(50)'],
    transitionState = 'TS1',
    kinetics = Arrhenius(A=(1e+13,'cm^3/(mol*s)'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Estimated using template (Y_rad,H_rad) for rate rule (Cd_rad/NonDe,H_rad)"""),
)

reaction(
    label = 'reaction2',
    reactants = ['CH3CHCH(44)', 'H(4)'],
    products = ['C3H6(50)'],
    transitionState = 'TS2',
    kinetics = Arrhenius(A=(1.21e+14,'cm^3/(mol*s)','+|-',4.82e+13), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), comment="""Exact match found for rate rule (Cd_pri_rad,H_rad)"""),
)

reaction(
    label = 'reaction3',
    reactants = ['C2H4(31)', 'CH2(S)(24)'],
    products = ['C3H6(50)'],
    transitionState = 'TS3',
    kinetics = Arrhenius(A=(5.304e+12,'cm^3/(mol*s)'), n=0.0073, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(250,'K'), Tmax=(2000,'K'), comment="""Exact match found for rate rule (carbene,ethene)
Ea raised from -4.4 to 0 kJ/mol."""),
)

reaction(
    label = 'reaction4',
    reactants = ['[CH2][CH]C(157)'],
    products = ['C3H6(50)'],
    transitionState = 'TS4',
    kinetics = Arrhenius(A=(1.262e+08,'s^-1'), n=0, Ea=(0,'kJ/mol'), T0=(1,'K'), Tmin=(300,'K'), Tmax=(1500,'K'), comment="""Exact match found for rate rule (Y_12_10)"""),
)

network(
    label = '101',
    isomers = [
        'C3H6(50)',
    ],
    reactants = [
    ],
    bathGas = {
        'He': 0.333333,
        'Ne': 0.333333,
        'N2': 0.333333,
    },
)

pressureDependence(
    label = '101',
    Tmin = (350,'K'),
    Tmax = (2000,'K'),
    Tcount = 8,
    Tlist = ([352.796,376.149,428.568,523.972,690.301,976.761,1431.38,1913.34],'K'),
    Pmin = (0.01,'bar'),
    Pmax = (100,'bar'),
    Pcount = 5,
    Plist = ([0.0125282,0.0667467,1,14.982,79.8202],'bar'),
    maximumGrainSize = (0.5,'kcal/mol'),
    minimumGrainCount = 250,
    method = 'modified strong collision',
    interpolationModel = ('Chebyshev', 6, 4),
    activeKRotor = True,
    activeJRotor = True,
    rmgmode = True,
)
```

**Comment by enochd** [comment]
Another issue I just noticed is that RMG decided to assign the smile string of `CH2(S)(24)` as `'C'`, making it look like methane reacts with ethane with no barrier in the generated network pdf. The RMG generated output mechanism does have the correct species corresponding to carbene, however.

**Comment by rwest** [comment]
Please open that SMILES error as a new issue. It's kind of an important one!

**Comment by goldmanm** [comment]
I tried the input file on my side. It worked flawlessly now.
