### ISSUE TITLE
Empty directories in RMG-database/input/kinetics/families/ cause a crash

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#346]
I had an empty (apart from perhaps a hidden file) directory in `RMG-database/input/kinetics/families/` because I'd changed back and forth between branches in my RMG-database, and the missing family caused a crash:

```
Loading the user-specified kinetics families from /Users/rwest/Code/RMG-database/input/kinetics/families
Traceback (most recent call last):
  File "../../../rmg.py", line 147, in <module>
    rmg.execute(args)
  File "/Users/rwest/Code/RMG-Py/rmgpy/rmg/main.py", line 442, in execute
    self.initialize(args)
  File "/Users/rwest/Code/RMG-Py/rmgpy/rmg/main.py", line 357, in initialize
    self.loadDatabase()
  File "/Users/rwest/Code/RMG-Py/rmgpy/rmg/main.py", line 284, in loadDatabase
    depository = False, # Don't bother loading the depository information, as we don't use it
  File "/Users/rwest/Code/RMG-Py/rmgpy/data/rmg.py", line 99, in load
    kineticsDepositories
  File "/Users/rwest/Code/RMG-Py/rmgpy/data/rmg.py", line 159, in loadKinetics
    depositories=kineticsDepositories
  File "/Users/rwest/Code/RMG-Py/rmgpy/data/kinetics/__init__.py", line 107, in load
    self.loadFamilies(os.path.join(path, 'families'), families, depositories)
  File "/Users/rwest/Code/RMG-Py/rmgpy/data/kinetics/__init__.py", line 194, in loadFamilies
    family.load(familyPath, self.local_context, self.global_context, depositoryLabels=depositories)
  File "/Users/rwest/Code/RMG-Py/rmgpy/data/kinetics/family.py", line 536, in load
    Database.load(self.groups, os.path.join(path, 'groups.py'), local_context, global_context)
  File "/Users/rwest/Code/RMG-Py/rmgpy/data/base.py", line 208, in load
    f = open(path, 'r')
IOError: [Errno 2] No such file or directory: '/Users/rwest/Code/RMG-database/input/kinetics/families/Fake_3products2/groups.py'
```

I think it should be more robust than this, or at least give a better error message.

**Comment by enochd** [comment]
Trying to understand what happened here... do you mean that your RMG input file was looking for the family `Fake_3products2`, and could not find it because you switched to a database branch where that family does not exist, and therefore received this error message?

**Comment by rwest** [comment]
It wasn't mentioned in my input file, but the directory existed. I think it looks for all directories in `RMG-database/input/kinetics/families/` and checks that they are explicitly mentioned in the `recommended.py` file. Probably a good safety check, overall. But the error message in this case is confusing.

**Comment by connie** [comment]
Now it looks like making an empty folder there gives the following error:

    raise DatabaseError('Family {0} not found in recommendation list (probably at {1}/recommended.py)'.format(d, path))
    rmgpy.data.base.DatabaseError: Family newfolder not found in recommendation list (probably at /home/connie/Research/Code/RMG-database/input/kinetics/families/recommended.py)

So I am closing this issue.
