### ISSUE TITLE
'make test' is giving ImportErrors

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#357]
On my Mac, I'm getting these import errors.

```...
Test the value of the speed of light in a vacuum. ... ok
Test that nodes can match other nodes. ... ok
Test that the MatchNodeToStructure family works properly. ... ok
Test that the loadFamilies function raises the correct exceptions ... ok
Failure: ImportError (No module named rmgpy) ... ERROR
Failure: ImportError (No module named rmgpy) ... ERROR
Failure: ImportError (No module named rmgpy) ... ERROR
Failure: ImportError (No module named rmgpy) ... ERROR
Test we can estimate solvation thermochemistry. ... ok
Test that for a given solvent viscosity and temperature we can calculate a solute's diffusivity ... ok
Test we can calculate and set the McGowan volume for species containing H,C,O,N or S ... ok
Test we can estimate Abraham solute parameters correctly using group contributions ... ok
...
```

The errors seem to be in the nosetests test loader, so I'm having a hard time figuring out where they are coming from.

```======================================================================
ERROR: Failure: ImportError (No module named rmgpy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 79, in importFromDir
    fh, filename, desc = find_module(part, path)
ImportError: No module named rmgpy

======================================================================
ERROR: Failure: ImportError (No module named rmgpy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 79, in importFromDir
    fh, filename, desc = find_module(part, path)
ImportError: No module named rmgpy

======================================================================
ERROR: Failure: ImportError (No module named rmgpy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 79, in importFromDir
    fh, filename, desc = find_module(part, path)
ImportError: No module named rmgpy

======================================================================
ERROR: Failure: ImportError (No module named rmgpy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 79, in importFromDir
    fh, filename, desc = find_module(part, path)
ImportError: No module named rmgpy
```

Comparing with the Travis log, there are no tests in between
```
Test that the loadFamilies function raises the correct exceptions ... ok
```
and
```
Test we can estimate solvation thermochemistry. ... ok
```

Any ideas?

The $RMGpy folder is on my $PYTHON_PATH and I can `import rmgpy` from any folder.

**Comment by connie** [comment]
There are no tests between 

    Test that the loadFamilies function raises the correct exceptions ... ok

and 

    Test we can estimate solvation thermochemistry. ... ok

for me either.  I think the errors can actually pop up anywhere and be related to other tests and probably doesn't indicate that they are occurring at that particular point.
