### ISSUE TITLE
Failed installation on Mac OSX 10.10.4

### ISSUE THREAD

**Issue by PWstmrlnd** [ReactionMechanismGenerator/RMG-Py#430]
```python
McNinch:RMG phillipwestmoreland$ !l
ls -Fl
total 8
-rw-r--r--@ 1 phillipwestmoreland  staff  921 Aug 18 15:15 input.py
McNinch:RMG phillipwestmoreland$ rmg.py input.py
Traceback (most recent call last):
  File "/Users/phillipwestmoreland/anaconda/bin/rmg.py", line 41, in <module>
    from rmgpy.rmg.main import RMG, initializeLog, processProfileStats, makeProfileGraph
  File "/Users/phillipwestmoreland/anaconda/lib/python2.7/site-packages/rmgpy/rmg/main.py", line 48, in <module>
    from rmgpy.molecule import Molecule
  File "/Users/phillipwestmoreland/anaconda/lib/python2.7/site-packages/rmgpy/molecule/__init__.py", line 31, in <module>
    from .adjlist import *
  File "/Users/phillipwestmoreland/anaconda/lib/python2.7/site-packages/rmgpy/molecule/adjlist.py", line 36, in <module>
    from .molecule import Atom, Bond
  File "rmgpy/molecule/element.pxd", line 27, in init rmgpy.molecule.molecule (rmgpy/molecule/molecule.c:41175)
  File "rmgpy/molecule/element.py", line 44, in init rmgpy.molecule.element (rmgpy/molecule/element.c:5181)
  File "/Users/phillipwestmoreland/anaconda/lib/python2.7/site-packages/rdkit/Chem/__init__.py", line 18, in <module>
    from rdkit import rdBase
ImportError: dlopen(/Users/phillipwestmoreland/anaconda/lib/python2.7/site-packages/rdkit/rdBase.so, 2): Symbol not found: __ZN5boost6python7objects15function_objectERKNS1_11py_functionERKSt4pairIPKNS0_6detail7keywordES9_E
  Referenced from: /Users/phillipwestmoreland/anaconda/lib/python2.7/site-packages/rdkit/rdBase.so
  Expected in: /Users/phillipwestmoreland/anaconda/lib/python2.7/site-packages/rdkit/../../../libboost_python.dylib
```

**Comment by PWstmrlnd** [comment]
Followed instructions from clean conda install, leading
```
$ conda list
# packages in environment at /Users/phillipwestmoreland/anaconda:
#
_license                  1.1                      py27_0  
abstract-rendering        0.5.1                np19py27_0  
alabaster                 0.7.3                    py27_0  
anaconda                  2.3.0                np19py27_0  
appscript                 1.0.1                    py27_0  
argcomplete               0.8.9                    py27_0  
astropy                   1.0.3                np19py27_0  
babel                     1.3                      py27_0  
backports.ssl-match-hostname 3.4.0.2                   <pip>
bcolz                     0.9.0                np19py27_0  
beautiful-soup            4.3.2                    py27_0  
beautifulsoup4            4.3.2                     <pip>
binstar                   0.11.0                   py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.8.0                     <pip>
blaze-core                0.8.0                np19py27_0  
blz                       0.6.2                np19py27_1  
bokeh                     0.9.0                np19py27_0  
boost                     1.57.0                        4  
boto                      2.38.0                   py27_0  
bottleneck                1.0.0                np19py27_0  
bzip2                     1.0.6                         0  
cairo                     1.12.18                       3  
cairocffi                 0.6                      py27_1  
cdecimal                  2.3                      py27_0  
certifi                   14.05.14                 py27_0  
cffi                      1.1.2                    py27_0  
cloog                     0.18.0                        0  
clyent                    0.3.4                    py27_0  
colorama                  0.3.3                    py27_0  
conda                     3.16.0                   py27_0  
conda-build               1.14.1                   py27_0  
conda-env                 2.4.2                    py27_0  
configobj                 5.0.6                    py27_0  
coverage                  3.7.1                    py27_0  
cryptography              0.9.1                    py27_0  
curl                      7.43.0                        0  
cython                    0.21                     py27_1  
cytoolz                   0.7.3                    py27_0  
datashape                 0.4.5                np19py27_0  
decorator                 3.4.2                    py27_0  
docutils                  0.12                     py27_0  
dynd-python               0.6.5                np19py27_0  
eigen                     3.2.1                         0  
enum34                    1.0.4                    py27_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py27_0  
flask                     0.10.1                   py27_1  
fontconfig                2.11.1                   py27_3  
freetype                  2.5.2                         2  
funcsigs                  0.4                      py27_0  
gevent                    1.0.1                    py27_0  
gevent-websocket          0.9.3                    py27_0  
gmp                       5.1.2                         6  
gprof2dot                 2015.02.03               py27_0  
graphviz                  2.38.0                        3  
greenlet                  0.4.7                    py27_0  
grin                      1.2.1                    py27_1  
guppy                     0.1.10                   py27_0  
h5py                      2.5.0                np19py27_3  
hdf5                      1.8.15.1                      1  
icu                       54.1                          0  
idna                      2.0                      py27_0  
ipaddress                 1.0.7                    py27_0  
ipython                   3.2.0                    py27_0  
ipython-notebook          3.2.0                    py27_0  
ipython-qtconsole         3.2.0                    py27_0  
isl                       0.12.2                        1  
itsdangerous              0.24                     py27_0  
jdcal                     1.0                      py27_0  
jedi                      0.8.1                    py27_0  
jinja2                    2.8                      py27_0  
jpeg                      8d                            2  
jsonschema                2.4.0                    py27_0  
launcher                  1.0.0                         3  
libdynd                   0.6.5                         0  
libgcc                    4.8.4                         1  
libpng                    1.6.17                        0  
libsodium                 0.4.5                         0  
libtiff                   4.0.3                         0  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        2  
llvmlite                  0.5.0                    py27_0  
lxml                      3.4.4                    py27_0  
markupsafe                0.23                     py27_0  
matplotlib                1.4.3                np19py27_3  
mistune                   0.5.1                    py27_1  
mock                      1.0.1                    py27_0  
mopac                     2012                          2  
mpc                       1.0.1                         0  
mpfr                      3.1.2                         0  
multipledispatch          0.4.7                    py27_0  
networkx                  1.9.1                    py27_0  
nltk                      3.0.3                np19py27_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py27_0  
numba                     0.19.1               np19py27_0  
numexpr                   2.4.3                np19py27_0  
numpy                     1.9.2                    py27_0  
odo                       0.3.2                np19py27_0  
openbabel                 2.3.2                    py27_4  
openpyxl                  1.8.5                    py27_0  
openssl                   1.0.1k                        1  
pandas                    0.16.2               np19py27_0  
patsy                     0.3.0                np19py27_0  
pep8                      1.6.2                    py27_0  
pillow                    2.8.2                    py27_0  
pip                       7.1.0                    py27_1  
pixman                    0.32.6                        0  
pkg-config                0.28                          1  
ply                       3.6                      py27_0  
psutil                    3.1.1                    py27_0  
ptyprocess                0.4                      py27_0  
py                        1.4.27                   py27_0  
pyasn1                    0.1.7                    py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.1                    py27_0  
pycparser                 2.14                     py27_0  
pycrypto                  2.6.1                    py27_0  
pycurl                    7.19.5.1                 py27_2  
pydas                     0.1.0                np19py27_1  
pydot                     2.0.1                    py27_1  
pydot2                    1.0.32                    <pip>
pydqed                    0.1.0                np19py27_1  
pyflakes                  0.9.2                    py27_0  
pygments                  2.0.2                    py27_0  
pyopenssl                 0.15.1                   py27_1  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.3                   py27_0  
pytables                  3.2.0                np19py27_0  
pytest                    2.7.1                    py27_0  
python                    2.7.10                        0  
python-dateutil           2.4.2                    py27_0  
python.app                1.2                      py27_4  
pytz                      2015.4                   py27_0  
pyyaml                    3.11                     py27_1  
pyzmq                     14.7.0                   py27_0  
qt                        4.8.6                         3  
quantities                0.10.1               np19py27_0  
rdkit                     2014.09.2            np19py27_0  
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.10.3                   py27_0  
requests                  2.7.0                    py27_0  
rmg                       0.1.0                np19py27_3  
rmg-database              0.1.0                     <pip>
rmg-py                    0.1.0                     <pip>
rmgdatabase               0.1.0                    py27_1  
rope                      0.9.4                    py27_1  
runipy                    0.1.3                    py27_0  
scikit-image              0.11.3               np19py27_0  
scikit-learn              0.16.1               np19py27_0  
scipy                     0.16.0               np19py27_1  
setuptools                18.1                     py27_0  
sip                       4.16.5                   py27_0  
six                       1.9.0                    py27_0  
snowballstemmer           1.2.0                    py27_0  
sockjs-tornado            1.0.1                    py27_0  
sphinx                    1.3.1                    py27_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py27_0  
spyder                    2.3.5.2                  py27_0  
spyder-app                2.3.5.2                  py27_0  
sqlalchemy                1.0.5                    py27_0  
sqlite                    3.8.4.1                       1  
ssl_match_hostname        3.4.0.2                  py27_0  
statsmodels               0.6.1                np19py27_0  
symmetry                  1.0.1                         0  
sympy                     0.7.6                    py27_0  
tables                    3.2.0                     <pip>
terminado                 0.5                      py27_0  
tk                        8.5.18                        0  
toolz                     0.7.2                    py27_0  
tornado                   4.2                      py27_0  
ujson                     1.33                     py27_0  
unicodecsv                0.9.4                    py27_0  
werkzeug                  0.10.4                   py27_0  
wheel                     0.24.0                   py27_0  
xlrd                      0.9.3                    py27_0  
xlsxwriter                0.7.3                    py27_0  
xlwings                   0.3.5                    py27_0  
xlwt                      1.0.0                    py27_0  
yaml                      0.1.6                         0  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  
```

**Comment by rwest** [comment]
This is mine which currently works:
```
rwest$ conda list
# packages in environment at /Users/rwest/anaconda/envs/rmg4:
#
alabaster                 0.7.3                    py27_0  
babel                     1.3                      py27_1  
boost                     1.56.0                   py27_1  
bzip2                     1.0.6                         0  
cairo                     1.12.18                       3  
cairocffi                 0.6                      py27_1  
cffi                      1.1.2                    py27_0  
cherrypy                  3.8.0                     <pip>
cloog                     0.18.0                        0  
coverage                  3.7.1                    py27_0  
cython                    0.21                     py27_1  
django                    1.8.2                    py27_0  
docutils                  0.12                     py27_0  
eigen                     3.2.1                         0  
expat                     2.1.0                         0  
fontconfig                2.11.1                   py27_3  
freetype                  2.5.2                         2  
gmp                       5.1.3                         0  
gprof2dot                 2015.02.03               py27_0  
graphviz                  2.38.0                        3  
guppy                     0.1.10                   py27_0  
ipdb                      0.8                      py27_2  
ipython                   3.2.1                    py27_0  
isl                       0.12.2                        1  
jinja2                    2.8                      py27_0  
jpeg                      8d                            2  
libgcc                    4.8.4                         1  
libpng                    1.6.17                        0  
libtiff                   4.0.3                         0  
libxml2                   2.9.2                         1  
libxslt                   1.1.28                        2  
lxml                      3.4.4                    py27_0  
markupsafe                0.23                     py27_0  
matplotlib                1.4.3                np19py27_3  
mopac                     2012                          1  
mpc                       1.0.1                         0  
mpfr                      3.1.2                         0  
ncurses                   5.9                           1  
nose                      1.3.7                    py27_0  
numpy                     1.9.2                    py27_0  
openbabel                 2.3.2                    py27_4  
openssl                   1.0.1k                        1  
pip                       7.1.0                    py27_1  
pixman                    0.32.6                        0  
pkg-config                0.28                          1  
psutil                    2.2.1                    py27_0  
pycparser                 2.14                     py27_0  
pydas                     0.1.0                np19py27_1  
pydot                     2.0.1                    py27_1  
pydot2                    1.0.32                    <pip>
pydqed                    0.1.0                np19py27_1  
pygments                  2.0.2                    py27_0  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.3                   py27_0  
python                    2.7.10                        0  
python-dateutil           2.4.2                    py27_0  
python.app                1.2                      py27_4  
pytz                      2015.4                   py27_0  
qt                        4.8.6                         3  
quantities                0.10.1               np19py27_0  
rdkit                     2015.03.1            np19py27_0  
readline                  6.2.5                         1  
scipy                     0.15.1               np19py27_0  
setuptools                18.1                     py27_0  
sip                       4.16.5                   py27_0  
six                       1.9.0                    py27_0  
snowballstemmer           1.2.0                    py27_0  
sphinx                    1.3.1                    py27_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py27_0  
sqlite                    3.8.4.1                       1  
symmetry                  1.0.1                         0  
tk                        8.5.18                        0  
wheel                     0.24.0                   py27_0  
xlwt                      1.0.0                    py27_0  
yapf                      0.2.3                     <pip>
zlib                      1.2.8                         1 
```

**Comment by PWstmrlnd** [comment]
Fixed as follows:
```
$ conda install -c rdkit rdkit
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment /Users/phillipwestmoreland/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    boost-1.56.0               |           py27_1        11.5 MB
    rdkit-2015.03.1            |       np19py27_0        15.6 MB
    ------------------------------------------------------------
                                           Total:        27.1 MB

The following packages will be UPDATED:

    rdkit: 2014.09.2-np19py27_0 --> 2015.03.1-np19py27_0

The following packages will be DOWNGRADED:

    boost: 1.57.0-4             --> 1.56.0-py27_1       

Proceed ([y]/n)? y

Fetching packages ...
boost-1.56.0-p 100% |##########################################################################################################| Time: 0:00:00  15.83 MB/s
rdkit-2015.03. 100% |##########################################################################################################| Time: 0:00:01  14.30 MB/s
Extracting packages ...
[      COMPLETE      ]|#############################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#############################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#############################################################################################################################| 100%
McNinch:RMG phillipwestmoreland$ conda list
# packages in environment at /Users/phillipwestmoreland/anaconda:
#
_license                  1.1                      py27_0  
abstract-rendering        0.5.1                np19py27_0  
alabaster                 0.7.3                    py27_0  
anaconda                  2.3.0                np19py27_0  
appscript                 1.0.1                    py27_0  
argcomplete               0.8.9                    py27_0  
astropy                   1.0.3                np19py27_0  
babel                     1.3                      py27_0  
backports.ssl-match-hostname 3.4.0.2                   <pip>
bcolz                     0.9.0                np19py27_0  
beautiful-soup            4.3.2                    py27_0  
beautifulsoup4            4.3.2                     <pip>
binstar                   0.11.0                   py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.8.0                     <pip>
blaze-core                0.8.0                np19py27_0  
blz                       0.6.2                np19py27_1  
bokeh                     0.9.0                np19py27_0  
boost                     1.56.0                   py27_1  
boto                      2.38.0                   py27_0  
bottleneck                1.0.0                np19py27_0  
bzip2                     1.0.6                         0  
cairo                     1.12.18                       3  
cairocffi                 0.6                      py27_1  
cdecimal                  2.3                      py27_0  
certifi                   14.05.14                 py27_0  
cffi                      1.1.2                    py27_0  
cloog                     0.18.0                        0  
clyent                    0.3.4                    py27_0  
colorama                  0.3.3                    py27_0  
conda                     3.16.0                   py27_0  
conda-build               1.14.1                   py27_0  
conda-env                 2.4.2                    py27_0  
configobj                 5.0.6                    py27_0  
coverage                  3.7.1                    py27_0  
cryptography              0.9.1                    py27_0  
curl                      7.43.0                        0  
cython                    0.21                     py27_1  
cytoolz                   0.7.3                    py27_0  
datashape                 0.4.5                np19py27_0  
decorator                 3.4.2                    py27_0  
docutils                  0.12                     py27_0  
dynd-python               0.6.5                np19py27_0  
eigen                     3.2.1                         0  
enum34                    1.0.4                    py27_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py27_0  
flask                     0.10.1                   py27_1  
fontconfig                2.11.1                   py27_3  
freetype                  2.5.2                         2  
funcsigs                  0.4                      py27_0  
gevent                    1.0.1                    py27_0  
gevent-websocket          0.9.3                    py27_0  
gmp                       5.1.2                         6  
gprof2dot                 2015.02.03               py27_0  
graphviz                  2.38.0                        3  
greenlet                  0.4.7                    py27_0  
grin                      1.2.1                    py27_1  
guppy                     0.1.10                   py27_0  
h5py                      2.5.0                np19py27_3  
hdf5                      1.8.15.1                      1  
icu                       54.1                          0  
idna                      2.0                      py27_0  
ipaddress                 1.0.7                    py27_0  
ipython                   3.2.0                    py27_0  
ipython-notebook          3.2.0                    py27_0  
ipython-qtconsole         3.2.0                    py27_0  
isl                       0.12.2                        1  
itsdangerous              0.24                     py27_0  
jdcal                     1.0                      py27_0  
jedi                      0.8.1                    py27_0  
jinja2                    2.8                      py27_0  
jpeg                      8d                            2  
jsonschema                2.4.0                    py27_0  
launcher                  1.0.0                         3  
libdynd                   0.6.5                         0  
libgcc                    4.8.4                         1  
libpng                    1.6.17                        0  
libsodium                 0.4.5                         0  
libtiff                   4.0.3                         0  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        2  
llvmlite                  0.5.0                    py27_0  
lxml                      3.4.4                    py27_0  
markupsafe                0.23                     py27_0  
matplotlib                1.4.3                np19py27_3  
mistune                   0.5.1                    py27_1  
mock                      1.0.1                    py27_0  
mopac                     2012                          2  
mpc                       1.0.1                         0  
mpfr                      3.1.2                         0  
multipledispatch          0.4.7                    py27_0  
networkx                  1.9.1                    py27_0  
nltk                      3.0.3                np19py27_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py27_0  
numba                     0.19.1               np19py27_0  
numexpr                   2.4.3                np19py27_0  
numpy                     1.9.2                    py27_0  
odo                       0.3.2                np19py27_0  
openbabel                 2.3.2                    py27_4  
openpyxl                  1.8.5                    py27_0  
openssl                   1.0.1k                        1  
pandas                    0.16.2               np19py27_0  
patsy                     0.3.0                np19py27_0  
pep8                      1.6.2                    py27_0  
pillow                    2.8.2                    py27_0  
pip                       7.1.0                    py27_1  
pixman                    0.32.6                        0  
pkg-config                0.28                          1  
ply                       3.6                      py27_0  
psutil                    3.1.1                    py27_0  
ptyprocess                0.4                      py27_0  
py                        1.4.27                   py27_0  
pyasn1                    0.1.7                    py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.1                    py27_0  
pycparser                 2.14                     py27_0  
pycrypto                  2.6.1                    py27_0  
pycurl                    7.19.5.1                 py27_2  
pydas                     0.1.0                np19py27_1  
pydot                     2.0.1                    py27_1  
pydot2                    1.0.32                    <pip>
pydqed                    0.1.0                np19py27_1  
pyflakes                  0.9.2                    py27_0  
pygments                  2.0.2                    py27_0  
pyopenssl                 0.15.1                   py27_1  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.3                   py27_0  
pytables                  3.2.0                np19py27_0  
pytest                    2.7.1                    py27_0  
python                    2.7.10                        0  
python-dateutil           2.4.2                    py27_0  
python.app                1.2                      py27_4  
pytz                      2015.4                   py27_0  
pyyaml                    3.11                     py27_1  
pyzmq                     14.7.0                   py27_0  
qt                        4.8.6                         3  
quantities                0.10.1               np19py27_0  
rdkit                     2015.03.1            np19py27_0  
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.10.3                   py27_0  
requests                  2.7.0                    py27_0  
rmg                       0.1.0                np19py27_3  
rmg-database              0.1.0                     <pip>
rmg-py                    0.1.0                     <pip>
rmgdatabase               0.1.0                    py27_1  
rope                      0.9.4                    py27_1  
runipy                    0.1.3                    py27_0  
scikit-image              0.11.3               np19py27_0  
scikit-learn              0.16.1               np19py27_0  
scipy                     0.16.0               np19py27_1  
setuptools                18.1                     py27_0  
sip                       4.16.5                   py27_0  
six                       1.9.0                    py27_0  
snowballstemmer           1.2.0                    py27_0  
sockjs-tornado            1.0.1                    py27_0  
sphinx                    1.3.1                    py27_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py27_0  
spyder                    2.3.5.2                  py27_0  
spyder-app                2.3.5.2                  py27_0  
sqlalchemy                1.0.5                    py27_0  
sqlite                    3.8.4.1                       1  
ssl_match_hostname        3.4.0.2                  py27_0  
statsmodels               0.6.1                np19py27_0  
symmetry                  1.0.1                         0  
sympy                     0.7.6                    py27_0  
tables                    3.2.0                     <pip>
terminado                 0.5                      py27_0  
tk                        8.5.18                        0  
toolz                     0.7.2                    py27_0  
tornado                   4.2                      py27_0  
ujson                     1.33                     py27_0  
unicodecsv                0.9.4                    py27_0  
werkzeug                  0.10.4                   py27_0  
wheel                     0.24.0                   py27_0  
xlrd                      0.9.3                    py27_0  
xlsxwriter                0.7.3                    py27_0  
xlwings                   0.3.5                    py27_0  
xlwt                      1.0.0                    py27_0  
yaml                      0.1.6                         0  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  
```

**Comment by rwest** [comment]
Comparing the lists above, I think @PWstmrlnd's "clean" conda install was on top of a "dirty" system Python, with an old (half) installation of RMG and RDKit in it.
I'm not sure if there's a way we can recommend to install conda so that it doesn't use the system packages at all? One option would be to force users to put RMG in its own conda environment which they have to activate to use RMG - that would ensure there were no other conflicts. Might be the cleanest thing to advise. Advanced users can always do their own thing and resolve their own conflicts.

One alternative solution to this precise problem (may not prevent all future problems) may be to change the requirements for RMG-Py to be the `2015.03.1` version of RDKit.

**Comment by connie** [comment]
I believe we do advise people to use and create a new 'rmg' environment in conda.  I imagine the issue is that the rmg conda environment `~/anaconda/envs/rmg/bin` is appended to `PATH`, but there are remnants of other things on `PATH` and `PYTHONPATH`.  Maybe we could suggest some sort of lines inside a `.bash_rmg` to wipe off other things in those variables and to source just prior to running a job?

    export PATH=~/anaconda/envs/rmg/bin
    export PYTHONPATH=$RMGPy:$PATH_TO_RMG_DATABASE

I believe rdkit package found on rmg channel is the `2015.03.1` version.  But yes, I think we should require it in the conda build and environment scripts.

**Comment by rwest** [comment]
> I believe we do advise people to use and create a new 'rmg' environment in conda
not in the "Binary Installation Using Anaconda: For Basic Users"
http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaUser.html
