### ISSUE TITLE
Generate Reactions Script Broken

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#523]
The `generateReactions.py` script is broken because the `ChemkinWriter()` and `OutputHTMLWriter()` require an argument for the `outputDirectory`.  We probably need unit tests to run the scripts regularly to catch these types of minor errors.

```
Traceback (most recent call last):
  File "/home/connie/Research/Code/RMG-Py/scripts/generateReactions.py", line 46, in <module>
    main()
  File "/home/connie/Research/Code/RMG-Py/scripts/generateReactions.py", line 43, in main
    generate_reactions.main()
  File "/home/connie/Research/Code/RMG-Py/rmgpy/tools/generate_reactions.py", line 123, in main
    rmg.attach(ChemkinWriter())
TypeError: __init__() takes exactly 2 arguments (1 given)
```

edit: I see that there are some unit tests already, but not of the form of running the example in the example folder....

**Comment by connie** [comment]
Appears to be working on master, but requires a fix to save to output html.
