### ISSUE TITLE
jinja2 error in saveOutputHTML

### ISSUE THREAD

**Issue by sherman-sc** [ReactionMechanismGenerator/RMG-Py#539]
```python
Traceback (most recent call last):
  File "/home/sherman.sc/Code/RMG-Py/rmg.py", line 155, in <module>
    cProfile.runctx(command, global_vars, local_vars, stats_file)
  File "/shared/apps/python/Python-2.7.5/INSTALL/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/shared/apps/python/Python-2.7.5/INSTALL/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/home/sherman.sc/Code/RMG-Py/rmgpy/rmg/main.py", line 712, in execute
    self.saveEverything()
  File "/home/sherman.sc/Code/RMG-Py/rmgpy/rmg/main.py", line 787, in saveEverything
    self.notify()
  File "/home/sherman.sc/Code/RMG-Py/rmgpy/util.py", line 106, in notify
    observer.update(self)
  File "/home/sherman.sc/Code/RMG-Py/rmgpy/rmg/output.py", line 1331, in update
    saveOutput(rmg)
  File "/home/sherman.sc/Code/RMG-Py/rmgpy/rmg/output.py", line 1299, in saveOutput
    saveOutputHTML(os.path.join(rmg.outputDirectory, 'output.html'), rmg.reactionModel, 'core')
  File "/home/sherman.sc/Code/RMG-Py/rmgpy/rmg/output.py", line 516, in saveOutputHTML
    f.write(template.render(title=title, species=species, reactions=reactions, families=families, familyCount=familyCount, getSpeciesIdentifier=getSpeciesIdentifier,textwrap=textwrap))
  File "/shared/apps/python/Python-2.7.5/INSTALL/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/shared/apps/python/Python-2.7.5/INSTALL/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 335, in top-level template code
  File "/home/sherman.sc/Code/RMG-Py/rmgpy/rmg/output.py", line 140, in csssafe
    return to_remove_from_css_names.sub('_',input)
TypeError: expected string or buffer
```

This was running on #537

**Comment by nickvandewiele** [comment]
I can also produce this error. [This line](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/rmg/output.py#L140) crashes when it is trying to filter a line from a Chemkin file containing:

`PDepNetwork #2`

which is located in the comment section of a P-dep reaction, eg:
```
! Reaction index: Chemkin #1; RMG #12
! PDep reaction: PDepNetwork #2
! Flux pairs: CH3(3), ethane(1); CH3(3), ethane(1); 
CH3(3)+CH3(3)(+M)=ethane(1)(+M)                     1.000e+00 0.000     0.000    
    TCHEB/ 300.000   3000.000 /
    PCHEB/ 0.001     98.692   /
    CHEB/ 6 4/
    CHEB/ 1.298e+01    6.224e-01    -1.447e-01   1.776e-02   /
    CHEB/ -1.148e+00   8.424e-01    -1.025e-01   -2.396e-02  /
    CHEB/ -6.621e-01   3.937e-01    2.545e-02    -2.785e-02  /
    CHEB/ -3.217e-01   1.480e-01    4.225e-02    -6.280e-03  /
    CHEB/ -1.547e-01   4.315e-02    2.488e-02    4.196e-03   /
    CHEB/ -7.153e-02   5.351e-03    9.588e-03    4.799e-03   /
```

I was using the `diff_models` functionality that calls the `rmgpy.rmg.output` module and the HTML writers located in there.

**Comment by nickvandewiele** [comment]
These are merely symptoms of the real issue here: `rmgpy.rmg.pdep.PdepReaction.getSource()` returns a `rmgpy.rmg.pdep.PDepNetwork` object whereas the regex pattern searcher can only accept a string or a buffer.

**Comment by connie** [comment]
@sherman-sc can you let us know if this resolves the issue for you?

**Comment by sherman-sc** [comment]
Hi,

Unfortunately this did not solve the issue. I tried running the job again
with generateOutputHTML=True , but the job crashed immediately again with
this error message:

  File "/home/sherman.sc/Code/RMG-Py/rmg.py", line 155, in <module>
    cProfile.runctx(command, global_vars, local_vars, stats_file)
  File
"/shared/apps/python/Python-2.7.5/INSTALL/lib/python2.7/cProfile.py", line
49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File
"/shared/apps/python/Python-2.7.5/INSTALL/lib/python2.7/cProfile.py", line
140, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/home/sherman.sc/Code/RMG-Py/rmgpy/rmg/main.py", line 712, in
execute
    self.saveEverything()
  File "/home/sherman.sc/Code/RMG-Py/rmgpy/rmg/main.py", line 787, in
saveEverything
    self.notify()
  File "/home/sherman.sc/Code/RMG-Py/rmgpy/util.py", line 106, in notify
    observer.update(self)
  File "/home/sherman.sc/Code/RMG-Py/rmgpy/rmg/output.py", line 1331, in
update
    saveOutput(rmg)
  File "/home/sherman.sc/Code/RMG-Py/rmgpy/rmg/output.py", line 1299, in
saveOutput
    saveOutputHTML(os.path.join(rmg.outputDirectory, 'output.html'),
rmg.reactionModel, 'core')
  File "/home/sherman.sc/Code/RMG-Py/rmgpy/rmg/output.py", line 516, in
saveOutputHTML
    f.write(template.render(title=title, species=species,
reactions=reactions, families=families, familyCount=familyCount,
getSpeciesIdentifier=getSpeciesIdentifier,textwrap=textwrap))
  File
"/shared/apps/python/Python-2.7.5/INSTALL/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/environment.py",
line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File
"/shared/apps/python/Python-2.7.5/INSTALL/lib/python2.7/site-packages/Jinja2-2.7.3-py2.7.egg/jinja2/environment.py",
line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 335, in top-level template code
  File "/home/sherman.sc/Code/RMG-Py/rmgpy/rmg/output.py", line 140, in
csssafe
    return to_remove_from_css_names.sub('_',input)
TypeError: expected string or buffer


Thanks,
Scott Sherman

**Comment by rwest** [comment]
@sherman-sc, just checking that you merged this fix correctly and recompiled RMG before testing? Not trivial in your case, because you were on the `enlargeReactionFilter` branch...

**Comment by sherman-sc** [comment]
Sorry. I do not think that I did merge the fix correctly. I will try again.

**Comment by rwest** [comment]
Looks like @connie has rebased `enlargeReactionFilter` so it includes this fix, which makes your like easier. So it should be something like
```
cd $RMGPy
git fetch origin
git checkout origin/enlargeReactionFilter
make
```
But check there were no errors at each stage.

**Comment by sherman-sc** [comment]
I fixed RMG and ran the job again. It has successfully saved the HTML
without crashing!

Scott
