### ISSUE TITLE
make test fails on mac: rmgpy.scoop_framework.utilTest.BroadcastTest could not start server

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#555]
```
$  cd $RMGpy
$  conda env create -n rmg5
$  source activate rmg5
$  make clean
$  make -j3
$  make test
```

dies thus:

```
======================================================================
ERROR: test suite for <class 'rmgpy.scoop_framework.utilTest.BroadcastTest'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rwest/anaconda/envs/rmg5/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/Users/rwest/anaconda/envs/rmg5/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/Users/rwest/anaconda/envs/rmg5/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/Users/rwest/anaconda/envs/rmg5/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/rwest/Code/RMG-Py/rmgpy/scoop_framework/framework.py", line 99, in setUpClass
    raise Exception('Could not start server!')
Exception: Could not start server!
```

```
$ conda list
# packages in environment at /Users/rwest/anaconda/envs/rmg5:
#
boost                     1.56.0                   py27_3    rdkit
bzip2                     1.0.6                         0    defaults
cairo                     1.12.18                       3    https://conda.binstar.org/rmg/osx-64/cairo-1.12.18-3.tar.bz2
cairocffi                 0.6                      py27_1    file:///Users/rwest/anaconda/conda-bld/osx-64/cairocffi-0.6-py27_1.tar.bz2
cffi                      1.2.1                    py27_0    defaults
coverage                  4.0                      py27_0    defaults
cycler                    0.9.0                    py27_0    defaults
cython                    0.21                     py27_1    defaults
eigen                     3.2.1                         0    https://conda.binstar.org/rmg/osx-64/eigen-3.2.1-0.tar.bz2
expat                     2.1.0                         0    https://conda.binstar.org/rwest/osx-64/expat-2.1.0-0.tar.bz2
fontconfig                2.11.1                        4    rmg
freetype                  2.5.5                         0    defaults
gprof2dot                 2015.02.03               py27_0    file:///Users/rwest/anaconda/conda-bld/osx-64/gprof2dot-2015.02.03-py27_0.tar.bz2
graphviz                  2.38.0                        3    https://conda.binstar.org/asmeurer/osx-64/graphviz-2.38.0-3.tar.bz2
greenlet                  0.4.9                    py27_0    defaults
guppy                     0.1.10                   py27_0    file:///Users/rwest/anaconda/conda-bld/osx-64/guppy-0.1.10-py27_0.tar.bz2
jbig                      2.1                           0    defaults
jinja2                    2.8                      py27_0    defaults
jpeg                      8d                            2    https://conda.binstar.org/asmeurer/osx-64/jpeg-8d-2.tar.bz2
libgcc                    4.8.5                         1    defaults
libpng                    1.6.17                        0    https://conda.binstar.org/asmeurer/osx-64/libpng-1.6.17-0.tar.bz2
libtiff                   4.0.6                         1    defaults
libxml2                   2.9.2                         0    defaults
markupsafe                0.23                     py27_0    <unknown>
matplotlib                1.5.1               np110py27_0    defaults
mopac                     2012                          2    file:///Users/rwest/anaconda/conda-bld/osx-64/mopac-2012-2.tar.bz2
nose                      1.3.7                    py27_0    defaults
numpy                     1.10.2                   py27_0    defaults
openbabel                 2.3.2                    py27_4    file:///Users/rwest/anaconda/conda-bld/osx-64/openbabel-2.3.2-py27_4.tar.bz2
openssl                   1.0.2f                        0    defaults
pip                       8.0.1                    py27_0    defaults
pixman                    0.32.6                        0    file:///Users/rwest/anaconda/conda-bld/osx-64/pixman-0.32.6-0.tar.bz2
pkg-config                0.28                          1    https://conda.binstar.org/asmeurer/osx-64/pkg-config-0.28-1.tar.bz2
psutil                    3.4.2                    py27_0    defaults
pycparser                 2.14                     py27_0    defaults
pydas                     1.0.2                    py27_0    rmg
pydot                     2.0.1                    py27_1    file:///Users/rwest/anaconda/conda-bld/osx-64/pydot-2.0.1-py27_1.tar.bz2
pydot2                    1.0.32                    <pip>
pydqed                    1.0.1                    py27_0    rmg
pyparsing                 2.0.3                    py27_0    <unknown>
pyqt                      4.11.4                   py27_1    defaults
python                    2.7.11                        0    defaults
python-dateutil           2.4.2                    py27_0    defaults
pytz                      2015.7                   py27_0    defaults
pyzmq                     15.2.0                   py27_0    defaults
qt                        4.8.7                         1    defaults
quantities                0.11.1                   py27_0    rmg
rdkit                     2015.09.2           np110py27_0    rmg
readline                  6.2                           2    <unknown>
scipy                     0.16.1              np110py27_0    defaults
scoop                     0.7                      py27_0    rmg
setuptools                19.4                     py27_0    defaults
sip                       4.16.9                   py27_0    defaults
six                       1.10.0                   py27_0    defaults
sqlite                    3.9.2                         0    defaults
symmetry                  1.0.1                         0    file:///Users/rwest/anaconda/conda-bld/osx-64/symmetry-1.0.1-0.tar.bz2
tk                        8.5.18                        0    <unknown>
wheel                     0.26.0                   py27_1    defaults
xlwt                      1.0.0                    py27_0    defaults
xz                        5.0.5                         0    defaults
zlib                      1.2.8                         0    <unknown>
```

**Comment by connie** [comment]
This issue persists for me as well.  It is something to do with ZMQ and address already being in use.  It is an error only for Mac

**Comment by nickvandewiele** [comment]
I agree, I cannot reproduce this error on linux machines.

**Comment by connie** [comment]
Detailed traceback

```
Traceback (most recent call last):
  File "/Users/connie/anaconda/envs/rmg_env/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/connie/anaconda/envs/rmg_env/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/connie/anaconda/envs/rmg_env/lib/python2.7/site-packages/scoop-0.7.2.0-py2.7.egg/scoop/broker/__main__.py", line 84, in <module>
  File "/Users/connie/anaconda/envs/rmg_env/lib/python2.7/site-packages/scoop-0.7.2.0-py2.7.egg/scoop/broker/brokerzmq.py", line 84, in __init__
  File "zmq/backend/cython/socket.pyx", line 489, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:4824)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7055)
zmq.error.ZMQError: Address already in use
..
======================================================================
ERROR: test suite for <class 'rmgpy.scoop_framework.utilTest.BroadcastTest'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/connie/anaconda/envs/rmg_env/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/Users/connie/anaconda/envs/rmg_env/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/Users/connie/anaconda/envs/rmg_env/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/Users/connie/anaconda/envs/rmg_env/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/Users/connie/code/RMG-Py/rmgpy/scoop_framework/framework.py", line 99, in setUpClass
    raise Exception('Could not start server!')
Exception: Could not start server!

----------------------------------------------------------------------
Ran 2 tests in 3.320s

FAILED (errors=1)
```

**Comment by JacksonBurns** [comment]
This issue is stale (Python 2.7 (!!)) and will not be worked on.
