### ISSUE TITLE
Make eg2 crashes with InvalidMicrocanonicalRateError

### ISSUE THREAD

**Issue by rwest** [ReactionMechanismGenerator/RMG-Py#557]
For me it gets this far
```
After model enlargement:
    The model core has 9 species and 1 reactions
    The model edge has 124 species and 157 reactions


Saving current model core to Chemkin file...
Chemkin file contains 1 reactions.
Saving current model to verbose Chemkin file...
Chemkin file contains 1 reactions.
Not saving restart file in this iteration.
Saving the QM generated thermo to qmThermoLibrary.py ...
Updating RMG execution statistics...
    Execution time (DD:HH:MM:SS): 00:00:06:46
    Memory used: 259.56 MB

Conducting simulation of reaction system 1...
At time 2.3889e-18 s, PDepNetwork #5 exceeded the minimum rate for exploring
    Characteristic rate: 6.8512e+02 mol/m^3*s
    [H](9) rate: 9.3264e-01 mol/m^3*s (0.001361)
    PDepNetwork #5 leak rate: 3.7016e+08 mol/m^3*s (5.403e+05)
    HXD13(1) conversion: 1.554e-13 
At time 2.3889e-18 s, PDepNetwork #5 exceeded the minimum rate for simulation interruption
    Characteristic rate: 6.8512e+02 mol/m^3*s
    [H](9) rate: 9.3264e-01 mol/m^3*s (0.001361)
    PDepNetwork #5 leak rate: 3.7016e+08 mol/m^3*s (5.403e+05)
    HXD13(1) conversion: 1.554e-13 


Exploring isomer C=C[CH]C(CC)C([CH]CC)C=C(31) in pressure-dependent network #5
```
then after many many warnings it ends up 
```python
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "C=C[CH]C(CC)C([CH]CC)C=C(31) <=> [CH2]C=C[C](CC)C(C=C)CCC(147)".
Warning: For path reaction C=C[CH]C(CC)C([CH]CC)C=C(31) <=> C=CC([CH]CC)[C](C=CC)CC(153):
Warning:     Expected kf(1896.74 K) = 10.3682
Warning:       Actual kf(1896.74 K) = 3.25373
Warning:     Expected Keq(1896.74 K) = 0.650192
Warning:       Actual Keq(1896.74 K) = 0
Error: Invalid k(E) values computed for path reaction "C=C[CH]C(CC)C([CH]CC)C=C(31) <=> C=CC([CH]CC)[C](C=CC)CC(153)".
Error: Increasing number of grains did not decrease error enough (Current badness: 0.5, previous 0.5). Something must be wrong with network 5
Traceback (most recent call last):
  File "rmg.py", line 155, in <module>
    cProfile.runctx(command, global_vars, local_vars, stats_file)
  File "/Users/rwest/anaconda/envs/rmg5/lib/python2.7/cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "/Users/rwest/anaconda/envs/rmg5/lib/python2.7/cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/Users/rwest/Code/RMG-Py/rmgpy/rmg/main.py", line 610, in execute
    self.reactionModel.enlarge(objectToEnlarge)
  File "/Users/rwest/Code/RMG-Py/rmgpy/rmg/model.py", line 806, in enlarge
    self.updateUnimolecularReactionNetworks(database)
  File "/Users/rwest/Code/RMG-Py/rmgpy/rmg/model.py", line 1596, in updateUnimolecularReactionNetworks
    network.update(self, database, self.pressureDependence)
  File "/Users/rwest/Code/RMG-Py/rmgpy/rmg/pdep.py", line 555, in update
    K = self.calculateRateCoefficients(Tlist, Plist, method)
  File "/Users/rwest/Code/RMG-Py/rmgpy/pdep/network.py", line 210, in calculateRateCoefficients
    self.setConditions(T, P)
  File "/Users/rwest/Code/RMG-Py/rmgpy/pdep/network.py", line 325, in setConditions
    raise error
InvalidMicrocanonicalRateError
make: *** [eg2] Error 1
```

Running with mopac on a mac.

**Comment by connie** [comment]
Lol this error has been in existence since the beginning of time.

**Comment by rwest** [comment]
Sorry. Should have just bumped #224. Would still be nice to give people a working example!
