### ISSUE TITLE
numpy.dtype has wrong size for conda daspk binary?

### ISSUE THREAD

**Issue by cfgoldsmith** [ReactionMechanismGenerator/RMG-Py#568]
Trying to install RMG-Py on Mac OS X
```
python -c "from pydas import daspk"


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "__init__.pxd", line 155, in init pydas.daspk (pydas/daspk.c:10326)
ValueError: numpy.dtype has the wrong size, try recompiling
```

With this environment:
```
$ conda list
# packages in environment at /Users/claudefranklingoldsmith/anaconda/envs/rmg_env:
#
backports.ssl-match-hostname 3.4.0.2                   <pip>
boost                     1.56.0                   py27_3    rmg
bzip2                     1.0.6                         0    defaults
cairo                     1.12.18                       3    rmg
cairocffi                 0.6                      py27_1    rmg
cffi                      1.2.1                    py27_0    defaults
coverage                  4.0                      py27_0    defaults
cycler                    0.9.0                    py27_0    defaults
cython                    0.21                     py27_1    defaults
eigen                     3.2.1                         0    rmg
expat                     2.1.0                         0    rmg
fontconfig                2.11.1                        4    rmg
freetype                  2.5.5                         0    defaults
gnureadline               6.3.3                     <pip>
gprof2dot                 2015.02.03               py27_0    rmg
graphviz                  2.38.0                        3    rmg
greenlet                  0.4.9                    py27_0    defaults
guppy                     0.1.10                   py27_0    rmg
ipython                   2.1.0                     <pip>
jbig                      2.1                           0    defaults
jinja2                    2.8                      py27_0    defaults
jpeg                      8d                            2    rmg
libgcc                    4.8.5                         1    defaults
libpng                    1.6.17                        0    <unknown>
libtiff                   4.0.6                         1    defaults
libxml2                   2.9.2                         0    <unknown>
markupsafe                0.23                     py27_0    <unknown>
matplotlib                1.5.1               np110py27_0    defaults
mkl                       11.3.1                        0    defaults
mock                      1.0.1                     <pip>
mopac                     2012                          2    rmg
nose                      1.3.7                    py27_0    <unknown>
numpy                     1.10.4                   py27_0    defaults
openbabel                 2.3.2                    py27_4    rmg
openssl                   1.0.2f                        0    defaults
pip                       8.0.2                    py27_0    defaults
pixman                    0.32.6                        0    rmg
pkg-config                0.28                          1    rmg
psutil                    3.4.2                    py27_0    defaults
pycparser                 2.14                     py27_0    <unknown>
pydas                     1.0.2                    py27_0    rmg
pydot                     2.0.1                    py27_1    rmg
pydot2                    1.0.32                    <pip>
pydqed                    1.0.1                    py27_0    rmg
pyparsing                 2.0.3                    py27_0    defaults
pyqt                      4.11.4                   py27_1    defaults
python                    2.7.11                        0    defaults
python-dateutil           2.4.2                    py27_0    <unknown>
pytz                      2015.7                   py27_0    defaults
pyzmq                     15.2.0                   py27_0    defaults
qt                        4.8.7                         1    defaults
quantities                0.11.1                   py27_0    rmg
rdkit                     2015.09.2           np110py27_0    rmg
readline                  6.2                           2    <unknown>
scipy                     0.17.0              np110py27_0    defaults
scoop                     0.7                      py27_0    rmg
setuptools                19.6.2                   py27_0    defaults
sip                       4.16.9                   py27_0    defaults
six                       1.10.0                   py27_0    defaults
sqlite                    3.9.2                         0    defaults
stevedore                 0.15                      <pip>
symmetry                  1.0.1                         0    rmg
tk                        8.5.18                        0    <unknown>
tornado                   3.2.2                     <pip>
virtualenv                1.11.6                    <pip>
virtualenv-clone          0.2.5                     <pip>
virtualenvwrapper         4.3                       <pip>
wheel                     0.29.0                   py27_0    defaults
wsgiref                   0.1.2                     <pip>
xlwt                      1.0.0                    py27_0    <unknown>
xz                        5.0.5                         0    defaults
zlib                      1.2.8                         0    <unknown>
```

**Comment by cfgoldsmith** [comment]
I just deleted anaconda entirely and installed from scratch. Same thing.

**Comment by connie** [comment]
Odd... the numpy version is 1.10 and the pydas is 1.0.2 so they should be matching up.  
Is there any chance that you might have pydas located elsewhere?  Can you please see what shows up with the following commands:

```
$PYTHONPATH
```

```
source activate rmg_env
python -c "import numpy; print numpy.__version__; print numpy.__file__"
python -c "import pydas; print pydas.__version__; print pydas.__file__"
```

**Comment by cfgoldsmith** [comment]
Hi Connie.

$PYTHONPATH
-bash: :/Users/claudefranklingoldsmith/code/RMG-Py/: No such file or directory

python -c "import numpy; print numpy.__version__; print numpy.__file__"
1.10.4
/Users/claudefranklingoldsmith/anaconda/envs/rmg_env/lib/python2.7/site-packages/numpy/__init__.pyc
python -c "import pydas; print pydas.__version__; print pydas.__file__"
1.0.2
/Users/claudefranklingoldsmith/anaconda/envs/rmg_env/lib/python2.7/site-packages/pydas/__init__.pyc

Oddly enough, I just did another clean sweep and install, and now pydas works. I cannot for the life of me see what I did differently this time...

**Comment by connie** [comment]
Very odd indeed, but glad that you have fixed it!

**Comment by alongd** [comment]
I get the same thing now, only on Pharos:
```
Traceback (most recent call last):
  File "/home/alongd/ws/RMG-Py/rmg.py", line 41, in <module>
    from rmgpy.rmg.main import RMG, initializeLog, processProfileStats, makeProfileGraph
  File "/home/alongd/ws/RMG-Py/rmgpy/rmg/main.py", line 45, in <module>
    from rmgpy.constraints import failsSpeciesConstraints
  File "/home/alongd/ws/RMG-Py/rmgpy/constraints.py", line 33, in <module>
    from rmgpy.species import Species
  File "__init__.pxd", line 155, in init rmgpy.species (build/pyrex/rmgpy/species.c:17806)
ValueError: numpy.dtype has the wrong size, try recompiling
```

That's basically the entire job.log file, RMG won't execute jobs.
I of course tried to recompile, and even went to the 1.0.3 version (already had it as a branch), and recompiled (`make clean`; `make`).
No matter what, the error persists.

**Comment by alongd** [comment]
I used an outdated command in the submit file (`source /opt/venv_rmg/bin/activate`).
The error is now gone (using `source activate rmg_env`).
Thanks @nickvandewiele !
