### ISSUE TITLE
Problematic unit tests on old windows 64-bit machine

### ISSUE THREAD

**Issue by connie** [ReactionMechanismGenerator/RMG-Py#573]
Installed RMG-Py on Bill's computer and these errors showed up, which look similar to https://github.com/ReactionMechanismGenerator/RMG-Py/issues/567

```

======================================================================
ERROR: testC3H4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 214, in testC3H4
    mol = self.compare(inchi, u_indices)
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 21, in compare
    mol = fromAugmentedInChI(Molecule(), aug_inchi)
  File "rmgpy\molecule\parser.py", line 254, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6648)
    def fromAugmentedInChI(mol, aug_inchi):
  File "rmgpy\molecule\parser.py", line 276, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6519)
    fix(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 656, in rmgpy.molecule.parser.fix (build\Release\pyrex\rmgpy\molecule\parser.c:13351)
    fix_unsaturated_bond(mol, u_indices, aug_inchi)
  File "rmgpy\molecule\parser.py", line 855, in rmgpy.molecule.parser.fix_unsaturated_bond (build\Release\pyrex\rmgpy\molecule\parser.c:16561)
    raise Exception( 'Cannot correct {} based on {} by converting unsaturated bonds into unpaired electrons...'\
Exception: Cannot correct multiplicity 3
1 C u2 p0 c0 {3,S} {4,S}
2 C u1 p-1 c0 {3,D} {5,S} {6,S}
3 C u0 p0 c0 {1,S} {2,D} {7,S}
4 H u0 p0 c0 {1,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {3,S}
 based on C3H4/c1-3-2/h1,3H,2H2/u1,1 by converting unsaturated bonds into unpaired electrons...

======================================================================
ERROR: testC5H6O (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 123, in testC5H6O
    self.compare(inchi, u_indices)
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 21, in compare
    mol = fromAugmentedInChI(Molecule(), aug_inchi)
  File "rmgpy\molecule\parser.py", line 254, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6648)
    def fromAugmentedInChI(mol, aug_inchi):
  File "rmgpy\molecule\parser.py", line 276, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6519)
    fix(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 656, in rmgpy.molecule.parser.fix (build\Release\pyrex\rmgpy\molecule\parser.c:13351)
    fix_unsaturated_bond(mol, u_indices, aug_inchi)
  File "rmgpy\molecule\parser.py", line 855, in rmgpy.molecule.parser.fix_unsaturated_bond (build\Release\pyrex\rmgpy\molecule\parser.c:16561)
    raise Exception( 'Cannot correct {} based on {} by converting unsaturated bonds into unpaired electrons...'\
Exception: Cannot correct multiplicity 3
1  C u0 p0 c0 {2,S} {3,D} {7,S}
2  C u1 p0 c0 {1,S} {4,S} {8,S}
3  C u1 p-1 c0 {1,D} {5,S} {9,S}
4  C u0 p0 c0 {2,S} {5,S} {10,S} {11,S}
5  C u0 p0 c0 {3,S} {4,S} {6,S} {12,S}
6  O u1 p2 c0 {5,S}
7  H u0 p0 c0 {1,S}
8  H u0 p0 c0 {2,S}
9  H u0 p0 c0 {3,S}
10 H u0 p0 c0 {4,S}
11 H u0 p0 c0 {4,S}
12 H u0 p0 c0 {5,S}
 based on C5H6O/c6-5-3-1-2-4-5/h1-3,5H,4H2/u2,6 by converting unsaturated bonds into unpaired electrons...

======================================================================
ERROR: testQuadriRadicalDoubleBondZwitterMult5 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 113, in testQuadriRadicalDoubleBondZwitterMult5
    mol = self.compare(inchi, u_indices)
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 21, in compare
    mol = fromAugmentedInChI(Molecule(), aug_inchi)
  File "rmgpy\molecule\parser.py", line 254, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6648)
    def fromAugmentedInChI(mol, aug_inchi):
  File "rmgpy\molecule\parser.py", line 276, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6519)
    fix(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 658, in rmgpy.molecule.parser.fix (build\Release\pyrex\rmgpy\molecule\parser.c:13365)
    check(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 180, in rmgpy.molecule.parser.check (build\Release\pyrex\rmgpy\molecule\parser.c:4704)
    ConsistencyChecker.check_partial_charge(at)
  File "E:\Code\RMG-Py\rmgpy\molecule\adjlist.py", line 113, in check_partial_charge
    .format(symbol=atom.symbol, radicals=atom.radicalElectrons, lonePairs=atom.lonePairs, charge=atom.charge))
InvalidAdjacencyListError: Invalid valency for atom C with 1 unpaired electrons, -1 pairs of electrons, and 1 charge.

======================================================================
ERROR: testTriRadicalZwitterMult4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 98, in testTriRadicalZwitterMult4
    self.compare(inchi, u_indices)
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 21, in compare
    mol = fromAugmentedInChI(Molecule(), aug_inchi)
  File "rmgpy\molecule\parser.py", line 254, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6648)
    def fromAugmentedInChI(mol, aug_inchi):
  File "rmgpy\molecule\parser.py", line 276, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6519)
    fix(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 658, in rmgpy.molecule.parser.fix (build\Release\pyrex\rmgpy\molecule\parser.c:13365)
    check(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 180, in rmgpy.molecule.parser.check (build\Release\pyrex\rmgpy\molecule\parser.c:4704)
    ConsistencyChecker.check_partial_charge(at)
  File "E:\Code\RMG-Py\rmgpy\molecule\adjlist.py", line 113, in check_partial_charge
    .format(symbol=atom.symbol, radicals=atom.radicalElectrons, lonePairs=atom.lonePairs, charge=atom.charge))
InvalidAdjacencyListError: Invalid valency for atom C with 1 unpaired electrons, -1 pairs of electrons, and 1 charge.

======================================================================
ERROR: test_C3H2 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 261, in test_C3H2
    self.compare(inchi, u_indices)
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 21, in compare
    mol = fromAugmentedInChI(Molecule(), aug_inchi)
  File "rmgpy\molecule\parser.py", line 254, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6648)
    def fromAugmentedInChI(mol, aug_inchi):
  File "rmgpy\molecule\parser.py", line 276, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6519)
    fix(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 658, in rmgpy.molecule.parser.fix (build\Release\pyrex\rmgpy\molecule\parser.c:13365)
    check(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 180, in rmgpy.molecule.parser.check (build\Release\pyrex\rmgpy\molecule\parser.c:4704)
    ConsistencyChecker.check_partial_charge(at)
  File "E:\Code\RMG-Py\rmgpy\molecule\adjlist.py", line 113, in check_partial_charge
    .format(symbol=atom.symbol, radicals=atom.radicalElectrons, lonePairs=atom.lonePairs, charge=atom.charge))
InvalidAdjacencyListError: Invalid valency for atom C with 2 unpaired electrons, -1 pairs of electrons, and 0 charge.

======================================================================
ERROR: test_C3H4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 266, in test_C3H4
    self.compare(inchi, u_indices)
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 21, in compare
    mol = fromAugmentedInChI(Molecule(), aug_inchi)
  File "rmgpy\molecule\parser.py", line 254, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6648)
    def fromAugmentedInChI(mol, aug_inchi):
  File "rmgpy\molecule\parser.py", line 276, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6519)
    fix(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 656, in rmgpy.molecule.parser.fix (build\Release\pyrex\rmgpy\molecule\parser.c:13351)
    fix_unsaturated_bond(mol, u_indices, aug_inchi)
  File "rmgpy\molecule\parser.py", line 855, in rmgpy.molecule.parser.fix_unsaturated_bond (build\Release\pyrex\rmgpy\molecule\parser.c:16561)
    raise Exception( 'Cannot correct {} based on {} by converting unsaturated bonds into unpaired electrons...'\
Exception: Cannot correct multiplicity 3
1 C u2 p0 c0 {3,S} {4,S}
2 C u1 p-1 c0 {3,D} {5,S} {6,S}
3 C u0 p0 c0 {1,S} {2,D} {7,S}
4 H u0 p0 c0 {1,S}
5 H u0 p0 c0 {2,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {3,S}
 based on C3H4/c1-3-2/h1,3H,2H2/u1,1 by converting unsaturated bonds into unpaired electrons...

======================================================================
ERROR: test_C3H4O4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 239, in test_C3H4O4
    self.compare(inchi, u_indices)
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 21, in compare
    mol = fromAugmentedInChI(Molecule(), aug_inchi)
  File "rmgpy\molecule\parser.py", line 254, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6648)
    def fromAugmentedInChI(mol, aug_inchi):
  File "rmgpy\molecule\parser.py", line 276, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6519)
    fix(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 656, in rmgpy.molecule.parser.fix (build\Release\pyrex\rmgpy\molecule\parser.c:13351)
    fix_unsaturated_bond(mol, u_indices, aug_inchi)
  File "rmgpy\molecule\parser.py", line 855, in rmgpy.molecule.parser.fix_unsaturated_bond (build\Release\pyrex\rmgpy\molecule\parser.c:16561)
    raise Exception( 'Cannot correct {} based on {} by converting unsaturated bonds into unpaired electrons...'\
Exception: Cannot correct multiplicity 3
1  C u1 p-1 c0 {2,D} {3,S} {8,S}
2  C u0 p0 c0 {1,D} {7,S} {9,S}
3  C u0 p0 c0 {1,S} {4,S} {5,S} {10,S}
4  O u1 p2 c0 {3,S}
5  O u1 p2 c0 {3,S}
6  O u0 p2 c0 {7,S} {11,S}
7  O u0 p2 c0 {2,S} {6,S}
8  H u0 p0 c0 {1,S}
9  H u0 p0 c0 {2,S}
10 H u0 p0 c0 {3,S}
11 H u0 p0 c0 {6,S}
 based on C3H4O4/c4-3(5)1-2-7-6/h1-3,6H/u4,5 by converting unsaturated bonds into unpaired electrons...

======================================================================
ERROR: test_C3H6_biradical_parsing (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 68, in test_C3H6_biradical_parsing
    self.compare(inchi, u_indices)
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 21, in compare
    mol = fromAugmentedInChI(Molecule(), aug_inchi)
  File "rmgpy\molecule\parser.py", line 254, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6648)
    def fromAugmentedInChI(mol, aug_inchi):
  File "rmgpy\molecule\parser.py", line 276, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6519)
    fix(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 658, in rmgpy.molecule.parser.fix (build\Release\pyrex\rmgpy\molecule\parser.c:13365)
    check(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 180, in rmgpy.molecule.parser.check (build\Release\pyrex\rmgpy\molecule\parser.c:4704)
    ConsistencyChecker.check_partial_charge(at)
  File "E:\Code\RMG-Py\rmgpy\molecule\adjlist.py", line 113, in check_partial_charge
    .format(symbol=atom.symbol, radicals=atom.radicalElectrons, lonePairs=atom.lonePairs, charge=atom.charge))
InvalidAdjacencyListError: Invalid valency for atom C with 1 unpaired electrons, -1 pairs of electrons, and 1 charge.

======================================================================
ERROR: test_C6H6O4 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 244, in test_C6H6O4
    self.compare(inchi, u_indices)
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 21, in compare
    mol = fromAugmentedInChI(Molecule(), aug_inchi)
  File "rmgpy\molecule\parser.py", line 254, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6648)
    def fromAugmentedInChI(mol, aug_inchi):
  File "rmgpy\molecule\parser.py", line 276, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6519)
    fix(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 658, in rmgpy.molecule.parser.fix (build\Release\pyrex\rmgpy\molecule\parser.c:13365)
    check(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 180, in rmgpy.molecule.parser.check (build\Release\pyrex\rmgpy\molecule\parser.c:4704)
    ConsistencyChecker.check_partial_charge(at)
  File "E:\Code\RMG-Py\rmgpy\molecule\adjlist.py", line 113, in check_partial_charge
    .format(symbol=atom.symbol, radicals=atom.radicalElectrons, lonePairs=atom.lonePairs, charge=atom.charge))
InvalidAdjacencyListError: Invalid valency for atom C with 1 unpaired electrons, -1 pairs of electrons, and 1 charge.

======================================================================
ERROR: test_C6H6O6 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 256, in test_C6H6O6
    self.compare(inchi, u_indices)
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 21, in compare
    mol = fromAugmentedInChI(Molecule(), aug_inchi)
  File "rmgpy\molecule\parser.py", line 254, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6648)
    def fromAugmentedInChI(mol, aug_inchi):
  File "rmgpy\molecule\parser.py", line 276, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6519)
    fix(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 658, in rmgpy.molecule.parser.fix (build\Release\pyrex\rmgpy\molecule\parser.c:13365)
    check(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 180, in rmgpy.molecule.parser.check (build\Release\pyrex\rmgpy\molecule\parser.c:4704)
    ConsistencyChecker.check_partial_charge(at)
  File "E:\Code\RMG-Py\rmgpy\molecule\adjlist.py", line 113, in check_partial_charge
    .format(symbol=atom.symbol, radicals=atom.radicalElectrons, lonePairs=atom.lonePairs, charge=atom.charge))
InvalidAdjacencyListError: Invalid valency for atom C with 1 unpaired electrons, -1 pairs of electrons, and 1 charge.

======================================================================
ERROR: test_C6H8O2 (rmgpy.molecule.inchiparsingTest.InChIParsingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 219, in test_C6H8O2
    self.compare(inchi, u_indices)
  File "E:\Code\RMG-Py\rmgpy\molecule\inchiparsingTest.py", line 21, in compare
    mol = fromAugmentedInChI(Molecule(), aug_inchi)
  File "rmgpy\molecule\parser.py", line 254, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6648)
    def fromAugmentedInChI(mol, aug_inchi):
  File "rmgpy\molecule\parser.py", line 276, in rmgpy.molecule.parser.fromAugmentedInChI (build\Release\pyrex\rmgpy\molecule\parser.c:6519)
    fix(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 658, in rmgpy.molecule.parser.fix (build\Release\pyrex\rmgpy\molecule\parser.c:13365)
    check(mol, aug_inchi)
  File "rmgpy\molecule\parser.py", line 180, in rmgpy.molecule.parser.check (build\Release\pyrex\rmgpy\molecule\parser.c:4704)
    ConsistencyChecker.check_partial_charge(at)
  File "E:\Code\RMG-Py\rmgpy\molecule\adjlist.py", line 113, in check_partial_charge
    .format(symbol=atom.symbol, radicals=atom.radicalElectrons, lonePairs=atom.lonePairs, charge=atom.charge))
InvalidAdjacencyListError: Invalid valency for atom C with 1 unpaired electrons, -1 pairs of electrons, and 1 charge.
```

I guess this might bean openbabel issue?

**Comment by JacksonBurns** [comment]
Windows no longer supported for source installs. Closing.
