### ISSUE TITLE
NetworkError: Unexpected type of path reaction

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#577]
Running RMG-Py with PDep for ethylamine oxidation, I get these NetwokErrors, for example:

```
  File "/home/alongd/ws/RMG-Py/rmgpy/pdep/network.py", line 569, in calculateMicrocanonicalRates
    raise NetworkError('Unexpected type of path reaction "{0}"'.format(rxn))
rmgpy.pdep.network.NetworkError: Unexpected type of path reaction "HCNH(263) + CH3(10) <=> CH3CHNH(294)"
```

or

```
  File "/home/alongd/ws/RMG-Py/rmgpy/pdep/network.py", line 569, in calculateMicrocanonicalRates
    raise NetworkError('Unexpected type of path reaction "{0}"'.format(rxn))
rmgpy.pdep.network.NetworkError: Unexpected type of path reaction "CC(=NC=[CH])[N](12189) <=> N1([C](C)[N])C=C1(12483)"
```

Seems to be similar to an error reported by @rwest in issue #41, quite some time ago, but could also have a different cause.

**Comment by bslakman** [comment]
Hi @alongd, do you have an input file that produces this error?

**Comment by alongd** [comment]
Yes, but the input file also used non-common libraries. I tried to reproduce this error with a minimal input file (so sorry for taking long to response), but only the original library combination resulted in that error.
The reactions RMG crashed on are not present in these libs.

If it's any help, here are the original input file ([input.py](https://github.com/ReactionMechanismGenerator/RMG-Py/files/192231/input.py.txt)), and libraries:
https://github.com/alongd/RMG-database/blob/nitrogen/input/thermo/libraries/1Cu4.py
https://github.com/alongd/RMG-database/blob/nitrogen/input/thermo/libraries/EA.py
https://github.com/alongd/RMG-database/tree/nitrogen/input/kinetics/libraries/A20

**Comment by alongd** [comment]
I get simulations crashing with the "Unexpected type of path reaction" error, e.g.:
```
rmgpy.pdep.network.NetworkError: Unexpected type of path reaction "[CH2][CH2](103) + CO2(30) <=> [CH2]CO[C]=O(4145)"
```
```
rmgpy.pdep.network.NetworkError: Unexpected type of path reaction "[CH2]CC([O])=O(4145) <=> [O]C1([O])CC1(4663)"
```
```
rmgpy.pdep.network.NetworkError: Unexpected type of path reaction "[CH2][CH2](103) + CO2(30) <=> [CH2]CC([O])=O(4145)"
```

This time, though, no unique libraries were used.

[xa1442.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/456915/xa1442.txt)

**Comment by alongd** [comment]
I got the following trace (also reported in [RMG-database issue 150](https://github.com/ReactionMechanismGenerator/RMG-database/issues/150)):
```
Traceback (most recent call last):
  File "C:\Code\RMG-Py/rmg.py", line 152, in <module>
    rmg.execute(**kwargs)
  File "C:\Code\RMG-Py\rmgpy\rmg\main.py", line 603, in execute
    self.reactionModel.enlarge(objectToEnlarge)
  File "C:\Code\RMG-Py\rmgpy\rmg\model.py", line 675, in enlarge
    self.updateUnimolecularReactionNetworks()
  File "C:\Code\RMG-Py\rmgpy\rmg\model.py", line 1471, in updateUnimolecularReactionNetworks
    network.update(self, self.pressureDependence)
  File "C:\Code\RMG-Py\rmgpy\rmg\pdep.py", line 561, in update
    K = self.calculateRateCoefficients(Tlist, Plist, method)
  File "C:\Code\RMG-Py\rmgpy\pdep\network.py", line 210, in calculateRateCoefficients
    self.setConditions(T, P)
  File "C:\Code\RMG-Py\rmgpy\pdep\network.py", line 317, in setConditions
    self.calculateMicrocanonicalRates()
  File "C:\Code\RMG-Py\rmgpy\pdep\network.py", line 569, in calculateMicrocanonicalRates
    raise NetworkError('Unexpected type of path reaction "{0}"'.format(rxn))
rmgpy.pdep.network.NetworkError: Unexpected type of path reaction "HNCO(74) + H(5) <=> C(=N)[O](180)"
```

For an association reaction, RMG runs the following in [network.py](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/pdep/network.py#L560):
```python
elif rxn.reactants in reactants and rxn.products[0] in isomers:
                # Association (reversible)
                reac = reactants.index(rxn.reactants) + Nisom
prod = isomers.index(rxn.products[0])
```
In this case, `rxn.products` are:
```
[[Species(index=30, label="NHCHOj", thermo=..., molecule=[Molecule(SMILES="C(=N)[O]")]...],
[Species(index=5, label="H", thermo..., molecule=[Molecule(SMILES="[H]")]..., 
Species(index=279, label="[C](=N)[O]", thermo=..., molecule=[Molecule(SMILES="[C](=N)[O]")]...],
[Species(index=5, label="H", thermo=..., molecule=[Molecule(SMILES="[H]")]...,
Species(index=146, label="C(=[N])[O]", thermo=..., molecule=[Molecule(SMILES="C(=[N])[O]")]...],
[Species(index=329, label="[CH]1NO1", thermo=..., molecule=[Molecule(SMILES="[CH]1NO1")]...],
[Species(index=282, label="[C](=N)O", thermo=..., molecule=[Molecule(SMILES="[C](=N)O")]...],
[Species(index=91, label="NCHOH", thermo=..., molecule=[Molecule(SMILES="C(=[N])O")]...]]`
```
Hence rxn.products[0] is `[Species(index=30, label="NHCHOj", thermo=..., molecule=[Molecule(SMILES="C(=N)[O]")]...]`.

While `isomers` is `[Species(index=290, label="C(=O)[NH]", thermo..., molecule=[Molecule(SMILES="C(=N)[O]")]...]`

`rxn.products[0]` and `isomers` have the same SMILES, but a different index (and label), which implies they are different species (?). Anyway, the `in` operator is not expected to give `TRUE` here.

The entire data for further troubleshooting is here:
```
isomers = [Species(index=290, label="C(=O)[NH]", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[3.68205,0.000897464,3.08569e-05,-3.75657e-08,1.32629e-11,-412.022,7.55169], Tmin=(100,'K'), Tmax=(1012.13,'K')), NASAPolynomial(coeffs=[5.88602,0.00817627,-3.62651e-06,7.55717e-10,-5.7883e-14,-1677.13,-7.15347], Tmin=(1012.13,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(-3.56536,'kJ/mol'), Cp0=(33.2579,'J/(mol*K)'), CpInf=(128.874,'J/(mol*K)'), comment="""Thermo library: thermo_DFT_CCSDTF12_BAC + radical(RC=COJ)"""), conformer=Conformer(E0=(-3.56536,'kJ/mol'), modes=[HarmonicOscillator(frequencies=([180,828.409,1302.06,1302.56,1304.21,1304.76,1305,1305.29,1305.78],'cm^-1'))], spinMultiplicity=2), molecule=[Molecule(SMILES="C(=N)[O]")], molecularWeight=(44.0327,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85))]
reactants = [[Species(index=5, label="H", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[2.5,-1.06333e-12,1.30802e-15,-5.21436e-19,6.38303e-23,25472.7,-0.454534], Tmin=(100,'K'), Tmax=(4950.76,'K')), NASAPolynomial(coeffs=[2.77499,-0.000212693,6.15681e-08,-7.90365e-12,3.79566e-16,25188.8,-2.23281], Tmin=(4950.76,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(211.792,'kJ/mol'), Cp0=(20.7862,'J/(mol*K)'), CpInf=(20.7862,'J/(mol*K)'), comment="""Thermo library: KlippensteinH2O2"""), conformer=Conformer(E0=(211.792,'kJ/mol'), modes=[]), molecule=[Molecule(SMILES="[H]")], transportData=TransportData(shapeIndex=0, epsilon=(1205.6,'J/mol'), sigma=(2.05,'angstroms'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=0.0, comment="""GRI-Mech"""), molecularWeight=(1.00794,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85)), Species(index=29, label="HNCO", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[3.65571,0.00533511,4.7649e-06,-9.42245e-09,3.79379e-12,-15401.4,6.14085], Tmin=(100,'K'), Tmax=(995.317,'K')), NASAPolynomial(coeffs=[5.30104,0.00413837,-1.59306e-06,3.02765e-10,-2.2043e-14,-15997.2,-3.13674], Tmin=(995.317,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(-128.174,'kJ/mol'), Cp0=(33.2579,'J/(mol*K)'), CpInf=(83.1447,'J/(mol*K)'), comment="""Thermo library: thermo_DFT_CCSDTF12_BAC"""), conformer=Conformer(E0=(-128.174,'kJ/mol'), modes=[HarmonicOscillator(frequencies=([210.859,1028.81,1031.23,1032.28,1991.49,4000],'cm^-1'))]), molecule=[Molecule(SMILES="N=C=O")], transportData=TransportData(shapeIndex=2, epsilon=(1932.29,'J/mol'), sigma=(3.828,'angstroms'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=1.0, comment="""GRI-Mech"""), molecularWeight=(43.0248,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85))], [Species(index=6, label="O", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[2.5,-1.06333e-12,1.30802e-15,-5.21436e-19,6.38303e-23,29246.9,5.1312], Tmin=(100,'K'), Tmax=(4950.76,'K')), NASAPolynomial(coeffs=[2.77499,-0.000212693,6.15681e-08,-7.90365e-12,3.79566e-16,28962.9,3.35293], Tmin=(4950.76,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(243.172,'kJ/mol'), Cp0=(20.7862,'J/(mol*K)'), CpInf=(20.7862,'J/(mol*K)'), comment="""Thermo library: KlippensteinH2O2"""), conformer=Conformer(E0=(243.172,'kJ/mol'), modes=[]), molecule=[Molecule(SMILES="[O]")], transportData=TransportData(shapeIndex=0, epsilon=(665.16,'J/mol'), sigma=(2.75,'angstroms'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=0.0, comment="""GRI-Mech"""), molecularWeight=(15.9994,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85)), Species(index=71, label="HCNH", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[3.91146,-0.000903511,1.85396e-05,-2.16945e-08,7.80063e-12,33904.9,4.88429], Tmin=(100,'K'), Tmax=(958.181,'K')), NASAPolynomial(coeffs=[4.35402,0.00459159,-1.55739e-06,2.85796e-10,-2.09031e-14,33483.1,1.00922], Tmin=(958.181,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(281.854,'kJ/mol'), Cp0=(33.2579,'J/(mol*K)'), CpInf=(83.1447,'J/(mol*K)'), comment="""Thermo library: thermo_DFT_CCSDTF12_BAC"""), conformer=Conformer(E0=(281.854,'kJ/mol'), modes=[HarmonicOscillator(frequencies=([3120,650,792.5,1650,1457.73,3027.44],'cm^-1'))], spinMultiplicity=2), molecule=[Molecule(SMILES="[CH]=N")], transportData=TransportData(shapeIndex=2, epsilon=(920.412,'J/mol'), sigma=(4.443e-10,'m'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=0, comment="""Epsilon & sigma estimated with fixed Lennard Jones Parameters. This is the fallback method! Try improving transport databases!"""), molecularWeight=(28.0333,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85))]]
products = [[Species(index=30, label="NHCHOj", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[3.68205,0.000897464,3.08569e-05,-3.75657e-08,1.32629e-11,-412.022,7.55169], Tmin=(100,'K'), Tmax=(1012.13,'K')), NASAPolynomial(coeffs=[5.88602,0.00817627,-3.62651e-06,7.55717e-10,-5.7883e-14,-1677.13,-7.15347], Tmin=(1012.13,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(-3.56536,'kJ/mol'), Cp0=(33.2579,'J/(mol*K)'), CpInf=(128.874,'J/(mol*K)'), comment="""Thermo library: thermo_DFT_CCSDTF12_BAC + radical(RC=COJ)"""), conformer=Conformer(E0=(-3.56536,'kJ/mol'), modes=[HarmonicOscillator(frequencies=([180,828.409,1302.06,1302.56,1304.21,1304.76,1305,1305.29,1305.78],'cm^-1'))], spinMultiplicity=2), molecule=[Molecule(SMILES="C(=N)[O]")], molecularWeight=(44.0327,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85))], [Species(index=5, label="H", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[2.5,-1.06333e-12,1.30802e-15,-5.21436e-19,6.38303e-23,25472.7,-0.454534], Tmin=(100,'K'), Tmax=(4950.76,'K')), NASAPolynomial(coeffs=[2.77499,-0.000212693,6.15681e-08,-7.90365e-12,3.79566e-16,25188.8,-2.23281], Tmin=(4950.76,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(211.792,'kJ/mol'), Cp0=(20.7862,'J/(mol*K)'), CpInf=(20.7862,'J/(mol*K)'), comment="""Thermo library: KlippensteinH2O2"""), conformer=Conformer(E0=(211.792,'kJ/mol'), modes=[]), molecule=[Molecule(SMILES="[H]")], transportData=TransportData(shapeIndex=0, epsilon=(1205.6,'J/mol'), sigma=(2.05,'angstroms'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=0.0, comment="""GRI-Mech"""), molecularWeight=(1.00794,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85)), Species(index=279, label="[C](=N)[O]", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[3.60487,0.00449237,1.39109e-05,-1.98005e-08,7.18811e-12,29307.4,8.22731], Tmin=(100,'K'), Tmax=(1045.41,'K')), NASAPolynomial(coeffs=[6.2686,0.00510961,-2.48434e-06,5.45414e-10,-4.26315e-14,28159.8,-7.56699], Tmin=(1045.41,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(243.527,'kJ/mol'), Cp0=(33.2579,'J/(mol*K)'), CpInf=(128.874,'J/(mol*K)'), comment="""Thermo library: thermo_DFT_CCSDTF12_BAC + radical(RC=COJ) + radical(Cds_P)"""), conformer=Conformer(E0=(243.527,'kJ/mol'), modes=[HarmonicOscillator(frequencies=([893.12,893.122,893.125,893.166,893.177,893.185],'cm^-1'))], spinMultiplicity=3), molecule=[Molecule(SMILES="[C](=N)[O]")], molecularWeight=(43.0248,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85))], [Species(index=5, label="H", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[2.5,-1.06333e-12,1.30802e-15,-5.21436e-19,6.38303e-23,25472.7,-0.454534], Tmin=(100,'K'), Tmax=(4950.76,'K')), NASAPolynomial(coeffs=[2.77499,-0.000212693,6.15681e-08,-7.90365e-12,3.79566e-16,25188.8,-2.23281], Tmin=(4950.76,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(211.792,'kJ/mol'), Cp0=(20.7862,'J/(mol*K)'), CpInf=(20.7862,'J/(mol*K)'), comment="""Thermo library: KlippensteinH2O2"""), conformer=Conformer(E0=(211.792,'kJ/mol'), modes=[]), molecule=[Molecule(SMILES="[H]")], transportData=TransportData(shapeIndex=0, epsilon=(1205.6,'J/mol'), sigma=(2.05,'angstroms'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=0.0, comment="""GRI-Mech"""), molecularWeight=(1.00794,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85)), Species(index=146, label="C(=[N])[O]", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[3.72155,0.00163417,2.03676e-05,-2.52683e-08,8.81705e-12,24270.1,8.78658], Tmin=(100,'K'), Tmax=(1041.84,'K')), NASAPolynomial(coeffs=[5.78988,0.00570279,-2.78137e-06,6.08972e-10,-4.75024e-14,23187.3,-4.40474], Tmin=(1041.84,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(201.677,'kJ/mol'), Cp0=(33.2579,'J/(mol*K)'), CpInf=(128.874,'J/(mol*K)'), comment="""Thermo library: thermo_DFT_CCSDTF12_BAC + radical(Cs_P) + radical(RC=COJ)"""), conformer=Conformer(E0=(201.677,'kJ/mol'), modes=[HarmonicOscillator(frequencies=([965.417,965.604,965.605,965.727,965.769,965.944],'cm^-1'))], spinMultiplicity=3), molecule=[Molecule(SMILES="C(=[N])[O]")], molecularWeight=(43.0248,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85))], [Species(index=329, label="[CH]1NO1", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[3.78233,-0.00857717,6.7607e-05,-9.34639e-08,3.95209e-11,42863.2,-14.2093], Tmin=(100,'K'), Tmax=(876.327,'K')), NASAPolynomial(coeffs=[11.7052,-0.00918005,7.76929e-06,-1.63564e-09,1.13593e-13,40109.2,-59.1774], Tmin=(876.327,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(356.214,'kJ/mol'), Cp0=(33.2579,'J/(mol*K)'), CpInf=(108.088,'J/(mol*K)'), comment="""Thermo group additivity estimation: group(Cs-CsCsCsCs) + other(R) + group(N3s-CsHOs) + other(R) + group(Os-CsN3s) + other(R) + ring(Ethylene_oxide) + radical(Cs_P)"""), conformer=Conformer(E0=(356.214,'kJ/mol'), modes=[]), molecule=[Molecule(SMILES="[CH]1NO1")], molecularWeight=(44.0327,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85))], [Species(index=282, label="[C](=N)O", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[3.41564,0.00606007,2.17501e-05,-3.32663e-08,1.30699e-11,11184.8,9.15588], Tmin=(100,'K'), Tmax=(980.269,'K')), NASAPolynomial(coeffs=[8.02945,0.00428004,-1.61081e-06,3.60927e-10,-3.0366e-14,9461.18,-17.1887], Tmin=(980.269,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(92.7699,'kJ/mol'), Cp0=(33.2579,'J/(mol*K)'), CpInf=(128.874,'J/(mol*K)'), comment="""Thermo library: thermo_DFT_CCSDTF12_BAC + radical(Cds_P)"""), conformer=Conformer(E0=(92.7699,'kJ/mol'), modes=[HarmonicOscillator(frequencies=([3615,1277.5,1000,681.275,682.267,682.748,683.542,684.904],'cm^-1')), HinderedRotor(inertia=(0.000363544,'amu*angstrom^2'), symmetry=1, barrier=(0.119627,'kJ/mol'), semiclassical=False)], spinMultiplicity=2), molecule=[Molecule(SMILES="[C](=N)O")], transportData=TransportData(shapeIndex=2, epsilon=(1971.36,'J/mol'), sigma=(5.118e-10,'m'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=0, comment="""Epsilon & sigma estimated with fixed Lennard Jones Parameters. This is the fallback method! Try improving transport databases!"""), molecularWeight=(44.0327,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85))], [Species(index=91, label="NCHOH", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[3.53064,0.00322192,2.81355e-05,-3.86403e-08,1.46583e-11,6147.53,9.72115], Tmin=(100,'K'), Tmax=(982.511,'K')), NASAPolynomial(coeffs=[7.55777,0.00486136,-1.90104e-06,4.22889e-10,-3.5105e-14,4485.72,-14.0662], Tmin=(982.511,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(50.9201,'kJ/mol'), Cp0=(33.2579,'J/(mol*K)'), CpInf=(128.874,'J/(mol*K)'), comment="""Thermo library: thermo_DFT_CCSDTF12_BAC + radical(Cs_P)"""), conformer=Conformer(E0=(50.9201,'kJ/mol'), modes=[HarmonicOscillator(frequencies=([3615,1277.5,1000,746.814,746.974,747.547,747.861,747.868],'cm^-1')), HinderedRotor(inertia=(0.000301025,'amu*angstrom^2'), symmetry=1, barrier=(0.119627,'kJ/mol'), semiclassical=False)], spinMultiplicity=2), molecule=[Molecule(SMILES="C(=[N])O")], molecularWeight=(44.0327,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85))]]
rxn.reactants = [Species(index=5, label="H", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[2.5,-1.06333e-12,1.30802e-15,-5.21436e-19,6.38303e-23,25472.7,-0.454534], Tmin=(100,'K'), Tmax=(4950.76,'K')), NASAPolynomial(coeffs=[2.77499,-0.000212693,6.15681e-08,-7.90365e-12,3.79566e-16,25188.8,-2.23281], Tmin=(4950.76,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(211.792,'kJ/mol'), Cp0=(20.7862,'J/(mol*K)'), CpInf=(20.7862,'J/(mol*K)'), comment="""Thermo library: KlippensteinH2O2"""), conformer=Conformer(E0=(211.792,'kJ/mol'), modes=[]), molecule=[Molecule(SMILES="[H]")], transportData=TransportData(shapeIndex=0, epsilon=(1205.6,'J/mol'), sigma=(2.05,'angstroms'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=0.0, comment="""GRI-Mech"""), molecularWeight=(1.00794,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85)), Species(index=29, label="HNCO", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[3.65571,0.00533511,4.7649e-06,-9.42245e-09,3.79379e-12,-15401.4,6.14085], Tmin=(100,'K'), Tmax=(995.317,'K')), NASAPolynomial(coeffs=[5.30104,0.00413837,-1.59306e-06,3.02765e-10,-2.2043e-14,-15997.2,-3.13674], Tmin=(995.317,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(-128.174,'kJ/mol'), Cp0=(33.2579,'J/(mol*K)'), CpInf=(83.1447,'J/(mol*K)'), comment="""Thermo library: thermo_DFT_CCSDTF12_BAC"""), conformer=Conformer(E0=(-128.174,'kJ/mol'), modes=[HarmonicOscillator(frequencies=([210.859,1028.81,1031.23,1032.28,1991.49,4000],'cm^-1'))]), molecule=[Molecule(SMILES="N=C=O")], transportData=TransportData(shapeIndex=2, epsilon=(1932.29,'J/mol'), sigma=(3.828,'angstroms'), dipoleMoment=(0,'C*m'), polarizability=(0,'angstroms^3'), rotrelaxcollnum=1.0, comment="""GRI-Mech"""), molecularWeight=(43.0248,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85))]
rxn.products = [Species(index=30, label="NHCHOj", thermo=NASA(polynomials=[NASAPolynomial(coeffs=[3.68205,0.000897464,3.08569e-05,-3.75657e-08,1.32629e-11,-412.022,7.55169], Tmin=(100,'K'), Tmax=(1012.13,'K')), NASAPolynomial(coeffs=[5.88602,0.00817627,-3.62651e-06,7.55717e-10,-5.7883e-14,-1677.13,-7.15347], Tmin=(1012.13,'K'), Tmax=(5000,'K'))], Tmin=(100,'K'), Tmax=(5000,'K'), E0=(-3.56536,'kJ/mol'), Cp0=(33.2579,'J/(mol*K)'), CpInf=(128.874,'J/(mol*K)'), comment="""Thermo library: thermo_DFT_CCSDTF12_BAC + radical(RC=COJ)"""), conformer=Conformer(E0=(-3.56536,'kJ/mol'), modes=[HarmonicOscillator(frequencies=([180,828.409,1302.06,1302.56,1304.21,1304.76,1305,1305.29,1305.78],'cm^-1'))], spinMultiplicity=2), molecule=[Molecule(SMILES="C(=N)[O]")], molecularWeight=(44.0327,'amu'), energyTransferModel=SingleExponentialDown(alpha0=(3.5886,'kJ/mol'), T0=(300,'K'), n=0.85))]
```

**Comment by bslakman** [comment]
I am not sure if this is the same issue or not, but you might try my fix in #623 .

**Comment by mliu49** [comment]
@alongd, your most recent case seems to be linked to the duplicate species issue previously reported by @rgillis8 (#831). The following occurred right before the error. It seems that the duplicate species were added, then RMG tried to explore a pdep network which had 2 duplicate species, which caused the error.

However, I'm not sure if the prior cases were due to the same issue.

```
Summary of Secondary Model Edge Enlargement
---------------------------------
Added 0 new core species
Created 48 new edge species
    C(=O)[NH](281)
    [C](=N)O(282)
    C(=O)[NH](283)
    C(=O)[NH](284)
    C(=O)[NH](285)
    C(=O)[NH](286)
    C(=O)[NH](287)
    C(=O)[NH](288)
    C(=O)[NH](289)
    C(=O)[NH](290)
    C(=O)[NH](291)
    C(=O)[NH](292)
    C(=O)[NH](293)
    C(=O)[NH](294)
    C(=O)[NH](295)
    C(=O)[NH](296)
    C(=O)[NH](297)
    C(=O)[NH](298)
    C(=O)[NH](299)
    C(=O)[NH](300)
    C(=O)[NH](301)
    C(=O)[NH](302)
    C(=O)[NH](303)
    C(=O)[NH](304)
    C(=O)[NH](305)
    C(=O)[NH](306)
    C(=O)[NH](307)
    C(=O)[NH](308)
    C(=O)[NH](309)
    C(=O)[NH](310)
    C(=O)[NH](311)
    C(=O)[NH](312)
    C(=O)[NH](313)
    C(=O)[NH](314)
    C(=O)[NH](315)
    C(=O)[NH](316)
    C(=O)[NH](317)
    C(=O)[NH](318)
    C(=O)[NH](319)
    C(=O)[NH](320)
    C(=O)[NH](321)
    C(=O)[NH](322)
    C(=O)[NH](323)
    C(=O)[NH](324)
    C(=O)[NH](325)
    [N+](=N)[O-](326)
    C(=O)[NH](327)
    C(=O)[NH](328)
Added 0 new core reactions
Created 166 new edge reactions
```

**Comment by alongd** [comment]
Thanks @mliu49 for spotting that.
Should we add a `checkForExistingSpecies` procedure similar to the one in #644 for all species during the second enlargement step (not only biaromatics)?

**Comment by alongd** [comment]
[`checkForExistingSpecies`](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/90e31340bc95f5e6d68e23dce72706ed5dcdde4f/rmgpy/rmg/model.py#L234) works well, but perhaps it's either not called at the right timing, or the action to remove the redundant species is problematic.

I did manage to catch all redundant species in the model by calling `checkForExistingSpecies` again just before [`printEnlargeSummary`](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/90e31340bc95f5e6d68e23dce72706ed5dcdde4f/rmgpy/rmg/model.py#L692) using the following code:

```python
        # run checkForExistingSpecies again
        for spec1 in self.edge.species[numOldEdgeSpecies:]:
            for mol in spec1.molecule:
                found, spec2 = self.checkForExistingSpecies(mol)
                if found == True:
                    if spec1.index != spec2.index:
                        logging.info("!!! Species {0} isn't new and already exists as species {1}".format(spec1,spec2))
```

It turns out that my model had even more redundant species than thought (the following is a partial list):
```
!!! Species [N+](=N)[O-](203) isn't new and already exists as species HNNO(58)
!!! Species [N+](=N)[O-](203) isn't new and already exists as species HNNO(58)
!!! Species [N+](=N)[O-](254) isn't new and already exists as species HNNO(58)

!!! Species [N+](=N)[O-](262) isn't new and already exists as species HNNO(58)
!!! Species [N+](=N)[O-](262) isn't new and already exists as species HNNO(58)

!!! Species C(=O)[NH](281) isn't new and already exists as species C(=N)[O](180)
!!! Species C(=O)[NH](325) isn't new and already exists as species C(=N)[O](180)
!!! Species [N+](=N)[O-](326) isn't new and already exists as species HNNO(58)
!!! Species [N+](=N)[O-](326) isn't new and already exists as species HNNO(58)
!!! Species C(=O)[NH](327) isn't new and already exists as species C(=N)[O](180)
!!! Species C(=O)[NH](328) isn't new and already exists as species C(=N)[O](180)
```

**Comment by mliu49** [comment]
I figured out the problem! Please see my explanation in issue #831 and the fix in #850.

The input file you gave me converges fairly quickly with the fix.

**Comment by alongd** [comment]
Awesome, thanks!

**Comment by alongd** [comment]
@mliu49 , thanks again, works great!
