### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data' in addGroupThermoData

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#578]
After running for 15 hrs, my sim crushed with the following message:

```

Garbage collector: collected 15188 objects.

Exploring isomer C(=[C]C#C)N=[C]O(28412) in pressure-dependent network #8627
Generating thermodynamics for new species...
Resonance isomer 1 C1(C(=N1)O)[C]=C=[CH] gives H298=688745 J/mol
Resonance isomer 2 C1(C(=N1)O)C#C[CH] gives H298=727029 J/mol
Resonance isomer 3 C1(C(=N1)O)[C]C#C gives H298=747321 J/mol
Resonance isomer 1 C(=N[C]=C=C=[CH])O gives H298=598705 J/mol
Resonance isomer 2 C(=N[C]=[C]C#C)O gives H298=629039 J/mol
Resonance isomer 3 C(=NC#C[C]=[CH])O gives H298=657825 J/mol
Resonance isomer 4 [CH]([N]C#CC#C)O gives H298=695690 J/mol
Resonance isomer 5 [CH](N=C=[C]C#C)O gives H298=743095 J/mol
Resonance isomer 6 [CH](N=C=C=C=[CH])O gives H298=747488 J/mol
Resonance isomer 1 [C](=C)C#CN=[C]O gives H298=657825 J/mol
Resonance isomer 2 C(=C)=C=[C]N=[C]O gives H298=691590 J/mol
Resonance isomer 3 C(=C)=C=C=N[C]O gives H298=849327 J/mol
Resonance isomer 1 C1(=NC=C1[C]=[CH])O gives H298=544230 J/mol
Resonance isomer 2 C1(=C(C=N1)[C]=[CH])O gives H298=587492 J/mol
Resonance isomer 3 C1(=N[CH]C1=C=[CH])O gives H298=613684 J/mol
Resonance isomer 4 C1(=N[CH][C]1C#C)O gives H298=623475 J/mol
Resonance isomer 5 [C]1([C](C=N1)C#C)O gives H298=645901 J/mol
Resonance isomer 6 [C]1(C(=C=[CH])C=N1)O gives H298=651340 J/mol
Resonance isomer 7 C1(=C([CH][N]1)C#C)O gives H298=697364 J/mol
Resonance isomer 8 [C]1(C(=C[N]1)C#C)O gives H298=700962 J/mol
Resonance isomer 1 C1(=NC=C=C1[CH])O gives H298=419295 J/mol
Resonance isomer 2 C1(=NC=[C]C1=[CH])O gives H298=460968 J/mol
Resonance isomer 1 C(=[C]N=[C]O)C#C gives H298=638244 J/mol
Resonance isomer 2 C(=C=N[C]O)C#C gives H298=761254 J/mol
Resonance isomer 1 N(=CO)C=C=C=[C] gives H298=558957 J/mol
Resonance isomer 2 N(=CO)C=[C]C#[C] gives H298=718995 J/mol
Resonance isomer 1 C1(=CN=[C]O)C=[C]1 gives H298=726803 J/mol
Resonance isomer 2 C1(=C=C1)[CH]N=[C]O gives H298=904723 J/mol
Resonance isomer 3 C1(=C=C1)C=N[C]O gives H298=962713 J/mol
Traceback (most recent call last):
  File "/home/alongd/ws/RMG-Py/rmg.py", line 165, in <module>
    rmg.execute(inputFile, output_dir, **kwargs)
  File "/home/alongd/ws/RMG-Py/rmgpy/rmg/main.py", line 566, in execute
    self.reactionModel.enlarge(objectToEnlarge)
  File "/home/alongd/ws/RMG-Py/rmgpy/rmg/model.py", line 750, in enlarge
    spec.generateThermoData(database, quantumMechanics=self.quantumMechanics)
  File "/home/alongd/ws/RMG-Py/rmgpy/rmg/model.py", line 100, in generateThermoData
    thermo0 = database.thermo.getThermoData(self, trainingSet=None, quantumMechanics=quantumMechanics) 
  File "/home/alongd/ws/RMG-Py/rmgpy/data/thermo.py", line 724, in getThermoData
    tdata = self.estimateThermoViaGroupAdditivity(molecule)
  File "/home/alongd/ws/RMG-Py/rmgpy/data/thermo.py", line 999, in estimateThermoViaGroupAdditivity
    thermoData = self.estimateRadicalThermoViaHBI(molecule, self.computeGroupAdditivityThermo)
  File "/home/alongd/ws/RMG-Py/rmgpy/data/thermo.py", line 936, in estimateRadicalThermoViaHBI
    thermoData_sat = stableThermoEstimator(saturatedStruct)
  File "/home/alongd/ws/RMG-Py/rmgpy/data/thermo.py", line 1042, in computeGroupAdditivityThermo
    self.__addGroupThermoData(thermoData, self.groups['group'], molecule, {'*':atom})
  File "/home/alongd/ws/RMG-Py/rmgpy/data/thermo.py", line 1126, in __addGroupThermoData
    while node.data is None and node is not None:
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by connie** [comment]
Unfortunately it is unclear which structure RMG crashed on.  I tried both the first isomer and the last one, and both ran fine. This error is due to a missing node or missing thermo data in the thermoDatabase.groups['group']

You need to identify which molecule it crashes on. Find the suspected molecule using the `thermoEstimator` by modifying the species within `examples/thermoEstimator` until you find the one that crashes.

**Comment by alongd** [comment]
Thanks for the guidance. Two species identified:
```C1(=NC=C1[C]=[CH])O``` gave the error:
```
MOPAC Job: "/home/alongd/runs/test/QMscratch/pm3/IQTMGKLZWMFKLM-UHFFFAOYSA.mop" ended normally on Feb 18, 2016, at 15:09.
MOPAC Job: "/home/alongd/runs/test/QMscratch/pm3/DKMNSVKYBUYVHU-UHFFFAOYSA.mop" ended normally on Feb 18, 2016, at 15:09.
MOPAC Job: "/home/alongd/runs/test/QMscratch/pm3/VTHPMYIYWJBSOP-UHFFFAOYSA.mop" ended normally on Feb 18, 2016, at 15:09.
MOPAC Job: "/home/alongd/runs/test/QMscratch/pm3/GNYPBABFDPZIFZ-UHFFFAOYSA.mop" ended normally on Feb 18, 2016, at 15:09.
   ERROR:root:The adjacencyList in thermo file /home/alongd/runs/test/QMfiles/pm3/IQTMGKLZWMFKLM-UHFFFAOYSA.thermo did not match the current molecule InChI=1S/C5H5NO/c1-2-4-3-6-5(4)7/h2-3H,1H2,(H,6,7)
MOPAC Job: "/home/alongd/runs/test/QMscratch/pm3/WEWSWNKMPFVYSO-UHFFFAOYSA.mop" ended normally on Feb 18, 2016, at 15:09.
MOPAC Job: "/home/alongd/runs/test/QMscratch/pm3/BMRZARCFFMHABK-UHFFFAOYSA.mop" ended normally on Feb 18, 2016, at 15:10.
MOPAC Job: "/home/alongd/runs/test/QMscratch/pm3/RMVKBYYLYWCGPS-UHFFFAOYSA.mop" ended normally on Feb 18, 2016, at 15:10.
```
Which means that the problem is with ```Resonance isomer 5 [C]1([C](C=N1)C#C)O```

and ```C1(=NC=C=C1[CH])O``` gave a different error:
```
MOPAC Job: "/home/alongd/runs/test/QMscratch/pm3/MXSAZJJIECWEKU-UHFFFAOYSA.mop" ended normally on Feb 18, 2016, at 15:13.
   ERROR:root:MOPAC output file contains the following error: EXCESS NUMBER OF OPTIMIZATION CYCLES
MOPAC Job: "/home/alongd/runs/test/QMscratch/pm3/MXSAZJJIECWEKU-UHFFFAOYSA.mop" ended normally on Feb 18, 2016, at 15:13.
```

**Comment by connie** [comment]
Just to be sure- did you run your system with QM on in your original job?  You might need to remove QM from the thermoEstimator input.py file to truly replicate the error if you didn't have it in your original job.  This looks like a separate MOPAC error, whereas the original appears to be a thermo groups error.

What did RMG do after the MOPAC error?  Did it try to estimate using group additivity at all?

**Comment by mliu49** [comment]
Closing stale issue. Error reporting has also been improved for adding group contributions, so future instances should be easier to debug.
