### ISSUE TITLE
Invalid Microcanonical Rate Error

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#598]
Running a simulation involving nitrogen (Ethylamine), I got the following error:

```
Using 400 grains from -385.05 to 1269.31 kJ/mol in steps of 4.15 kJ/mol to compute the k(T,P) values at 1492.83 K
Warning: For path reaction [C]1(C(=N1)O[CH]C1=C=N1)C(=O)O(46196) <=> C12(C3([CH]OC1=N2)[C]=N3)C(=O)O(50507):
Warning:     Expected kf(1492.83 K) = 3.62307e+09
Warning:       Actual kf(1492.83 K) = 1.50306e+11
Warning:     Expected Keq(1492.83 K) = 5.96836e-25
Warning:       Actual Keq(1492.83 K) = 0
Error: Invalid k(E) values computed for path reaction "[C]1(C(=N1)O[CH]C1=C=N1)C(=O)O(46196) <=> C12(C3([CH]OC1=N2)[C]=N3)C(=O)O(50507)".
Error: Increasing number of grains did not decrease error enough (Current badness: 1.6, previous 0.3). Something must be wrong with network 15761
Traceback (most recent call last):
  File "/home/alongd/ws/RMG-Py/rmg.py", line 165, in <module>
    rmg.execute(inputFile, output_dir, **kwargs)
  File "/home/alongd/ws/RMG-Py/rmgpy/rmg/main.py", line 604, in execute
    self.reactionModel.enlarge(objectToEnlarge)
  File "/home/alongd/ws/RMG-Py/rmgpy/rmg/model.py", line 806, in enlarge
    self.updateUnimolecularReactionNetworks(database)
  File "/home/alongd/ws/RMG-Py/rmgpy/rmg/model.py", line 1596, in updateUnimolecularReactionNetworks
    network.update(self, database, self.pressureDependence)
  File "/home/alongd/ws/RMG-Py/rmgpy/rmg/pdep.py", line 555, in update
    K = self.calculateRateCoefficients(Tlist, Plist, method)
  File "/home/alongd/ws/RMG-Py/rmgpy/pdep/network.py", line 210, in calculateRateCoefficients
    self.setConditions(T, P)
  File "/home/alongd/ws/RMG-Py/rmgpy/pdep/network.py", line 325, in setConditions
    raise error
rmgpy.pdep.network.InvalidMicrocanonicalRateError
```

I'm still trying to figure whether I did anything different to get this error, other than updating RMG-Py & RMG-database to current versions.
Looks similar to the error of eg2 in Issue #224

**Comment by alongd** [comment]
Duplicate issue of #557, #761
