### ISSUE TITLE
unable to find reverse reaction in intra_H_migration

### ISSUE THREAD

**Issue by cfgoldsmith** [ReactionMechanismGenerator/RMG-Py#618]
After adding Alon's patch (ccfdc7e) for issue #617, rmgpy now crashes trying to move the hydrogen on a secondary amine to a radical on an aromatic ligand.
```
Error: Molecule "C1(Nc2cccc[c]2)C=CC=C[C]=1"
Error: Molecule "[H]"
Error: Molecule "c1(NC2=CC=CC=[C]2)ccccc1"
SKIP raise KineticsError for degeneracy flag
Error: Expecting one matching reverse reaction, not 2 in reaction family intra_H_migration for forward reaction Molecule "c1(NC2=CC=CC=[C]2)ccccc1" <=> Molecule "c1(ccccc1)[N]C1C=CC=CC=1".

Error: There is likely a bug in the RMG-database kinetics reaction family involving a missing group, missing atomlabels, forbidden groups, etc.
Reactant
multiplicity 2
1  C u0 p0 c0 {3,S} {4,D} {5,S}
2  C u0 p0 c0 {3,S} {6,B} {13,B}
3  N u0 p1 c0 {1,S} {2,S} {17,S}
4  C u0 p0 c0 {1,D} {7,S} {16,S}
5  C u0 p0 c0 {1,S} {10,D} {18,S}
6  C u0 p0 c0 {2,B} {8,B} {21,S}
7  C u0 p0 c0 {4,S} {9,D} {15,S}
8  C u0 p0 c0 {6,B} {11,B} {20,S}
9  C u0 p0 c0 {7,D} {10,S} {14,S}
10 C u0 p0 c0 {5,D} {9,S} {22,S}
11 C u0 p0 c0 {8,B} {12,B} {19,S}
12 C u0 p0 c0 {11,B} {13,B} {23,S}
13 C u1 p0 c0 {2,B} {12,B}
14 H u0 p0 c0 {9,S}
15 H u0 p0 c0 {7,S}
16 H u0 p0 c0 {4,S}
17 H u0 p0 c0 {3,S}
18 H u0 p0 c0 {5,S}
19 H u0 p0 c0 {11,S}
20 H u0 p0 c0 {8,S}
21 H u0 p0 c0 {6,S}
22 H u0 p0 c0 {10,S}
23 H u0 p0 c0 {12,S}

Product
multiplicity 2
1  C u0 p0 c0 {3,D} {4,S} {13,S}
2  C u0 p0 c0 {5,B} {6,B} {13,S}
3  C u0 p0 c0 {1,D} {7,S} {16,S}
4  C u0 p0 c0 {1,S} {10,D} {18,S}
5  C u0 p0 c0 {2,B} {8,B} {21,S}
6  C u0 p0 c0 {2,B} {12,B} {17,S}
7  C u0 p0 c0 {3,S} {9,D} {15,S}
8  C u0 p0 c0 {5,B} {11,B} {20,S}
9  C u0 p0 c0 {7,D} {10,S} {14,S}
10 C u0 p0 c0 {4,D} {9,S} {22,S}
11 C u0 p0 c0 {8,B} {12,B} {19,S}
12 C u0 p0 c0 {6,B} {11,B} {23,S}
13 N u1 p1 c0 {1,S} {2,S}
14 H u0 p0 c0 {9,S}
15 H u0 p0 c0 {7,S}
16 H u0 p0 c0 {3,S}
17 H u0 p0 c0 {6,S}
18 H u0 p0 c0 {4,S}
19 H u0 p0 c0 {11,S}
20 H u0 p0 c0 {8,S}
21 H u0 p0 c0 {5,S}
22 H u0 p0 c0 {10,S}
23 H u0 p0 c0 {12,S}

Error: Debugging why no reaction was found...
Error: Checking whether the family's forbidden species have affected reaction generation...
Error: Still experiencing error: Expecting one matching reverse reaction, not 2 in reaction family intra_H_migration for forward reaction <Molecule "c1(NC2=CC=CC=[C]2)ccccc1"> <=> <Molecule "c1(ccccc1)[N]C1C=CC=CC=1">.

Traceback (most recent call last):
  File "../../../rmg.py", line 165, in <module>
    rmg.execute(inputFile, output_dir, **kwargs)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/main.py", line 636, in execute
    bimolecularReact=self.bimolecularReact)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/model.py", line 748, in enlarge
    self.processNewReactions(self.react(database, self.core.species[i]), self.core.species[i], None)
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/rmg/model.py", line 649, in react
    reactionList.extend(database.kinetics.generateReactionsFromFamilies([moleculeA], products=None, only_families=only_families))
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/database.py", line 419, in generateReactionsFromFamilies
    reactionList.extend(family.generateReactions(reactants))
  File "/Users/claudefranklingoldsmith/code/RMG-Py/rmgpy/data/kinetics/family.py", line 1328, in generateReactions
    raise KineticsError("Did not find reverse reaction in reaction family {0} for reaction {1}.".format(self.label, str(rxn)))
rmgpy.data.kinetics.common.KineticsError: Did not find reverse reaction in reaction family intra_H_migration for reaction <Molecule "c1(NC2=CC=CC=[C]2)ccccc1"> <=> <Molecule "c1(ccccc1)[N]C1C=CC=CC=1">.
```

**Comment by alongd** [comment]
I got a similar error, but for H_Abs.
First RMG says `Expecting one matching reverse reaction, not 2 in reaction family...`, but at the end it says `Did not find reverse reaction in reaction family...`. Strange, but probably not the main point.

The molecules involve N, but the reaction itself is not directly related to nitrogen:
![1](https://cloud.githubusercontent.com/assets/16158262/19841451/562c6bb2-9ee2-11e6-9892-c315a8eb227c.png)

The triple-bonded C rad abstracts an H from another C-rad, forming a birad on one side of the molecule. Birads are allowed in the H Abstraction family, but still I couldn't reproduce this in the kinetic search on the website: RMG did not find an H Abstraction reaction between C=[C] and C#C (found only one addition reaction yielding C=CC#C).
The H Abstraction family requires that the reverse reaction will be of the same family. The in-existence of the reverse in RMG probably caused this error:


```
Error: Debugging why no reaction was found...
Error: Checking whether the family's forbidden species have affected reaction generation...
Error: Still experiencing error: Expecting one matching reverse reaction, not 2 in reaction family H_Abstraction for forward reaction <Molecule "N(=C=[CH])N=[CH]"> + <Molecule "C=N[N]C#[C]"> <=> <Molecule "C=N[N]C#C"> + <Molecule "N(=C=[C])N=[CH]">.

Traceback (most recent call last):
  File "D:\Code\RMG-Py\rmgpy\scoop_framework\util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "D:\Code\RMG-Py\rmgpy\rmg\react.py", line 96, in reactMolecules
    rxns = family.generateReactions(molecules)
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1336, in generateReactions
    raise KineticsError("Did not find reverse reaction in reaction family {0} for reaction {1}.".format(self.label, str(rxn)))
KineticsError: Did not find reverse reaction in reaction family H_Abstraction for reaction <Molecule "N(=C=[CH])N=[CH]"> + <Molecule "C=N[N]C#[C]"> <=> <Molecule "C=N[N]C#C"> + <Molecule "N(=C=[C])N=[CH]">.

Traceback (most recent call last):
  File "D:\Code\RMG-Py\/rmg.py", line 152, in <module>
    rmg.execute(**kwargs)
  File "D:\Code\RMG-Py\rmgpy\rmg\main.py", line 634, in execute
    bimolecularReact=self.bimolecularReact)
  File "D:\Code\RMG-Py\rmgpy\rmg\model.py", line 621, in enlarge
    rxns = reactAll(self.core.species, numOldCoreSpecies, unimolecularReact, bimolecularReact)
  File "D:\Code\RMG-Py\rmgpy\rmg\react.py", line 155, in reactAll
    rxns = list(react(*spcTuples))
  File "D:\Code\RMG-Py\rmgpy\rmg\react.py", line 75, in react
    combos
  File "D:\Code\RMG-Py\rmgpy\scoop_framework\util.py", line 154, in map_
    return map(WorkerWrapper(args[0]), *args[1:], **kwargs)
  File "D:\Anaconda\envs\rmg_env\lib\site-packages\scoop-0.7.2.0-py2.7.egg\scoop\fallbacks.py", line 49, in wrapper
  File "D:\Code\RMG-Py\rmgpy\scoop_framework\util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "D:\Code\RMG-Py\rmgpy\rmg\react.py", line 96, in reactMolecules
    rxns = family.generateReactions(molecules)
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1336, in generateReactions
    raise KineticsError("Did not find reverse reaction in reaction family {0} for reaction {1}.".format(self.label, str(rxn)))
rmgpy.data.kinetics.common.KineticsError: Did not find reverse reaction in reaction family H_Abstraction for reaction <Molecule "N(=C=[CH])N=[CH]"> + <Molecule "C=N[N]C#[C]"> <=> <Molecule "C=N[N]C#C"> + <Molecule "N(=C=[C])N=[CH]">.
```
