### ISSUE TITLE
RMG-Py/examples/thermoEstimator/input.py crashes: QMTP broken?

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#646]
When running thermo for the molecules from `RMG-Py/examples/thermoEstimator/input.py` with MOPAC 2012 PM3, the following crash was encountered:

```python
(rmg_env)nickv@pharos:~/ws/dev/RMG-Py/examples/thermoEstimator$ ./run.sh
Traceback (most recent call last):
  File "../../scripts/thermoEstimator.py", line 70, in <module>
    runThermoEstimator(inputFile)
  File "../../scripts/thermoEstimator.py", line 41, in runThermoEstimator
    species.generateThermoData(rmg.database, quantumMechanics=rmg.reactionModel.quantumMechanics)
  File "/home/nickv/ws/dev/RMG-Py/rmgpy/rmg/model.py", line 98, in generateThermoData
    thermo0 = database.thermo.getThermoData(self, trainingSet=None, quantumMechanics=quantumMechanics)
  File "/home/nickv/ws/dev/RMG-Py/rmgpy/data/thermo.py", line 791, in getThermoData
    thermo0 = quantumMechanics.getThermoData(original_molecule) # returns None if it fails
  File "/home/nickv/ws/dev/RMG-Py/rmgpy/qm/main.py", line 194, in getThermoData
    thermo0 = qm_molecule_calculator.generateThermoData()
  File "/home/nickv/ws/dev/RMG-Py/rmgpy/qm/molecule.py", line 328, in generateThermoData
    self.qmData = self.generateQMData()
  File "/home/nickv/ws/dev/RMG-Py/rmgpy/qm/mopac.py", line 241, in generateQMData
    success = self.run()
  File "/home/nickv/ws/dev/RMG-Py/rmgpy/qm/mopac.py", line 73, in run
    self.testReady()
  File "/home/nickv/ws/dev/RMG-Py/rmgpy/qm/mopac.py", line 69, in testReady
    if not os.path.exists(self.executablePath):
  File "/opt/anaconda/anaconda/envs/rmg_env/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

For some reason, the executablePath that should be set [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/qm/mopac.py#L23)
```python
    try:
        executablePath = distutils.spawn.find_executable('mopac') or \
                             distutils.spawn.find_executable('MOPAC2009.exe') or \
                             distutils.spawn.find_executable('MOPAC2012.exe')
    except:
        logging.debug("Did not find MOPAC on path, checking if it exists in a declared MOPAC_DIR...")
        mopacEnv = os.getenv('MOPAC_DIR', default="/opt/mopac")
        if os.path.exists(os.path.join(mopacEnv , 'MOPAC2012.exe')):
            executablePath = os.path.join(mopacEnv , 'MOPAC2012.exe')
        elif os.path.exists(os.path.join(mopacEnv , 'MOPAC2009.exe')):
            executablePath = os.path.join(mopacEnv , 'MOPAC2009.exe')
        elif os.path.exists(os.path.join(mopacEnv , 'mopac')):
            executablePath = os.path.join(mopacEnv , 'mopac')
        else:      
            executablePath = os.path.join(mopacEnv , '(MOPAC 2009 or 2012)')
```

is not retained when it is requested [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/qm/mopac.py#L68):
```python
    def testReady(self):
        if not os.path.exists(self.executablePath):
            raise Exception("Couldn't find MOPAC executable at {0}. Try setting your MOPAC_DIR environment variable.".format(self.executablePath))
```
I remove the mopac package from the rmg anaconda environment to ensure rmg is not finding that version.

I tried the following combinations afterwards, to no avail:
- exported MOPAC_DIR to the locally installed version of MOPAC 2012.
- created the `mopac` alias that pointed to the locally installed version of  MOPAC 2012. 

Am I forgetting something, or is this really a bug?

**Comment by rwest** [comment]
Looks like it never stores `executablePath` in `self.executablePath`?
Did this ever work??

**Comment by rwest** [comment]
#593 shows a bunch of the same error, eg
```python
======================================================================
ERROR: Test that generateThermoData() can load thermo from a previous run.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alongd/ws/RMG-Py/rmgpy/qm/mopacTest.py", line 143, in testLoadThermoData
    self.qmmol1.generateThermoData()
  File "/home/alongd/ws/RMG-Py/rmgpy/qm/molecule.py", line 328, in generateThermoData
    self.qmData = self.generateQMData()
  File "/home/alongd/ws/RMG-Py/rmgpy/qm/mopac.py", line 241, in generateQMData
    success = self.run()
  File "/home/alongd/ws/RMG-Py/rmgpy/qm/mopac.py", line 73, in run
    self.testReady()
  File "/home/alongd/ws/RMG-Py/rmgpy/qm/mopac.py", line 69, in testReady
    if not os.path.exists(self.executablePath):
  File "/opt/venv_rmg/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```
but @alongd says the problem went away.

**Comment by nickvandewiele** [comment]
Well, I am confused about the nature of `executablePath`.

It is created as a class attribute of `rmgpy.qm.mopac.MOPAC `, but then called as if it were an instance variable in `self.executablePath`. I am unsure if this is the right way to call that variable.

**Comment by alongd** [comment]
running `make test` again, I get on my local PC some ImportErrors for Cantera, but on Pharos I do get the MOPAC errors again, for example:
```
======================================================================
ERROR: Test that generateThermoData() works correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alongd/ws/RMG-Py/rmgpy/qm/mopacTest.py", line 59, in testGenerateThermoData
    self.qmmol1.generateThermoData()
  File "/home/alongd/ws/RMG-Py/rmgpy/qm/molecule.py", line 328, in generateThermoData
    self.qmData = self.generateQMData()
  File "/home/alongd/ws/RMG-Py/rmgpy/qm/mopac.py", line 241, in generateQMData
    success = self.run()
  File "/home/alongd/ws/RMG-Py/rmgpy/qm/mopac.py", line 73, in run
    self.testReady()
  File "/home/alongd/ws/RMG-Py/rmgpy/qm/mopac.py", line 69, in testReady
    if not os.path.exists(self.executablePath):
  File "/opt/anaconda/anaconda/envs/rmg_env/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Perhaps the definitions on Pharos were changed?

**Comment by rwest** [comment]
I've figured it out. 

>find_executable(executable, path=None)
>Try to find 'executable' in the directories listed in 'path' (a string listing directories separated by 'os.pathsep'; defaults to os.environ['PATH']). Returns the complete filename **or None if not found.**

Working on a patch now.
Storing as a class variable rather than an instance one is appropriate so we don't have to look for mopac (or gaussian) for each calculation, only once when loading RMG. We could access it via `Mopac.executablePath` instead of `self.executablePath` for clarity, and negligibly faster lookup.  I'll include this change in my patch.

**Comment by nickvandewiele** [comment]
I understand; it didn't throw an exception, only returned None.

But I am confused here:
`executablePath` is already created as a class variable of `rmgpy.qm.mopac.MOPAC`. I believe one can access class variables through created instances of that class, i.e. `self.executablePath` as well. Every instance just refers to the same variable.

**Comment by rwest** [comment]
Yes, you can. That worked.The call to `self.executablePath` correctly looked up the class variable `Mopac.executablePath`, which was `None`.
