### ISSUE TITLE
Travis CI builds fail with cantera.ck2cti.InputParseError

### ISSUE THREAD

**Issue by nickvandewiele** [ReactionMechanismGenerator/RMG-Py#718]
Currently, Travis CI builds fail with the following error.

```python
Traceback (most recent call last):
  File "/home/travis/build/ReactionMechanismGenerator/code/tested/RMG-Py/rmgpy/tools/regression.py", line 192, in <module>
    main()
  File "/home/travis/build/ReactionMechanismGenerator/code/tested/RMG-Py/rmgpy/tools/regression.py", line 189, in main
    run(benchmark, tested, *args)
  File "/home/travis/build/ReactionMechanismGenerator/code/tested/RMG-Py/rmgpy/tools/regression.py", line 151, in run
    observables = {'species': observables}
  File "/home/travis/miniconda/envs/benchmark/lib/python2.7/site-packages/rmgpy/tools/observablesRegression.py", line 105, in __init__
    self.newSim.loadChemkinModel(os.path.join(newDir,'chem_annotated.inp'), transportFile=newTransportPath, quiet=True)
  File "/home/travis/miniconda/envs/benchmark/lib/python2.7/site-packages/rmgpy/tools/canteraModel.py", line 262, in loadChemkinModel
    parser.convertMech(chemkinFile, transportFile=transportFile, outName=outName, **kwargs)
  File "/home/travis/miniconda/envs/benchmark/lib/python2.7/site-packages/cantera/ck2cti.py", line 1964, in convertMech
    raise InputParseError("No transport data for species '{0}'.".format(s))
cantera.ck2cti.InputParseError: No transport data for species 'Ar'.
```

**Comment by connie** [comment]
On master right now, after running minimal example the `tran.dat` is completely incorrect:

```
! Species         Shape    LJ-depth  LJ-diam   DiplMom   Polzblty  RotRelaxNum Data     
! Name            Index    epsilon/k_B sigma     mu        alpha     Zrot      Source   
! Ar                  None
! He                  None
! Ne                  None
! N2                  None
! ethane(1)           None
! CH3(2)              None
! C2H5(3)             None
! C(6)                None
! H(4)                None
! C2H4(8)             None
! H2(12)              None
! C3H7(14)            None
! C2H3(13)            None
! C#C(25)             None
! C4H7(28)            None
! C4H7(38)            None
! C3H5(32)            None
! C4H6(30)            None
! C4H7(42)            None
```

Works fine on the code before your PR thermo_engine.

**Comment by rwest** [comment]
Besides fixing this, we should figure out why the travis setup etc. didn't catch it before the PR was merged.

**Comment by nickvandewiele** [comment]
The culprit here is that `rmgpy.rmg.model.Species.generateTransportData` is no longer called, along with thermo.

I can either :
- add calls to spec.generateTransportData(db) when a thermo task is submitted _or_
- replace `spec.transportData` accesses by calls to a new method `rmgpy.rmg.model.Species.getTransportData()` that calculates transport when it is needed.

**Comment by connie** [comment]
Closed via https://github.com/ReactionMechanismGenerator/RMG-Py/pull/721
