### ISSUE TITLE
Error while running P-dep job that worked several months ago

### ISSUE THREAD

**Issue by zjburas** [ReactionMechanismGenerator/RMG-Py#723]
I was able to successfully run the attached P-dep RMG job about four months ago (although there was an issue with the converged mechanism, #621). Now, it crashes within a couple of minutes and gives the following error:

Warning: For path reaction CH2(S)(27) + H2(13) <=> CH4(1):
Warning:     Expected kf(302.59 K) = 3.63228e+06
Warning:       Actual kf(302.59 K) = 2.12629e+06
Warning:     Expected Keq(302.59 K) = 2.23673e+78
Warning:       Actual Keq(302.59 K) = 3.1013e+79
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "CH2(S)(27) + H2(13) <=> CH4(1)".
Traceback (most recent call last):
  File "/home/zjburas/RMG-Py/rmg.py", line 164, in <module>
    rmg.execute(**kwargs)
  File "/home/zjburas/RMG-Py/rmgpy/rmg/main.py", line 547, in execute
    bimolecularReact=self.bimolecularReact)
  File "/home/zjburas/RMG-Py/rmgpy/rmg/model.py", line 733, in enlarge
    self.updateUnimolecularReactionNetworks(database)
  File "/home/zjburas/RMG-Py/rmgpy/rmg/model.py", line 1513, in updateUnimolecularReactionNetworks
    network.update(self, database, self.pressureDependence)
  File "/home/zjburas/RMG-Py/rmgpy/rmg/pdep.py", line 559, in update
    K = self.calculateRateCoefficients(Tlist, Plist, method)
  File "/home/zjburas/RMG-Py/rmgpy/pdep/network.py", line 210, in calculateRateCoefficients
    self.setConditions(T, P)
  File "/home/zjburas/RMG-Py/rmgpy/pdep/network.py", line 345, in setConditions
    self.calculateCollisionModel()
  File "/home/zjburas/RMG-Py/rmgpy/pdep/network.py", line 732, in calculateCollisionModel
    collFreq[i] = isomer.calculateCollisionFrequency(self.T, self.P, self.bathGas)
  File "rmgpy/pdep/configuration.pyx", line 157, in rmgpy.pdep.configuration.Configuration.calculateCollisionFrequency (build/pyrex/rmgpy/pdep/configuration.c:4674)
  File "rmgpy/pdep/configuration.pyx", line 171, in rmgpy.pdep.configuration.Configuration.calculateCollisionFrequency (build/pyrex/rmgpy/pdep/configuration.c:4037)
AssertionError
discarding /opt/anaconda/anaconda/envs/rmg_env/bin from PATH

My version of RMG is up to date, as of yesterday, and also incorporates the smart_polycyclic_thermo. I can just use the mechanism I generated several months ago, but I wanted to share this issue with the developers.
 
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/377231/input.txt)

**Comment by nickvandewiele** [comment]
@zjburas you should update your RMG-Py: In the error trace I noticed

`self.updateUnimolecularReactionNetworks(database)`

which does not correspond to the latest master.

**Comment by zjburas** [comment]
@nickvandewiele updating RMG-Py worked. Thank you.
