### ISSUE TITLE
Trying to use chlorine unsupported atom in RMG

### ISSUE THREAD

**Issue by Ilyasem** [ReactionMechanismGenerator/RMG-Py#730]
Hello, I left an issue a while ago and was suggested to try a solution discussed in #457 
I have created a reaction library to use as a seed mechanism and have added in necessary thermo data into primaryThermoLibrary.
I have also marked Cl and Cl2 as nonreactive in my input file and attempted to run, this is the error I am stuck on and have been unable to solve, I would like some assistance.

```
Loading default kinetics families from C:\Users\ilya_\Anaconda2\envs\rmg_env\share\rmgdatabase\kinetics\families
Traceback (most recent call last):
  File "rmg.py", line 165, in <module>
    rmg.execute(inputFile, output_dir, **kwargs)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\rmg\main.py", line 514, in execute
    self.initialize(inputFile, output_directory, **kwargs)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\rmg\main.py", line 380, in initialize
    self.loadDatabase()
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\rmg\main.py", line 303, in loadDatabase
    depository = False, # Don't bother loading the depository information, as we don't use it
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\data\rmg.py", line 101, in load
    kineticsDepositories
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\data\rmg.py", line 164, in loadKinetics
    depositories=kineticsDepositories
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\data\kinetics\database.py", line 104, in load
    self.loadLibraries(os.path.join(path, 'libraries'), libraries)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\data\kinetics\database.py", line 205, in loadLibraries
    library_file = os.path.join(path, library_name,'reactions.py')
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\ntpath.py", line 67, in join
    p_drive, p_path = splitdrive(p)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\ntpath.py", line 116, in splitdrive
    normp = p.replace(altsep, sep)
AttributeError: 'tuple' object has no attribute 'replace'
```

Here are relevant files:

[primaryThermoLibrarycopy.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/385259/primaryThermoLibrarycopy.txt)

[reactionscopy.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/385260/reactionscopy.txt)

[inputcopy.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/385263/inputcopy.txt)

Thank you for assisting me earlier, and thank you for looking at this now.

-Ilya

**Comment by rwest** [comment]
I haven't tested this fix, but reading the error message it looks like some path manipulation function called by os.path.join is getting a tuple object when it expects a string. I think it is because your input file has
`    seedMechanisms = [('CustomCl',True)],`
Try replacing that with
    seedMechanisms = ['CustomCl'],
See
http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/input.html#seed-mechanisms

**Comment by Ilyasem** [comment]
Hello again, I have followed your advice and ran into this issue after finally getting my reaction library to be accepted. 

Generating thermodynamics for new species...
Found thermo for OCl in thermo library: primarythermolibrary
Found thermo for OCCO in thermo library: cho
Found thermo for [O]CCO in thermo library: dft_qci_thermo
Found thermo for [CH2]OCO in thermo library: dft_qci_thermo
Traceback (most recent call last):
  File "rmg.py", line 165, in <module>
    rmg.execute(inputFile, output_dir, **kwargs)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\rmg\main.py", line 541, in execute
    bimolecularReact=self.bimolecularReact)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\rmg\model.py", line 764, in enlarge
    spec.generateThermoData(database, quantumMechanics=self.quantumMechanics)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\rmg\model.py", line 100, in generateThermoData
    thermo0 = database.thermo.getThermoData(self, trainingSet=None, quantumMechanics=quantumMechanics)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\data\thermo.py", line 738, in getThermoData
    thermo0 = self.getThermoDataFromGroups(species)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\data\thermo.py", line 901, in getThermoDataFromGroups
    tdata = self.estimateThermoViaGroupAdditivity(molecule)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\data\thermo.py", line 1003, in estimateThermoViaGroupAdditivity
    thermoData = self.computeGroupAdditivityThermo(molecule)
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\data\thermo.py", line 1042, in computeGroupAdditivityThermo
    self.__addGroupThermoData(thermoData, self.groups['group'], molecule, {'*':atom})
  File "C:\Users\ilya_\Anaconda2\envs\rmg_env\lib\site-packages\rmgpy\data\thermo.py", line 1126, in __addGroupThermoData
    while node.data is None and node is not None:
AttributeError: 'NoneType' object has no attribute 'data'


I have included thermo data in primarythermolibrary so I am not sure what is causing the failure

here are all files of most recent update:

[inputcopy.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/386821/inputcopy.txt)

[CustomCl.zip](https://github.com/ReactionMechanismGenerator/RMG-Py/files/386827/CustomCl.zip)


[primaryThermoLibrarycopy.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/386831/primaryThermoLibrarycopy.txt)

Please direct me in the right direction. I am most thankful

**Comment by mliu49** [comment]
The final error you encountered is due to lack of chlorine groups in the thermo groups database. New chlorine GAV values have since been added, which should resolve the issue.

Alternatively, you could have provided a thermo library containing the parameters for all of your chlorine species. I'm sorry for the lack of a timely response.
