### ISSUE TITLE
1,3-Hexadiene example crashes with InvalidMicrocanonicalRateError

### ISSUE THREAD

**Issue by mliu49** [ReactionMechanismGenerator/RMG-Py#761]
I'm creating this issue based on @rwest's discovery. Running the 1,3-hexadiene example without QMThermo crashes with the following error:

```
Error: Invalid k(E) values computed for path reaction "C=C[CH]C(CC)C([CH]CC)C=C(31) <=> C=CC([CH]CC)[C](C=CC)CC(160)".
Error: Increasing number of grains did not decrease error enough (Current badness: 0.4, previous 0.4). Something must be wrong with network 5
Traceback (most recent call last):
  File "/home/mjliu/Code/RMG-Py/rmg.py", line 164, in <module>
    rmg.execute(**kwargs)
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/main.py", line 616, in execute
    self.reactionModel.enlarge(objectToEnlarge)
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/model.py", line 675, in enlarge
    self.updateUnimolecularReactionNetworks()
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/model.py", line 1454, in updateUnimolecularReactionNetworks
    network.update(self, self.pressureDependence)
  File "/home/mjliu/Code/RMG-Py/rmgpy/rmg/pdep.py", line 559, in update
    K = self.calculateRateCoefficients(Tlist, Plist, method)
  File "/home/mjliu/Code/RMG-Py/rmgpy/pdep/network.py", line 210, in calculateRateCoefficients
    self.setConditions(T, P)
  File "/home/mjliu/Code/RMG-Py/rmgpy/pdep/network.py", line 325, in setConditions
    raise error
rmgpy.pdep.network.InvalidMicrocanonicalRateError
```

There are also many warnings like the following:

```
Warning: Significant corrections to k(E) to be consistent with high-pressure limit for path reaction "C=C[CH]C(CC)C[CH]C=CCC(35) <=> [CH2]C=CC(CC)C[C]=CCCC(339)".
Warning: For path reaction C=C[CH]C(CC)C[CH]C=CCC(35) <=> [CH2]C=CC([CH]C=CCCC)CC(340):
Warning:     Expected kf(1896.74 K) = 0.0600994
Warning:       Actual kf(1896.74 K) = 0.00876467
Warning:     Expected Keq(1896.74 K) = 1
Warning:       Actual Keq(1896.74 K) = 0
```

Most concerning is the fact that the Actual Keq is 0 in every one of these warnings.

Testing showed that this behavior has been present at least since the 1.0.2 release. I haven't checked further back due to incompatible dependencies. The reaction triggering the error changed with the changes to tree averaging, but that doesn't seem very helpful.

I assume that the example worked at some point. Since identifying when the example stopped working wasn't working very well, I'll try debugging to see if I can discover anything.

**Comment by alongd** [comment]
Just linking past relevant issues of the InvalidMicrocanonicalRateError:
#224, #470 , #557 , #598 , #752

**Comment by mliu49** [comment]
Thanks! I probably should have done a search myself.

According to Connie in #557, "Lol this error has been in existence since the beginning of time."

**Comment by alongd** [comment]
For the record, I ran (made) eg2 with what is now the current official master head (142383cebffbfa96ced881446c951d6fd24a251d) with QM on, it crashed on the following reaction after running for ~10 min:
```
Error: Invalid k(E) values computed for path reaction "C=C[CH]C(CC)C[CH]C=CCC(35) <=> [CH2]C=CC([CH]                                                                                    C=CCCC)CC(341)".
Error: Increasing number of grains did not decrease error enough (Current badness: 0.8, previous 0.8                                                                                    ). Something must be wrong with network 9
Traceback (most recent call last):
  File "rmg.py", line 155, in <module>
    cProfile.runctx(command, global_vars, local_vars, stats_file)
  File "C:\Anaconda\envs\rmg_env\lib\cProfile.py", line 49, in runctx
    prof = prof.runctx(statement, globals, locals)
  File "C:\Anaconda\envs\rmg_env\lib\cProfile.py", line 140, in runctx
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "C:\Code\RMG-Py\rmgpy\rmg\main.py", line 600, in execute
    self.reactionModel.enlarge(objectToEnlarge)
  File "C:\Code\RMG-Py\rmgpy\rmg\model.py", line 675, in enlarge
    self.updateUnimolecularReactionNetworks()
  File "C:\Code\RMG-Py\rmgpy\rmg\model.py", line 1454, in updateUnimolecularReactionNetworks
    network.update(self, self.pressureDependence)
  File "C:\Code\RMG-Py\rmgpy\rmg\pdep.py", line 561, in update
    K = self.calculateRateCoefficients(Tlist, Plist, method)
  File "C:\Code\RMG-Py\rmgpy\pdep\network.py", line 210, in calculateRateCoefficients
    self.setConditions(T, P)
  File "C:\Code\RMG-Py\rmgpy\pdep\network.py", line 325, in setConditions
    raise error
InvalidMicrocanonicalRateError
makefile:98: recipe for target 'eg2' failed
mingw32-make: *** [eg2] Error 1
```

**Comment by cgrambow** [comment]
Update: The network I am calculating has a submerged barrier channel to a unimolecular intermediate, which can further dissociate in a barrierless process. I am able to resolve the error if I calculate the high-P limit rate for the submerged barrier channel in a separate Cantherm job and specify those kinetics directly in the P-dep calculation. The rate for the barrierless process is specified directly anyway.
