### ISSUE TITLE
Pylab cannot be imported in RMG environment

### ISSUE THREAD

**Issue by zjburas** [ReactionMechanismGenerator/RMG-Py#788]
I would like to use pylab in an python script while in rmg_env. However, when I try "import pylab" I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/anaconda/envs/rmg_env/lib/python2.7/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/opt/anaconda/anaconda/envs/rmg_env/lib/python2.7/site-packages/matplotlib/pylab.py", line 274, in <module>
    from matplotlib.pyplot import *
  File "/opt/anaconda/anaconda/envs/rmg_env/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/opt/anaconda/anaconda/envs/rmg_env/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/opt/anaconda/anaconda/envs/rmg_env/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/opt/anaconda/anaconda/envs/rmg_env/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "/opt/anaconda/anaconda/envs/rmg_env/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 31, in <module>
    from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
  File "/opt/anaconda/anaconda/envs/rmg_env/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 124, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named PyQt4
```

**Comment by mliu49** [comment]
I think the problem is with the backend setting for matplotlib. The current default is `Qt4Agg` as specified in the matplotlibrc configuration file (located at `/opt/anaconda/anaconda/envs/rmg_env/lib/python2.7/site-packages/matplotlib/mpl-data`). However, `rmg_env` has PyQt5 installed, not PyQt4.

Changing the configuration file would require admin privileges, so the simplest solution for you is probably to change the backend in your script like so:
```
import matplotlib
matplotlib.use('Qt5Agg')
import pylab
```

This will change the backend to Qt5Agg, which should work with the installed PyQt5.
