### ISSUE TITLE
Unable to find reverse reaction of C-birad + C#C

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#806]
First RMG says Expecting one matching reverse reaction, not 2 in reaction family..., but at the end it says Did not find reverse reaction in reaction family.... Strange, but probably not the main point.

The molecules involve N, but the reaction itself is not directly related to nitrogen:

![](https://cloud.githubusercontent.com/assets/16158262/19841451/562c6bb2-9ee2-11e6-9892-c315a8eb227c.png)

The triple-bonded C rad abstracts an H from another C-rad, forming a birad on one side of the molecule. Birads are allowed in the H Abstraction family, but still I couldn't reproduce this in the kinetic search on the website: RMG did not find an H Abstraction reaction between C=[C] and C#C (found only one addition reaction yielding C=CC#C).
The H Abstraction family requires that the reverse reaction will be of the same family. The in-existence of the reverse in RMG probably caused this error:

Error: Debugging why no reaction was found...
Error: Checking whether the family's forbidden species have affected reaction generation...
Error: Still experiencing error: Expecting one matching reverse reaction, not 2 in reaction family H_Abstraction for forward reaction <Molecule "N(=C=[CH])N=[CH]"> + <Molecule "C=N[N]C#[C]"> <=> <Molecule "C=N[N]C#C"> + <Molecule "N(=C=[C])N=[CH]">.

Traceback (most recent call last):
  File "D:\Code\RMG-Py\rmgpy\scoop_framework\util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "D:\Code\RMG-Py\rmgpy\rmg\react.py", line 96, in reactMolecules
    rxns = family.generateReactions(molecules)
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1336, in generateReactions
    raise KineticsError("Did not find reverse reaction in reaction family {0} for reaction {1}.".format(self.label, str(rxn)))
KineticsError: Did not find reverse reaction in reaction family H_Abstraction for reaction <Molecule "N(=C=[CH])N=[CH]"> + <Molecule "C=N[N]C#[C]"> <=> <Molecule "C=N[N]C#C"> + <Molecule "N(=C=[C])N=[CH]">.

Traceback (most recent call last):
  File "D:\Code\RMG-Py\/rmg.py", line 152, in <module>
    rmg.execute(**kwargs)
  File "D:\Code\RMG-Py\rmgpy\rmg\main.py", line 634, in execute
    bimolecularReact=self.bimolecularReact)
  File "D:\Code\RMG-Py\rmgpy\rmg\model.py", line 621, in enlarge
    rxns = reactAll(self.core.species, numOldCoreSpecies, unimolecularReact, bimolecularReact)
  File "D:\Code\RMG-Py\rmgpy\rmg\react.py", line 155, in reactAll
    rxns = list(react(*spcTuples))
  File "D:\Code\RMG-Py\rmgpy\rmg\react.py", line 75, in react
    combos
  File "D:\Code\RMG-Py\rmgpy\scoop_framework\util.py", line 154, in map_
    return map(WorkerWrapper(args[0]), *args[1:], **kwargs)
  File "D:\Anaconda\envs\rmg_env\lib\site-packages\scoop-0.7.2.0-py2.7.egg\scoop\fallbacks.py", line 49, in wrapper
  File "D:\Code\RMG-Py\rmgpy\scoop_framework\util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "D:\Code\RMG-Py\rmgpy\rmg\react.py", line 96, in reactMolecules
    rxns = family.generateReactions(molecules)
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1336, in generateReactions
    raise KineticsError("Did not find reverse reaction in reaction family {0} for reaction {1}.".format(self.label, str(rxn)))
rmgpy.data.kinetics.common.KineticsError: Did not find reverse reaction in reaction family H_

**Comment by alongd** [comment]
related to #618

**Comment by mliu49** [comment]
The error message is a bit misleading. RMG is looking for a reverse reaction, and expects to find *one* reverse reaction. The error message is accurate when RMG finds zero reverse reactions, but in this case, it actually found *two* reverse reactions.

I think this is the same as an issue that I've been encountering, and it's actually a problem with resonance and reaction isomorphism checking. Essentially, for a given set of reactants and products, RMG will generate all reactions with the products as reactants. Then, it will

1. remove reactions that don't generate the original reactants
2. try to combine the remaining reactions (and increase the degeneracy)

The expectation is that once all of the reactions that don't generate the original reactants are removed, then the remaining reactions should all be isomorphic and be combined into a single reaction. The error occurs when more resonance structures are generated during the first step than during the second step. As a result, some reactions that should have been combined are not combined. Because the root cause is with resonance structure generation, this error tends to occur with aromatics and nitrogen species (because they have the most complicated resonance patterns, and we don't handle them very well).

This is something that I want to fix, but I don't know when I will get around to it. Improving resonance structure generation should reduce the frequency of this error, but there might still be a chance of encountering it, so some changes might also need to be made with reaction isomorphism checking.

Something that could be done quickly might be to improve the error messages to make them more useful. We could print different messages depending on whether 0 or >1 reverse reactions are found.

Unfortunately, I'm not aware of any quick way to bypass the error. I think that there is some degree of chance with this, so you might not encounter the error if you were to run the job again. I would need to confirm though, based on the exact resonance structure that is causing problems.

**Comment by alongd** [comment]
Thanks for the detailed response, @mliu49!
Running this 4 times always resulted in the same error, so if there's a degree of chance, it's not high.
I'm still puzzled, though: searching `C=[C]` + `C#C` (the simplest case with no N \ aromatics)  in the kinetic search online did not result in an H Abstraction reaction. If I understand correctly, this could be the reason that the reverse reaction isn't identified in the case above.
(Do you think that 2 reverse reactions were found? RMG says 2, then says 0. I couldn't populate _any_ using the website.)

**Comment by mliu49** [comment]
I did some more detailed investigation of this case, and there is actually no (or negligibly small) degree of chance. This is one of the cases where resonance structure generation is strictly input dependent.

In Step 1 (from my previous comment), RMG generates resonance structures for the original reactants. The problematic reactant is
![image](https://cloud.githubusercontent.com/assets/10817103/19862575/535c4bde-9f67-11e6-948f-f2c7aa4d74bf.png)
RMG obtains the following resonance structures, both via allyl shift:
![image](https://cloud.githubusercontent.com/assets/10817103/19862593/64f194e4-9f67-11e6-9a86-f0b020bf4c56.png) (1)
![image](https://cloud.githubusercontent.com/assets/10817103/19862589/5f38a0a6-9f67-11e6-9ac7-8cf73dadebf2.png) (2)

In the second step, RMG generates resonance structures for the products in these reverse reactions (ie. the original reactants). It happens that the (2) came first in the list of reactions, so RMG generated the resonance structures of (2). However, with the current resonance algorithm, (2) does not have any resonance forms because the allyl shift method only accepts atoms with a single radical. Thus, we end up with fewer resonance forms in step 2 than in step 1, giving us more than 1 reverse reaction.

The website is unable to react C=[C] with C#C because biradicals are globally forbidden (I know you removed some of them, but they're still forbidden on the website). The one reaction you get is from a library, which is not subject to forbidden groups (specifically for the website).

**Comment by alongd** [comment]
Currently RMG does generate the correct resonance structures starting from the birad species, I think this issue could be closed now.
