### ISSUE TITLE
Missing the species name when RMG's unable to determine atom type

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#809]
Recent changes to nitrogen atom type representations made in RMG (nitrogen branch) predicted a new N atom type with 2 lone pairs and 2 single bonds (e.g., `[NH-][S+]=C`, `[NH-][N+]#C`) with the following error in `rmgpy.molecule.atomtype.getAtomType`:
```
Traceback (most recent call last):
  File "D:\Code\RMG-Py\rmgpy\scoop_framework\util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "D:\Code\RMG-Py\rmgpy\rmg\react.py", line 96, in reactMolecules
    rxns = family.generateReactions(molecules)
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1308, in generateReactions
    reactionList.extend(self.__generateReactions(reactants, forward=True))
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1460, in __generateReactions
    productStructures = self.__generateProductStructures(reactantStructures, [mapA, mapB], forward)
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1200, in __generateProductStructures
    productStructures = self.applyRecipe(reactantStructures, forward=forward)
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1166, in applyRecipe
    struct.update()
  File "rmgpy\molecule\molecule.py", line 742, in rmgpy.molecule.molecule.Molecule.update (build\Release\pyrex\rmgpy\molecule\molecule.c:14864)
    self.updateAtomTypes()
  File "rmgpy\molecule\molecule.py", line 938, in rmgpy.molecule.molecule.Molecule.updateAtomTypes (build\Release\pyrex\rmgpy\molecule\molecule.c:18011)
    atom.atomType = getAtomType(atom, atom.edges)
  File "rmgpy\molecule\atomtype.py", line 479, in rmgpy.molecule.atomtype.getAtomType (build\Release\pyrex\rmgpy\molecule\atomtype.c:6464)
  File "rmgpy\molecule\atomtype.py", line 523, in rmgpy.molecule.atomtype.getAtomType (build\Release\pyrex\rmgpy\molecule\atomtype.c:6338)
AtomTypeError: Unable to determine atom type for atom N-, which has 2 single bonds, 0 double bonds to C, 0 double bonds to O, 0 double bonds to S, 0 triple bonds, 0 benzene bonds, and 2 lone pairs.

Traceback (most recent call last):
  File "D:\Code\RMG-Py\/rmg.py", line 152, in <module>
    rmg.execute(**kwargs)
  File "D:\Code\RMG-Py\rmgpy\rmg\main.py", line 634, in execute
    bimolecularReact=self.bimolecularReact)
  File "D:\Code\RMG-Py\rmgpy\rmg\model.py", line 621, in enlarge
    rxns = reactAll(self.core.species, numOldCoreSpecies, unimolecularReact, bimolecularReact)
  File "D:\Code\RMG-Py\rmgpy\rmg\react.py", line 155, in reactAll
    rxns = list(react(*spcTuples))
  File "D:\Code\RMG-Py\rmgpy\rmg\react.py", line 75, in react
    combos
  File "D:\Code\RMG-Py\rmgpy\scoop_framework\util.py", line 154, in map_
    return map(WorkerWrapper(args[0]), *args[1:], **kwargs)
  File "D:\Anaconda\envs\rmg_env\lib\site-packages\scoop-0.7.2.0-py2.7.egg\scoop\fallbacks.py", line 49, in wrapper
  File "D:\Code\RMG-Py\rmgpy\scoop_framework\util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "D:\Code\RMG-Py\rmgpy\rmg\react.py", line 96, in reactMolecules
    rxns = family.generateReactions(molecules)
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1308, in generateReactions
    reactionList.extend(self.__generateReactions(reactants, forward=True))
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1460, in __generateReactions
    productStructures = self.__generateProductStructures(reactantStructures, [mapA, mapB], forward)
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1200, in __generateProductStructures
    productStructures = self.applyRecipe(reactantStructures, forward=forward)
  File "D:\Code\RMG-Py\rmgpy\data\kinetics\family.py", line 1166, in applyRecipe
    struct.update()
  File "rmgpy\molecule\molecule.py", line 742, in rmgpy.molecule.molecule.Molecule.update (build\Release\pyrex\rmgpy\molecule\molecule.c:14864)
  File "rmgpy\molecule\molecule.py", line 938, in rmgpy.molecule.molecule.Molecule.updateAtomTypes (build\Release\pyrex\rmgpy\molecule\molecule.c:18011)
  File "rmgpy\molecule\atomtype.py", line 479, in rmgpy.molecule.atomtype.getAtomType (build\Release\pyrex\rmgpy\molecule\atomtype.c:6464)
  File "rmgpy\molecule\atomtype.py", line 523, in rmgpy.molecule.atomtype.getAtomType (build\Release\pyrex\rmgpy\molecule\atomtype.c:6338)
rmgpy.molecule.atomtype.AtomTypeError: Unable to determine atom type for atom N-, which has 2 single bonds, 0 double bonds to C, 0 double bonds to O, 0 double bonds to S, 0 triple bonds, 0 benzene bonds, and 2 lone pairs.
```

Although the missing atom type is wonderfully described (number and type of expected bonds, rads, lone pairs), I would be great if RMG also reported the species\reaction it recently tried to generate that raised this error.
(I already added an `N2s` atomType with these specs, but it still didn't solve the problem. If I knew the species\reaction, that would have helped.)

**Comment by alongd** [comment]
Testing the nitrogen atom types some more, I got the following similar error:
```
Unable to determine atom type for atom N--, which has 1 single bonds, 0 double bonds to C, 0 double bonds to O, 0 double bonds to S, 0 triple bonds, 0 benzene bonds, and 3 lone pairs.
```
Knowing which species (or reaction where the products cannot be generated) caused the error would help to understand RMG's predictions better.

**Comment by rwest** [comment]
Is the stack trace for the second one the same as the first? (So we know where to put the extra debug logging)

**Comment by alongd** [comment]
Not identical (this error was raised from a species in the input file, not a reaction product) but points to the same `raise AtomTypeError` at the end of atomtype.py:
```
Traceback (most recent call last):
  File "D:\Code\RMG-Py\/rmg.py", line 152, in <module>
    rmg.execute(**kwargs)
  File "D:\Code\RMG-Py\rmgpy\rmg\main.py", line 506, in execute
    self.initialize(**kwargs)
  File "D:\Code\RMG-Py\rmgpy\rmg\main.py", line 355, in initialize
    self.loadInput(self.inputFile)
  File "D:\Code\RMG-Py\rmgpy\rmg\main.py", line 205, in loadInput
    readInputFile(path, self)
  File "D:\Code\RMG-Py\rmgpy\rmg\input.py", line 395, in readInputFile
    exec f in global_context, local_context
  File "D:\Code\runs\x\nitrogen-new\new.py", line 55, in <module>
    """),
  File "D:\Code\RMG-Py\rmgpy\rmg\input.py", line 96, in species
    spec, isNew = rmg.reactionModel.makeNewSpecies(structure, label=label, reactive=reactive)
  File "D:\Code\RMG-Py\rmgpy\rmg\model.py", line 327, in makeNewSpecies
    spec.generateResonanceIsomers()
  File "rmgpy\species.py", line 165, in rmgpy.species.Species.generateResonanceIsomers (build\Release\pyrex\rmgpy\species.c:4005)
  File "rmgpy\species.py", line 173, in rmgpy.species.Species.generateResonanceIsomers (build\Release\pyrex\rmgpy\species.c:3944)
  File "rmgpy\molecule\molecule.py", line 1506, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build\Release\pyrex\rmgpy\molecule\molecule.c:27712)
  File "rmgpy\molecule\molecule.py", line 1507, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build\Release\pyrex\rmgpy\molecule\molecule.c:27649)
  File "rmgpy\molecule\resonance.py", line 10, in rmgpy.molecule.resonance.generateResonanceIsomers (build\Release\pyrex\rmgpy\molecule\resonance.c:2531)
  File "rmgpy\molecule\resonance.py", line 26, in rmgpy.molecule.resonance.generateResonanceIsomers (build\Release\pyrex\rmgpy\molecule\resonance.c:2323)
  File "rmgpy\molecule\resonance.py", line 131, in rmgpy.molecule.resonance.generateN5dd_N5tsResonanceIsomers (build\Release\pyrex\rmgpy\molecule\resonance.c:4629)
  File "rmgpy\molecule\resonance.py", line 176, in rmgpy.molecule.resonance.generateN5dd_N5tsResonanceIsomers (build\Release\pyrex\rmgpy\molecule\resonance.c:4213)
  File "rmgpy\molecule\molecule.py", line 938, in rmgpy.molecule.molecule.Molecule.updateAtomTypes (build\Release\pyrex\rmgpy\molecule\molecule.c:18011)
  File "rmgpy\molecule\atomtype.py", line 480, in rmgpy.molecule.atomtype.getAtomType (build\Release\pyrex\rmgpy\molecule\atomtype.c:6518)
  File "rmgpy\molecule\atomtype.py", line 523, in rmgpy.molecule.atomtype.getAtomType (build\Release\pyrex\rmgpy\molecule\atomtype.c:6392)
rmgpy.molecule.atomtype.AtomTypeError: Unable to determine atom type for atom N--, which has 1 single bonds, 0 double bonds to C, 0 double bonds to O, 0 double bonds to S, 0 triple bonds, 0 benzene bonds, and 3 lone pairs.
```

**Comment by alongd** [comment]
I'm changing the func def to:
`def getAtomType(atom, bonds, *args):`
and in the raise error I added at the end: `'... while processing: {8:s}'.format(atom, ..., args)`
Now I'm trying to add either the species or reaction to every instance of calling `getAtomType`

**Comment by alongd** [comment]
But the compiler says: `cdef function cannot have star argument`, so my approach is probably wrong

**Comment by rwest** [comment]
Rather than try to pass the species or reaction in to the getAtomType method, I would put `try/except` blocks further up the stack trace, where more is known about the reaction/species. Something like: 
```python
try:
    # do something with a reaction or species that may raise an error
except rmgpy.molecule.atomtype.AtomTypeError: # (or more generic if you want)
    logging.error("Problematic reaction: {}".format(reaction)") # or species, or whatever
    raise
```

By ending the exception handling block with a `raise` statement it will re-raise the exception that it caught, and will behave just as before, crashing with the same stack trace. But just before crashing, it will print some information to the log about the problematic reaction or species, to help you debug.
