### ISSUE TITLE
CClib parsing error when using MOPAC

### ISSUE THREAD

**Issue by yunsiechung** [ReactionMechanismGenerator/RMG-Py#832]
I have encountered the following error a few times when I used MOPAC QM method.
It seems to be the same problem addressed in the previous issue [#134](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/134), and I am not sure why it is occurring again.

``` python
2 radicals on CC(C)(O[O])C1(CO)CCC(CC1)O[O] exceeds limit of 0. Using HBI method.
Trying MopacMolPM7 attempt 1 of 10 on molecule CC(C)(OO)C1(CO)CCC(CC1)OO.
Error: MOPAC output file contains the following error: IMAGINARY FREQUENCIES
Trying MopacMolPM7 attempt 2 of 10 on molecule CC(C)(OO)C1(CO)CCC(CC1)OO.
Error: MOPAC output file contains the following error: IMAGINARY FREQUENCIES
Trying MopacMolPM7 attempt 3 of 10 on molecule CC(C)(OO)C1(CO)CCC(CC1)OO.
Error: MOPAC output file contains the following error: IMAGINARY FREQUENCIES
Trying MopacMolPM7 attempt 4 of 10 on molecule CC(C)(OO)C1(CO)CCC(CC1)OO.
Error: MOPAC output file contains the following error: IMAGINARY FREQUENCIES
Trying MopacMolPM7 attempt 5 of 10 on molecule CC(C)(OO)C1(CO)CCC(CC1)OO.
Error: The passed in cclibData has these attributes: ['aonames', 'aooverlaps', 'atombasis', 'atomcoords', 'atomnos', 'ccenergies', 'charge', 'coreelectrons', 'etenergies', 'etoscs', 'etrotats', 'etsecs', 'etsyms', 'fonames', 'fooverlaps', 'fragnames', 'frags', 'gbasis', 'geotargets', 'geovalues', 'grads', 'hessian', 'homos', 'mocoeffs', 'moenergies', 'molmass', 'mosyms', 'mpenergies', 'mult', 'natom', 'nbasis', 'nmo', 'nocoeffs', 'rotcons', 'rotsymm', 'scfenergies', 'scftargets', 'scfvalues', 'stericenergy', 'vibdisps', 'vibfreqs', 'vibirs', 'vibramans', 'vibsyms']
Traceback (most recent call last):
  File "/home/yunsie/Code/RMG-Py/rmg.py", line 152, in <module>
    rmg.execute(**kwargs)
  File "/home/yunsie/Code/RMG-Py/rmgpy/rmg/main.py", line 634, in execute
    bimolecularReact=self.bimolecularReact)
  File "/home/yunsie/Code/RMG-Py/rmgpy/rmg/model.py", line 630, in enlarge
    self.processNewReactions([rxn], spc)
  File "/home/yunsie/Code/RMG-Py/rmgpy/rmg/model.py", line 711, in processNewReactions
    rxn, isNew = self.makeNewReaction(rxn)
  File "/home/yunsie/Code/RMG-Py/rmgpy/rmg/model.py", line 450, in makeNewReaction
    products  = [self.makeNewSpecies(product)[0]  for product  in forward.products ]
  File "/home/yunsie/Code/RMG-Py/rmgpy/rmg/model.py", line 330, in makeNewSpecies
    submit(spec)
  File "/home/yunsie/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 136, in submit
    spc.thermo = submit_(evaluator, spc)
  File "/home/yunsie/Code/RMG-Py/rmgpy/scoop_framework/util.py", line 171, in submit_
    return func(*args, **kwargs)
  File "/home/yunsie/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 122, in evaluator
    thermo = generateThermoData(spc)
  File "/home/yunsie/Code/RMG-Py/rmgpy/thermo/thermoengine.py", line 103, in generateThermoData
    thermo0 = thermodb.getThermoData(spc) 
  File "/home/yunsie/Code/RMG-Py/rmgpy/data/thermo.py", line 1038, in getThermoData
    tdata = self.estimateRadicalThermoViaHBI(molecule, quantumMechanics.getThermoData)
  File "/home/yunsie/Code/RMG-Py/rmgpy/data/thermo.py", line 1304, in estimateRadicalThermoViaHBI
    thermoData_sat = stableThermoEstimator(saturatedStruct)
  File "/home/yunsie/Code/RMG-Py/rmgpy/qm/main.py", line 220, in getThermoData
    thermo0 = qm_molecule_calculator.generateThermoData()
  File "/home/yunsie/Code/RMG-Py/rmgpy/qm/molecule.py", line 328, in generateThermoData
    self.qmData = self.generateQMData()
  File "/home/yunsie/Code/RMG-Py/rmgpy/qm/mopac.py", line 259, in generateQMData
    success = self.run()
  File "/home/yunsie/Code/RMG-Py/rmgpy/qm/mopac.py", line 96, in run
    return self.verifyOutputFile()
  File "/home/yunsie/Code/RMG-Py/rmgpy/qm/mopac.py", line 166, in verifyOutputFile
    qmData = self.parse()
  File "/home/yunsie/Code/RMG-Py/rmgpy/qm/molecule.py", line 305, in parse
    qmData = parseCCLibData(cclibData, radicalNumber+1) # Should `radicalNumber+1` be `self.molecule.multiplicity` in the next line of code? It's the electronic ground state degeneracy.
  File "/home/yunsie/Code/RMG-Py/rmgpy/qm/qmdata.py", line 72, in parseCCLibData
    raise e
AttributeError: 'ccData' object has no attribute 'molmass'
discarding /home/yunsie/.conda/envs/rmg_env/bin from PATH
```

**Comment by mliu49** [comment]
The temporary fix mentioned in the old issue (waiting for 1 sec before accessing the file) is not actually in the official version of RMG. You could try adding that line in to see if it fixes the issue for you.
