### ISSUE TITLE
String\float confusion in ConsistencyChecker.check_partial_charge

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/RMG-Py#898]
I had a mistake in an adjList in a new library. Since the actual charge was different than theoretical, an `InvalidAdjacencyListError` was raised, but crashed when it tried to report the atom's bonds:
```
Traceback (most recent call last):
  File "C:\Code\RMG-Py/rmg.py", line 156, in <module>
    rmg.execute(**kwargs)
  File "C:\Code\RMG-Py\rmgpy\rmg\main.py", line 529, in execute
    self.initialize(**kwargs)
  File "C:\Code\RMG-Py\rmgpy\rmg\main.py", line 395, in initialize
    self.loadDatabase()
  File "C:\Code\RMG-Py\rmgpy\rmg\main.py", line 306, in loadDatabase
    depository = False, # Don't bother loading the depository information, as we don't use it
  File "C:\Code\RMG-Py\rmgpy\data\rmg.py", line 101, in load
    kineticsDepositories
  File "C:\Code\RMG-Py\rmgpy\data\rmg.py", line 164, in loadKinetics
    depositories=kineticsDepositories
  File "C:\Code\RMG-Py\rmgpy\data\kinetics\database.py", line 104, in load
    self.loadLibraries(os.path.join(path, 'libraries'), libraries)
  File "C:\Code\RMG-Py\rmgpy\data\kinetics\database.py", line 209, in loadLibraries
    library.load(library_file, self.local_context, self.global_context)
  File "C:\Code\RMG-Py\rmgpy\data\kinetics\library.py", line 231, in load
    speciesDict = self.getSpecies(os.path.join(os.path.dirname(path),'dictionary.txt'))
  File "C:\Code\RMG-Py\rmgpy\data\base.py", line 284, in getSpecies
    species = Species().fromAdjacencyList(adjlist)
  File "rmgpy\species.py", line 193, in rmgpy.species.Species.fromAdjacencyList (build\Release\pyrex\rmgpy\species.c:4932)
  File "rmgpy\species.py", line 200, in rmgpy.species.Species.fromAdjacencyList (build\Release\pyrex\rmgpy\species.c:4583)
  File "rmgpy\molecule\molecule.py", line 1280, in rmgpy.molecule.molecule.Molecule.fromAdjacencyList (build\Release\pyrex\rmgpy\molecule\molecule.c:24509)
  File "rmgpy\molecule\molecule.py", line 1288, in rmgpy.molecule.molecule.Molecule.fromAdjacencyList (build\Release\pyrex\rmgpy\molecule\molecule.c:24084)
  File "C:\Code\RMG-Py\rmgpy\molecule\adjlist.py", line 703, in fromAdjacencyList
    for atom in atoms: ConsistencyChecker.check_partial_charge(atom)
  File "C:\Code\RMG-Py\rmgpy\molecule\adjlist.py", line 99, in check_partial_charge
    bonds=','.join([bond.order for bond in atom.bonds.values()])
TypeError: sequence item 0: expected string, float found
```

**Comment by mliu49** [comment]
I think we might need to do a search for all calls to bond.order in RMG-Py...

@goldmanm

**Comment by goldmanm** [comment]
I'll look into this and make a pull request

**Comment by mliu49** [comment]
@alongd Could you check that this is fixed now?

**Comment by alongd** [comment]
Yes, fixed my issue.
