### ISSUE TITLE
Error with Resonance Structure Generation for Complex Ring Systems

### ISSUE THREAD

**Issue by amarkpayne** [ReactionMechanismGenerator/RMG-Py#961]
I submitted an RMG job that crashed, giving me the error message below. I had successful run this job a month ago, but I tried running this job again in RMG version 2.1, which crashed.

```
Traceback (most recent call last):
  File "/home/ampayne/RMG/RMG-Py/rmgpy/scoop_framework/util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/rmg/react.py", line 96, in reactMolecules
    rxns = family.generateReactions(molecules)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 1323, in generateReactions
    reactionList.extend(self.__generateReactions(reactants, forward=True))
  File "/home/ampayne/RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 1530, in __generateReactions
    products0 = [product.generateResonanceIsomers() for product in products0]
  File "rmgpy/molecule/molecule.py", line 1573, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build/pyrex/rmgpy/molecule/molecule.c:29371)
    def generateResonanceIsomers(self):
  File "rmgpy/molecule/molecule.py", line 1574, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build/pyrex/rmgpy/molecule/molecule.c:29308)
    return resonance.generateResonanceStructures(self)
  File "rmgpy/molecule/resonance.py", line 133, in rmgpy.molecule.resonance.generateResonanceStructures (build/pyrex/rmgpy/molecule/resonance.c:4178)
    def generateResonanceStructures(mol):
  File "rmgpy/molecule/resonance.py", line 178, in rmgpy.molecule.resonance.generateResonanceStructures (build/pyrex/rmgpy/molecule/resonance.c:3769)
    _generateResonanceStructures(newMolList, [generateClarStructures])
  File "rmgpy/molecule/resonance.py", line 232, in rmgpy.molecule.resonance._generateResonanceStructures (build/pyrex/rmgpy/molecule/resonance.c:4359)
    newMolList.extend(method(molecule))
  File "rmgpy/molecule/resonance.py", line 613, in rmgpy.molecule.resonance.generateClarStructures (build/pyrex/rmgpy/molecule/resonance.c:9833)
    def generateClarStructures(mol):
  File "rmgpy/molecule/resonance.py", line 625, in rmgpy.molecule.resonance.generateClarStructures (build/pyrex/rmgpy/molecule/resonance.c:9316)
    output = _clarOptimization(mol)
  File "rmgpy/molecule/resonance.py", line 791, in rmgpy.molecule.resonance._clarOptimization (build/pyrex/rmgpy/molecule/resonance.c:11849)
    innerSolutions = _clarOptimization(mol, constraints=constraints, maxNum=maxNum)
  File "rmgpy/molecule/resonance.py", line 754, in rmgpy.molecule.resonance._clarOptimization (build/pyrex/rmgpy/molecule/resonance.c:11295)
    lpsolve('add_constraint', lp, constraint[0], '<=', constraint[1])
error: invalid vector.

Traceback (most recent call last):
  File "/home/ampayne/RMG/RMG-Py/rmg.py", line 156, in <module>
    rmg.execute(**kwargs)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/rmg/main.py", line 665, in execute
    bimolecularReact=self.bimolecularReact)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/rmg/model.py", line 621, in enlarge
    rxns = reactAll(self.core.species, numOldCoreSpecies, unimolecularReact, bimolecularReact)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/rmg/react.py", line 155, in reactAll
    rxns = list(react(*spcTuples))
  File "/home/ampayne/RMG/RMG-Py/rmgpy/rmg/react.py", line 75, in react
    combos
  File "/home/ampayne/RMG/RMG-Py/rmgpy/scoop_framework/util.py", line 154, in map_
    return map(WorkerWrapper(args[0]), *args[1:], **kwargs)
  File "/opt/anaconda/envs/rmg_env/lib/python2.7/site-packages/scoop-0.7.2.0-py2.7.egg/scoop/fallbacks.py", line 49, in wrapper
  File "/home/ampayne/RMG/RMG-Py/rmgpy/scoop_framework/util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/rmg/react.py", line 96, in reactMolecules
    rxns = family.generateReactions(molecules)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 1323, in generateReactions
    reactionList.extend(self.__generateReactions(reactants, forward=True))
  File "/home/ampayne/RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 1530, in __generateReactions
    products0 = [product.generateResonanceIsomers() for product in products0]
  File "rmgpy/molecule/molecule.py", line 1573, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build/pyrex/rmgpy/molecule/molecule.c:29371)
  File "rmgpy/molecule/molecule.py", line 1574, in rmgpy.molecule.molecule.Molecule.generateResonanceIsomers (build/pyrex/rmgpy/molecule/molecule.c:29308)
  File "rmgpy/molecule/resonance.py", line 133, in rmgpy.molecule.resonance.generateResonanceStructures (build/pyrex/rmgpy/molecule/resonance.c:4178)
  File "rmgpy/molecule/resonance.py", line 178, in rmgpy.molecule.resonance.generateResonanceStructures (build/pyrex/rmgpy/molecule/resonance.c:3769)
  File "rmgpy/molecule/resonance.py", line 232, in rmgpy.molecule.resonance._generateResonanceStructures (build/pyrex/rmgpy/molecule/resonance.c:4359)
  File "rmgpy/molecule/resonance.py", line 613, in rmgpy.molecule.resonance.generateClarStructures (build/pyrex/rmgpy/molecule/resonance.c:9833)
  File "rmgpy/molecule/resonance.py", line 625, in rmgpy.molecule.resonance.generateClarStructures (build/pyrex/rmgpy/molecule/resonance.c:9316)
  File "rmgpy/molecule/resonance.py", line 791, in rmgpy.molecule.resonance._clarOptimization (build/pyrex/rmgpy/molecule/resonance.c:11849)
  File "rmgpy/molecule/resonance.py", line 754, in rmgpy.molecule.resonance._clarOptimization (build/pyrex/rmgpy/molecule/resonance.c:11295)
lpsolve.error: invalid vector.
```

I switched to an updated branch on 3/20/17 and did a clean make before running the job, so the error is likely from a recent change.

If necessary, the branches I have been working on are:

Successful: Surrogate_Oil_AMP_Py (its using RMG version 2.0 still)
Crashed: SO_2.1_AMP (using RMG version 2.1)

These branches have not been updated since the jobs were ran.

**Comment by mliu49** [comment]
This is a known error with resonance structure generation for complex ring systems where `getSmallestSetOfSmallestRings` doesn't return the expected result. I'm currently working on a fix.

**Comment by amarkpayne** [comment]
This issue also appears related to the discussion in the bottom of #936

**Comment by mliu49** [comment]
This should be fixed by c92f47d86684661db5c5a682feac46ed96aa24b3.

**Comment by amarkpayne** [comment]
Thanks! I'll cherry-pick this commit and let you know what happens.

**Comment by amarkpayne** [comment]
Unfortunately my RMG simulation crashed in the same place. Just in case there are any differences I'll paste the error traceback.

``

**Comment by mliu49** [comment]
Could you cherry-pick this commit 96db5b27996b9bfd29c03da00b8502ad91ec29be and rerun to find out what molecule is causing the issue? Thanks!

**Comment by amarkpayne** [comment]
Can do! Also, do I need to make clean?

**Comment by mliu49** [comment]
I don't think you need to, but it probably wouldn't hurt.

**Comment by amarkpayne** [comment]
Here is my error traceback. Interestingly, it did not crash in the same place. It crashed ~200 species later on. I haven't updating my branch (SO_2.1_AMP) besides your cherry-picked commits, so I am not sure what to make of that (though I did do make clean this time).

```
Error: Reactant: Molecule(SMILES="CC1C=CC=CC=1")
Error: Reactant: Molecule(SMILES="CCCCCCCCC[CH]C1:C:C2C=CC:1:C:C:2")
Error: Product: Molecule(SMILES="CCCCCCCCCC(c1cc2C=Cc1cc2)C1C=CC=C[C]1C")
Traceback (most recent call last):
  File "/home/ampayne/RMG/RMG-Py/rmgpy/scoop_framework/util.py", line 112, in __
call__
    return self.myfn(*args, **kwargs)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/rmg/react.py", line 96, in reactMolecules
    rxns = family.generateReactions(molecules)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 1376, in g
enerateReactions
    reactionList.extend(self.__generateReactions(reactants, forward=False))
  File "/home/ampayne/RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 1627, in _
_generateReactions
    reaction.degeneracy = self.calculateDegeneracy(reaction)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 1393, in c
alculateDegeneracy
    'but generated {2}').format(reaction, self.label, len(reactions)))
KineticsError: Unable to calculate degeneracy for reaction <Molecule "CC1C=CC=CC
=1"> + <Molecule "CCCCCCCCC[CH]c1cc2C=Cc1cc2"> <=> <Molecule "CCCCCCCCCC(C1:C:C2
C=CC:1:C:C:2)C1C=CC=C[C]1C"> in reaction family R_Addition_MultipleBond. Expecte
d 1 reaction but generated 2

Traceback (most recent call last):
  File "/home/ampayne/RMG/RMG-Py/rmg.py", line 156, in <module>
    rmg.execute(**kwargs)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/rmg/main.py", line 665, in execute
    bimolecularReact=self.bimolecularReact)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/rmg/model.py", line 621, in enlarge
    rxns = reactAll(self.core.species, numOldCoreSpecies, unimolecularReact, bim
olecularReact)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/rmg/react.py", line 155, in reactAll
    rxns = list(react(*spcTuples))
  File "/home/ampayne/RMG/RMG-Py/rmgpy/rmg/react.py", line 75, in react
    combos
  File "/home/ampayne/RMG/RMG-Py/rmgpy/scoop_framework/util.py", line 154, in map_
    return map(WorkerWrapper(args[0]), *args[1:], **kwargs)
  File "/opt/anaconda/envs/rmg_env/lib/python2.7/site-packages/scoop-0.7.2.0-py2.7.egg/scoop/fallbacks.py", line 49, in wrapper
  File "/home/ampayne/RMG/RMG-Py/rmgpy/scoop_framework/util.py", line 112, in __call__
    return self.myfn(*args, **kwargs)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/rmg/react.py", line 96, in reactMolecules
    rxns = family.generateReactions(molecules)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 1376, in generateReactions
    reactionList.extend(self.__generateReactions(reactants, forward=False))
  File "/home/ampayne/RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 1627, in __generateReactions
    reaction.degeneracy = self.calculateDegeneracy(reaction)
  File "/home/ampayne/RMG/RMG-Py/rmgpy/data/kinetics/family.py", line 1393, in calculateDegeneracy
    'but generated {2}').format(reaction, self.label, len(reactions)))
rmgpy.data.kinetics.common.KineticsError: Unable to calculate degeneracy for reaction <Molecule "CC1C=CC=CC=1"> + <Molecule "CCCCCCCCC[CH]c1cc2C=Cc1cc2"> <=> <Molecule "CCCCCCCCCC(C1:C:C2C=CC:1:C:C:2)C1C=CC=C[C]1C"> in reaction family R_Addition_MultipleBond. Expected 1 reaction but generated 2
```

**Comment by amarkpayne** [comment]
Looking more closely, this looks like a different kind of error. Perhaps doing make clean made the difference? Is this error related?

**Comment by mliu49** [comment]
It's likely that make clean made the difference. The last cherry picked commit would not have changed where the run crashed.

This error is probably related to how resonance is handled during the degeneracy calculation, and is no longer related to a failure in Clar structure generation. There is no easy solution at this point, although I've been working on completely refactoring the degeneracy algorithm.

**Comment by amarkpayne** [comment]
In that case I am going to close the solved issue, and open this new issue.

**Comment by zerayhg** [comment]
@mliu49 I am having a problem with scoopzmq or brokerzmq while I run it to the cluster. The error message is shown below. Do you have any fix with that? Thanks.
[2024-07-24 14:34:16,673] launcher  INFO    SCOOP 0.7 2.0 on linux2 using Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 22:17:58) [GCC 7.3.0], API: 1013
[2024-07-24 14:34:16,673] launcher  INFO    Detected SLURM environment.
[2024-07-24 14:34:16,673] launcher  INFO    Deploying 8 worker(s) over 1 host(s).
[2024-07-24 14:34:16,673] launcher  INFO    Worker distribution: 
[2024-07-24 14:34:16,673] launcher  INFO       cn01:	7 + origin
Launching 8 worker(s) using /bin/bash.
[2024-07-24 14:38:32,944] brokerzmq (127.0.0.1:42541) ERROR   Could not unpickle status update message.
[2024-07-24 14:41:55,646] brokerzmq (127.0.0.1:42541) ERROR   Could not unpickle status update message.
[2024-07-24 14:45:42,042] brokerzmq (127.0.0.1:42541) ERROR   Could not unpickle status update message.
[2024-07-24 14:46:31,798] brokerzmq (127.0.0.1:42541) ERROR   Could not unpickle status update message.
[2024-07-24 14:51:08,895] brokerzmq (127.0.0.1:42541) ERROR   Could not unpickle status update message.
[2024-07-24 14:53:15,431] scoopzmq  (192.168.0.111:64689) ERROR   A worker exited unexpectedly. Read the worker logs for more information. SCOOP pool will now shutdown.
Traceback (most recent call last):
  File "/opt/ohpc/pub/apps/miniconda3/py311_23.5.2/envs/py27/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/opt/ohpc/pub/apps/miniconda3/py311_23.5.2/envs/py27/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/ohpc/pub/apps/miniconda3/py311_23.5.2/envs/py27/lib/python2.7/site-packages/scoop/bootstrap/__main__.py", line 298, in <module>
    b.main()
  File "/opt/ohpc/pub/apps/miniconda3/py311_23.5.2/envs/py27/lib/python2.7/site-packages/scoop/bootstrap/__main__.py", line 92, in main
    self.run()
  File "/opt/ohpc/pub/apps/miniconda3/py311_23.5.2/envs/py27/lib/python2.7/site-packages/scoop/bootstrap/__main__.py", line 285, in run
    futures_startup()
  File "/opt/ohpc/pub/apps/miniconda3/py311_23.5.2/envs/py27/lib/python2.7/site-packages/scoop/bootstrap/__main__.py", line 266, in futures_startup
    run_name="__main__"
  File "/opt/ohpc/pub/apps/miniconda3/py311_23.5.2/envs/py27/lib/python2.7/site-packages/scoop/futures.py", line 71, in _startup
    result = _controller.switch(rootFuture, *args, **kargs)
  File "/opt/ohpc/pub/apps/miniconda3/py311_23.5.2/envs/py27/lib/python2.7/site-packages/scoop/_control.py", line 258, in runController
    future = execQueue.pop()
  File "/opt/ohpc/pub/apps/miniconda3/py311_23.5.2/envs/py27/lib/python2.7/site-packages/scoop/_types.py", line 359, in pop
    self.updateQueue()
  File "/opt/ohpc/pub/apps/miniconda3/py311_23.5.2/envs/py27/lib/python2.7/site-packages/scoop/_types.py", line 382, in updateQueue
    for future in self.socket.recvFuture():
  File "/opt/ohpc/pub/apps/miniconda3/py311_23.5.2/envs/py27/lib/python2.7/site-packages/scoop/_comm/scoopzmq.py", line 352, in recvFuture
    received = self._recv()
  File "/opt/ohpc/pub/apps/miniconda3/py311_23.5.2/envs/py27/lib/python2.7/site-packages/scoop/_comm/scoopzmq.py", line 239, in _recv
    thisFuture = pickle.loads(msg[1])
cPickle.UnpicklingError: pickle data was truncated

**Comment by JacksonBurns** [comment]
Please see: https://github.com/ReactionMechanismGenerator/RMG-Py/discussions/2696#discussioncomment-10160856
